### ISSUE TITLE
[需求] 可以考虑下支持 css in js 的 linaria

### ISSUE THREAD

**Issue by xiamu14** [remaxjs/remax#1009]
**需求描述**
在 React 社区有一个著名的 CSS-in-JS 解决方案: styled-components。但遗憾的是，styled-components 使用 <style> 标签来动态地控制样式，在小程序没有类似的方案。

**解决方案**
但我们可以通过 linaria 实现同样的功能，linaria 主要提供以下特性：

- 近似于 styled-components 的 API

- 完整的 TypeScript 支持

- 零运行时

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
支持的。https://taro-docs.jd.com/taro/docs/3.0.0-beta.5/css-in-js 和 Taro 描述的差不多。只不过是要配置 ignore 掉 @remax 的包

**Comment by xiamu14** [comment]
谢谢，我这边已经尝试添加可以了。

**Comment by pcdotfan** [comment]
> 谢谢，我这边已经尝试添加可以了。

可以贴一下配置吗
