### ISSUE TITLE
接入 F2

### ISSUE THREAD

**Issue by afc163** [remaxjs/remax#101]
https://github.com/antvis/f2/

**Comment by malash** [comment]
请问什么是F2？

**Comment by zhangyifei007** [comment]
@afc163  可以参考这个库https://github.com/harrydengchao/taro-chart-f2去写个适配到remax就行了，目前我们已经成功将项目从taro迁移到remax

**Comment by Darmody** [comment]
@zhangyifei007 请问你们的我想买上线了吗

**Comment by yesmeck** [comment]
f2 的例子 https://github.com/remaxjs/examples/tree/master/alipay-f2

**Comment by afc163** [comment]
@malash https://f2.antv.vision/zh
