### ISSUE TITLE
[BUG] 钉钉小程序无法进行网络请求

### ISSUE THREAD

**Issue by Leo428** [remaxjs/remax#1011]
**bug 描述**
钉钉小程序无法使用 remax/ali 的request进行网络请求。
![image](https://user-images.githubusercontent.com/19278677/83266023-dff9be80-a1f4-11ea-9889-93dc138d158e.png)

**复现步骤**
```typescript
request({
      url: 'http://localhost:3000/', //any url
      method: 'GET',
      complete: (res) => console.log(res)
});
```

**期望结果**
请求正常发起。

**复现代码**
同上

**版本信息:**

- remax 版本: 2.0.7
- 手机型号 模拟器, Pixel 4
- 小程序端 钉钉小程序
- 小程序版本 小程序开发者工具1.12.15, dd/SDKVersion: 1.7.108
- 开发环境 Windows 10

**其他信息**
根据官网的[文档](https://opendocs.alipay.com/mini/api/owycmh), 钉钉小程序没有request，只有httprequest，但是remax/ali 没有httprequest。希望能指教如何正确地在钉钉小程序中使用网络请求，谢谢您！如果有第三方库能实现相同的功能，请给我推荐一下。

**Comment by iugo** [comment]
推荐通过 https://www.npmjs.com/package/@zsqk/dd-sdk-mini-program 来使用钉钉小程序的 API.
