### ISSUE TITLE
[BUG] antv/F2 图表组件在ios微信小程序中显示不正常

### ISSUE THREAD

**Issue by wlfcss** [remaxjs/remax#1012]
**bug 描述**
F2 图标组件在ios微信小程序显示不正常

**复现步骤**
下载并运行 `remaxjs/examples/wechat-f2` 
- ios端WeChat文字消失：
![image](https://user-images.githubusercontent.com/12138285/83324730-d5ddcb80-a299-11ea-9be7-5da21c101dc7.png)

**期望结果**
- 安卓端wechat运行正常：
![image](https://user-images.githubusercontent.com/12138285/83324725-cc546380-a299-11ea-915e-ac5de8d493e6.png)

**复现代码**
-

**版本信息:**

- remax 版本: [2.1.1]
- 手机型号 [e.g. iPhone 11]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]
- f2版本："@antv/f2": "^3.6.4-beta.7"  与 "@antv/f2": "^3.6.0"

**其他信息**

**Comment by yesmeck** [comment]
@wlfcss 直接用小程序写是否正常？

**Comment by wlfcss** [comment]
@yesmeck 微信原生直接写是正常的，https://github.com/antvis/wx-f2/tree/master/src

**Comment by lich-yoo** [comment]
@wlfcss ios 微信某一版本才有的 bug，设置单字体即可解决。
详见[f2-issues](https://github.com/antvis/wx-f2/issues/260#issuecomment-603214114)
