### ISSUE TITLE
[BUG] 从1.0迁移到2.0微信小程序View的bindtap失效，hover-class也失效。

### ISSUE THREAD

**Issue by lee88688** [remaxjs/remax#1013]
**bug 描述**
RT，刚从1.0迁移到2.0版本，发现View的bindtap直接失效，必须使用onTap，完全不提供兼容的方法吗？对于不考虑跨平台的应用程序感觉改动好大。另外View的hover-class也无法使用了，只能使用hoverClass，这改动真的还有点大哦😓。
直接将View改为view之后bindtap可以使用，但是hover-class还是没办法使用。

**期望结果**
希望View能够直接使用bindtap和hove-class，或者至少提供一个回退配置，不知道现在有没有这种配置。此外希望这些差异能够在迁移指南中提及一下，不然真的是一脸懵逼😂。

**版本信息:**

- remax 版本: [2.2.0]

**Comment by yesmeck** [comment]
原来支持 `bindtap` 和  `hover-class` 其实属于意外。我们不希望一个项目里出现两种风格的写法，所以在 2.0 里去掉了这个意外。

**Comment by lee88688** [comment]
@yesmeck 想问一下另外一个问题，不少第三方的小程序组件库（例如Vant）的属性采用的是xx-xx这种形式，这种属性你们也做了转义，需要写成驼峰方式才行？

**Comment by yesmeck** [comment]
第三方的小程序组件库我们没做处理，按组件本身的定义来写。
