### ISSUE TITLE
remax中使用react-recoil报错。

### ISSUE THREAD

**Issue by mumuwen520** [remaxjs/remax#1023]
**remax中使用react-recoil状态管理库报错**
安装依赖和引入都没有问题，不过页面会报错。

**只引入recoil的api**
<img src="https://cdn.weipaitang.com/static/202006028d7400fc-1f6b-00fc1f6b-2c65-7e619ed9d742-W1002H289">

**版本信息:**

- remax 版本: [e.g. 2.0.7]
- 小程序端 [e.g. 微信小程序]
- 开发环境 [e.g. mac OS]

**Comment by yesmeck** [comment]
https://github.com/facebookexperimental/Recoil/pull/220

因为 react-recoil 引用了 window

**Comment by Darmody** [comment]
https://github.com/facebookexperimental/Recoil/blob/master/CHANGELOG.md#009-2020-06-17

修复了
