### ISSUE TITLE
[BUG]桌面提醒坏掉了

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#1026]
**bug 描述**

现在有编译错误时提醒是这个样子的。

<img width="401" alt="Screen Shot 2020-06-03 at 00 00 39" src="https://user-images.githubusercontent.com/465125/83542430-8b747d00-a52d-11ea-8779-b9ca67001760.png">

**Comment by inJs** [comment]
我电脑啥反应没有...
电脑：MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
系统：MacOS 10.15.3
终端：版本2.10 (433)
remax：2.2.0
