### ISSUE TITLE
[BUG]原生组件和用remax写的页面引用同一份js的时候有问题

### ISSUE THREAD

**Issue by liujin10** [remaxjs/remax#1028]
**bug 描述**
***remax编写的page与原生组件引用同一份js，编译之后会生成两份js，导致内部变量的状态有问题。***
使用remax编写的page（src/pages/index/index.js）和原生组件（src/npm/ec-canvas/ec-canvas.js）引用了同一份src/npm/ec-canvas/echarts.min.js文件。
![image](https://user-images.githubusercontent.com/18552493/83599587-278a9c80-a59f-11ea-8507-fa19b1bb5dc6.png)
![image](https://user-images.githubusercontent.com/18552493/83599608-383b1280-a59f-11ea-979c-74404db3ba40.png)
打包之后
src/pages/index/index.js引用的部分会包裹成webpack形式的依赖文件
![image](https://user-images.githubusercontent.com/18552493/83599646-4721c500-a59f-11ea-8752-c6daee17deda.png)
src/npm/ec-canvas/ec-canvas.js引用的部分会输出问单独的文件
![image](https://user-images.githubusercontent.com/18552493/83599686-628cd000-a59f-11ea-8437-99ad19faab7f.png)

**版本信息:**

- remax 版本: 2.2.0
- 小程序端：微信小程序

**Comment by yesmeck** [comment]
需要在 webpack 里配置把 `./echarts.min` external 掉，试试：

```javascript
// remax.config.js

module.exports = {
  configWebpack({ config }) {
     config.externals({
       './echats.min': 'require('./echarts.min')',
     })
  }
}
```
