### ISSUE TITLE
[问题]生产环境打包编译微信小程序时开启watch，重新编译会删除生成的app.json和base.wxml

### ISSUE THREAD

**Issue by JesuisTong** [remaxjs/remax#1042]
**问题描述**
同标题，第一次打包完成时有`app.json`和`base.wxml`，文件改动重新编译之后两个文件就被删了，修改`app.config.ts`也不会生成新的`app.json`。

**示例代码**
无实例代码
remax版本：2.3.0

**其他信息**
https://github.com/remaxjs/remax/blob/93bbd2c5e8f8968699002bc1d99913a097304f97/packages/remax-cli/src/build/webpack/baseConfig.ts#L27-L29
和这个有关吗？

**Comment by yesmeck** [comment]
估计可能有。

**Comment by Darmody** [comment]
可以通过修改配置把 clean-webpack-plugin 去掉
