### ISSUE TITLE
[rfc] 支持 createPortal

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#1046]
用于提供对全局/公共组件的支持

1. 允许创建一个 `container`
2. 在模板里渲染多个 `container`，可以定义顺序
3. 在 page 挂载的时候，也挂载用户自定义的 container

**Comment by yesmeck** [comment]
解决什么问题？

**Comment by Darmody** [comment]
> 一个 portal 的典型用例是当父组件有 overflow: hidden 或 z-index 样式时，但你需要子组件能够在视觉上“跳出”其容器。例如，对话框、悬浮卡以及提示框：

**Comment by yesmeck** [comment]
具体怎么实现？

**Comment by IronLu233** [comment]
这是ReactDOM的。我想，能否简化一下，直接挂载在page的根节点创建一个<View /> 把节点放进去。
```
render() {
  // React 并*没有*创建一个新的 div。它只是把子元素渲染到 `domNode` 中。
  // `domNode` 是一个可以在任何位置的有效 DOM 节点。
  return ReactDOM.createPortal(
    this.props.children,
    domNode
  );
}
```

**Comment by IronLu233** [comment]
或者还有一种思路，不要createPortal 这个API，直接在@remax/one里提供一个Modal组件。Modal组件会保证它的Children一定会渲染在页面顶层。

这是ReactNative的方案。

**Comment by yesmeck** [comment]
@IronLu233 ReactNative 的文档有么，感觉这个靠谱点

**Comment by IronLu233** [comment]
https://reactnative.dev/docs/modal.html

**Comment by Darmody** [comment]
> 或者还有一种思路，不要createPortal 这个API，直接在@remax/one里提供一个Modal组件。Modal组件会保证它的Children一定会渲染在页面顶层。
> 
> 这是ReactNative的方案。

不仅仅支持 Modal，如果还能支持全局通用的 Header，Footer 就更好了

**Comment by yesmeck** [comment]
Modal 感觉可以，但是这个组件要放哪个包里呢？

**Comment by yesmeck** [comment]
> 不仅仅支持 Modal，如果还能支持全局通用的 Header，Footer 就更好了

这是另外一个问题了

**Comment by Darmody** [comment]
> > 不仅仅支持 Modal，如果还能支持全局通用的 Header，Footer 就更好了
> 
> 这是另外一个问题了

这个是因为我们不支持在 App 里面渲染基础组件。所以我想可以通过 createPortal 一起来做。

当时不支持在App 里渲染，有一个问题是数据共享。其实现在想一想可以用 Context 共享数据就行了。

要么我觉得可以支持在 App 里渲染基础组件

**Comment by IronLu233** [comment]
> > 不仅仅支持 Modal，如果还能支持全局通用的 Header，Footer 就更好了
> 
> 这是另外一个问题了

这个组件，叫做`<Portal />`会更合适一些。
我还翻了一下Ant design RN的实现。首先，它在自己的`<Provider />`组件里，不仅提供了i18n，还用`<Portal.Host />`组件，指定了`<Portal />`挂载的位置。

然后，在任意地方渲染`<Portal />`组件，`<Portal />`的内容就会被一一渲染进PortalHost里。
因此，如果我们可以在App中提供一个“默认”的PortalHost，让所有的Portal都渲染到最顶层。

https://github.com/ant-design/ant-design-mobile-rn/blob/4344e2850727a3fa1c1f7691f362438e2a3a6bfc/components/provider/index.tsx

https://github.com/ant-design/ant-design-mobile-rn/blob/4344e28507/components/portal/portal.tsx

**Comment by Darmody** [comment]
🤔

**Comment by yesmeck** [comment]
明确下，这里讨论了两个问题，不能搞在一起。

1. Modal 类组件的层级问题。
2. App.js 内支持基础组件。

问题一，可以参考 RN 的做法，提供一个内置的渲染在树顶层的 Modal 组件。

问题二，另外开 issue 吧，不要混在一起了。

**Comment by IronLu233** [comment]
> 明确下，这里讨论了两个问题，不能混在一起。
> 
> 1. Modal 类组件的层级问题。
> 2. App.js 内支持基础组件。
> 
> 问题一，可以参考 RN 的做法，提供一个内置的渲染在树顶层的 Modal 组件。
> 
> 问题二，另外开 issue 吧，不要混在一起了。

emmm我更建议组件叫做`<Portal />`

**Comment by yesmeck** [comment]
ant-design-mobile-rn 那样的 Portal.Host 可能不大还实现。

**Comment by yesmeck** [comment]
可以试一下

**Comment by yesmeck** [comment]
看了下 `<Portal />` 的实现，感觉这样的组件在组件库里去实现就可以了。

**Comment by Darmody** [comment]
结论是我们在 remax/one 里提供一个 <Modal /> 组件

**Comment by Darmody** [comment]
close vi #1133
