### ISSUE TITLE
[需求] 支持自定义内敛样式转换规则

### ISSUE THREAD

**Issue by noyobo** [remaxjs/remax#1047]
**需求描述**
能否也提供自定义 `transformPx` 途径?

在过去我们写的 react 组件使用的是 rem 单位，html.fontSize = 100px;  所以自定义 transformPx 方法的需求。

这么做的目的是为了保留过去 H5 的开发习惯。

```js
{width: 100, border: '0.01rem solid red'}
```
转换到 web 

```js
{width: '1rem', border: '0.01rem solid red'}
```

转换到 小程序

```js
{width: '100rpx', border: '1rpx solid red'}
```

**解决方案**

RuntimePlugin 支持自定义转换规则。

```js
{
  pxToRpx: true, // 开启内置的默认转换,
  pxToRpx: function(value, cssProperty) => value.replace() // 自定义转换。
}
```

> 或者有其他方式，其他字段

**Comment by noyobo** [comment]
额，还是有点使用程度上的复杂，一个是在 remax 的运行时，这里可以修改 remax-runtime 的转换规整，web 就是 react 运行了。 只能在组件上做处理？ 类似于 `useWebPlaceholderStyle` 的操作。

**Comment by Darmody** [comment]
是不是关掉 pxToRpx，交给开发者自己去做转换就可以了
