### ISSUE TITLE
[BUG]使用状态控制Input的focus，不断地触发focus和blur事件

### ISSUE THREAD

**Issue by Jkanon** [remaxjs/remax#1048]
**bug 描述**
如题，想要通过一个state来控制input的focus属性，鼠标移入input的时候，多次触发了focus和blur事件

**期望结果**
只触发一次focus事件

**复现代码**

```tsx
import * as React from 'react'
import { useState } from 'react'
import { View, Input, InputEvent } from 'remax/one'

export default () => {
  const [focus, setFocus] = useState(false)

  const handleFocus = (event: InputEvent): void => {
    console.log('focus')
    setFocus(true)
  }

  const handleBlur = (event: InputEvent): void => {
    console.log('blur')
    setFocus(false)
  }

  return (
    <View>
      <Input focus={focus} onFocus={handleFocus} onBlur={handleBlur}></Input>
    </View>
  )
}
```

**版本信息:**

- remax 版本: [2.3.0]
- 手机型号 [android]
- 小程序端 [微信小程序]
- 开发环境 [window 10]

**Comment by Darmody** [comment]
这个问题我看一下。

你对 focus 的需求是什么？小程序里不用对  focus 做实时受控的

**Comment by Jkanon** [comment]
> 这个问题我看一下。
> 
> 你对 focus 的需求是什么？小程序里不用对 focus 做实时受控的

比如通过focus状态对元素或者样式进行控制

**Comment by Darmody** [comment]
> > 这个问题我看一下。
> > 你对 focus 的需求是什么？小程序里不用对 focus 做实时受控的
> 
> 比如通过focus状态对元素或者样式进行控制

那可以用 useRef 记录 受控状态就行，不用去一直 setState。小程序本身不需要对 focus 受控

**Comment by Darmody** [comment]
说错了。。那只需要记录 focus 状态就行，不需要去控制 focus 字段

**Comment by Darmody** [comment]
我在本地试了一下，没有复现你说的问题

**Comment by Darmody** [comment]
安卓试了一下也是好的

**Comment by Darmody** [comment]
先关闭了，如果还有问题再看看

**Comment by Jkanon** [comment]
升级remax为2.4后无此问题
