### ISSUE TITLE
[BUG] 自定义 remax 组件使用 onPageScroll 不生效

### ISSUE THREAD

**Issue by noyobo** [remaxjs/remax#1054]
**bug 描述**
```jsx
// ./components/c.js
import { usePageEvent } from '@remax/macro';
import { View } from '@remax/wechat';

const C:React.FC<any> = (props) => {
	usePageEvent('onPageScroll', console.log)
	return <View>监听滚动的组件</View>
};

export default C;
```

```jsx
// pages/index/index.js
import C from '../../../components/c.js';

export default function Demo(){
	return <C />
}
```

```js
- app
    - pages/index/index
    - remax.config.js
- components
    - c.js
```

此时 pages/index/index 页面滚动，C 组件中的 onPageScroll 事件不生效, 由于 components 目录已经不属于 process.cwd 下的子集。

**期望结果**

C 组件中的 onPageScroll 起作用

**版本信息:**

- remax 版本: 2.4.0

**Comment by Darmody** [comment]
试了一下可以的呀？有没有完整的复现 demo？

**Comment by noyobo** [comment]
https://github.com/noyobo/remax-issues-demo/tree/page-scroll

**Comment by Darmody** [comment]
还是不能复现。。

**Comment by Darmody** [comment]
先关闭了

**Comment by noyobo** [comment]
https://github.com/noyobo/remax-issues-demo/tree/page-scroll

按 readme 中的步骤复现。

**Comment by noyobo** [comment]
似乎和 `@remax/cli` 的路径有关系？

**Comment by noyobo** [comment]
原因：由于 `@remax/cli` 不是安装在当前目录，会有两份 `@remax/macro` 依赖，生成的 pageEvents 就不是同一个对象了。 导致实际生命周期未声明。

**Comment by Darmody** [comment]
remax cli 还是要和 remax runtime 绑定的
