### ISSUE TITLE
[BUG]微信小程序app.config中配置的iconPath没有被打包到目录中导致找不到文件

### ISSUE THREAD

**Issue by fake-car** [remaxjs/remax#1061]
**bug 描述**
 在app.config.ts中定义的iconPath的图片没有被打包进去
**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 2.0.0]
- 小程序端 微信小程序
- 开发环境 mac OS

**其他信息**
<img width="636" alt="图片" src="https://user-images.githubusercontent.com/13540489/84065189-83698100-a9f6-11ea-90ae-120fed74ccdf.png">
<img width="289" alt="图片" src="https://user-images.githubusercontent.com/13540489/84065207-8d8b7f80-a9f6-11ea-99f9-926cc37b4e82.png">
<img width="303" alt="图片" src="https://user-images.githubusercontent.com/13540489/84065315-c6c3ef80-a9f6-11ea-854e-093db7d5daf7.png">

**Comment by Darmody** [comment]
https://remaxjs.org/guide/basic/public

2.3.0 之前的版本需要通过 copy-webpack-plugin 来配置全局资源

**Comment by Darmody** [comment]
https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/webpack/config.mini.ts#L194-L196

2.3.0 之前的版本在 `remax.config.js` 中通过 `configWebpack` 配置

**Comment by fake-car** [comment]
感谢 明白了
