### ISSUE TITLE
[BUG] remax/toutiao'里的radio选中后并不显示选中效果

### ISSUE THREAD

**Issue by gavin99587** [remaxjs/remax#1067]
**bug 描述**
remax/toutiao'里的radio选中后并不显示选中效果,在onChange事件中能检测到选中事件

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
import {RadioGroup, Radio} from 'remax/toutiao';
<RadioGroup className={styles.radioGroup} onChange={handleRadioGroupChange}>
                        <Label className={styles.radio}>
                            <Radio value={PlatFormType.wechat} checked={true}/>微信
                        </Label>
                        <Label className={styles.radio}>
                            <Radio value={PlatFormType.toutiao} checked={true}/>头条
                        </Label>
                    </RadioGroup>

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]
<img width="296" alt="截屏2020-06-10 22 09 06" src="https://user-images.githubusercontent.com/11565497/84278180-03165d80-ab67-11ea-9afe-1f55817d6bf5.png">

**Comment by yesmeck** [comment]
@gavin99587 能提供一个重现的 demo 吗

**Comment by gavin99587** [comment]
> @gavin99587 能提供一个重现的 demo 吗

这个问题是我自己的问题,他其实是选中了的,没效果是因为我没有加背景色,<Radio color="red" value={PlatFormType.toutiao}/>头条  必须加color属性就显示了
