### ISSUE TITLE
[BUG]input 受控时，value 更新时会刷新组件，在 ios 会卡顿

### ISSUE THREAD

**Issue by dyb881** [remaxjs/remax#1069]
**bug 描述**
input 受控时，value 更新时会刷新组件，在 ios 会卡得很明显

**复现步骤**
使用 rc-field-form 的 Field 包裹 Input 后，在手机上输入的时候，光标会错乱
在控制台会看到，更改一次值，就会在小程序刷新一次 input 

**期望结果**
能否不卡

**复现代码**
`
<Field name="test" trigger="onInput" getValueFromEvent={(value) => value.detail.value}>
  <Input />
</Field>;
`

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
remax 1 是哪个版本？

**Comment by dyb881** [comment]
1.21.6


| |
15118995517
|
|
15118995517@163.com
|
签名由网易邮箱大师定制


在2020年06月12日 10:16，Cai Huanyu<notifications@github.com> 写道：

remax 1 是哪个版本？

**Comment by Darmody** [comment]
微信受控是需要通过 `onInput` 的返回值控制的，不知道是不是和这个有关系。

小程序的受控行为性能是会差一些的

**Comment by dyb881** [comment]
可是输入框体验极差，好难搞呀，输入的间隔稍微快一点点，文字就会回跳


| |
15118995517
|
|
15118995517@163.com
|
签名由网易邮箱大师定制


在2020年06月12日 11:43，Cai Huanyu<notifications@github.com> 写道：

微信受控是需要通过 onInput 的返回值控制的，不知道是不是和这个有关系。

小程序的受控行为性能是会差一些的

**Comment by Darmody** [comment]
提供一个复现 demo 我来看看吧

**Comment by dyb881** [comment]
我用 v2 版本尝试了一下，体验正常了。估计是处理了这个问题。我还是想办法升级吧


| |
15118995517
|
|
15118995517@163.com
|
签名由网易邮箱大师定制


在2020年06月12日 12:29，Cai Huanyu<notifications@github.com> 写道：

提供一个复现 demo 我来看看吧

**Comment by Darmody** [comment]
那我先关闭了

**Comment by Ahcnge** [comment]
2.7版本还是有这个问题
