### ISSUE TITLE
[BUG]postcss 会把引用的组件包都一起转 rem 了

### ISSUE THREAD

**Issue by dyb881** [remaxjs/remax#1070]
**bug 描述**
引用 antd-mobile 后样式被转化为 rem 了

**复现步骤**

**期望结果**
能否配置 postcss 排除文件夹，如 node_modules

**复现代码**

**版本信息:**

- remax 版本: [e.g. 2.3.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by dyb881** [comment]
目前我修改 postcss 配置达成目的，但期望官方可以作出调整
`
module.exports = ({ options }) => {
  const plugins = {};
  Object.keys(options.plugins).forEach((i) => {
    if (!/postcss-px2units/.test(i)) {
      plugins[i] = options.plugins[i];
    }
  });

  return {
    plugins: {
      ...plugins,
      'postcss-plugin-px2rem': {
        rootValue: 100,
        exclude: /(node_module)/,
      },
    },
  };
};
`

**Comment by dyb881** [comment]
目前我修改了 postcss 配置达成目的，但还是期望官方作出调整
```
module.exports = ({ options }) => {
  const plugins = {};
  Object.keys(options.plugins).forEach((i) => {
    if (!/postcss-px2units/.test(i)) {
      plugins[i] = options.plugins[i];
    }
  });

  return {
    plugins: {
      ...plugins,
      'postcss-plugin-px2rem': {
        rootValue: 100,
        exclude: /(node_module)/,
      },
    },
  };
};

```

**Comment by Darmody** [comment]
目前不打算支持。可以简化一下配置，把 px2Rpx 配置关闭，再修改 plugins 就行。
