### ISSUE TITLE
[BUG]配置babel-plugin-import不会将使用的库打包进去

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#1094]
**bug 描述**
配置了babel-plugin-import插件后使用一个库，编译的dist里的文件并没有包含那个库的import

**复现步骤**
https://github.com/mushan0x0/remex-issue-import/blob/master/src/pages/index/index.tsx#L10

**复现代码**
https://github.com/mushan0x0/remex-issue-import

**版本信息:**

- remax 版本: 2.5.0

**Comment by yesmeck** [comment]
看起来是 babel-plugin-import 的 bug。

**Comment by yesmeck** [comment]
是我们的问题

**Comment by yesmeck** [comment]
2.5.4 修复了

**Comment by yesmeck** [comment]
2.5.4 修复了
