### ISSUE TITLE
集成测试

### ISSUE THREAD

**Issue by xcodebuild** [remaxjs/remax#11]
现在每个 PR 都需要手动 clone 下来编译，跑 demo 查看功能是否正常。

是否有办法加上集成测试和单元测试

**Comment by HuiguangChu** [comment]
可以用jenkin, teamcity做基本的测试。但是只能测试代码语法以及编译是否有问题。

**Comment by CodeFalling** [comment]
嗯至少可以先补上构建阶段的检测，后面的逻辑测试还要想其他方案。
