### ISSUE TITLE
[BUG]remax/one Button  wechat-bindgetuserinfo 无效

### ISSUE THREAD

**Issue by dyb881** [remaxjs/remax#1103]
**bug 描述**
remax/one Button  wechat-bindgetuserinfo 无效

**复现步骤**
```
import React, { useEffect } from 'react';
import { Button } from 'remax/one';

<Button wechat-lang="zh_CN" wechat-openType="getUserInfo" wechat-bindgetuserinfo={console.log}>
  确认授权
</Button>
```

**期望结果**
wechat-bindgetuserinfo 能够正常回调

**复现代码**

**版本信息:**

- remax 版本: [e.g. 2.5.4]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by dominicleo** [comment]
wechat-open-type="getUserInfo"

**Comment by dyb881** [comment]
依然无效
```
<Button wechat-lang="zh_CN" wechat-open-type="getUserInfo" wechat-bindgetuserinfo={console.log}>
          确认授权
</Button>
```

**Comment by dyb881** [comment]
整明白了， remax/one 不可在其他文件导出再引用，需要在使用的地方直接引用使用
