### ISSUE TITLE
微信小程序 canvas 行内样式默认 display: none

### ISSUE THREAD

**Issue by PlutoCA** [remaxjs/remax#1122]
**问题描述**
微信小程序 canvas 行内样式默认 display: none

尝试用 css 、 行内样式 覆盖都不生效
**示例代码**
```jsx
//     "remax": "^2.5.5",
<Canvas className="dd" style={{display: 'block', fontSize: '30px'}} id="canvas" />
```

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/31099607/86113135-6a3a8880-bafb-11ea-92aa-15c30bb113ab.png)

**Comment by PlutoCA** [comment]
https://github.com/remaxjs/remax/blob/9973b8c2734f3a3994a41893c24cb9c4c56f91e7/packages/remax-runtime/src/hostConfig/index.ts#L144

会不会是这里的问题 😂

**Comment by Darmody** [comment]
你有用 React Suspense 吗？

**Comment by PlutoCA** [comment]
> 你有用 React Suspense 吗？

没有用

**Comment by PlutoCA** [comment]
新建了一个demo 也会有这情况

**Comment by Darmody** [comment]
https://developers.weixin.qq.com/community/develop/doc/00040c7a0184b09bf9a70eb0c5b400

**Comment by PlutoCA** [comment]
好吧 抱歉 canvasId我写成 id 去了😂
