### ISSUE TITLE
[需求]支持 QQ 小程序

### ISSUE THREAD

**Issue by Tenodec** [remaxjs/remax#1127]
希望添加支持QQ小程序。相比于Taro，同时做选择，我个人偏向选择remax，但是如果我的产品需要支持QQ小程序，那我就只能选择Taro了

**Comment by yesmeck** [comment]
@Tenodec 有空帮我们支持下么

**Comment by rikumi** [comment]
直接编译到微信小程序就可以支持 QQ 小程序。

**Comment by Darmody** [comment]
> 直接编译到微信小程序就可以支持 QQ 小程序。

确实
