### ISSUE TITLE
跨平台代码书写

### ISSUE THREAD

**Issue by newset** [remaxjs/remax#113]
**需求描述**

目前跨平台的书写需要自行区分平台

```
import { View as WechatView, Text as WechatText } from 'remax/wechat';
import { View as AlipayView, Text as AlipayText } from 'remax/alipay';
```
建议 改为

```
import { View, Text } from 'remax';
```
在 remax-cli 中 根据 target ，将 remax 自动改 为 reamx-wechat 或者 remax-alipay

**Comment by Darmody** [comment]
感谢建议。

这个我们有考虑过，但是跨平台开发最大的问题就是多端代码如何抹平。

```
import { View, Text } from 'remax';
```

如果我们采用这种形式，会面临的问题有：

1. 不同平台的 View，`props` 定义不同怎么办？
2. 不同平台的 View, `onClick` 行为不同怎么办？
3. 不同平台的 View, Type 定义要怎么写？

要解决上面的问题，Remax 就要对不同平台做抹平处理，而且所有 Type 要定义在一起。
这样既丧失了灵活性，又很难维护。

因此 Remax 提供对多端的支持，在具体的跨平台开发场景中，交给开发者自己构建跨平台的逻辑。

可以查看 [指南：跨平台开发](https://remaxjs.org/advanced-guide/cross-platform)

**Comment by Darmody** [comment]
> 在 remax-cli 中 根据 target ，将 remax 自动改 为 reamx-wechat 或者 remax-alipay

这种做法的问题是，无法看到正确的 type 定义

**Comment by newset** [comment]
> > 在 remax-cli 中 根据 target ，将 remax 自动改 为 reamx-wechat 或者 remax-alipay
> 
> 这种做法的问题是，无法看到正确的 type 定义

谢谢解答，了解了
