### ISSUE TITLE
[BUG]Remax One Input 组件需要支持设置 ali-controlled

### ISSUE THREAD

**Issue by dyb881** [remaxjs/remax#1130]
**bug 描述**
Input 需要支持设置 ali-controlled

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
<Input controlled={false} />

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
remax one 的 Input 不需要关心 controlled 这个概念
