### ISSUE TITLE
[需求]web端 访问未注册的路由，会显示空白页面，期望可以跳到首页

### ISSUE THREAD

**Issue by dyb881** [remaxjs/remax#1146]
**bug 描述**
web端 访问未注册的路由，会显示空白页面

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
可以跳到首页

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by dyb881** [comment]
希望支持访问未注册路由的处理

**Comment by yesmeck** [comment]
可以参考 next.js 支持自定义 404 页面。

https://nextjs.org/docs/advanced-features/custom-error-page#404-page

**Comment by dyb881** [comment]
那就直接在 404 页面加个重定向规避这种问题吧
