### ISSUE TITLE
createHostComponent注册基础组件无法使用

### ISSUE THREAD

**Issue by Timooooooo** [remaxjs/remax#1158]
**问题描述**
[详细地描述问题，让大家都能理解]
我使用remax开发淘宝千牛PC端小程序，想使用小程序原生的基础组件，使用了createHostComponent注册了组件，发现简单组件是可以注册成功的，但是嵌套类型组件，注册之后无法使用，相关参数也没办法配置，示例给了一个button组件和一个select组件，存在的问题是，button组件加载不到样式，select组件加载不到option,请问如何进行该基础组件的注册
**示例代码**
[如果有必要，展示代码，线上示例，或仓库]
`import * as React from 'react';
import { View } from 'remax/ali';
import styles from './index.css';
import { createHostComponent } from 'remax/macro';
const Button = createHostComponent('button', [
  'type',
  // 支持传入一个数组来做属性别名
  ['class', 'className'],
]);
const Select = createHostComponent('select', [
  'defaultValue',
  'showSearch',
  'hasClear',
  // 支持传入一个数组来做属性别名
  ['class', 'className'],
]);
const Option = createHostComponent('option', [
  'value',
  // 支持传入一个数组来做属性别名
  ['class', 'className'],
]);
export default () => {
  return (
    <View className={styles.app}>
      <View className={styles.header}>
        <Button type="normal" >我是按钮</Button>
        <Select defaultValue="jack" showSearch hasClear>
            <Option value="jack">Jack</Option>
            <Option value="frank">Frank</Option>
            <Option value="hugo">Hugo</Option>
        </Select>
      </View>
    </View>
  );
};
`
**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/22143058/87508274-94ff1200-c6a1-11ea-92a4-d9d258bfe550.png)

**Comment by yesmeck** [comment]
button 组件是有样式的。 select 组件需要特殊处理下。。。

**Comment by yesmeck** [comment]
开发这个 PC 版估计坑还比较多的。@Timooooooo  能否帮忙看看其他组件还有没有问题，我统一看看怎么处理下。

**Comment by Timooooooo** [comment]
是的，table组件也有问题

**Comment by Timooooooo** [comment]
还有要集成一个扩展组件mini-router和iframe

**Comment by Timooooooo** [comment]
要是有有一个统一的方案我可以自己注册，改写也可以的，现在完全没有思路。

**Comment by Darmody** [comment]
这个问题是不是和 createHostComponent 无关?

**Comment by Darmody** [comment]
看起来是目前无法适用淘宝 PC 小程序组件
