### ISSUE TITLE
文档中有没有代码调试source-map的相关配置说明

### ISSUE THREAD

**Issue by ts-study** [remaxjs/remax#1159]
**需求描述**
想调试源码，但现在默认生成的dist文件夹下没有source-map的文件，不支持源码调试，如果有的话，请在文档中说明，如果没有也请在文档中说明一下啊！

**Comment by Darmody** [comment]
你可以试试修改 webpack 配置生成 sourcemap，但是不确定小程序 IDE 能否搭配使用 sourcemap

**Comment by z-juln** [comment]
remax.config.js下配置
`
/** @type {import('@remax/types').Options} */
module.exports = {
  one: true,
  output: 'dist/' + process.env.REMAX_PLATFORM,
  configWebpack({ config }) {
    config.set('devtool', 'source-map'); // 这一行
  },
  plugins: [require('@remax/plugin-less')()],
};
`
