### ISSUE TITLE
[BUG] Text decode 属性不生效

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#1166]

**Comment by wangfandev** [comment]
import React from 'react';
import { View, Text } from '@tarojs/components';

export default function TextDemo() {

  return (
    <View>
      <Text decode dangerouslySetInnerHTML={{ __html: '测试换行\nxxxx' }} />
    </View>
  );
}

decode属性设置后，\n换行符没有作用，紧急求助@Darmody @yesmeck
