### ISSUE TITLE
[BUG]微信小程序端样式加载顺序有问题

### ISSUE THREAD

**Issue by wuhuanda** [remaxjs/remax#1176]
**bug 描述**
从组件外部传入的样式无法覆盖组件内部样式。

**复现步骤**

**期望结果**
从组件外部传入的样式能够覆盖组件内部样式。

**复现代码**
https://github.com/wuhuanda/remax-style-bugs-demo

**版本信息:**

- remax 版本: [e.g. 2.7.3]
- 小程序端 [e.g. 微信小程序]
- 开发环境 [e.g. win10]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
https://github.com/wuhuanda/remax-style-bugs-demo/blob/master/src/pages/index/index.js#L4-L6

样式文件引入顺序决定了优先级
