### ISSUE TITLE
打出来的remax-vendors.js包太大了 超出2mb了

### ISSUE THREAD

**Issue by XYH1996** [remaxjs/remax#1177]
如题

**Comment by yesmeck** [comment]
可以用 `-a` 参数分析下什么原因 `remax build -a`

**Comment by Darmody** [comment]
https://remaxjs.org/faq#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E4%B8%8B-remax-build---watch-%E6%97%A0%E6%B3%95%E7%9C%9F%E6%9C%BA%E9%A2%84%E8%A7%88

看看是不是开发模式不压缩的问题

**Comment by XYH1996** [comment]
> https://remaxjs.org/faq#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F%E4%B8%8B-remax-build---watch-%E6%97%A0%E6%B3%95%E7%9C%9F%E6%9C%BA%E9%A2%84%E8%A7%88
> 
> 看看是不是开发模式不压缩的问题

的却是，打开了compressTemplate效果也不明显，包还是很大，用了-m打包就好了很多

**Comment by 18086829907** [comment]
remax build -m 打包出来的文件大小确实变小了，但是没有办法正常运行呢？

**Comment by 18086829907** [comment]
![Uploading image.png…]()

**Comment by 18086829907** [comment]
VM512:9 app.js错误:
 ReferenceError: my is not defined
    at runtime.js? [sm]:1
    at runtime.js? [sm]:1
    at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1)
    at n (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1)
    at app.js? [sm]:1
    at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1)
    at <anonymous>:7:9
    at doWhenAllScriptLoaded (<anonymous>:97:21)
    at Object.scriptLoaded (<anonymous>:125:5)
    at Object.<anonymous> (<anonymous>:150:22)(env: Windows,mp,1.06.2212011; lib: 2.29.0)
(anonymous) @ VM512:9
doWhenAllScriptLoaded @ VM505:97
scriptLoaded @ VM505:125
(anonymous) @ VM505:150
Promise.then (async)
(anonymous) @ VM505:171
(anonymous) @ VM505:175
loadScripts @ assubloader.js:1
async function (async)
loadScripts @ assubloader.js:1
loadAppResourceScripts @ assubloader.js:1
(anonymous) @ appservice.app.js:5
evalScript @ VM12 subasdebug.js:1
I @ VM12 subasdebug.js:1
t.loadJsFiles @ VM12 subasdebug.js:1
batchLoadJsFiles @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
loadJsFiles @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
L @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
Pe @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
l.emit @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
emit @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
(anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
emit @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1
c @ VM9 asdebug.js:10
r @ VM9 asdebug.js:10
(anonymous) @ VM482:13
Promise.then (async)
(anonymous) @ VM482:5
loadScripts @ assubloader.js:1
(anonymous) @ assubloader.js:1
e @ assubloader.js:1
(anonymous) @ assubloader.js:1
Promise.then (async)
e @ assubloader.js:1
(anonymous) @ assubloader.js:1
Promise.then (async)
e @ assubloader.js:1
(anonymous) @ assubloader.js:1
Promise.then (async)
e @ assubloader.js:1
(anonymous) @ assubloader.js:1
Promise.then (async)
e @ assubloader.js:1
proceedAsyncTasks @ assubloader.js:1
submitSerialAsyncTasks @ assubloader.js:1
(anonymous) @ VM468:2
t.loadScripts @ VM9 asdebug.js:10
loadAppService @ VM9 asdebug.js:10
messagerCallback @ VM9 asdebug.js:10
(anonymous) @ VM9 asdebug.js:1
f @ VM9 asdebug.js:1
g @ VM9 asdebug.js:1
(anonymous) @ VM9 asdebug.js:1
_ws.onmessage @ VM9 asdebug.js:1
WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 ReferenceError: my is not defined
    at runtime.js? [sm]:1
    at runtime.js? [sm]:1
    at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1)
    at n (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1)
    at app.js? [sm]:1
    at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1)
    at <anonymous>:7:9
    at doWhenAllScriptLoaded (<anonymous>:97:21)
    at Object.scriptLoaded (<anonymous>:125:5)
    at Object.<anonymous> (<anonymous>:150:22)(env: Windows,mp,1.06.2212011; lib: 2.29.0)

**Comment by watsonhaw5566** [comment]
> VM512:9 app.js错误: ReferenceError: my is not defined at runtime.js? [sm]:1 at runtime.js? [sm]:1 at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1) at n (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1) at app.js? [sm]:1 at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1) at :7:9 at doWhenAllScriptLoaded (:97:21) at Object.scriptLoaded (:125:5) at Object. (:150:22)(env: Windows,mp,1.06.2212011; lib: 2.29.0) (anonymous) @ VM512:9 doWhenAllScriptLoaded @ VM505:97 scriptLoaded @ VM505:125 (anonymous) @ VM505:150 Promise.then (async) (anonymous) @ VM505:171 (anonymous) @ VM505:175 loadScripts @ assubloader.js:1 async function (async) loadScripts @ assubloader.js:1 loadAppResourceScripts @ assubloader.js:1 (anonymous) @ appservice.app.js:5 evalScript @ VM12 subasdebug.js:1 I @ VM12 subasdebug.js:1 t.loadJsFiles @ VM12 subasdebug.js:1 batchLoadJsFiles @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 loadJsFiles @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 L @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 Pe @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 l.emit @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 emit @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 (anonymous) @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 emit @ WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 c @ VM9 asdebug.js:10 r @ VM9 asdebug.js:10 (anonymous) @ VM482:13 Promise.then (async) (anonymous) @ VM482:5 loadScripts @ assubloader.js:1 (anonymous) @ assubloader.js:1 e @ assubloader.js:1 (anonymous) @ assubloader.js:1 Promise.then (async) e @ assubloader.js:1 (anonymous) @ assubloader.js:1 Promise.then (async) e @ assubloader.js:1 (anonymous) @ assubloader.js:1 Promise.then (async) e @ assubloader.js:1 (anonymous) @ assubloader.js:1 Promise.then (async) e @ assubloader.js:1 proceedAsyncTasks @ assubloader.js:1 submitSerialAsyncTasks @ assubloader.js:1 (anonymous) @ VM468:2 t.loadScripts @ VM9 asdebug.js:10 loadAppService @ VM9 asdebug.js:10 messagerCallback @ VM9 asdebug.js:10 (anonymous) @ VM9 asdebug.js:1 f @ VM9 asdebug.js:1 g @ VM9 asdebug.js:1 (anonymous) @ VM9 asdebug.js:1 _ws.onmessage @ VM9 asdebug.js:1 WAServiceMainContext.js?t=wechat&s=1672737684335&v=2.29.0:1 ReferenceError: my is not defined at runtime.js? [sm]:1 at runtime.js? [sm]:1 at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1) at n (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1) at app.js? [sm]:1 at S (WASubContext.js?t=wechat&s=1672737684335&v=2.29.0:1) at :7:9 at doWhenAllScriptLoaded (:97:21) at Object.scriptLoaded (:125:5) at Object. (:150:22)(env: Windows,mp,1.06.2212011; lib: 2.29.0)

新开一个问题，贴一下你的 remax.config.js

**Comment by cdl235** [comment]
打包："build": "cross-env NODE_ENV=production remax build -m -t wechat"
