### ISSUE TITLE
[BUG]getBluetoothAdapterState在IOS端报错??

### ISSUE THREAD

**Issue by joesdu** [remaxjs/remax#1178]
**bug 描述**
![image](https://user-images.githubusercontent.com/13188169/88125855-c11b1580-cc02-11ea-805f-3afb0f40188a.png)

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
怎么调用的呢？

**Comment by joesdu** [comment]
> 怎么调用的呢？
![image](https://user-images.githubusercontent.com/13188169/88126441-10157a80-cc04-11ea-88ce-3985bd88b3c1.png)
如图调用IOS就报错了,安卓没问题.

**Comment by Darmody** [comment]
finally 这个不是所有环境都能用吧？

**Comment by Darmody** [comment]
看起来和 `getBluetoothAdapterState` 没有关系。是 finally 支不支持的问题

**Comment by joesdu** [comment]
> 看起来和 `getBluetoothAdapterState` 没有关系。是 finally 支不支持的问题

这个是报这个东西没有then,catch和finally这些方法.我改成官网那个版本试试吧

**Comment by joesdu** [comment]
> 看起来和 `getBluetoothAdapterState` 没有关系。是 finally 支不支持的问题

我看过了,不只是这一个函数,好几个蓝牙相关的函数,用了promise后,在IOS端都无法识别.
