### ISSUE TITLE
支持 windows 开发

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#118]

**Comment by yesmeck** [comment]
https://github.com/umijs/umi/blob/2e2943415d77aa064cafd9c92339315cc67e8ee6/packages/umi-utils/src/winPath.js

据说把所有用到 `__dirname` 和 `__filename` 的 path 这么处理下就可以了。

**Comment by yesmeck** [comment]
算 bug 吧

**Comment by Darmody** [comment]
就是处理 slash 咯

**Comment by yesmeck** [comment]
有没有 windows，跑一下看看还有没有别的问题。
