### ISSUE TITLE
[问题]在remax配置中关闭了pxToRpx之后引入第三方ui库，第三方库样式尺寸如何转换？

### ISSUE THREAD

**Issue by XYH1996** [remaxjs/remax#1181]
**问题描述**
引入了anna-remax-ui库后里面样式是使用px，当我关闭了pxToRpx后如何能对这个第三方库样式进行pxToRpx转换，而不影响到我本身的样式

**其他信息**
anna-ui部分css:
![image](https://user-images.githubusercontent.com/34530396/88250620-b3d15a00-ccda-11ea-9e42-04ba50e2cea6.png)

**Comment by yesmeck** [comment]
关闭后自己配置下插件，参考 https://github.com/remaxjs/remax/issues/1070#issuecomment-643865487

**Comment by yesmeck** [comment]
在 postcss.config.js  中配置，参考 https://remaxjs.org/guide/config/postcss
