### ISSUE TITLE
小程序开发模式下开启压缩后手机预览无法正常打开小程序

### ISSUE THREAD

**Issue by PlutoCA** [remaxjs/remax#1184]
**bug 描述**
微信小程序开发模式下开启`-m`压缩后手机无法正常打开小程序
错误信息如下
`"dev": "remax build -t wechat -w -m",`
![image](https://user-images.githubusercontent.com/31099607/88451691-487aba00-ce8b-11ea-93c8-febee84f81a4.png)
开发工具能正常访问，手机通过开发工具真机调试可以正常访问，就是无法通过预览。

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
正常使用

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 2.7.3]
- 手机型号 [e.g. iPhone 11]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
一般这种情况要把 dist 目录删掉重新生成，或者重启 IDE 等操作来解决。

如果解决不了来个复现 demo 看看

**Comment by PlutoCA** [comment]
我这边` npx create-remax-app my-app` 跑出来的也直接报错 [demo仓库地址](https://github.com/PlutoCA/remax-issues-demo) @Darmody 老哥帮看下

**Comment by PlutoCA** [comment]
em....

**Comment by Darmody** [comment]
不好意思一直没时间看。。今晚我看看

PlutoCA <notifications@github.com> 于 2020年7月29日周三 上午10:19写道：

**Comment by PlutoCA** [comment]
好的👌 麻烦了哈

**Comment by yesmeck** [comment]
@PlutoCA 我这边用你提供的仓库测试没复现错误。

![20200729162051](https://user-images.githubusercontent.com/465125/88775646-893e4000-d1b7-11ea-8347-0a6230ec8e0e.jpg)

**Comment by PlutoCA** [comment]
> @PlutoCA 我这边用你提供的仓库测试没复现错误。
> 
> ![20200729162051](https://user-images.githubusercontent.com/465125/88775646-893e4000-d1b7-11ea-8347-0a6230ec8e0e.jpg)

手机预览呢。我这边和同事打开都有问题，一个iPhone11 一个7

**Comment by yesmeck** [comment]
@PlutoCA 预览也没问题。

我这的 IDE 版本 1.04.2007282，Node 版本 12.16.3

**Comment by PlutoCA** [comment]
我去 我找到复现的情况了。
@yesmeck 
你们开发工具导入项目的时候把所有文件导入进去，不要单独导入`dist`目录，就会出现这个情况了
。
我切到dist 就正常了。。。。
![image](https://user-images.githubusercontent.com/31099607/88889239-66249680-d272-11ea-8b5d-bb8832002763.png)

**Comment by yesmeck** [comment]
看起来是 IDE 的 bug。

**Comment by PlutoCA** [comment]
害

**Comment by yesmeck** [comment]
@PlutoCA 要把自动压缩混淆关掉 `"minified": false`

**Comment by PlutoCA** [comment]
ok 看到了，打开这个就去世了。感谢🙏
