### ISSUE TITLE
[问题]remax-vendor 过大

### ISSUE THREAD

**Issue by XYH1996** [remaxjs/remax#1185]
**问题描述**
使用-m打包后remax-vendor还有1.4M 加上图片也都打在wechat根目录下，根本没办法预览啊 分分钟超过2M

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
![微信截图_20200725213019](https://user-images.githubusercontent.com/34530396/88458157-8f35d780-cebe-11ea-9c8f-16d36d471b9b.png)

**Comment by PlutoCA** [comment]
这么大的图片别存本地吧

**Comment by XYH1996** [comment]
> 这么大的图片别存本地吧

删掉一个500kb的和一个100kb的图片也达到了1.9M 还是用了分包的情况，功能才开发了1/4

**Comment by cdl235** [comment]
"build": "cross-env NODE_ENV=production remax build **-m** -t wechat"
