### ISSUE TITLE
[BUG]头条小程序报错

### ISSUE THREAD

**Issue by winteraq** [remaxjs/remax#1186]
**bug 描述**
头条 2.7.4 版本启动报错，2.7.3正常
![image](https://user-images.githubusercontent.com/26573933/88481523-84e30e80-cf8e-11ea-92e2-7a3655463648.png)

**复现步骤**
使用2.7.4 remax即可
**版本信息:**

- remax 版本: 2.7.4

**其他信息**

**Comment by yesmeck** [comment]
亲测没问题啊， @winteraq 可以提供一个复现的 repo 么。

**Comment by QC-L** [comment]
@winteraq 请检查开发者工具的版本，非最新版本会存在运行时编译问题，如在遇到请升级至最新。
