### ISSUE TITLE
[BUG] 使用lodash中floor函数打包生产环境报错

### ISSUE THREAD

**Issue by zxtyjx** [remaxjs/remax#1204]
**bug 描述**
使用import floor from 'lodash/floor';方式引入floor函数，
开发模式（dev）下没有问题，但是生产环境（build）下回报:
TypeError: nativeIsFinite is not a function

[详细地描述 bug，让大家都能理解]

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
`import floor from 'lodash/floor';

const priceValue = useMemo(() => {
    return floor(props.minPrice / 1000, 2);
  }, [props.minPrice])
`
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [2.6.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by zxtyjx** [comment]
业务数据错误

**Comment by zxtyjx** [comment]
经测试，使用import {floor} from 'lodash';方式引入就没有问题

**Comment by yesmeck** [comment]
先去人下原生小程序中使用 ` 'lodash/floor';` 是否有问题。

**Comment by zxtyjx** [comment]
小程序限制
