### ISSUE TITLE
web产物不能运行在自定义目录里

### ISSUE THREAD

**Issue by juvham** [remaxjs/remax#1210]
http服务只能以web目录为根目录。
如果http服务在web目录的上级目录会导致 web/index.html 引用js和cs报错
web产物 html里的 js 和css 应该为相对路径

**Comment by yesmeck** [comment]
可以自己设置下 publicPath

**Comment by juvham** [comment]
在哪里设置？是在webpack配置里还是在 app.config.js里 能给个文档么。

**Comment by Darmody** [comment]
https://remaxjs.org/guide/config/remax#configwebpack

**Comment by juvham** [comment]
thanks ,这个最好在文档里面能写出来。感觉现在是有很多隐藏功能，文档里没有的。

**Comment by Darmody** [comment]
> thanks ,这个最好在文档里面能写出来。感觉现在是有很多隐藏功能，文档里没有的。

🤔可以把常问的一些问题写成 FAQ
