### ISSUE TITLE
[BUG] 使用vant中sticky组件问题

### ISSUE THREAD

**Issue by zxtyjx** [remaxjs/remax#1219]
**bug 描述**
使用Sticky组件中container属性时异常，通过官方文档该属性为func类型，我传递进入一个function，但是通过调试发现传入的数据变成了string类型，如下：

![image](https://user-images.githubusercontent.com/8037264/89773786-2e053980-db37-11ea-8ce9-4c8686f41874.png)

尝试在传递参数的名称之前加入bind和catch情况都相同，是否remax在传递function给小程序组件时有什么特殊要求或者写法？

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
跟 https://github.com/remaxjs/remax/issues/707 是同一个问题，Remax 现在没法给小程序自定义组件传一个函数。

**Comment by Darmody** [comment]
就保留 #707 open 吧
