### ISSUE TITLE
[BUG] usePageEvent 同路由转跳时，历史页面的事件也被触发

### ISSUE THREAD

**Issue by k55k32** [remaxjs/remax#1225]
**bug 描述**
当使用 usePageEvent 的时候， 页面路径相同，参数不同时，转跳后，之前路由的页面响应的event也会被触发

**复现步骤**
写一个页面，监听 `usePageEvent('onShow', () => console.log('hello'))` 事件，页面写个按钮，也是跳到这个当前页面，可以传不同参数

**期望结果**
同页面路径转跳后，`hello` 只被输出一次

**版本信息:**

- remax 版本: [e.g. 2.7.7]
- 手机型号 [e.g. 开发者工具]
- 小程序端 [e.g. 支付宝小程序]
- 开发环境 [e.g. win10]

**Comment by Darmody** [comment]
是 web 环境的问题吗？

**Comment by k55k32** [comment]
> 是 web 环境的问题吗？



> 是 web 环境的问题吗？

支付宝小程序开发者工具中出现的问题

**Comment by Darmody** [comment]
@k55k32 我试了试没有复现额

**Comment by Darmody** [comment]
> @k55k32 我试了试没有复现额

微信没问题，支付宝确实有问题🤔
