### ISSUE TITLE
[BUG]remax/one 中 onTouchEnd touches 、changedTouches 数组为空

### ISSUE THREAD

**Issue by wyh-skr** [remaxjs/remax#1229]
**bug 描述**
使用remax/one 中 View onTouchEnd事件 touches 、changedTouches数组为空；使用remax/ali 的View onTouchEnd 事件  touches 也为空，changedTouches数组有值。remax 版本2.6.0

**Comment by Darmody** [comment]
remax/one 中 onTap 是 TapEvent 。只有 TouchEvent 才会有 touches 这些属性。比如可以在 onTouchStart 中获取。

不过可以考虑将 touches 这些属性加入到 TapEvent 中🤔
