### ISSUE TITLE
请问使用TS进行remax开发,调用原生组件时props属性为中划线的Ts检查配置[问题]

### ISSUE THREAD

**Issue by zxtyjx** [remaxjs/remax#1231]
**问题描述**
我在用ts进行remax开发，但是发现调用原生组件时需要传入中划线，但是ts检查是不支持的，这个咱们有没有好的解决方案？

比如Vant的button组件
![image](https://user-images.githubusercontent.com/8037264/90349844-c76ba880-e06d-11ea-9d8a-a3817d73c9c9.png)
这些属性目前我没有方法传入

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
讲道理不会吧？是不是你没有写 Button 的定义？要么就是你 eslint 的校验？

**Comment by yesmeck** [comment]
鼠标放上去看下具体的错误信息
