### ISSUE TITLE
[需求/讨论]关于remax如何支持淘宝千牛PC端小程序组件的探讨

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [remaxjs/remax#1238]
**场景**
开发 淘宝-商家应用PC版-[使用千牛PC组件](https://miniapp.open.taobao.com/docV3.htm?docId=117038&docType=1&source=search) 的小程序

**需求**
让`createHostComponent`正确编译出千牛PC组件

**问题**
只要是**嵌套的且remax未支持**的原生组件，使用[createHostComponent](https://remaxjs.org/api/remax-macro#createhostcomponentname-props)，就不能正确编译出来

**场景还原**
比如我要使用千牛PC组件的 [tab](https://miniapp.open.taobao.com/docV3.htm?docId=118131&docType=1&source=search)

```jsx
import React, { useState, useEffect } from 'react';
import { View } from 'remax/one';
import { createHostComponent } from 'remax/macro';

const Tab1 = createHostComponent('tab', []);
const TabItem = createHostComponent('tab-item', []);

const TabsComp = () => {
  return (
    <Tab1>
      <TabItem
        title="aaa"
        key="aaa"
       children1="ccc"
      >
        ccc
      </TabItem>
      <TabItem
        title="bbb"
        key="bbb"
        children1="ddd"
      >
        ddd
      </TabItem>
    </Tab1>
  );
};

export default TabsComp;
```
运行命令`yarn run dev ali`
找到`dist/ali/pages/index/index.axml`，可以看到：
```jsx
<template name="REMAX_TPL_1_tab">
  <tab>
    <block a:for="{{item.children}}" key="{{item.id}}">
      <template is="REMAX_TPL_1_CONTAINER" data="{{item: item}}" />
    </block> 
  </tab>
</template>

<template name="REMAX_TPL_1_tab-item">
  <tab>
    <tab-item a:for="{{item.children}}" key="{{item.id}}">
        ccccc
    </tab-item>
  </tab>
</template>
```
**可以发现，tab-item没有嵌套在tab中，导致未能正确渲染组件！**

![image](https://user-images.githubusercontent.com/26433572/90499057-a4c7b580-e17b-11ea-9e44-a865e0d95192.png)

手动拼接后，可以渲染出来：
```jsx
<template name="REMAX_TPL_1_tab">
  <tab >
     <tab-item
      a:for="{{item.children}}"
      a:for-item="oneItem"
      key="{{oneItem.props.key}}"
      title="{{oneItem.props.title}}"
     >
       {{oneItem.props.children1}}
     </tab-item>
  </tab>
</template>
```

![image](https://user-images.githubusercontent.com/26433572/90515158-d00ace80-e194-11ea-97d5-c62b89289003.png)

**解决方案**
也就是说，我们需要在源码上的`createHostComponent`，单独为「千牛PC」组件做编译处理。

**与千牛PC组件相关的issue**
- [createHostComponent注册基础组件无法使用](https://github.com/remaxjs/remax/issues/1158)

**Comment by AttackXiaoJinJin** [comment]
部分组件的支持情况：

| 组件 | remax |anna-remax-ui|参考图片|
| ------ | ------ |------|------|
| [tab](https://miniapp.open.taobao.com/docV3.htm?docId=118131&docType=1&source=search) | **不支持嵌套的tab-item** |**简单使用**|![image](https://user-images.githubusercontent.com/26433572/90515825-c46bd780-e195-11ea-9c0a-c34e072d560c.png)| 
| [table](https://miniapp.open.taobao.com/docV3.htm?docId=117327&docType=1&source=search) | **不支持嵌套的table-column** |**暂未实现**|![image](https://user-images.githubusercontent.com/26433572/90515884-d9486b00-e195-11ea-9270-b22c628e01bf.png)| 
| [date-picker](https://miniapp.open.taobao.com/docV3.htm?docId=117328&docType=1&source=search) | **简单使用** |**暂未实现**|![image](https://user-images.githubusercontent.com/26433572/90515934-ec5b3b00-e195-11ea-9981-b52b7918d8a6.png)| 
| [switch](https://miniapp.open.taobao.com/docV3.htm?docId=117031&docType=1&source=search) | **只有样式** |**简单使用**|![image](https://user-images.githubusercontent.com/26433572/90516013-03019200-e196-11ea-8fa7-9c4ea6212704.png)| 
| [button](https://miniapp.open.taobao.com/docV3.htm?docId=117031&docType=1&source=search) | **点击后样式不能恢复** |**样式混乱**|![image](https://user-images.githubusercontent.com/26433572/90516066-16146200-e196-11ea-8946-22bc22e366ef.png)| 
| [ballon](https://miniapp.open.taobao.com/docV3.htm?spm=a219a.7386797.0.0.669c669aDcWw7U&source=search&docId=118107&docType=1) | 暂不支持 |暂不支持|![image](https://user-images.githubusercontent.com/26433572/90516130-27f60500-e196-11ea-8906-5def8096f32a.png)|

**Comment by yesmeck** [comment]
我在想是不是可以再加个参数可以自定义组件的渲染模板。

```js
createHostComponent('tab',  [], `
  <tab >
     <tab-item
      a:for="{{item.children}}"
      a:for-item="oneItem"
      key="{{oneItem.props.key}}"
      title="{{oneItem.props.title}}"
     >
       {{oneItem.props.children1}}
     </tab-item>
  </tab>
`)
```

**Comment by 569202812** [comment]
千牛pc端预览可以正常使用吗

**Comment by yesmeck** [comment]
建议还是不要用来开发千牛小程序吧，问题太多了。
