### ISSUE TITLE
[BUG] remax/one 的 Input 非受控模式下在微信端会闪烁

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#1240]
**bug 描述**

https://streamable.com/e3qi7w

**复现步骤**

```js
<Input type="text" />
```

**Comment by Darmody** [comment]
由于只有 IOS 才会有这个现象。应该和官方的这个问题相关 https://developers.weixin.qq.com/community/develop/doc/000662f6bf48c8ed515aa98af5b800?page=1#comment-list
