### ISSUE TITLE
[需求]能否使用微信小程序的生成骨架屏

### ISSUE THREAD

**Issue by vscing** [remaxjs/remax#1242]
**需求描述**
[详细地描述需求，让大家都能理解]

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
有链接吗

**Comment by vscing** [comment]
> 有链接吗
https://developers.weixin.qq.com/miniprogram/dev/devtools/skeleton.html

**Comment by Darmody** [comment]
看了下，应该能生成后当做自定义组件使用，可以试试

**Comment by vscing** [comment]
> 看了下，应该能生成后当做自定义组件使用，可以试试

好的
