### ISSUE TITLE
[问题]remax 中使用 mobx 的class写法， 如何实现

### ISSUE THREAD

**Issue by EvanJin** [remaxjs/remax#1244]
**问题描述**
[详细地描述问题，让大家都能理解]
想在remax(typescript version)中使用mobx，store的写法希望能按照class 方式组织，修改了下example里面的 wechat-mobx, 发现数据修改完成后，视图层并没有重新触发rerender 机制，希望有个demo看下实现方式

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]
TodoStore.ts
![image](https://user-images.githubusercontent.com/1031636/90879311-4dbf1c00-e3d9-11ea-9cf8-ec99ca8bb349.png)

useStores.ts
![image](https://user-images.githubusercontent.com/1031636/90879371-629baf80-e3d9-11ea-85f0-56220101afa2.png)

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/1031636/90878875-ae9a2480-e3d8-11ea-8e5c-110cf5e5f910.png)

**Comment by farzer** [comment]
👀

**Comment by yesmeck** [comment]
参考 https://juejin.im/post/6864359719121715213
