### ISSUE TITLE
[BUG]物料中使用了 `onShareAppMessage` 时，接入时需要 usePageEvent('onShareAppMessage', () => {}) 才会生效

### ISSUE THREAD

**Issue by inJs** [remaxjs/remax#1245]
**bug 描述**
最近在落地 remax 最佳实践，该实践会讲大量的业务模块拆成不同粒度的物料。其中有 *页面* 粒度的物料（以下简称物料）。
当物料中使用了 `onShareAppMessage` 这个 API 时，如果：
```javascript
React.forwardRef((props, ref) => {
   return <MyPage {...props} ref={ref}  />
})
```
这样接入的话，会导致物料中的 `onShareAppMessage` 始终不会被触发。需要做如下调整：

```javascript
React.forwardRef((props, ref) => {
   usePageEvent('onShareAppMessage', noop)
   return <MyPage {...props} ref={ref}  />
})
```
**版本信息:**

- remax 版本: 2.7.7
- 小程序端 ：支付宝
- 开发环境 ： mac OS

**Comment by whereiscode** [comment]
你用usePageEvent('onShareAppMessage', () => {})  有效果？
我用usePageEvent('onShareAppMessage', () => {})  直接就报错了 react hook的错
