### ISSUE TITLE
[BUG] mobx decorator @computed语法报错

### ISSUE THREAD

**Issue by EvanJin** [remaxjs/remax#1246]
**bug 描述**
mobx 开启decorator方式，@computed语法在微信小程序中报下图的错误

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: 2.7.8
- mobx 版本: 5.15.6
- mobx-react 版本: 6.2.5
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/1031636/90897967-81f60500-e3f8-11ea-830a-9ec183cdeb9f.png)

**Comment by yesmeck** [comment]
提供下重现的仓库吧

**Comment by yesmeck** [comment]
参考 https://juejin.im/post/6864359719121715213
