### ISSUE TITLE
[BUG]跨平台开发时，在不同后缀名文件里引入自定义组件，编译后的页面配置文件中没有引入组件

### ISSUE THREAD

**Issue by Highnesslin** [remaxjs/remax#1247]
**bug 描述**
[小程序跨平台开发时根据文件后缀名区分平台](https://remaxjs.org/guide/one#%E4%BD%BF%E7%94%A8%E6%96%87%E4%BB%B6%E5%90%8D%E5%90%8E%E7%BC%80%E5%8C%BA%E5%88%86%E4%B8%8D%E5%90%8C%E5%B9%B3%E5%8F%B0%E4%BB%A3%E7%A0%81)，文件内引入第三方组件（比如mini-ali-ui），编译生成的页面配置文件（index.json）没有自动引入组件。

**复现步骤**
- src/component/Input/index.ts
   ```
   import React from "react"
   import InputItem from "mini-ali-ui/es/input-item"
   import { InputProps } from "remax/ali"

   const input: React.FC<InputProps> = props =>
      React.createElement(InputItem, props)

   export default input
   ```

- src/component/Input/index.wechat.ts
   ```
   import React from "react"
   import { Input } from "remax/wechat"
   import { InputProps } from "remax/wechat"
   import { InputProps as InputParams } from "remax/ali"

   const input: React.FC<InputProps & InputParams> = props =>
      React.createElement(Input, {
         ...props,
         bindinput: props.onInput
      }
   )

   export default input
   ```
- src/pages/index.ts
   ```
   import Input from "@/component/Input"
   ```

编译后生成的文件
- pages/index/index.json
   ```
   {
      "usingComponents": {}
   }
   ```

**期望结果**
编译后生成的页面配置文件
- pages/index/index.json
   ```
   {
      "usingComponents": {
         "index": "/remaxVendors/npm/mini-ali-ui/es/input-item/index"
      }
   }
   ```

**版本信息:**

- remax 版本: [e.g. 2.7.7]
- 手机型号 [e.g. iPhone 6]
- 小程序端 [e.g. 钉钉小程序]
- 开发环境 [e.g. windows 10]

**Comment by Darmody** [comment]
为啥我试了一下没问题额

**Comment by Darmody** [comment]
这个问题并不是跨平台后缀。而是使用原生自定义组件时，由于 remax 需要静态分析，因此不能用 `createElement` 的方式使用。只能用 JSX 标签使用。
