### ISSUE TITLE
[BUG]外部节点发生变化，scrollView会自动滚动到顶部

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#1254]
**bug 描述**
外部节点发生变化，scrollView会自动滚动到顶部

**复现步骤**
demo里scrollView滚动到一定距离，再点显示按钮scrollView就回到顶部了

**期望结果**
正常

**复现代码**
https://github.com/mushan0x0/remax-scroll-bug

**版本信息:**

- remax 版本: 2.7.7
- 开发环境: mac OS

**Comment by Darmody** [comment]
这个似乎是微信又改了什么东西。。我用了其他框架也会有这个问题。

**Comment by Darmody** [comment]
目前建议的解决方案是，用 useRef 去追踪 scrollTop 的值，伪代码：

```js
function Page() {
  const scrollTop = React.useRef();

  function handleScroll(event) {
    scrollTop.current = event.detail.scrollTop;
  }

  return <ScrollView onScroll={handleScroll} scrollY={true} scrollTop={scrollTop.current} />
}
```

**Comment by qiwang97** [comment]
https://developers.weixin.qq.com/community/develop/doc/0008c46e0a04586d86e7dbd2e5bc00   微信这个 bug 还没修复
