### ISSUE TITLE
[Bug] 2.0.0 是不是默认取消了对scss的支持？

### ISSUE THREAD

**Issue by zmofei** [remaxjs/remax#1263]
**bug 描述**

安装了`node-sass`之后在引入`xxx.scss`和`xx.module.scss`的时候，webpack-laoder报错，是取消了默认 scss的配置么还是一个bug？

使用的是 typescript的模板 `npx degit remaxjs/template-wechat-typescript mp-ocr`

**版本信息:**

- remax 版本: 2.0.0

**其他信息**

![image](https://user-images.githubusercontent.com/3351337/91843698-c307d800-ec88-11ea-82df-11dbebf0f97f.png)

```
"dependencies": {
    "anna-remax-ui": "^1.8.17",
    "node-sass": "^4.14.1",
    "react": "^16.12.0",
    "remax": "^2.0.0"
},
"devDependencies": {
    "@types/react": "^16.9.16",
    "cross-env": "^7.0.2",
    "typescript": "^3.7.3"
}
```

**Comment by zmofei** [comment]
排查了一下版本，升级到2.7.7也遇到了同样的问题
```
"dependencies": {
    "node-sass": "^4.14.1",
    "react": "^16.12.0",
    "remax": "^2.7.7"
},
"devDependencies": {
    "cross-env": "^7.0.2"
}
```

**Comment by zmofei** [comment]
项目打包目录入下：
[mp-ocr的副本.zip](https://github.com/remaxjs/remax/files/5155924/mp-ocr.zip)

**Comment by yesmeck** [comment]
对的，请使用 remix-plugin-sass https://github.com/remaxjs/plugins#%E6%8F%92%E4%BB%B6%E5%88%97%E8%A1%A8

**Comment by yesmeck** [comment]
插件使用参考 https://remaxjs.org/guide/advanced/plugin

**Comment by wujun4code** [comment]
@yesmeck 如何在最新版 2.10.1 上使用 scss 的样式?谢谢。我想用https://annasearl.github.io/annar/components/data-entry/radio 这个库，发现它都是 scss 写的。

**Comment by yesmeck** [comment]
@wujun4code  https://github.com/remaxjs/plugins/tree/master/packages/sass
