### ISSUE TITLE
[BUG] 千牛端开发模式下预览异常

### ISSUE THREAD

**Issue by GakkiiSmile** [remaxjs/remax#1265]
**bug 描述**
开发模式下，千牛小程序预览会预览出错，trycatch之后发现如下图报错，去除掉错误代码则能够正常预览。生产模式预览正常

**复现步骤**
npx create-remax-app my-app  初始化版本可直接复现

**期望结果**
希望能解决此问题

**版本信息:**

- remax 版本: [e.g. 2.7.8]
- 手机型号 [e.g. 千牛]
- 小程序端 [e.g. 千牛]
- 小程序版本[e.g. 最新版]
- 开发环境 [e.g. mac OS]

**其他信息**
![WechatIMG27](https://user-images.githubusercontent.com/18532706/91924372-11f35300-ed05-11ea-96d5-3e67074851f0.jpeg)
![WechatIMG28](https://user-images.githubusercontent.com/18532706/91924387-1c155180-ed05-11ea-90e8-5ac1ed48dae2.jpeg)
查看相关代码，有点像这个依赖问题
![WechatIMG26](https://user-images.githubusercontent.com/18532706/91924388-1f104200-ed05-11ea-93eb-bd6619113744.jpeg)

**Comment by Darmody** [comment]
千牛不在 remax 的支持范围内，有可能会有问题

**Comment by GakkiiSmile** [comment]
弄一个千牛的预览webpack插件，可供后来者踩坑。

/**
 * @extends {import('webpack').Plugin}
 */
class QnDevPlugin {
    /**
     *
     * @param {import('webpack').compilation.Compilation} compilation
     */
    emitHook(compilation) {
        if ("app.js" in compilation.assets) {
            /**
             * @type {string}
             */
            const sourceText = compilation.assets["app.js"].source();

            // 替换一下错误代码
            const changeAppFileString = sourceText.replace(
                `f && "onreadystatechange" in f.createElement("script")`,
                `f && f.createElement && "onreadystatechange" in f.createElement("script")`
            );

            compilation.assets["app.js"] = {
                source() {
                    return changeAppFileString;
                },
                size() {
                    return changeAppFileString.length;
                },
            };
        }
    }

    /**
     *
     * @param {import('webpack').Compiler} compiler
     */
    apply(compiler) {
        if (compiler.hooks) {
            compiler.hooks.emit.tap("QnDevPlugin", this.emitHook);
        }
    }
}

module.exports = QnDevPlugin;
