### ISSUE TITLE
如何解决 ScrollView 的 scrollTop 一直被更新的问题，需要出一份文档

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#1290]

**Comment by yesmeck** [comment]
或者单独出个 @remax/scroll-view 组件。

**Comment by Fuyun791** [comment]
hello， 我使用了scroll-view的组件，在使用过程中无法触发scroll相关的方法。onScrollToUpper，onScrollToLower，onScroll这些都没有发挥作用

**Comment by Darmody** [comment]
> hello， 我使用了scroll-view的组件，在使用过程中无法触发scroll相关的方法。onScrollToUpper，onScrollToLower，onScroll这些都没有发挥作用

看一下微信 scroll-view 的文档，有注意事项的
