### ISSUE TITLE
[BUG] npm run dev 报错

### ISSUE THREAD

**Issue by jihgao** [remaxjs/remax#1291]
**bug 描述**
初始化项目之后执行npm run dev报错

**复现步骤**
根据文档进行初始化之后执行npm run dev

**期望结果**
脚本成功执行

**复现代码**
根据官网get started初始化

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
![image](https://user-images.githubusercontent.com/1960578/93417375-8e2b9000-f8da-11ea-885b-8a6b4ede1b11.png)

**Comment by Darmody** [comment]
remax one 项目启动请提供 对应平台
