### ISSUE TITLE
Remax 的性能为何这么叼？

### ISSUE THREAD

**Issue by code-artisan** [remaxjs/remax#1293]
**问题描述**
Remax 的性能为何这么叼？单次 setState 始终是在 1ms 之内，是怎么做到的？

**示例代码**

**其他信息**
![image](https://user-images.githubusercontent.com/5195218/93470210-1eda8e00-f924-11ea-8b46-97d1f7b80df7.png)

**Comment by rikumi** [comment]
因为是逻辑层内部模拟操作，然后异步更新到视图层进行渲染，并不会等到视图层真正渲染完成再回调。
