### ISSUE TITLE
建议支持打包成app啊

### ISSUE THREAD

**Issue by chenzx023** [remaxjs/remax#1294]
**需求描述**
目前市面上好用的也就taro了 但是用hook还得自己改不方便建议remax能支持写app

**Comment by Darmody** [comment]
是指 支持 react native 之类的吗

**Comment by chenzx023** [comment]
> 是指 支持 react native 之类的吗

对啊 就是这样

**Comment by yesmeck** [comment]
暂无计划支持 React Native。
