### ISSUE TITLE
[问题]使用装饰器

### ISSUE THREAD

**Issue by kankungyip** [remaxjs/remax#1298]
**问题描述**
我用TS写代码使用装饰器特性，可以编译通过，但是在小程序端运行总是提示：
`TypeError: Super expression must either be null or a function`
我在`tsconfig.json`里面已经添加：
`"experimentalDecorators": true`

**Comment by yesmeck** [comment]
还需要配置下 babel，参考 https://juejin.im/post/6864359719121715213
