### ISSUE TITLE
css与wxml打包文件目录

### ISSUE THREAD

**Issue by yejinjian** [remaxjs/remax#130]
发现wxss与wxml 会被集中打包到  app.wxss 与 base.wxml 这个方式不利于分包

**Comment by Darmody** [comment]
app.wxss 我们可以不 extract，但是 base.wxml 确实是会合成一个文件

**Comment by Darmody** [comment]
closed via #685

**Comment by yvanwangl** [comment]
base.wxml 文件可以拆分不，这样可以减小主包大小
