### ISSUE TITLE
[需求] remax-styles.acss 样式被 app.acss 样式覆盖

### ISSUE THREAD

**Issue by qq1353709** [remaxjs/remax#1304]
**问题描述**
1. app.js 引入 `import 'anna-remax-ui/dist/anna.css';`
2. 多个页面引入同一个组件，dist 自动生成 `remax-styles.acss`
3. app.acss 出现第一条 `@import "./remax-styles.acss";` 后面为 `anna-remax-ui/dist/anna.css';` 样式，导致组件的样式被anna.css样式覆盖

**期望结果**
anna.css样式不覆盖组件的样式

**Comment by aototo** [comment]
我的跟你差不多，但是是开了plugins 插件配置后，组件的样式会被先引入，然后app.acss在继续引入，覆盖了组件的样式

**Comment by Darmody** [comment]
实际上样式的引入顺序都是和模块的 import 顺序挂钩的。

我猜测你们在 app 文件里有导出模块，并在其他页面引入了 app 文件。然后 app 的引入顺序在 组件的引入顺序之后，因此导致 样式顺序问题。

我在本地测试过了，和 import 模块的顺序有关，建议检查一下。
