### ISSUE TITLE
样式文件不做 extract

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#131]
**需求描述**
不需要把样式文件 extract 到 app.css 中。

**解决方案**
不做 extract

**其他信息**
#130

**Comment by Darmody** [comment]
由于组件也会单独生成一个目录，样式文件也会对应得放到组件目录下。但是小程序的样式必须放在 page 同级目录或者 component 同级目录下才能生效。而 remax 的组件并非小程序自定义组件，这会导致组件的样式生效。

要解决这个问题，就得追溯每个page引用的所有 js 文件，实现太过复杂，还是不切分了。

**Comment by yesmeck** [comment]
> 就得追溯每个page引用的所有 js 文件，实现太过复杂

其实现在有这么做了。。

**Comment by Darmody** [comment]
是要把这个page下所有相关的样式文件合并起来

**Comment by Darmody** [comment]
突然想到还有一个方式是，只切分page的样式，其他组件的样式依然合并入app.css

**Comment by yesmeck** [comment]
这里就看到 webpack 的好处了。。

**Comment by Darmody** [comment]
> 这里就看到 webpack 的好处了。。

hmmm,我搞了一个上午感觉越搞越复杂了逻辑

**Comment by Darmody** [comment]
其实主要是小程序的样式文件配置方式和模块引入模式的冲突。

1. 要先找出所有带有 css import entry 文件，并且要排除 app.css。
2. 

```js
// index.js
import 'xxx.module.css'
import '../../xxx.css'
```

必须找出 entry 中所有 import 的文件然后把他们合并，并且命名成和 `wxml` 相同的名字放在一个目录下。

3. 把非 entry 引用的 css 文件合并入 app.css

然后还有使用 less/sass 后，样式文件中的 import 会不会受影响还不确定。

**Comment by Pochodaydayup** [comment]
> 其实主要是小程序的样式文件配置方式和模块引入模式的冲突。
> 
> 1. 要先找出所有带有 css import entry 文件，并且要排除 app.css。
> 
> ```js
> // index.js
> import 'xxx.module.css'
> import '../../xxx.css'
> ```
> 
> 必须找出 entry 中所有 import 的文件然后把他们合并，并且命名成和 `wxml` 相同的名字放在一个目录下。
> 
> 1. 把非 entry 引用的 css 文件合并入 app.css
> 
> 然后还有使用 less/sass 后，样式文件中的 import 会不会受影响还不确定。

这里直接在 rollup-plugin-postcss 那里改就好了，应该跟 nativeComponent 那里的 generateBundle 的处理逻辑是一样的

**Comment by Darmody** [comment]
是的，我正在改

**Comment by Darmody** [comment]
还是先不搞了
