### ISSUE TITLE
[需求] 使用 remax 框架进行开发将被微信识别为使用了大量的收集信息 API，需要一个方案来规避

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#1325]
**需求描述**
在微信小程序后台有这样一个设置，入口路径是 “设置” > “功能设置” > “用户隐私保护指引”

![Lark20201013143123](https://user-images.githubusercontent.com/9160743/95823814-db2b4680-0d60-11eb-8b1f-6294452c84e5.png)

这个设置将被展示在 “点击小程序胶囊” > “点击小程序名称” > “更多资料” > “服务条款”

我们实际使用的 API 并没有这么多，猜测是因为 remax 中对 wx 大部分 api 的 promise 化导致的，微信官方应该是 AST 解析检查到有引用就直接算使用

**解决方案**
期望能够摇树自动移除未使用的 API 引用，或者提供一个配置项，允许开发者决定使用哪些 API 或者禁用哪些 API

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
不用猜测，是微信官方新上线的隐私。填写实际用途即可。

**Comment by WhiteMinds** [comment]
> 不用猜测，是微信官方新上线的隐私。填写实际用途即可。

实际用途是根本没用到。。那些都是框架引入的，被微信识别为小程序使用了大量的接口

**Comment by watsonhaw5566** [comment]
你想多了，就是一份表格，小程序后台都有，为这个玩意还给你写个AST检测，醒醒。

**Comment by Darmody** [comment]
3.0 可以考虑去掉内置的小程序 api

**Comment by WhiteMinds** [comment]
> 想多了，就是一份表单，小程序后台都有，为这个玩意还给你写个AST检测，醒醒，不是一切都需要用技术处理的。

但实际情况就是这样，我们一共用 3 个小程序，1 个 kbone 的，检测出大量的 api（比 remax 还多），1 个 remax 的，检测出图中这些 api，还有一个原生的，只检测出 1 个我们确实使用了的 api。

没必要语气这么嘲讽，我只是在基于现有的事实上进行推断而已，或者说，你有什么推测吗，只是基于个人的主观臆想？

**Comment by watsonhaw5566** [comment]
> > 想多了，就是一份表单，小程序后台都有，为这个玩意还给你写个AST检测，醒醒，不是一切都需要用技术处理的。
> 
> 但实际情况就是这样，我们一共有 3 个小程序
> 1.kbone 写的，检测出大量的 api（比 remax 还多）
> 2.remax 写的，检测出图中这些 api（8 个）
> 3.原生写的，只检测出 1 个我们确实使用了的 api。
> 
> 没必要语气这么嘲讽，我只是在基于现有的事实上进行推断而已，或者说，你有什么推测吗，只是基于个人的主观臆想？

我确实也说的不对，向你道歉，调侃过头了。
你可以截图一下你们三个图片吗？因为我这边也是C端B端的隐私协议都是一样的，所以做个这个判断。
另外是因为这个隐私协议会影响你们审核还是别的？Remax中的微信小程序是封装了一层，也是为了方便IDE智能提示。
可能我觉得为了少写几个隐私协议选项而导致开发去支持的工作量有点得不偿失。
另外这个问题我去问一下我微信的朋友核实一下。
![image](https://user-images.githubusercontent.com/4210367/96327843-f99a8600-106f-11eb-84ed-b321a0ecca8b.png)
![image](https://user-images.githubusercontent.com/4210367/96327866-336b8c80-1070-11eb-8224-05e306fce339.png)

**Comment by WhiteMinds** [comment]
> 你可以截图一下你们三个图片吗？因为我这边也是C端B端的隐私协议都是一样的，所以做个这个判断。

嗯，一样可能是因为都是用的 remax？
我最近请假了，截图我之后让同事发一下。

> 另外是因为这个隐私协议会影响你们审核还是别的？Remax中的微信小程序是封装了一层，也是为了方便IDE智能提示。
> 可能我觉得为了少写几个隐私协议选项而导致开发去支持的工作量有点得不偿失。


隐私协议我们是怕用户看到的时候，发现我们用了这么多收集隐私的 api，有疑虑。

**Comment by yesigrid** [comment]
![原生](https://user-images.githubusercontent.com/7357777/96427207-d8cd5e80-1230-11eb-9306-1c3ddb936fd9.png)
![kbone remax](https://user-images.githubusercontent.com/7357777/96427222-dbc84f00-1230-11eb-8797-a392a79040d4.png)

您好，我是WhiteMinds的同事，这里是我们的3个小程序的不同隐私保护说明截图。
由于我们在产品合规方面比较小心，希望能尽量避免用户或有关监管部门误会我们有超范围收集个人信息、过度索取权限等问题，所以希望能获得一定帮助，非常感谢！

**Comment by watsonhaw5566** [comment]
@WhiteMinds @army8735 抱歉，是我的错了，这边问过微信的朋友，确实是通过代码的引用分析生成的表单，我为我之前的言语不恰当为您道歉，以为我们的C段B端都是用了Remax所以表单是一样的。再次对不住你们，这个只能等宇之兄他们那边3.0版本更新了。

**Comment by WhiteMinds** [comment]
> @WhiteMinds @army8735 抱歉，是我的错了，这边问过微信的朋友，确实是通过代码的引用分析生成的表单，我为我之前的言语不恰当为您道歉，因为我们C/B端都是用了Remax所以表单是一样的。再次对不住你们，这个只能等宇之兄他们那边3.0版本更新了。

嗯，没关系，3.0 大概是什么时候出？

**Comment by yesmeck** [comment]
需要升级到 Webpack 5 才能解决这个问题。

参考 https://webpack.js.org/blog/2020-10-10-webpack-5-release/#nested-tree-shaking

**Comment by cpdeam** [comment]
> 需要升级到 Webpack 5 才能解决这个问题。
> 
> 参考 https://webpack.js.org/blog/2020-10-10-webpack-5-release/#nested-tree-shaking

这个解决方案是需要框架层面处理还是使用方可以处理呢？如果使用方可以处理，能否给一份详细的解决方案文档，近期小程序更新了隐私协议，必须要填完整所有隐私API调用的目的才可以提审，但是其实大部分API我们都没有使用，也会被打包进小程序里，参见 #1751

**Comment by yesmeck** [comment]
See https://github.com/remaxjs/remax/issues/1751#issuecomment-976197561
