### ISSUE TITLE
[BUG]CONTRIBUTING.md中的Remax实现原理链接404

### ISSUE THREAD

**Issue by wzhkobe2408** [remaxjs/remax#1327]
**bug 描述**
[CONTRIBUTING.md](https://github.com/remaxjs/remax/blob/master/CONTRIBUTING.md)中的[《Remax 实现原理》](https://remaxjs.org/advanced-guide/implementation-notes)链接404，应改为https://remaxjs.org/guide/implementation-notes 或者 https://v1.remaxjs.org/advanced-guide/implementation-notes？

**Comment by yesmeck** [comment]
@wzhkobe2408 来个 PR 吧
