### ISSUE TITLE
[需求] 增加针对阿里小程序组件的注释

### ISSUE THREAD

**Issue by iugo** [remaxjs/remax#1331]
**需求描述**

在写阿里小程序组件的过程中, 可以看到更多注释及官方文档链接.

**解决方案**

我可以修改修改如 https://github.com/remaxjs/remax/blob/master/packages/remax-ali/src/hostComponents/Navigator/index.ts 这样的文件, 用 JSDoc 格式写注释.

注释内容有两方面:

1. 文字描述.
2. 官方文档链接.

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
欢迎 PR。

**Comment by yesmeck** [comment]
可以直接 PR。
