### ISSUE TITLE
[BUG] dd.httpRequest json bug

### ISSUE THREAD

**Issue by huiyuanai709** [remaxjs/remax#1332]
**bug 描述**
>文档 https://ding-doc.dingtalk.com/doc#/dev/httprequest
// Content-Type为application/json时，data参数只支持json字符串，用户需要手动调用JSON.stringify进行序列化

DingTalk dd.httpRequest content-type 为 application/json时需要自己转 json 然后 as any

**复现步骤**
官网

**期望结果**
* 修改 network.d.ts data 改为 data?: Record<string, any> | string; 自己转
* 或者封装一个统一的 request，抹平平台间差异

**复现代码**

[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: 2.8.3
- 小程序端  钉钉小程序
- 开发环境 Windows

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by iugo** [comment]
这个应该不算 bug, 只是需求特性吧.

如果要改, 自己封装一下就好. 比如 https://github.com/zsqk/dd-sdk-mini-program/blob/294f1d8097cf1319418615b3b8e3d7eaf6cd082c/src/index.ts#L319-L324

**Comment by Darmody** [comment]
这个问题看起来和 remax 没有关系
