### ISSUE TITLE
[需求]可以增加remax/ali的声明文件吗

### ISSUE THREAD

**Issue by Chryseis** [remaxjs/remax#1340]
**需求描述**
类似 ```import { View, Text, Image } from 'remax/ali';``` 缺少声明文件，ide没有智能提示，强迫症有点难受

**其他信息**
![image](https://user-images.githubusercontent.com/13757352/96951225-9c467f00-151e-11eb-8768-08fbe8fdfe90.png)

**Comment by Darmody** [comment]
有类型定义的。这个高亮怎么看起来怪怪的🤔，是不是哪里搞错了

**Comment by Chryseis** [comment]
> 有类型定义的。这个高亮怎么看起来怪怪的🤔，是不是哪里搞错了
现在ide找到的 .d.ts 文件是
![image](https://user-images.githubusercontent.com/13757352/97170660-08e3a700-17c7-11eb-8056-f22f38baac51.png)这个，是因为我用webstorm的原因吗

**Comment by 2nini** [comment]
与 https://github.com/remaxjs/remax/issues/1331 需求类似.

我们已经进行了一些注释补充自用, 待整理后会提交 PR.

**Comment by Chryseis** [comment]
> 与 #1331 需求类似.
> 
> 我们已经进行了一些注释补充自用, 待整理后会提交 PR.

更新2.9.1后，已经有提示，感谢大佬
