### ISSUE TITLE
[问题]如何在app.css中引入ui组件的公共样式？

### ISSUE THREAD

**Issue by hongmaoxiao** [remaxjs/remax#1341]
**问题描述**
[详细地描述问题，让大家都能理解]
使用原生微信小程序的时候，可以在app.wxss里直接引入`@import '@vant/weapp/common/index.wxss';`

现在app.css里用的是 `page{}` 这样的形式

如果我需要引入`@import '@vant/weapp/common/index.wxss';`这样的代码，应该怎么写呢？

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by hongmaoxiao** [comment]
更新：
发现`@import '../node_modules/@vant/weapp/dist/common/index.wxss';`这样引入可以，但是总是觉得相对路径引入不太优雅

**Comment by Darmody** [comment]
https://webpack.js.org/loaders/css-loader/#import
