### ISSUE TITLE
[需求]优化dev开发的编译速度

### ISSUE THREAD

**Issue by hongmaoxiao** [remaxjs/remax#1343]
**需求描述**
[详细地描述需求，让大家都能理解]
现在`npm run dev`开发的模式下，比如修改一个样式，等待样式变化需要编译最少5秒，长的甚至在10秒以上，这个会极大的降低开发的效率。不知道有没有优化的思路和方法。

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
有多少页面了

**Comment by hongmaoxiao** [comment]
> 有多少页面了

只是首页一个页面

**Comment by Darmody** [comment]
那不应该啊。。

**Comment by Darmody** [comment]
@hongmaoxiao 还有问题吗

**Comment by hongmaoxiao** [comment]
> @hongmaoxiao 还有问题吗

目前升级了微信开发者工具以后，貌似已经快了一些，但总体还是觉得慢的，不过我现在也不是重点关心了，本来我大概改一个样式就想看一下变化，现在我同时改完5-10个样式才去看一次总体变化，所以感觉没有那么惨了

**Comment by Darmody** [comment]
> > @hongmaoxiao 还有问题吗
> 
> 目前升级了微信开发者工具以后，貌似已经快了一些，但总体还是觉得慢的，不过我现在也不是重点关心了，本来我大概改一个样式就想看一下变化，现在我同时改完5-10个样式才去看一次总体变化，所以感觉没有那么惨了

所以你指的是开发者工具的反应时间吧？这个就和 remax 关系不大了

**Comment by hongmaoxiao** [comment]
> > > @hongmaoxiao 还有问题吗
> > 
> > 
> > 目前升级了微信开发者工具以后，貌似已经快了一些，但总体还是觉得慢的，不过我现在也不是重点关心了，本来我大概改一个样式就想看一下变化，现在我同时改完5-10个样式才去看一次总体变化，所以感觉没有那么惨了
> 
> 所以你指的是开发者工具的反应时间吧？这个就和 remax 关系不大了

也许是 我不确定
