### ISSUE TITLE
[问题]事件警告，onInput 需要在 pages/index 中定义

### ISSUE THREAD

**Issue by postbird** [remaxjs/remax#1355]
**问题描述**
**app.js? [sm]:5891 Do not have $$REMAX_METHOD_9_onInput handler in component: pages/index/index. Please make sure that $$REMAX_METHOD_9_onInput handler has been defined in pages/index/index.**

**示例代码**
```jsx
<Input
  className={styles.input}
  onInput={handleInput}
  onConfirm={handleInputComfirm}
/>
```

**其他信息**
![image](https://user-images.githubusercontent.com/16200574/97862920-22de3600-1d41-11eb-846b-933ec66ccc74.png)

**Comment by Darmody** [comment]
麻烦提供一下完整的复现 demo

**Comment by postbird** [comment]
> 麻烦提供一下完整的复现 demo

本来想写个 demo，结果重新起了个工程，一样的代码复制过去之后，就不会报错了。。。。
