### ISSUE TITLE
[问题]未能访问到环境变量

### ISSUE THREAD

**Issue by fenyiwudian** [remaxjs/remax#1362]
**问题描述**
我按照官方文档：[环境变量](https://remaxjs.org/guide/config/environment-variables)这一节的方法，尝试在`pages/index/index.js`中访问`process.env`，但是`console.log(process.env)`显示的是一个空对象。
无论是`REMAX_APP_`开头的变量还是默认的`NODE_ENV`都不存在。

**示例代码**
构建任务如下：
```
  "scripts": {
    "dev": "cross-env REMAX_APP_TEST_VAR=dev NODE_ENV=development remax build -w -t",
    "build": "cross-env REMAX_APP_TEST_VAR=prod NODE_ENV=production remax build -t"
  },
```

index.js中的组件中：
```
console.log(process.env) // 输出 {}
```

完整重现可以使用这个[示例仓库](https://github.com/fenyiwudian/demo-app)重现：

**其他信息**
无

**Comment by yesmeck** [comment]
环境变量的注入机制是替换，注入的 `REMAX_APP_TEST_VAR` 变量只能通过 `process.env.REMAX_APP_TEST_VAR` 访问到。
