### ISSUE TITLE
swiper-item 添加class 不生效

### ISSUE THREAD

**Issue by PlutoCA** [remaxjs/remax#1369]
![image](https://user-images.githubusercontent.com/31099607/99535611-182fcc00-29e4-11eb-97f7-53f20b87c09d.png)
![image](https://user-images.githubusercontent.com/31099607/99535635-21b93400-29e4-11eb-9f0b-6fccd686e07b.png)

使用版本 v2.7.7

**Comment by yesmeck** [comment]
按[文档](https://developers.weixin.qq.com/miniprogram/dev/component/swiper-item.html) SwiperItem 是没 class 的，如果实际有的话的欢迎 PR。

**Comment by PlutoCA** [comment]
#1371 
第一次pr 🤣
