### ISSUE TITLE
[问题]如何配置 pnp-webpack-plugin

### ISSUE THREAD

**Issue by lotosbin** [remaxjs/remax#1372]
**问题描述**
pnp-webpack-plugin 's config
```
const PnpWebpackPlugin = require(`pnp-webpack-plugin`);

module.exports = {
  resolve: {
    plugins: [
      PnpWebpackPlugin,
    ],
  },
  resolveLoader: {
    plugins: [
      PnpWebpackPlugin.moduleLoader(module),
    ],
  },
};
```
PnpWebpackPlugin.moduleLoader(module)'s module is ref module,
how to config this in webpack-chain
```
config.merge({
      resolve: {
        plugins: [PnpWebpackPlugin]
      },
      resolveLoader: {
        plugins: [PnpWebpackPlugin.moduleLoader(module)]  //module should be webpack config's module, but cannot access
      }
    }
```
**其他信息**
https://github.com/neutrinojs/webpack-chain/issues/282

**Comment by yesmeck** [comment]
我估计现在支持不了 pnp

**Comment by lotosbin** [comment]
https://yarnpkg.com/features/pnp#different-behaviours-based-on-workspace--not-a-workspace
webpack 5 native support yarn v2 PNP mode.
any plan to upgrade to webpack 5?

**Comment by yesmeck** [comment]
有想法，但是目前没有确切时间点。

**Comment by yesmeck** [comment]
主要是 Remax 本身会需要去读  node_mdoules 里的文件，估计会有问题。

**Comment by lotosbin** [comment]
pnp模式下yarn patch了 node的fs，可以解析zip包的路径，
只要所有读取node_modules文件的路径使用 require.resolve 就没有问题，拼接的路径是不行的，
require.resolve会生成zip包中的路径，

**Comment by yesmeck** [comment]
我找时间学习下 pnp

**Comment by nekronhuang** [comment]
因为yarn会检查依赖，在yarn配置里使用`pnpMode: loose`可以跑起来，但会有比较多的warning。

期望控制台干净些的话，需要配很多`packageExtensions`。

**Comment by lotosbin** [comment]
https://yarnpkg.com/features/pnp#compatibility-table
Note that because the loose mode directly calls the node-modules hoister, it follows the exact same implementation as the true algorithm used by the node-modules linker!

pnpMode: loose 的逻辑和  node-modules linker 是一致的，

我现在使用的也是  node-modules linker ，这个是兼容原先的node_module目录的方式，特别是在workspace模式下，会在每个package下面生成一个 node_modules 目录，

packageExtensions的配置问题不大，只要配置一次就可以了，这个可以pr提交给@yarnpkg/plugin-compat 或者 共享一下，
