### ISSUE TITLE
[BUG]2.9.2微信小程序无法运行

### ISSUE THREAD

**Issue by wenmingtang** [remaxjs/remax#1394]
**bug 描述**
2.9.2微信小程序无法运行，提示my函数无法找到

**复现步骤**
升级至2.9.2编译后运行微信小程序

**期望结果**
正常

**复现代码**
无

**版本信息:**

- remax 版本: 2.9.2
- 手机型号： 模拟器
- 小程序端： 微信小程序
- 开发环境： mac OS

**其他信息**
如图

![image](https://user-images.githubusercontent.com/1620172/100539630-c3f1db00-3272-11eb-9002-0e27266a1a96.png)
![image](https://user-images.githubusercontent.com/1620172/100539636-c94f2580-3272-11eb-9a5b-45a84a85b668.png)

**Comment by lyboy2012** [comment]
如何解？

**Comment by yesmeck** [comment]
可以给个重现的 repo 吗？

**Comment by wenmingtang** [comment]
@yesmeck 钉钉群很多反馈的，应该是普遍现象。我这边是升级至2.9.2编译后就运行不起来了，降级至2.9.0后正常。

**Comment by yesmeck** [comment]
@wenmingtang 可否给个重现呢，我这边测试新建项目没有问题。

**Comment by yesmeck** [comment]
2.9.3 修复了
