### ISSUE TITLE
[需求]希望有一个完整的UI框架支持

### ISSUE THREAD

**Issue by hanyunmuyu** [remaxjs/remax#1405]
给一个star，希望发展更好，期待一个完整的UI框架

**Comment by anuxs** [comment]
> 给一个star，希望发展更好，期待一个完整的UI框架

试过 https://annasearl.github.io/annar/ 了吗？不算完整，但是够用。你需要多完整的？可以去提需求。

**Comment by yesmeck** [comment]
可以试下楼上的 annar。
