### ISSUE TITLE
[BUG] remax2.9版本以上小程序自定义组件带有具名 slot的组件不显示，2.8.10功能正常

### ISSUE THREAD

**Issue by q759410559** [remaxjs/remax#1406]
**bug 描述**
小程序自定义组件带有具名 slot的自定义名称组件不显示，只会显示默认的组件

**复现步骤**
![image](https://user-images.githubusercontent.com/11240348/100817199-98453f80-3482-11eb-998e-cf2c2d0ba8d3.png)
https://remaxjs.org/guide/basic/custom-component#%E5%AF%B9%E4%BA%8E%E5%B8%A6%E6%9C%89%E5%85%B7%E5%90%8D-slot-%E7%9A%84%E7%BB%84%E4%BB%B6%EF%BC%8C%E5%85%B7%E5%90%8D-slot-%E9%83%A8%E5%88%86%E7%9A%84%E6%9C%80%E5%A4%96%E5%B1%82%E5%8F%AA%E8%83%BD%E7%94%A8-view-%E7%BB%84%E4%BB%B6%E3%80%82
就像官方文档里的示例， <View slot="inner">Remax</View> 并不显示。
remax版本2.8.10功能正常，升级到2.9 以上的版本全部都不行

**期望结果**
修复相关bug

**复现代码**

**版本信息:**

- remax 版本: [e.g.  2.9.5]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.9.5]
- 开发环境 [e.g. mac OS]

**其他信息**

**Comment by lyboy2012** [comment]
同样问题

**Comment by yesmeck** [comment]
亲测没问题啊，可以给个重现的代码仓库么？

**Comment by q759410559** [comment]
重现的代码仓库   https://github.com/q759410559/remax-test-001.git

![image](https://user-images.githubusercontent.com/11240348/101274866-90680100-37dc-11eb-81e6-e400d5b10b99.png)
remax 2.8.10正常

![image](https://user-images.githubusercontent.com/11240348/101274883-a4136780-37dc-11eb-8c92-580c19bc98fe.png)
remax 2.9.x  2.10.x 都不行

**Comment by liuzhenji** [comment]
亲测：2.11.8 问题重现
小程序自定义组件带有具名 slot的自定义名称组件不显示，只会显示默认的组件
