### ISSUE TITLE
如何配置微信小程序里的 project.config.json

### ISSUE THREAD

**Issue by Kerminate** [remaxjs/remax#1407]
**问题描述**
如何配置微信小程序里的 project.config.json

**Comment by yesmeck** [comment]
可以把 project.config.json 放在 public 目录下。

**Comment by anuxs** [comment]
> **问题描述**
> 如何配置微信小程序里的 project.config.json

从其他微信小程序demo 里面复制一个配置文件过来就可以了啊。根据你的情况再改改。非常 Easy。

**Comment by cpdeam** [comment]
> 直接在根目录下新建 project.config.json 即可。

直接在编译或者打包后的dist里新建吗？但是这样有一个问题，每次build后需要再手动建一次，有解决办法吗？我现在想利用miniprogram-ci工具，直接build后自动构建npm，但是build后如果需要手动新建project.config.json的话，就没办法利用ci工具自动构建了

**Comment by watsonhaw5566** [comment]
> > 直接在根目录下新建 project.config.json 即可。
> 
> 直接在编译或者打包后的dist里新建吗？但是这样有一个问题，每次build后需要再手动建一次，有解决办法吗？我现在想利用miniprogram-ci工具，直接build后自动构建npm，但是build后如果需要手动新建project.config.json的话，就没办法利用ci工具自动构建了

不用吧，我们用了miniprogram-ci一样可以正常自动构建的。
头条的project.config.json是没有打包的，微信的CI是可以的。你可以参考一下我之前写的。
[微信小程序CI实践（Remax版）](https://zhuanlan.zhihu.com/p/375033001)

**Comment by cpdeam** [comment]
> > > 直接在根目录下新建 project.config.json 即可。
> > 
> > 
> > 直接在编译或者打包后的dist里新建吗？但是这样有一个问题，每次build后需要再手动建一次，有解决办法吗？我现在想利用miniprogram-ci工具，直接build后自动构建npm，但是build后如果需要手动新建project.config.json的话，就没办法利用ci工具自动构建了
> 
> 不用吧，我们用了miniprogram-ci一样可以正常自动构建的。 头条的project.config.json是没有打包的，微信的CI是可以的。你可以参考一下我之前写的。 [微信小程序CI实践（Remax版）](https://zhuanlan.zhihu.com/p/375033001)

但是每次build后，我看dist里是没有project.config.json文件的，请问你们那里build后是有这个文件的吗？

**Comment by watsonhaw5566** [comment]
我们build后是有的，您的版本号目前是多少
![image](https://user-images.githubusercontent.com/4210367/140276182-b9639f14-997e-4cdf-82ad-861e94bc72bc.png)
