### ISSUE TITLE
TabBar不显示

### ISSUE THREAD

**Issue by BenLampson** [remaxjs/remax#1410]
这个是app.config.js
![image](https://user-images.githubusercontent.com/15414750/100972105-2a2c7580-3573-11eb-9ee8-7ebd1817e5f5.png)
这个是项目目录
![image](https://user-images.githubusercontent.com/15414750/100972127-357fa100-3573-11eb-8484-88fb1eca90ed.png)
效果上没有
![image](https://user-images.githubusercontent.com/15414750/100972163-492b0780-3573-11eb-963f-a3c165ac56a1.png)

**Comment by yesmeck** [comment]
可以看下构建出来的 `dist/app.json` 对不对。

**Comment by anuxs** [comment]
`  tabBar: {
    "list": [{
      "pagePath": "pages/index/index",
      "text": "首页"
    }, {
      "pagePath": "pages/jjrz_wo/create",
      "text": "工单"
    }, {
      "pagePath": "pages/my/index",
      "text": "我的"
    }]
  },`

我这样养些没有问题。

**Comment by BenLampson** [comment]
谢谢,目前的版本APP.CONFIG.TS并不会在保存后直接参与编译.麻烦大家了

**Comment by yesmeck** [comment]
> 谢谢,目前的版本APP.CONFIG.TS并不会在保存后直接参与编译.麻烦大家了

我们的设计应该是会自动编译的，这也是个问题。

**Comment by yesmeck** [comment]
试了下 app.config.ts 有被 watch 的，如果还有问题再反馈吧。

**Comment by BenLampson** [comment]
这个问题很容易复现呀~
1.新建TS模式的库(官方的脚手架)
2.直接npm run dev
3.给app.config.ts增加一个新页面,
4.查看dist输出

你会发现没有该页面

**Comment by yesmeck** [comment]
@BenLampson 是 Windows 吗？

**Comment by BenLampson** [comment]
是的

**Comment by anuxs** [comment]
> 这个问题很容易复现呀~
> 1.新建TS模式的库(官方的脚手架)
> 2.直接npm run dev
> 3.给app.config.ts增加一个新页面,
> 4.查看dist输出
> 
> 你会发现没有该页面

我是 macos，按照你的说法新建一个模板项目，增加页面，增加app.config.ts中的配置，yarn dev 或者 yarn build ，dist 中都会出现新增加的页面。我没有 windows，所以没有测试。

**Comment by yesmeck** [comment]
Windows 的 watch 可能是有问题。

**Comment by yesmeck** [comment]
Duplicate #1433
