### ISSUE TITLE
[需求]压缩setData的数据传输

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#143]
**需求描述**
从触发更新到数据完成传输的时间，可以进一步压缩。

**解决方案**
给 props 做简短别名，优化虚拟 dom 计算

**其他信息**

**Comment by Darmody** [comment]
className, FunctionName 都可以抽取出来

**Comment by Darmody** [comment]
创建500条数据时，看到传输的数据量有600KB，大可以优化

**Comment by Darmody** [comment]
`wxs` 不知道为什么执行了两遍，也影响了性能，需要进一步研究

**Comment by Darmody** [comment]
创建500条数据，传输量，原生：39KB，remax：620KB。

**Comment by army8735** [comment]
应该可以对data做diff然后最小化setData的范围吧

**Comment by yesmeck** [comment]
@army8735 现在其实已经有 diff 了，只会 setData 有变化的元素

**Comment by Darmody** [comment]
目前来看这个压缩不是很必要了
