### ISSUE TITLE
2.10.1配置css-loader 启动失败，在2.8.8 中没有问题[BUG]

### ISSUE THREAD

**Issue by wangiek** [remaxjs/remax#1440]
**bug 描述**
[详细地描述 bug，让大家都能理解]
配置css-loader后启动报错如下
**/node_modules/mini-css-extract-plugin/dist/CssModule.js:65
    const resource = this._identifier.split('!').pop();
                                      ^
TypeError: Cannot read property 'split' of undefined

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]
1. package.json 配置remax 版本为 2.10.1
       "remax": "2.10.1"
2. 使用下面 remax.config.js 配置 
const sass = require('@remax/plugin-sass');
module.exports = {
  plugins: [sass()],
  configWebpack({config}) {
    //配合VSCode的CSS Modules插件,配置"cssModules.camelCase": true
    config.module.rule('sass').oneOf('modules').use('css-loader').merge({
      options: {
         localsConvention: 'camelCase'
      }
    })
  }
};

3.更新node_module并启动
npm i && npm run dev
**期望结果**
[描述你原本期望看到的结果]
期望启动成功，但是报了如下错误

**/node_modules/mini-css-extract-plugin/dist/CssModule.js:65
    const resource = this._identifier.split('!').pop();
                                      ^
TypeError: Cannot read property 'split' of undefined

**版本信息:**
- remax 版本 [2.10.1]
- 开发环境 [mac OS]

**Comment by yesmeck** [comment]
@wangiek 有可重现的仓库么？

**Comment by wangiek** [comment]
> @wangiek有可重现的仓库么？

https://github.com/wangiek/remax-css-loader.git

**Comment by yesmeck** [comment]
https://github.com/remaxjs/plugins/blob/master/packages/sass/index.js#L1

sass 插件可以直接传配置进去的，不需要自己加 loader。

**Comment by yesmeck** [comment]
看起来是这段配置导致的 https://github.com/wangiek/remax-css-loader/blob/master/remax.config.js#L6-L10

**Comment by yesmeck** [comment]
因为插件的执行在 remax.config.js 里的 configWebpack 之后。所以 configWebpack 执行的时候 sass rule 其实还不存在。可以参考 https://github.com/remaxjs/plugins/blob/master/packages/sass/index.js 自己配置下 sass。
