### ISSUE TITLE
[BUG]remax/wechat依赖报错「soryBy is not defined」

### ISSUE THREAD

**Issue by yangtao00** [remaxjs/remax#1441]
**bug 描述**
<img width="1264" alt="D06AD2BC-A793-4AED-8EB9-132E0CAB62DE" src="https://user-images.githubusercontent.com/24250687/102077078-b11b0100-3e43-11eb-89f5-19cb834bdf4a.png">

**复现步骤**
yarn install / npm i 暗转依赖，yarn dev 运行

**期望结果**
正常运行

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [2.7.8]
- 小程序端 [微信小程序]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
@yangtao00 有可重现的仓库么？

**Comment by yangtao00** [comment]
@yesmeck https://github.com/yangtao00/remax-example.git

**Comment by noyobo** [comment]
```
"@doctorwork/one-pro@0.1.8":
  version "0.1.8"
  resolved "http://nexus.aihaisi.com/repository/npm/@doctorwork/one-pro/-/one-pro-0.1.8.tgz#041d8cf3cbb081a20ac64de150fc456611df006c"
  integrity sha1-BB2M88uwgaIKxk3hUPxFZhHfAGw=
  dependencies:
    "@doctorwork/one" "^0.1.6"
    "@doctorwork/themes" "^0.1.6"
    "@remax/one" "^2.7.0"
    "@remax/wechat" "^2.7.0"
    classnames "^2.2.6"
    less-plugin-npm-import "^2.1.0"
    react "^16.13.1"
```

@doctorwork/one-pro 的依赖版本 @remax/one 是 ^2.7.0 会安装最新的版本。与实际运行的 remax 2.7.8 不兼容。请使用最新版本或相同的版本。

**Comment by yangtao00** [comment]
> ```
> "@doctorwork/one-pro@0.1.8":
>   version "0.1.8"
>   resolved "http://nexus.aihaisi.com/repository/npm/@doctorwork/one-pro/-/one-pro-0.1.8.tgz#041d8cf3cbb081a20ac64de150fc456611df006c"
>   integrity sha1-BB2M88uwgaIKxk3hUPxFZhHfAGw=
>   dependencies:
>     "@doctorwork/one" "^0.1.6"
>     "@doctorwork/themes" "^0.1.6"
>     "@remax/one" "^2.7.0"
>     "@remax/wechat" "^2.7.0"
>     classnames "^2.2.6"
>     less-plugin-npm-import "^2.1.0"
>     react "^16.13.1"
> ```
> 
> @doctorwork/one-pro 的依赖版本 @remax/one 是 ^2.7.0 会安装最新的版本。与实际运行的 remax 2.7.8 不兼容。请使用最新版本或相同的版本。

thanks
