### ISSUE TITLE
remax web 怎么打包出来，nginx里访问不到静态文件呢，哪里怎么配置 publickpath?

### ISSUE THREAD

**Issue by MOOO-M** [remaxjs/remax#1445]
**问题描述**
[详细地描述问题，让大家都能理解]

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
需要配置 webpack，参考 https://remaxjs.org/guide/config/remax#configwebpack

**Comment by KouSum** [comment]
`config.output.publicPath("/web/");`
