### ISSUE TITLE
[BUG]registerRuntimePlugin 使用 onAppConfig, onPageConfig 报错

### ISSUE THREAD

**Issue by dpyzo0o** [remaxjs/remax#1449]
**bug 描述**

参照[文档](https://remaxjs.org/guide/advanced/plugin#%E8%BF%90%E8%A1%8C%E6%97%B6-hooks)使用 registerRuntimePlugin 修改 onAppConfig, onPageConfig, 构建项目后运行出错, 报错信息如下

![1608533317541](https://user-images.githubusercontent.com/24768249/102747720-b6c09b80-439b-11eb-81b5-6f57358f643e.jpg)

**复现步骤**
见下面的 repo

**期望结果**
可以正常使用插件

**复现代码**
repo: https://github.com/dpyzo0o/remax-bug-runtime-plugin

**版本信息:**

- remax 版本: 2.11.2
- 小程序端: 微信小程序
- 开发环境: mac OS

**其他信息**

使用方式参考的这个 [issue](https://github.com/remaxjs/remax/issues/1228)

**Comment by dpyzo0o** [comment]
@Darmody 这个问题有人看一看嘛，因为想对page的一些方法比如 onShow onHide进行重写，需要依赖这个feature..

**Comment by yesmeck** [comment]
正确的写法应该是这样，已更新文档。
```
module.exports = {
  onAppConfig({ config }) {
    const onLaunch = config.onLaunch
    config.onLaunch = function(...args) {
      console.log('onLaunch from plugin')
      if (onLaunch) {
        onLaunch.call(this, ...args)
      }
    }
    return config
  },
  onPageConfig({ config }) {
    const onLoad = config.onLoad
    config.onLoad = function(...args) {
      console.log('onLoad from plugin')
      if (onLoad) {
        onLoad.call(this, ...args)
      }
    }
    return config
  },
}
```
