### ISSUE TITLE
web开发 annarUI组件库  .anna-btn样式 被 .remax-button覆盖

### ISSUE THREAD

**Issue by KouSum** [remaxjs/remax#1451]
**bug 描述**
web开发 annar .anna-btn样式 被 .remax-button覆盖

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 2.11.2]
- 开发环境 [e.g. windows]

**其他信息**
![1608536829(1)](https://user-images.githubusercontent.com/39258402/102752418-86312f80-43a4-11eb-9f31-be69896b2af8.png)

**Comment by yesmeck** [comment]
新版本应该已修复。
