### ISSUE TITLE
[BUG]px转rpx的比例错误

### ISSUE THREAD

**Issue by hanyunmuyu** [remaxjs/remax#1454]
**bug 描述**

微信开发的模拟器和真机效果差异比较大。希望给一个px转rpx的比例，还有设计稿的跨高规范。目前我市按照iPhone6的是设计稿开发的。微信官方给的是：在iPhone6下750px=750rpx

css

`
.top-bar {
  background-color: #ff5d00;
  color: red;
  width: 100%;
  height: 186rpx;

  .search {
    background-color: white;
    position: fixed;
    height: 72rpx;
    border-radius: 36rpx;
    top: 45rpx;
  }
}

`

模拟器

`
.top-bar .search {
    background-color: white;
    position: fixed;
    height: 72rpx;
    border-radius: 36rpx;
    top: 45rpx;
}

`
手机端
`
.top-bar .search {
    background-color: #fff;
    position: fixed;
    height: 34px;
    border-radius: 17px;
    top: 21px;
}

`

**版本信息:**

- remax 版本:  [2.11.2]

- 手机型号 [华为荣耀]
- 开发环境 [e.g. mac OS]

**Comment by yesmeck** [comment]
看起来是微信小程序本身的问题？

**Comment by YInJunWen** [comment]
@hanyunmuyu 我可能遇到和你说的差不多问题 我的解决方案是 所有style像素单位都统一转换为rpx 再由remax解析成px 这样就没有问题了～希望帮到你。

```
import { getSystemInfoSync } from 'remax/wechat'
/**
 * 默认 px => rpx
 * @param pixel 像素
 * @param pixelType 转换后类型 'rpx'
 */
export default (pixel: number, pixelType?: boolean): number => {
  const { windowWidth } = getSystemInfoSync()
  return pixelType ? (pixel / 750) * windowWidth : pixel * (750 / windowWidth)
}

```
