### ISSUE TITLE
[BUG] 自定义小程序组件默认值错误

### ISSUE THREAD

**Issue by menhal** [remaxjs/remax#1457]
**bug 描述**
不同页面(或者同一页面)的组件, 会互相影响属性的默认值 (比如两个Cell标签, border属性默认应是true, 其中一个写了border属性, 另一个标签不写border属性, 但是该属性却变成了null)

**复现步骤**
```

import * as React from 'react';
import Cell from "@vant/weapp/lib/cell";

export default () => {
  return (
    <div>
        <Cell>dfasdf</Cell>  {* Cell组件如果不写border属性, 默认值应该是true. 但是这里不显示border *}
        <Cell border>asdfasd</Cell>
    </div>
  );
};
```

**期望结果**
不写的属性应该表现为默认值

**版本信息:**

- remax 版本: [2.9.1]
- 手机型号 [小米8]
- 小程序端 [微信小程序]
- 小程序版本[7.0.21]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
确实有这个问题。

**Comment by yesmeck** [comment]
目前无解，建议显示设置属性。
