### ISSUE TITLE
[BUG] 升级后部分包报错

### ISSUE THREAD

**Issue by yuelight** [remaxjs/remax#1458]
**bug 描述**
项目中使用linaria，2.9.1正常，升级后报错

**复现步骤**
必现

**期望结果**
正常使用

**复现代码**
[linaria-error](https://gitee.com/yuelight/remax-issuse-demo1.git)

**版本信息:**

- remax 版本: 2.11.2
- 小程序端 微信小程序
- 开发环境 mac OS

**其他信息**
原因：linaria/loader会使用@linaria/webpack4-loader/lib/index.js导出的函数作为loader，loader中this.resourcePath为undefined;

此外，如果没有在babel.config中添加allExtensions和isTSX，此loader报错会更多。[2.9.1版本的demo](https://gitee.com/yuelight/remax-issuse-demo1/tree/demo2.9.1/)则可以正常使用

**Comment by yesmeck** [comment]
rule 需要改成 `js`。
```js
module.exports = {
	one: true,
	output: 'dist/' + process.env.REMAX_PLATFORM,
	configWebpack({ config, webpack, addCSSRule }) {
		// linaria/loader 选项详见 https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack
		config.module
			.rule('js')
			.use('linariaLoader')
			.loader('linaria/loader')
			.options({
				sourceMap: process.env.NODE_ENV !== 'production',
			});
	},
};
