### ISSUE TITLE
如果在ios上输入内容的时候别把界面往上推？

### ISSUE THREAD

**Issue by whereiscode** [remaxjs/remax#1459]
**bug 描述**
希望可以告诉我一个临时解决的代码调整  我先取消这个  不然我的项目要费了  我很着急 谢谢了

**复现步骤**
输入框一输入整个界面就往上推，导致form不可用
我试了下原生，输入的时候界面不上推  就没bug

**期望结果**
不要往上推界面  这样不出现bug

- remax 版本:
最新
- 手机型号
iPhone 12
- 小程序端
微信
- 小程序版本
2.14.0
- 开发环境 
真机

**Comment by whereiscode** [comment]
经过测试  这是微信的官方的bug  2018年的 依然没更新

**Comment by whereiscode** [comment]
持续关注 如果解决了 我贴在这

**Comment by whereiscode** [comment]
我又用原生的代码以同样的界面测试了大概50变，remax确实存在这个bug   微信原生没有

**Comment by whereiscode** [comment]
bindtap可以触发到，问题就在bindsubmit无法执行，当你一遍遍的把之前点击页面移走的操作，聚焦后点确定，哪怕你不点确认按钮，也有可能触发到onSubmit 好像是有键盘没完成  必须要让每个textarea的键盘都完整的走一遍收起才能结束一样

**Comment by whereiscode** [comment]
我怀疑remax渲染成微信小程序语言的时候  是不是把key管理混乱了 导致必须一一确认textarea的完成？

**Comment by whereiscode** [comment]
整个项目都费了  表单经常无法提交   欲哭无泪 正在用原生再写一遍

**Comment by whereiscode** [comment]
谁要是遇到了同样的问题 希望能及时回复我

**Comment by whereiscode** [comment]
无解，算了

**Comment by yesmeck** [comment]
@whereiscode 可以搞个重现demo 上来看看
