### ISSUE TITLE
[BUG]分包页面的图片不会分包

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#1464]
打包之后所有图片都在根目录了，本身图片是最占体积的

**Comment by YInJunWen** [comment]
@mushan0x0 副包里面建立Images放图片就会好了

**Comment by mushan0x0** [comment]
> @mushan0x0 副包里面建立Images放图片就会好了

还是会打包到根目录呀

**Comment by YInJunWen** [comment]
> > @mushan0x0 副包里面建立Images放图片就会好了
> 
> 还是会打包到根目录呀

哦 我忘记和你说了 你需要自己稍微动一动webpack的配置 
```js
const sass = require('@remax/plugin-sass')

module.exports = {
  configWebpack({ config, webpack, addCSSRule }) {
    config.module
      .rule('image')
      .use('file')
      .loader('file-loader')
      .options({
        outputPath: (url, resourcePath, context) => {
          if (/subPackages/.test(resourcePath)) {
            let subPackageName = resourcePath.split('subPackages/')[1].split('/')[0]
            return `subPackages/${subPackageName}/images/${url}`
          }
        }
      })
  },
  plugins: [sass()]
}
```

**Comment by mushan0x0** [comment]
> > > @mushan0x0 副包里面建立Images放图片就会好了
> > 
> > 
> > 还是会打包到根目录呀
> 
> 哦 我忘记和你说了 你需要自己稍微动一动webpack的配置
> 
> ```js
> const sass = require('@remax/plugin-sass')
> 
> module.exports = {
>   configWebpack({ config, webpack, addCSSRule }) {
>     config.module
>       .rule('image')
>       .use('file')
>       .loader('file-loader')
>       .options({
>         outputPath: (url, resourcePath, context) => {
>           if (/subPackages/.test(resourcePath)) {
>             let subPackageName = resourcePath.split('subPackages/')[1].split('/')[0]
>             return `subPackages/${subPackageName}/images/${url}`
>           }
>         }
>       })
>   },
>   plugins: [sass()]
> }
> ```

谢谢，空了试试
