### ISSUE TITLE
[问题]求教 目前最新版本的remax 如何引入三方的UI库呢 譬如vant-weapp/wechat-miniprogram？

### ISSUE THREAD

**Issue by YInJunWen** [remaxjs/remax#1466]
**问题描述**

求教 目前最新版本的remax 如何引入三方的UI库呢 譬如vant-weapp/wechat-miniprogram？
按照文档写的我尝试过 一直都报错。

**Comment by q759410559** [comment]
import VanGrid from '@vant/weapp/dist/grid'
import VanGridItem from '@vant/weapp/dist/grid-item'

**Comment by yesmeck** [comment]
@YInJunWen 什么错呢，发个重现仓库看看

**Comment by huang-xiong** [comment]
能否发一个引入第三方库 如@vant/weapp的使用例子呢?

**Comment by anuxs** [comment]
> > import VanGrid from '@vant/weapp/dist/grid'
> > import VanGridItem from '@vant/weapp/dist/grid-item'
> 
> 我试过不可以 编译报错

有赞的组件和微信的组件我都在用，直接 import，没报错。你贴代码把。@vant 的例子在官方文档上就有啊，要多详细？其实把微信和有赞的文档分别看懂，原理搞懂，这里面基本没 remax 什么事情，remax 就是个胶水，把不同的组件粘合在一起，通过编译后交给微信去执行。

**Comment by anuxs** [comment]
> 能否发一个引入第三方库 如@vant/weapp的使用例子呢?

```js
import CellGroup from "@vant/weapp/dist/cell-group/index";
import Cell from "@vant/weapp/dist/Cell/index";
```

```xml
<CellGroup title="请登录并绑定手机号">
          <Cell is-link link-type="navigateTo" url="../my/login/index" value="验证手机号绑定房屋" border="true">
          </Cell>
          <Cell is-link link-type="navigateTo" url="../my/login/index" value="签到获得积分"  border="true">
          </Cell>
</CellGroup>
```
就这，随便丢到一个空项目里面运行，我这里没问题。

**Comment by anuxs** [comment]
> > import VanGrid from '@vant/weapp/dist/grid'
> > import VanGridItem from '@vant/weapp/dist/grid-item'
> 
> 我试过不可以 编译报错

路径后面加 index，因为组件是放在 index 里面的，要到文件，到目录确实会报错，微信组件一样要到文件。看官方文档中的路径。

**Comment by YInJunWen** [comment]
@yesmeck @anuxs @q759410559 @huang-xiong 
感谢各位百忙之中愿意花时间帮忙解决问题。之前是因为我手动修改了一些东西导致的报错，确实是自己的疏忽导致的，由于前段时间太忙了，回复晚了，还请见谅。
