### ISSUE TITLE
[BUG]微信小程序MovableView和Slider的onTouchStart和onTouchEnd事件没有触发

### ISSUE THREAD

**Issue by hongmaoxiao** [remaxjs/remax#1468]
**bug 描述**
[详细地描述 bug，让大家都能理解]

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0] 2.11.2
- 手机型号 [e.g. iPhone X] iPhone 6/7/8
- 小程序端 [e.g. 微信小程序] 微信小程序 调试模式（非真机）
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS] mac OS

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
代码片段和报错截图呢？就这么一段title，我们如何复现问题

**Comment by huangbinjie** [comment]
我也遇到了，随便绑个 onTouchEnd 就行

**Comment by watsonhaw5566** [comment]
> 我也遇到了，随便绑个 onTouchEnd 就行

可以提供一小段repo吗。

**Comment by huangbinjie** [comment]
> 可以提供一小段repo吗。

@watsonhaw5566 https://github.com/huangbinjie/remax-movable-view-ontouchevent-notworking

这几个 console 都打印不出来

**Comment by watsonhaw5566** [comment]
> > 可以提供一小段repo吗。
> 
> @watsonhaw5566 https://github.com/huangbinjie/remax-movable-view-ontouchevent-notworking
> 
> 这几个 console 都打印不出来

https://developers.weixin.qq.com/miniprogram/dev/component/movable-view.html

你是否用错属性了？movable-view并没有你的touchStart和touchEnd属性，那怎么会出发你的打印呢？

**Comment by huangbinjie** [comment]
@watsonhaw5566 如果用 ts 的话，remax 是有类型提示的。另外别的的实现里是用到这个属性了的
https://developers.weixin.qq.com/community/develop/article/doc/000e28e6524c308bec4c6e5e951c13

**Comment by watsonhaw5566** [comment]
> huangbinjie

remax是有类型提示的，但是你这个两个参数并没有在文档里，建议更换一下实现方式

**Comment by huangbinjie** [comment]
> remax是有类型提示的，但是你这个两个参数并没有在文档里，建议更换一下实现方式

有没有可能是这是基础属性，微信文档里故意不写呢？我明天试试他们官方的

**Comment by huangbinjie** [comment]
@watsonhaw5566 大佬，我试过微信原生 `movable-view` 是支持 touch 事件的，之所以他们文档没写，看起来就是因为这是 html 属性而不是自定义的。

所以 remax 仍然有问题？

**Comment by huangbinjie** [comment]
希望有人跟进下

**Comment by huangbinjie** [comment]
@watsonhaw5566 大佬牛逼 👍
