### ISSUE TITLE
[问题] 页面.json配置怎么按平台或单独弄页面定制添加？

### ISSUE THREAD

**Issue by jefth** [remaxjs/remax#1469]
**跨平台开发模式,remax: v2.9.1**

**问题描述**
比如现在的一个功能需求是实现微信小程序的单页面的自定义navigation。
添加单页面级的"navigationStyle":"custom"
build后，页面报错。

**示例代码**
```
/pages/mine/mine.json
{
  "navigationStyle":"custom",
  "usingComponents": {
  }
}
```

也尝试了 
- [+] /pages/mine/mine.json
- [+] /pages/mine/mine.ali.json
- [+] /pages/mine/mine.wechat.json
都是报错。
不确信remax是不是因为会自动处理usingComponents后，没有处理其他配置项.
请问该如何处理页面级的差异化的json配置项？

PS:  /src/app.config.ts 中只能处理全局的。

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/771326/104834510-cbc91580-58da-11eb-8f31-03afa1ebbdda.png)
![image](https://user-images.githubusercontent.com/771326/104834513-d08dc980-58da-11eb-859c-e00f370cd5b3.png)
![image](https://user-images.githubusercontent.com/771326/104834515-d2578d00-58da-11eb-8fe3-a82bcae56bc9.png)

**Comment by yesmeck** [comment]
参考 

https://remaxjs.org/guide/framework/page#%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE
https://remaxjs.org/guide/framework/app#%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE

**Comment by yesmeck** [comment]
Page 配置也可以像 App 配置那样设置的。
