### ISSUE TITLE
[问题] 关于template的使用

### ISSUE THREAD

**Issue by jefth** [remaxjs/remax#1471]
**问题描述**
阿里文档：https://opendocs.alipay.com/mini/framework/axml-template
微信文档：https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/template.html

**问题**
请问，通过npx create-remax-app my-app 创建项目，这种开发模式下，是否支持上面所述的<template>的写法？
翻了文档和examples都没找到-_-

**Comment by yesmeck** [comment]
模板在 Remax 里没有意义。

**Comment by jefth** [comment]
那针对同个数据源的显示，模板可以很方便的切换数据显示方式。
没有模板，就是通过不同的组件来切换？

**Comment by yesmeck** [comment]
先学习下 React 吧。
