### ISSUE TITLE
请问remax怎么自定义标题栏？

### ISSUE THREAD

**Issue by sadJohn** [remaxjs/remax#1472]
**问题描述**
设置navigationStyle为custom后在哪里写自定义的标题栏呢？

**Comment by yesmeck** [comment]
可以发下小程序相关的文档么？

**Comment by elowes** [comment]
custom 模式下所有的东西都要你自己实现了呀，标题栏文字都需要自己在代码里面实现。通常通过 `getMenuButtonBoundingClientRect` 这个方法拿到 custom 模式下右上方胶囊按钮的位置，然后来自己实现一个导航栏。
