### ISSUE TITLE
[问题] TURBO_RENDERS  相关的文档

### ISSUE THREAD

**Issue by xeodou** [remaxjs/remax#1476]
**问题描述**

代码里允许增加 `TURBO_RENDERS` 环境变量在打包的时候去除 `react-reconciler` , 参见 
https://github.com/remaxjs/remax/blob/8339820f1ffbac96ae7fb2e44f4b480ee813283d/packages/remax-cli/src/build/webpack/config.mini.ts#L95-L99

能否提供更多的信息，在什么情况下推荐使用，以及该参数具体的作用。

谢谢。

Xeodou

**Comment by yesmeck** [comment]
不推荐使用。

**Comment by xeodou** [comment]
能否分享更多的信息？不推荐使用的原因是说是什么？ 文档里的turbopages 配置也从代码里删掉了，请问还有其他性能优化的方案/建议提供么？

**Comment by yesmeck** [comment]
turbo 模式会做一些静态分析，但是会对业务代码产生一些限制，且带来的性能提升有限。你在什么场景碰到了性能问题？
