### ISSUE TITLE
[问题]打包成微信小程序 项目体积太大 但是基本没写什么东西

### ISSUE THREAD

**Issue by qhdxwdm** [remaxjs/remax#1477]
大家有遇到过吗？

**Comment by Darmody** [comment]
开发环境不会压缩代码，如果需要压缩加上 -m 命令

**Comment by qhdxwdm** [comment]
谢谢
在2021年1月27日 17:37，Cai Huanyu<notifications@github.com> 写道：

Closed #1477.
