### ISSUE TITLE
[React.lazy(() => import('./Comp'))报错]

### ISSUE THREAD

**Issue by zephyr19** [remaxjs/remax#1479]
**问题描述**
React.lazy(() => import('./Comp'))报错

**示例代码**
const Login = React.lazy(() => import('../../component/Login'))

<React.Suspense fallback={<View>Loading...</View>}>
    { <Login /> }
  </React.Suspense>

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/46860204/106345778-8b5f9380-62ed-11eb-9112-b0e9f61fd01d.png)

**Comment by yesmeck** [comment]
不支持动态 import。
