### ISSUE TITLE
[问题]微信小程序编译会自动包裹一层view，自动添加的样式会影响里面的组件

### ISSUE THREAD

**Issue by giamchen** [remaxjs/remax#1481]
**问题描述**
微信小程序编译会自动包裹一层view，View有个app的居中样式，我不需要这个样式或者这层View，这样会导致很多样式错乱，有没有什么办法可以去掉，或者不自动加载

**其他信息**
![20210202151458](https://user-images.githubusercontent.com/33769348/106565763-44320680-656a-11eb-9292-8eb304083fc9.png)

**Comment by yesmeck** [comment]
这个看起来是你自己加的呀

**Comment by giamchen** [comment]
> 这个看起来是你自己加的呀

看右边的样式名称，框架自带的，其实我不想要那个居中而已

**Comment by yesmeck** [comment]
@giamchen 把你的代码库发上来看看

**Comment by giamchen** [comment]
重新写样式覆盖就好了
