### ISSUE TITLE
请问remax的事件是如何代理的？

### ISSUE THREAD

**Issue by jy0529** [remaxjs/remax#1485]
**问题描述**
最近在学习各个小程序框架的运行原理，在事件处理这块，了解到mpvue是在编译时生成handleProxy的标记，看Taro next的分享也是如此，但看remax的demo时，却是生成$$REMAX_METHOD_xx, 不太明白其中原理，当前小程序Page对象里有这个方法的吗？

**其他信息**
![image](https://user-images.githubusercontent.com/12868934/107849969-d6bf8900-6e39-11eb-8ac9-0355e9c010bf.png)
![image](https://user-images.githubusercontent.com/12868934/107849986-ee970d00-6e39-11eb-908d-85a8c5de1c71.png)

**Comment by jy0529** [comment]
@yesmeck  @Darmody

**Comment by yesmeck** [comment]
应该都是一样的原理，具体代码在这里 https://github.com/remaxjs/remax/blob/8c93af94fb041599b6843df8a1a8bc6565610e91/packages/remax-runtime/src/hostConfig/index.ts#L27
