### ISSUE TITLE
[需求能不能把umi-request 引入到Remax，微信小程序的request不习惯

### ISSUE THREAD

**Issue by hot588** [remaxjs/remax#1493]
**需求描述**
[详细地描述需求，让大家都能理解]
umi-request是封装最好最好的request了，官方能不能整合进来啊！兼容各个小程序端，这样多好啊！就少早轮子了！
**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
可以试试 https://github.com/bigMeow/axios-miniprogram-adapter

**Comment by 23233** [comment]
可以直接使用 @ahooksjs/use-request

**Comment by yesmeck** [comment]
建议自己封装，也可以开源出来给大家用。
