### ISSUE TITLE
[BUG] 开启component2后，mini-ali-ui slot渲染问题

### ISSUE THREAD

**Issue by zehuichan** [remaxjs/remax#1496]
![image](https://user-images.githubusercontent.com/16459997/110062700-bb92ca00-7da4-11eb-8da6-f480e086dc8a.png)

mini-ali-ui版本v1.3.1
remaxjs版本v2.11.5

**Comment by yesmeck** [comment]
小程序框架的问题，建议不要开 Component 2 或者用 React 抄一下有问题的组件。

也可以看一下这个组件库 https://annasearl.github.io/annar/
