### ISSUE TITLE
[BUG] 在使用storybook时，导入remax组件失败

### ISSUE THREAD

**Issue by shruckCode** [remaxjs/remax#1501]
**bug 描述**
[详细地描述 bug，让大家都能理解]
在使用storybook开发remax组件时，导入remax组件如下
```
import React from "react";

import { View } from "remax/wechat";
import { Button } from "@storybook/react/demo";

export default {
  title: "UI 组件",
  component: View,
};

export const Default = () => <Button >Button默认</Button>;
export const Other = () => <View>这是一个测试</View>;

```
**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**
 
PS D:\workplace\remax-ks\ks> npm info remax

remax@2.11.6 | MIT | deps: 11 | versions: 534
Remax 是一个全新的基于 React 的小程序开发框架
https://remaxjs.org

bin: remax

dist
.tarball: https://registry.npm.taobao.org/remax/download/remax-2.11.6.tgz
.shasum: 60aeaa2fdad5db37b621a05d5ed2c3b47a8366ab

dependencies:
@remax/ali: 2.11.6              @remax/one: 2.11.6              @remax/types: 2.11.6            mini-types: ^0.1.1
@remax/cli: 2.11.6              @remax/runtime: 2.11.6          @remax/web: 2.11.6              miniprogram-api-typings: ^3.1.3
@remax/macro: 2.11.6            @remax/toutiao: 2.11.6          @remax/wechat: 2.11.6

maintainers:
- xcodebuild <me@xcodebuild.com>
- yesmeck <yesmeck@gmail.com>

dist-tags:
alpha: 2.0.1-14eb47bb.0  latest: 2.11.6           next: 2.0.0-alpha.18
- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]
错误输出    
**Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.**

**Check the render method of `unboundStoryFn`.**

**Comment by yesmeck** [comment]
`remax/wechat` 的组件只能跑在微信上。`remax/one` 的组件才是跨平台的。

**Comment by shruckCode** [comment]
> `remax/wechat` 的组件只能跑在微信上。`remax/one` 的组件才是跨平台的。

ERROR in ./node_modules/@remax/web/esm/bootstrap.js
Module not found: Error: Can't resolve 'history' in 'D:\workplace\remax-ks\ks\node_modules\@remax\web\esm'
 @ ./node_modules/@remax/web/esm/bootstrap.js 3:0-66 9:77-94 9:99-119
 @ ./node_modules/@remax/web/esm/index.js
 @ ./node_modules/@remax/one/esm/api/index.js
 @ ./node_modules/@remax/one/esm/index.js
 @ ./node_modules/remax/one.js
 @ ./src/components/Icon/index.stories.js
 @ ./src/components sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./node_modules/@remax/react-router-cache-route/dist/cacheRoute.js
Module not found: Error: Can't resolve 'react-router-dom' in 'D:\workplace\remax-ks\ks\node_modules\@remax\react-router-cache-route\dist'
 @ ./node_modules/@remax/react-router-cache-route/dist/cacheRoute.js 2:123-150
 @ ./node_modules/@remax/react-router-cache-route/index.js
 @ ./node_modules/@remax/web/esm/createApp.js
 @ ./node_modules/@remax/web/esm/bootstrap.js
 @ ./node_modules/@remax/web/esm/index.js
 @ ./node_modules/@remax/one/esm/api/index.js
 @ ./node_modules/@remax/one/esm/index.js
 @ ./node_modules/remax/one.js
 @ ./src/components/Icon/index.stories.js
 @ ./src/components sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./node_modules/@remax/web/esm/createApp.js
Module not found: Error: Can't resolve 'react-router-dom' in 'D:\workplace\remax-ks\ks\node_modules\@remax\web\esm'
 @ ./node_modules/@remax/web/esm/createApp.js 15:0-72 37:32-38 40:36-41 41:40-48 48:36-41 49:40-48 54:19-30
 @ ./node_modules/@remax/web/esm/bootstrap.js
 @ ./node_modules/@remax/web/esm/index.js
 @ ./node_modules/@remax/one/esm/api/index.js
 @ ./node_modules/@remax/one/esm/index.js
 @ ./node_modules/remax/one.js
 @ ./src/components/Icon/index.stories.js
 @ ./src/components sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./node_modules/@remax/web/esm/TabBar.js
Module not found: Error: Can't resolve 'react-router-dom' in 'D:\workplace\remax-ks\ks\node_modules\@remax\web\esm'
 @ ./node_modules/@remax/web/esm/TabBar.js 18:0-40 43:32-36
 @ ./node_modules/@remax/web/esm/createApp.js
 @ ./node_modules/@remax/web/esm/bootstrap.js
 @ ./node_modules/@remax/web/esm/index.js
 @ ./node_modules/@remax/one/esm/api/index.js
 @ ./node_modules/@remax/one/esm/index.js
 @ ./node_modules/remax/one.js
 @ ./src/components/Icon/index.stories.js
 @ ./src/components sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined

ERROR in ./node_modules/@remax/web/esm/hooks/useQuery.js
Module not found: Error: Can't resolve 'react-router-dom' in 'D:\workplace\remax-ks\ks\node_modules\@remax\web\esm\hooks'
 @ ./node_modules/@remax/web/esm/hooks/useQuery.js 1:0-47 5:65-76
 @ ./node_modules/@remax/web/esm/index.js
 @ ./node_modules/@remax/one/esm/api/index.js
 @ ./node_modules/@remax/one/esm/index.js
 @ ./node_modules/remax/one.js
 @ ./src/components/Icon/index.stories.js
 @ ./src/components sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.js)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-links/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addDecorator.js-generated-other-entry.js ./node_modules/@storybook/addon-backgrounds/dist/preset/addParameter.js-generated-other-entry.js ./.storybook/preview.js-generated-config-entry.js ./.storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  6.18 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.97 KiB {HtmlWebpackPlugin_0} [built]   

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
