### ISSUE TITLE
【需求】建议增加可配置的额外编译目录。

### ISSUE THREAD

**Issue by liuzhenji** [remaxjs/remax#1508]
目前查看文档，只有代码根目录一项配置。编译目录应该是基于这个。但是想custom-tab-bar这种，也需要进行编译（可能需要引入第三方的组件）。

**Comment by yesmeck** [comment]
把 custom-tab-bar 放在 [public](https://remaxjs.org/guide/basic/public) 目录下即可。

**Comment by liuzhenji** [comment]
重申下，两个问题。public只是copy目录，并不会把依赖一并打包，所以public还是无效的。
目前我的解决办法是，把这些依赖在别的文件里引入一下
