### ISSUE TITLE
[问题]关于remax新增的show/hide生命周期和react的component生命周期的定位顺序

### ISSUE THREAD

**Issue by mumuwen520** [remaxjs/remax#151]
**问题描述**
remax新增的生命周期onShow/onHide，hook的useShow/useHide是为了迎合小程序开发新增的生命周期，定义的周期时间应该是页面展示和页面消失的时候执行。那么问题来了，如果现在用react开发，和class Component原本的生命周期didMount，willunMount等执行先后是如何定义等，show是在render前还是render后，hide是在和willunMount呢？

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
首先 onShow 和 onHide 是指页面出现和消失，并不意味着组件一定会挂载或卸载。

在 Remax 中，didMount 相当于 onLoad, willUnmount 相当于 onUnload.

onShow, onHide, onLoad, onUnload 的执行顺序参考各个小程序平台的文档即可。

比如微信小程序，第一次挂载的执行顺序是 didMount -> onShow
