### ISSUE TITLE
[BUG]Video根据文档设置enable-auto-rotation，没有效果

### ISSUE THREAD

**Issue by dajavu** [remaxjs/remax#1510]
**bug 描述**
小程序文档Video enable-auto-rotation功能描述：是否开启手机横屏时自动全屏，当系统设置开启自动旋转时生效

**复现步骤**
点击小程序全屏按钮，并且横屏放置手机（手机竖屏锁关闭）

**期望结果**
视频全屏播放

**复现代码**
<Video Video enable-auto-rotation="true"></Video>

**版本信息:**

- 手机型号 [iPhone 12]
- 开发环境 [mac OS]

**Comment by yesmeck** [comment]
微信还是支付宝？

**Comment by dajavu** [comment]
> 微信还是支付宝？

微信

**Comment by watsonhaw5566** [comment]
@dajavu 可以了兄弟
