### ISSUE TITLE
[需求]微信的登录改了，为什么咱们新版本的没有更新呢！

### ISSUE THREAD

**Issue by hot588** [remaxjs/remax#1511]
微信小程序，用户登录授权的的模式要改变了，不在用getuserinfo了，Remax 怎么还不改呢！

**Comment by yesmeck** [comment]
直接用 wx  的接口就行。

**Comment by hot588** [comment]
2021年4月13日后发布的新版本小程序，开发者通过组件调用wx.getUserInfo将不再弹出弹窗，直接返回匿名的用户个人信息，获取加密后的openID、unionID数据的能力不做调整；若开发者需要获取用户的个人信息（头像、昵称、性别与地区），可以通过wx.getUserProfile接口进行获取。具体参考公告：https://developers.weixin.qq.com/community/develop/doc/000cacfa20ce88df04cb468bc52801

**Comment by hot588** [comment]
wx.getUserProfile  这个接口怎么在remax 没有呢？找遍了，也没有！！

**Comment by yesmeck** [comment]
直接调`wx.getUserProfile`就行。

**Comment by hot588** [comment]
wx.getUserProfile  IDE报错啊！我查了，没有这个组件啊！怎么调用啊！

**Comment by hot588** [comment]
解决了，但是VScode 总是报错，wx.getUserProfile   这个wx. 看着总是那么，那么不舒服！唉，那个下面一个波浪线！

**Comment by elowes** [comment]
> 解决了，但是VScode 总是报错，wx.getUserProfile 这个wx. 看着总是那么，那么不舒服！唉，那个下面一个波浪线！

![image](https://user-images.githubusercontent.com/8766034/113391830-b25a4480-93c6-11eb-9507-0fd6e1788649.png)

波浪线和 remax 没有关系，和你的 ESLint 配置有关，没配置对。

**Comment by joesdu** [comment]
> > 解决了，但是VScode 总是报错，wx.getUserProfile 这个wx. 看着总是那么，那么不舒服！唉，那个下面一个波浪线！
> 
> ![image](https://user-images.githubusercontent.com/8766034/113391830-b25a4480-93c6-11eb-9507-0fd6e1788649.png)
> 
> 波浪线和 remax 没有关系，和你的 ESLint 配置有关，没配置对。
> ![image](https://user-images.githubusercontent.com/8766034/113391898-d74eb780-93c6-11eb-9472-d06e76d60bfa.png)

你这个是怎么弄的>?如何声明的wx

**Comment by hellohejinyu** [comment]
> > > 解决了，但是VScode 总是报错，wx.getUserProfile 这个wx. 看着总是那么，那么不舒服！唉，那个下面一个波浪线！
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/8766034/113391830-b25a4480-93c6-11eb-9507-0fd6e1788649.png)
> > 波浪线和 remax 没有关系，和你的 ESLint 配置有关，没配置对。
> > ![image](https://user-images.githubusercontent.com/8766034/113391898-d74eb780-93c6-11eb-9472-d06e76d60bfa.png)
> 
> 你这个是怎么弄的>?如何声明的wx

![image](https://user-images.githubusercontent.com/8766034/118456247-d631d980-b72b-11eb-9f38-cb780c643ee1.png)
用的 `miniprogram-api-typings` 这个声明库。

**Comment by joesdu** [comment]
> miniprogram-api-typings

OK 3QQ
