### ISSUE TITLE
remax引入小程序插件报错[BUG]

### ISSUE THREAD

**Issue by mmryzmr** [remaxjs/remax#1515]
引入插件
![image](https://user-images.githubusercontent.com/22735565/113247270-3a6c1b80-92ed-11eb-889d-950a2968c8c1.png)
我的项目中编译报错：
![image](https://user-images.githubusercontent.com/22735565/113247313-52dc3600-92ed-11eb-8b69-9ccbfe9d0114.png)
从官网下载项目引入插件报错如下：
![image](https://user-images.githubusercontent.com/22735565/113249316-127eb700-92f1-11eb-8b34-7965109b861b.png)

**版本信息:**

- remax 版本: [v2.11.3]
- 小程序端 [微信小程序开发工具]
- 开发环境 [mac OS]

**Comment by yesmeck** [comment]
Duplicate of #1513
