### ISSUE TITLE
Swiper里面嵌套Swiper出现问题

### ISSUE THREAD

**Issue by XYH1996** [remaxjs/remax#1518]
app.js? [sm]:6136 WXMLRT_$gwx:./base.wxml:template:3831:16: Template `REMAX_TPL_2_swiper` not found.

层级如下：
Swiper>SwiperItem>Swiper>SwiperItem

现在是一个tab swiper的使用场景 里面还需要有轮播图，然而在SwiperItem里面在加入Swiper组件就完全不被渲染出来，报如上的错，在微信开发工具里面使用原生写法，那样子嵌套则没有问题

**Comment by noyobo** [comment]
`remax.config.js` 配置 `UNSAFE_wechatTemplateDepth`  

https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/defaultOptions/UNSAFE_wechatTemplateDepth.ts#L35
