### ISSUE TITLE
[需求] 是否支持第三方react-apollo开发？

### ISSUE THREAD

**Issue by lizhoukai** [remaxjs/remax#152]
**需求描述**
graphql + react-apollo-hooks + apollo-boost 进行开发

**解决方案**

**其他信息**

**Comment by yesmeck** [comment]
应该是没问题的，需要尝试下。

**Comment by lizhoukai** [comment]
期待ing

**Comment by Darmody** [comment]
@yesmeck 这个是不是支持了？

**Comment by yesmeck** [comment]
等 1.1.0 看下吧

**Comment by yesmeck** [comment]
1.1.0 已经支持了。例子 https://github.com/remaxjs/examples/tree/master/alipay-apollo

唯一有点麻烦的地方就是要自己模拟一下 fetch

**Comment by eugle** [comment]
示例已不存在了，现在可以直接支持apollo client 了吗
