### ISSUE TITLE
为什么 remax 在开发中不同平台使用不同平台组件

### ISSUE THREAD

**Issue by ddcouples** [remaxjs/remax#1524]
**问题描述**
import { View, Text, Image, Button } from 'remax/wechat'; // import { View, Text, Image, Button } from 'remax/ali'
这里引入 和taro  import { View, Button, Text } from '@tarojs/components' 区别比较大
remax的方式 是用户自己感知到的自己开发的平台，然后只能编译对应的平台， 而taro不会， 可以直接其他平台 如 web 微信
**示例代码**
```
import * as React from 'react';
import { View, Text, Image, Button } from 'remax/wechat'; // import { View, Text, Image, Button } from 'remax/ali'
import styles from './index.css';

export default () => {
  const [state, setState] = React.useState({index: 1}) 
  return (
    <View className={styles.app}>
      <div>sdfsdf</div>
      <View className={styles.header}>
        <Image
          src="https://gw.alipayobjects.com/mdn/rms_b5fcc5/afts/img/A*OGyZSI087zkAAAAAAAAAAABkARQnAQ"
          className={styles.logo}
          alt="logo"
        />
        <View className={styles.text}>
          编辑 {state.index % 2 === 0 ? <Text className={styles.path}>src/pages/index/index.js</Text> : null}
          开始
        </View>
        <Button onClick={() => {
          setState({
            index: state.index+1
          })
        }}>setState</Button>
      </View>
    </View>
  );
};
```

**其他信息**
![image](https://user-images.githubusercontent.com/19562658/114184080-fa550a80-9976-11eb-8fb0-9aa599836acd.png)

**Comment by elowes** [comment]
从`remax/one`引呢，你试试。https://remaxjs.org/api/remax-one/components

**Comment by ddcouples** [comment]
> 从`remax/one`引呢，你试试。https://remaxjs.org/api/remax-one/components

那 remax 相对于taro的优势是什么呢

**Comment by elowes** [comment]
> > 从`remax/one`引呢，你试试。https://remaxjs.org/api/remax-one/components
> 
> 那 remax 相对于taro的优势是什么呢

![image](https://user-images.githubusercontent.com/8766034/114546983-65148780-9c90-11eb-96e3-9b13b89a75dd.png)
上图是官方的解释。
但是我个人觉得其实没啥优势，不过 Taro 从 3 开始才这么干的，以前只是类 React 写法而已，Remax 作为市面上第一个自己实现 React 渲染器的框架，还是很酷的，就酱。
