### ISSUE TITLE
为什么不能痛快的用微信小程序的导航功能

### ISSUE THREAD

**Issue by hot588** [remaxjs/remax#1536]
<Navigator url="/pages/pump/index" >跳转到新页面</Navigator>  点击根本就没有任何反应，后来看了下官方的演示，都是用navigateTo 这个函数来跳转的，现在这个跳转存在BUG，只能用跳转tab可以，但是跳转其他页面，就报错！

算了，放弃吧！这个是半成品！还是原生开发比较快！ 失望！

**Comment by yesmeck** [comment]
具体是什么问题？

**Comment by elowes** [comment]
我怀疑你的`url`写错了，假设`pages`目录下面有个`detail/detail.tsx`，你像下面这样写，应该可以跳转过去。
```js
wx.navigateTo({
  url: `/pages/detail/detail`,
})
```
