### ISSUE TITLE
微信小程序开发中配置devServer不生效

### ISSUE THREAD

**Issue by lee88688** [remaxjs/remax#1537]
**问题描述**
在微信小程序开发中需要使用到webpack的dev server的功能，我通过configWebpack配置后好像并没有生效。

**示例代码**
```
    config.devServer
      .port(9486)
      .host('0.0.0.0')
      .proxy({
        '/': {
          target: 'http://10.xxx.xxx.xx:10002',
          changeOrigin: true
        }
      })
````

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
小程序编译并没有用到 devServer

**Comment by yesmeck** [comment]
小程序里应该不存在跨域问题，要区分不同环境的服务端地址建议使用[环境变量](https://remaxjs.org/guide/config/environment-variables)。

**Comment by lee88688** [comment]
我自己配置了devServer也没办法生效吗？

**Comment by yesmeck** [comment]
没办法

**Comment by lee88688** [comment]
如果需要支持需要修改remax-cli代码才能实现？

**Comment by yesmeck** [comment]
没办法支持。

**Comment by lee88688** [comment]
我只是初略的看了一下remax-cli代码，不太明白是什么原因造成的，应该只需要修改配置应该就可以啊（之前未做过webpack相关开发，勿喷😂）。能够大概给出具体什么原因呢？我去学习一下。

**Comment by yesmeck** [comment]
前面说了，remax 代码编译到小程序代码时没有用到 devServer，你直接说你的实际需求吧。

**Comment by lee88688** [comment]
小程序在本地调试的时候可能需要借助devServer做一个简单的本地网关，将不同前缀url转发到不同的服务器上去。

**Comment by yesmeck** [comment]
建议自己搞个 dev server，或者用上面说的环境变量实现。
