### ISSUE TITLE
[BUG] remax 2.13.0 View组件 onClick没有阻止冒泡

### ISSUE THREAD

**Issue by q759410559** [remaxjs/remax#1540]
**bug 描述**
remax 2.13.0 View组件 onClick没有阻止冒泡

**复现步骤**
https://remaxjs.org/guide/framework/event
实例用官方demo就行，通过console.log()打印结果，可以看到两个方法同时生效，没有起到阻止冒泡效果

**期望结果**
修复相关BUG

**复现代码**
https://remaxjs.org/guide/framework/event

**版本信息:**

- remax 版本: [e.g. 2.13.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.16.0]
- 开发环境 [e.g. mac OS]

**其他信息**

**Comment by yesmeck** [comment]
能提供一个重现 demo 吗？

**Comment by q759410559** [comment]
https://github.com/q759410559/remax-test-001.git

**Comment by hellohejinyu** [comment]
> https://github.com/q759410559/remax-test-001.git

```js
function handleFooClick(event) {
    event.stopPropagation();
}
```
你的 demo 里面漏掉了阻止冒泡的代码。
