### ISSUE TITLE
[问题]请问如何在remax项目中使用import方法加载组件

### ISSUE THREAD

**Issue by annilq** [remaxjs/remax#1541]
项目是使用如下命令行创建的
```
npx create-remax-app my-app
```
想根据本地文件是否存在来动态加载组件，之前的web项目可以使用import方法，请问remax项目应该如何配置使用
代码示例如下
![QQ截图20210422170642](https://user-images.githubusercontent.com/6497194/115687917-3a5fb880-a38d-11eb-8de8-5cf36890c97f.png)

**Comment by yesmeck** [comment]
小程序不支持动态加载代码的。

**Comment by annilq** [comment]
好的，谢谢，第一次开发小程序，小程序文档看的不多
