### ISSUE TITLE
[BUG]Remax 2.13.1 安装依赖报错

### ISSUE THREAD

**Issue by RiderGj** [remaxjs/remax#1543]
**bug 描述**
项目安装remax依赖时，报错Error: [remax@2.13.1 › @remax/types@2.13.1] Can't find package @remax/types's version: 2.13.1

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [2.13.1]
- 开发环境 [mac OS]

**其他信息**
![image](https://user-images.githubusercontent.com/23232713/115810065-d89c5e80-a41f-11eb-83a3-ad9d2f217250.png)

**Comment by yesmeck** [comment]
是不是用了非官方 register？

**Comment by yesmeck** [comment]
https://www.npmjs.com/package/@remax/types

**Comment by RiderGj** [comment]
> 是不是用了非官方 register？

用的tnpm，淘宝的镜像。是内部同学吗，给个花名钉你一下

**Comment by yesmeck** [comment]
边柳
