### ISSUE TITLE
向原生微信小程序组件中传递函数参数失败

### ISSUE THREAD

**Issue by lee88688** [remaxjs/remax#1544]
**问题描述**
RT，如果我在给第三方微信小程序组件（以vant的Calendar的formatter参数为例）传递函数作为参数的时候，组件没办法接收到。我在原生小程序的环境中测试也发现，直接传递小程序的函数给组件参数也是不行，但将函数写在data中是可以传递的。不知道remax这个传递方式是什么样的，这个问题可以修复吗？

**Comment by yesmeck** [comment]
是已知问题，目前无法支持给小程序组件传递函数。

**Comment by yesmeck** [comment]
Duplicate of #1526

**Comment by liuzhenji** [comment]
> **问题描述**
> RT，如果我在给第三方微信小程序组件（以vant的Calendar的formatter参数为例）传递函数作为参数的时候，组件没办法接收到。我在原生小程序的环境中测试也发现，直接传递小程序的函数给组件参数也是不行，但将函数写在data中是可以传递的。不知道remax这个传递方式是什么样的，这个问题可以修复吗？

兄弟，你那有什么替代方案嘛

**Comment by lee88688** [comment]
@liuzhenji  remax支持混合开发，将要使用函数的组件变为原生组件，把函数通过原生组件传递进去。

**Comment by Tenodec** [comment]
我也遇到了，只能通过原生组件传递了

**Comment by watsonhaw5566** [comment]
> 我也遇到了，只能通过原生组件传递了

是的，remax需要预编译好，所以函数参数是无法传递的
