### ISSUE TITLE
关闭再打开同一路径页面，参数不同，页面数据会有缓存[BUG]

### ISSUE THREAD

**Issue by overlbjn** [remaxjs/remax#1545]
**bug 描述**
关闭再打开同一路径页面，参数不同，页面数据会有缓存。
比如：关闭了商品A页面，再重新打开商品B页面，页面路径相同，参数不同，打开B的时候会闪现A页面的缓存数据，请问怎么处理？

**Comment by yesmeck** [comment]
能给个重现 demo 吗？
