### ISSUE TITLE
[需求] 能否在H5上运行？

### ISSUE THREAD

**Issue by xuya227939** [remaxjs/remax#155]
**需求描述**
[详细地描述需求，让大家都能理解]

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
计划中的

**Comment by xuya227939** [comment]
@yesmeck 大概是多久呢？

**Comment by malash** [comment]
请问有什么大概的思路吗？ cc @MingruiZhang

**Comment by haol666** [comment]
> 计划中的

最好是支持h5啊，现在的框架太多，学习成本还是很高的

**Comment by yesmeck** [comment]
是否支持 H5 跟学习成本没关系吧

**Comment by yesmeck** [comment]
https://github.com/remaxjs/remax/issues/741
