### ISSUE TITLE
[需求]能使用gzip压缩包的大小吗

### ISSUE THREAD

**Issue by fewoy** [remaxjs/remax#1550]
**需求描述**
目前的压缩方案，感觉压缩效果还不是很明显，已经使用了-m的，compressTemplate也设置为true了
包的大小还是有点大。

**解决方案**
能否使用gzip方式压缩
**其他信息**
![image](https://user-images.githubusercontent.com/14038970/116496039-b5b5f280-a8d6-11eb-9375-903001596095.png)
gzipped
![image](https://user-images.githubusercontent.com/14038970/116496072-c6666880-a8d6-11eb-917c-62459350403b.png)

**Comment by yesmeck** [comment]
不行的。。可以自己分析下哪些依赖比较大。
