### ISSUE TITLE
微信小程序的性能问题

### ISSUE THREAD

**Issue by chenjigeng** [remaxjs/remax#156]
**问题描述**
其实这个思想是挺好的，不像Taro那样通过编译的方式来兼容语法，而是直接提供一套运行时。跟微信官方的kbone是一样的想法。不过有个最大的问题就是性能。
刚才试了下，把官方样例的TODO LIST初始化为1000个，发现渲染出来慢、操作卡顿。而通过原生则发现秒渲染出来，操作也不会卡顿。想看下这里有没有什么比较好的方法来解决性能问题。

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
#134 可以看看这里

**Comment by chenjigeng** [comment]
看了下，感觉性能确实会有提示。

**Comment by yesmeck** [comment]
https://github.com/remaxjs/benchmark

**Comment by Darmody** [comment]
更新了优化模板渲染后微信的 benchmark 数据。
通过微信小程序预览，打开性能测试面板，跑十次后取平均值。
(append data 我偷懒就没有跑十次了。。)
<img width="543" alt="屏幕快照 2019-08-26 21 12 49" src="https://user-images.githubusercontent.com/6788752/63693302-515fa780-c846-11e9-82ae-ccaa6eddc8ec.png">

**Comment by chenjigeng** [comment]
@Darmody 棒~那明天我也真机体验下性能问题。（弱弱问一句，有没有更新前的性能对比

**Comment by Darmody** [comment]
我会再贴一下和原生的对比

**Comment by Darmody** [comment]
<img width="804" alt="屏幕快照 2019-08-26 22 06 07" src="https://user-images.githubusercontent.com/6788752/63696777-05b0fc00-c84e-11e9-9a17-7f7b8f0272bf.png">

**Comment by Darmody** [comment]
通过 #143 我们还可以进一步优化

**Comment by Darmody** [comment]
<img width="782" alt="屏幕快照 2019-08-27 22 54 56" src="https://user-images.githubusercontent.com/6788752/63782673-54c66200-c91e-11e9-8022-c2b2f981122a.png">



尝试做了一下传输量压缩后的新数据，还有一些提升空间

**Comment by Darmody** [comment]
![屏幕快照 2019-08-28 16 41 31](https://user-images.githubusercontent.com/6788752/63840049-f39c9e00-c9b2-11e9-932a-fc2015905458.png)


我们本来希望通过 wxs 提升速度，结果发现 wxs 不符合预期。。现在去掉 wxs，数据又提升了一些

**Comment by Darmody** [comment]
@chenjigeng 不知道你了不了解微信小程序模板渲染的一些原理？我们现在有些性能问题有些摸不着头脑

**Comment by chenjigeng** [comment]
@Darmody 你可以描述下，我看下能不能帮上忙

**Comment by Darmody** [comment]
> @Darmody 你可以描述下，我看下能不能帮上忙

非常感谢。目前有以下几个问题：

1. 如果我把每个组件的属性都写满，就会导致渲染卡顿，把属性写少了以后，就好了很多。
2. 因为我们要动态渲染节点，所以每个组件都是提前定义成一个模板，然后根据 data 中的 type 通过 `<template is="{{type}}" />` 决定渲染哪一个模板。这种方式也比直接写死模板性能要差。
3. 我们用到 wxs 来处理我们 setData 的数组，之后我发现当 wxs 和 template 配合使用的时候，好像会重复执行 wxs 的方法，所以不知道 wxs 的执行时机是怎么样的，会不会影响渲染。

**Comment by chenjigeng** [comment]
下面这些都是从我个人理解来说的
第一个问题，由于小程序会将wxml转化为js对象（应该跟VDom是类似）传输给渲染层，因此你如果属性写得越多，我理解传输的对象就会越大越复杂，在重新setData后diff用的时间会越久。所以可能会导致渲染卡顿。

**Comment by chenjigeng** [comment]
其他两个问题我不太了解，不好评价。

**Comment by Darmody** [comment]
https://github.com/remaxjs/remax-window

长列表组件，解决长列表性能问题

**Comment by Darmody** [comment]
目前长列表是已知的与原生性能差距比较明显的案例，因此我们专门为长列表提供了解决方案

**Comment by yinhangfeng** [comment]
从目前的 benchmark 看性能问题是完全可以接受的，但 benchmark 测试的太理想化了，只渲染了 View Text 的部分属性。我改了一下加了 `<View {...props} /> <Text {...props} />` 让模板中渲染所有属性发现总时间增加了1倍以上，情况不乐观...
那个默认值处理函数 _h.v() 有什么意义么，我去掉之后性能有略微提升(10%左右) 除了编译出来的模板里有好多 undefined，好像也没碰到什么问题
还有头条小程序目前是不是几乎不可用啊，由于不支持 wxs 每次 setData 都是提交整棵树

**Comment by Darmody** [comment]
`_h.v()` 是为了缩减微信模板的大小

**Comment by Darmody** [comment]
> 从目前的 benchmark 看性能问题是完全可以接受的，但 benchmark 测试的太理想化了，只渲染了 View Text 的部分属性。我改了一下加了 `<View {...props} /> <Text {...props} />` 让模板中渲染所有属性发现总时间增加了1倍以上，情况不乐观...
> 那个默认值处理函数 _h.v() 有什么意义么，我去掉之后性能有略微提升(10%左右) 除了编译出来的模板里有好多 undefined，好像也没碰到什么问题
> 还有头条小程序目前是不是几乎不可用啊，由于不支持 wxs 每次 setData 都是提交整棵树

其实你把原生小程序的属性都写满，也会发现性能变差

**Comment by aofong** [comment]
开发工具编译的非常慢
新建默认项目后，在index页面随便增加几个文字，小程序开发工具预览需要等待蛮久（大概20多秒）

**Comment by Darmody** [comment]
> 开发工具编译的非常慢
> 新建默认项目后，在index页面随便增加几个文字，小程序开发工具预览需要等待蛮久（大概20多秒）

我们没看到有人反馈过这个问题，有没有让同事试过？

**Comment by coppyC** [comment]
> 开发工具编译的非常慢
新建默认项目后，在index页面随便增加几个文字，小程序开发工具预览需要等待蛮久（大概20多秒

我同事的 windows 也会这样，项目复杂的话，甚至出现开发者工具直接卡死，机子性能不差，是台式机，8代i5，1050ti。

似乎是编译的时候，所有文件都会覆盖写入，然后windows io比较差导致的。
(修改dist目录下的npm文件，然后再编译，修改的文件会被覆盖改回去)

**Comment by Darmody** [comment]
> 开发工具编译的非常慢
> 新建默认项目后，在index页面随便增加几个文字，小程序开发工具预览需要等待蛮久（大概20多秒）

是不是开启了增强编译？关掉试试

**Comment by huiliuliuhui** [comment]
> > 开发工具编译的非常慢
> > 新建默认项目后，在index页面随便增加几个文字，小程序开发工具预览需要等待蛮久（大概20多秒
> 
> 我同事的 windows 也会这样，项目复杂的话，甚至出现开发者工具直接卡死，机子性能不差，是台式机，8代i5，1050ti。
> 
> 似乎是编译的时候，所有文件都会覆盖写入，然后windows io比较差导致的。
> (修改dist目录下的npm文件，然后再编译，修改的文件会被覆盖改回去)

我用的是windows，也会有这个问题

**Comment by Darmody** [comment]
@huiliuliuhui 看有没有开了增强编译选项。

升级新版的 remax，文件会少很多。

**Comment by watsonhaw5566** [comment]
> 从目前的 benchmark 看性能问题是完全可以接受的，但 benchmark 测试的太理想化了，只渲染了 View Text 的部分属性。我改了一下加了 `<View {...props} /> <Text {...props} />` 让模板中渲染所有属性发现总时间增加了1倍以上，情况不乐观... 那个默认值处理函数 _h.v() 有什么意义么，我去掉之后性能有略微提升(10%左右) 除了编译出来的模板里有好多 undefined，好像也没碰到什么问题 还有头条小程序目前是不是几乎不可用啊，由于不支持 wxs 每次 setData 都是提交整棵树

现在头条支持了sjs了，但是我测试了一下会多加了一些baseProps的属性
