### ISSUE TITLE
reamx如何引入babel-plugin-lodash，能提供示例吗

### ISSUE THREAD

**Issue by fewoy** [remaxjs/remax#1562]
**问题描述**
reamx如何引入babel-plugin-lodash，能提供示例吗

**示例代码**

**其他信息**

**Comment by yesmeck** [comment]
你自己引入有碰到什么问题吗？另外其实没必要用这个插件，用 `lodash-es` 就可以了，会有 Tree Shaking。

**Comment by fewoy** [comment]
用lodash-es需要改很多代码的，有其他方式搞不

**Comment by yesmeck** [comment]
先说下你碰到的问题吧。

**Comment by fewoy** [comment]
我先用loadsh-es解决这个问题吧
