### ISSUE TITLE
[BUG] WeChat小程序未导出getUserProfile API

### ISSUE THREAD

**Issue by joesdu** [remaxjs/remax#1575]
**bug 描述**
remax未导出getUserProfile函数,WeChat已经建议使用新的函数获取用户信息.原本的getUserInfo已经不可用.
![image](https://user-images.githubusercontent.com/13188169/118393409-8f7fa900-b671-11eb-8081-34bd0ec111e0.png)
图中为WeChat官网描述.

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
直接使用 `wx.getUserProfile` 即可。

**Comment by joesdu** [comment]
> 直接使用 `wx.getUserProfile` 即可。

👌后期会加入导出吗?

**Comment by yesmeck** [comment]
后面计划把 API 全部从 remax 里去掉。可以用 https://github.com/remaxjs/promise-mini-api 代替。

**Comment by hot588** [comment]
promise-mini-api   已经11个月没有更新一下了！

**Comment by joesdu** [comment]
> promise-mini-api 已经11个月没有更新一下了！

😂以后去掉了,估计这个库他们会更新的多一些.

**Comment by danieltanfh95** [comment]
可爱的是这个要通过button按了才能使用。。。

**Comment by watsonhaw5566** [comment]
> 可爱的是这个要通过button按了才能使用。。。

嗯，是的，直接写在对应的Button事件里面就好了。
