### ISSUE TITLE
[BUG] 微信 PageMeta 组件渲染成PageContainer

### ISSUE THREAD

**Issue by q759410559** [remaxjs/remax#1582]
**bug 描述**
微信 PageMeta 组件渲染成PageContainer组件

**复现步骤**
![image](https://user-images.githubusercontent.com/11240348/119326261-4a342a80-bcb4-11eb-8f17-d65dc3d08a7c.png)
源码写错了吧

**期望结果**
修复bug

**复现代码**

**版本信息:**

- remax 版本: [e.g. 2.13.2]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by douxc** [comment]
我的，晚上我修复下
