### ISSUE TITLE
[需求]__remax_runtime_options__.js 为啥不压缩呢？

### ISSUE THREAD

**Issue by fewoy** [remaxjs/remax#1609]
**需求描述**
__remax_runtime_options__.js压缩一下是否可以节省空间？

**解决方案**

**其他信息**
![image](https://user-images.githubusercontent.com/14038970/121141754-e726c400-c86d-11eb-85b5-7dc9cacdc2b5.png)

**Comment by yesmeck** [comment]
所有代码都是不压缩的，小程序 IDE 会去压缩。

**Comment by fewoy** [comment]
微信小程序IDE，好像不太稳定，有时候不会压缩。我自己手动压缩了一下这个文件。
