### ISSUE TITLE
[需求]需要页面预加载

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#1611]
**需求描述**
在界面复杂的页面打开会短暂白屏，希望可以预先加载

**解决方案**
https://taro-docs.jd.com/taro/docs/prerender

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by lee88688** [comment]
taro的预渲染代码比较简单，我照着写了一个[remax插件](https://github.com/lee88688/remax-prerender-plugin)，使用在项目中给人的感觉并没有太大的影响。

**Comment by watsonhaw5566** [comment]
这样的用户体验会更好一点？

**Comment by watsonhaw5566** [comment]
@mushan0x0 你可以试试 @lee88688 兄弟的这个插件。这个不会嵌入到remax源码中，如果对你有用，麻烦关闭一下需求。谢谢

**Comment by mushan0x0** [comment]
> @mushan0x0 你可以试试 @lee88688 兄弟的这个插件。这个不会嵌入到remax源码中，如果对你有用，麻烦关闭一下需求。谢谢

有用，但是效果不明显
