### ISSUE TITLE
[需求]通过收集到的host component减少base模板体积

### ISSUE THREAD

**Issue by lee88688** [remaxjs/remax#1618]
**需求描述**
在`babel-plugin-remax-host-component`插件中会收集用户已经使用的host component，但是在`remax-build-store`的`getCollectedComponents`会将所有的host component写入（[代码地址](https://github.com/remaxjs/remax/blob/7a74621e8cab87ede8c432a41e07ec20b32620fd/packages/remax-build-store/src/index.ts#L81)），导致最终生成的模板中存在所有使用以及未使用的host component。如果用户大量使用第三方小程序组件，那小程序自己的组件很少使用，将未使用的host component不写入模板会降低base模板的体积。

**解决方案**
因为React的动态特性，目前`babel-plugin-remax-host-component`插件收集方式可能会导致某些host component没有收集到，但是如果不考虑跨平台开发，按照插件的收集方式导入和使用host component并不会造成影响。因此可以考虑添加一个配置选项，在用户确认已经按照既定模式开发的时候使用。

**Comment by lee88688** [comment]
另外我对`getCollectedComponents`这个函数的做法也有一些疑问。如果只是想要将registeredHostComponents和collectedComponents两个数据合并，完全没必要去覆盖collectedComponents的数据，应该新建一个Map然后将需要的数据存进去。
```ts
  getCollectedComponents() {
    this.registeredHostComponents.forEach((component, key) => {
      if (!this.collectedComponents.has(key)) {
        this.collectedComponents.set(key, {
          id: key,
          props: unique(component.props).sort(),
          additional: component.additional,
        });
      }
    });
    return this.collectedComponents;
  },
```

**Comment by yesmeck** [comment]
一开始确实是这么做的。不过这种收集过于依赖静态分析，会导致部分静态写法失效，比如：

```js
const MyView = View;

<MyView>123</MyView>
```

**Comment by lee88688** [comment]
可以通过额外配置参数手动开启，也算是手动优化一种，手动开启也让开发者能够明白某一些做法不行。
