### ISSUE TITLE
[问题]如何减小remax-vender的大小

### ISSUE THREAD

**Issue by junchaohu** [remaxjs/remax#1627]
**问题描述**
remax-vendors默认就有1.6MB， 微信主包最大只能2MB， 剩余可用开发代码空间太小了

如果需要引入第三方SDK，大小就更不可操控了。

请问大家都是怎么处理的？

**Comment by fewoy** [comment]
NODE_ENV=production 和 使用-m

**Comment by yesmeck** [comment]
有个问题，微信包大小是按 IDE 压缩代码前算的，还是压缩代码后算的？

**Comment by junchaohu** [comment]
@fewoy 真机调试 -m 确实管用，谢谢

**Comment by watsonhaw5566** [comment]
> 有个问题，微信包大小是按 IDE 压缩代码前算的，还是压缩代码后算的？

开发时候是压缩前，build后是压缩后算的。所以就会开发的时候直接主包超出了2m不让预览了

**Comment by watsonhaw5566** [comment]
@junchaohu 你好，如果已处理你的问题麻烦关闭一下issue，谢谢

**Comment by smallbaoo** [comment]
能不能做到按需引入呢？有些时候，我们引入一个第三方包，只是想使用包中的部分功能，其余没用到的方法是不是可以不打包进去，现在写代码确实，没写几句代码，微信的大小都已经超了，-m和分包也不能彻底解决这个问题，代码总会越写越多的

**Comment by watsonhaw5566** [comment]
> 能不能做到按需引入呢？有些时候，我们引入一个第三方包，只是想使用包中的部分功能，其余没用到的方法是不是可以不打包进去，现在写代码确实，没写几句代码，微信的大小都已经超了，-m和分包也不能彻底解决这个问题，代码总会越写越多的，另外生成的remax-vendors.js可以压缩一下，里面的注释什么的，应该也不会有人去看吧，能减少一点空间是一点空间啊

可以的，有在规划这个问题。对生成的 remax-vendors 执行二次压缩。

**Comment by cdl235** [comment]
**"build": "cross-env NODE_ENV=production remax build -m -t wechat"**
