### ISSUE TITLE
[问题]第三方组件传入的props不生效

### ISSUE THREAD

**Issue by smallBattery** [remaxjs/remax#1638]
**问题描述**
requirePluginComponent使用第三方插件，传入的任何props不生效

**示例代码**
1. captcha: {
      version: '1.0.0',
      provider: 'wxb302e0fc8ab232b4',
  }

2. Captcha = requirePluginComponent('plugin://captcha/t-captcha');

3.  < Captcha id="captcha" app-id={CAPTCHA_APP_ID} bindverify="bindverify"  >

**其他信息**
小程序调试器查看wxml，传入的属性没有生效，后查看base.wxml，发现
< captcha-t-captcha-5e23bef > 
手动修改如下后，传入属性生效，且组件正常运作
< captcha-t-captcha-5e23bef
    id="{{_h.v(i.props['id'])}}"
    app-id="{{_h.v(i.props['app-id'])}}"
    bindready="{{_h.v(i.props['bindready'])}}"
    bindverify="{{_h.v(i.props['bindverify'])}}"
    binderror="{{_h.v(i.props['binderror'])}}" >

连id都没生效，所以感觉不应该是bug，求问是不是漏了什么步骤？

版本信息如下
"remax": "^2.7.8",
"react": "^16.12.0",

**Comment by watsonhaw5566** [comment]
收到，晚上我复现一下。

**Comment by smallBattery** [comment]
> 收到，晚上我复现一下。 你的这个是用哪家插件？

https://cloud.tencent.com/document/product/1110/49319 验证码插件

**Comment by smallBattery** [comment]
能通过createHostComponent 变相解决吗

**Comment by smallBattery** [comment]
打算使用原生组件的方式加一层来解决了，不知道有无其他更好的方案

**Comment by smallBattery** [comment]
已验证是使用了JSX 的 相关语法后props失效
{
     Captcha && <Captcha id='captcha' />
}
这种写法不行，直接<Captcha id='captcha' />是可以的

**Comment by smallBattery** [comment]
问题是因为 我对Captcha 有初始null变量，因为我只有小程序环境需要这个组件，如果直接const Captcha = requirePluginComponent() 是ok，我自己再通过其他方式封装一下把

**Comment by watsonhaw5566** [comment]
如果已经自行处理了，麻烦也关闭一下issue
