### ISSUE TITLE
请问打包生成好的微信小程序，运行到开发者工具报错，是为什么

### ISSUE THREAD

**Issue by Maohei997** [remaxjs/remax#1640]
![image](https://user-images.githubusercontent.com/62044261/124890993-2716cd80-e00b-11eb-9b6b-cdd0d921ef56.png)

应该要怎么处理，谢谢大佬

**Comment by Maohei997** [comment]
create-remax-app 版本是 2.0.9

**Comment by watsonhaw5566** [comment]
请描述完整的信息和复现的代码片段。

**Comment by Maohei997** [comment]
> 请描述完整的信息和复现的代码截图。

已经解决了，是因为微信小程序的开发者工具不是最新版，不兼容生成的代码，就会报这样的错误 0.0

**Comment by watsonhaw5566** [comment]
> > 请描述完整的信息和复现的代码截图。
> 
> 已经解决了，是因为微信小程序的开发者工具不是最新版，不兼容生成的代码，就会报这样的错误 0.0

嗯，提issue的时候最好给个上下文。

**Comment by Maohei997** [comment]
> 请描述完整的信息和复现的代码截图。

已经解决了，是因为微信小程序的开发者工具不是最新版，不兼容生成的代码，就会报这样的错误 0.0

> > > 请描述完整的信息和复现的代码截图。
> > 
> > 
> > 已经解决了，是因为微信小程序的开发者工具不是最新版，不兼容生成的代码，就会报这样的错误 0.0
> 
> 嗯，提issue的时候最好给个上下文。

好的  谢谢大佬
