### ISSUE TITLE
[BUG] Typescript 项目下，微信小程序 Animation.export() 返回的数据类型和组件的 animation 属性类型不一致，虽然可以编译但是 VSCODE 会提示类型错误

### ISSUE THREAD

**Issue by darylgo** [remaxjs/remax#1642]
**bug 描述**
![image](https://user-images.githubusercontent.com/37319207/125550027-b8205418-ccca-4394-9d4c-ec0d8c0db3d5.png)

Typescript 项目下，微信小程序 Animation.export() 返回的数据类型和组件的 animation 属性类型不一致，虽然可以编译但是 VSCODE 会提示类型错误：

```
Type 'AnimationExportResult' is missing the following properties from type 'Record<string, any>[]': length, pop, push, concat, and 26 more.ts(2740)
component.d.ts(15, 5): The expected type comes from property 'animation' which is declared here on type 'IntrinsicAttributes & ViewProps & { children?: ReactNode; }'
(JSX attribute) BaseProps.animation?: Record<string, any>[] | undefined
```

**复现步骤**

1. 通过 remax/wechat 导入 createAnimation 方法创建 Animation 对象。
2. 调用 Animation 对象的 export() 方法得到动画数据。
3. 将动画数据赋值给任意组件的 animation 属性。

**期望结果**

微信小程序 Animation.export() 返回的数据类型和组件的 animation 属性类型保持一致。

**复现代码**

```tsx
import * as React from 'react';
import { View, createAnimation } from 'remax/wechat';

export default function IndexPage() {
  const animation = createAnimation({ duration: 1 });
  animation.translateY(100).step();
  const animationData = animation.export();
  return <View animation={animationData}>Hello</View>; // FIXME：此处出现类型错误提示
}

```

**版本信息:**

- remax 版本: 2.14.0
- 开发环境: mac OS

**Comment by watsonhaw5566** [comment]
@darylgo 这个是miniprogram-api-typings的类型问题，不属于remax的bug，因为这些接口经常变动，所以更新的也不是很及时。

**Comment by darylgo** [comment]
> @darylgo 这个是miniprogram-api-typings的类型问题，不属于remax的bug。

感谢答复，那我把这个问题提到 typings 那边去吧。

**Comment by watsonhaw5566** [comment]
> > @darylgo 这个是miniprogram-api-typings的类型问题，不属于remax的bug。
> 
> 感谢答复，typings 似乎不再维护了吧。

维护的， [时不时还是会更新，但是还是会漏掉一些新的接口类型。你可以在npm上面看看。[miniprogram-api-typings](https://www.npmjs.com/package/miniprogram-api-typings)
