### ISSUE TITLE
remax能新增类似Vue的路由拦截么

### ISSUE THREAD

**Issue by tys1244147276** [remaxjs/remax#1643]
类似与Vue的路由钩子函数，beforeEach，beforeEnter，remax可以在路由中设置类似钩子函数么

**Comment by yesmeck** [comment]
不就是 `onShow` 吗？

**Comment by tys1244147276** [comment]
> 不就是 `onShow` 吗？

onShow是页面可见，一般路由拦截是在进入页面未加载时判断，就像Vue路由的钩子函数，目前react好像只能通过高阶组件套一层，在未进入之前判断，类似于进入某个页面前的权限验证

**Comment by yesmeck** [comment]
那高阶组件挺好的。

**Comment by tys1244147276** [comment]
By the way，remax转换出来的微信代码，在哪里通过配置可以将js中的es5代码还原回es6代码

**Comment by yesmeck** [comment]
可以自己改 babel 配置 https://remaxjs.org/guide/config/babel

**Comment by tys1244147276** [comment]
我在项目路径下新建了babel.config.js ，配置了module.exports = {
  presets: [
    [
       "es2015",
    ]
  ]
  
}
  
  安装了babel-preset-es2015,
但是打包时终端报错提示apply-runtime-options.js: Cannot read property 'bindings' of null
我按照百度提示安装@babel/cli ,无果

**Comment by yesmeck** [comment]
为什么要「es5代码还原回es6代码」？

**Comment by tys1244147276** [comment]
> 为什么要「es5代码还原回es6代码」？

1、想把react项目转成华为快应用
2、但是华为快应用对于react端不支持，可以支持正宗小程序转换
3、remax转换之后的小程序再转成快应用不支持
4、所以想看一下转换之后的微信es6代码，看看能不能改一改结构，毕竟现在的es5代码，着实看不懂

**Comment by yesmeck** [comment]
这个需要你自己研究一下。
