### ISSUE TITLE
[BUG]useEffect合并更新问题

### ISSUE THREAD

**Issue by xiaoze77** [remaxjs/remax#1644]
**bug 描述**
该问题我看到已经关闭closed，并且在2.14.0更新日志中显示bug已经修复合并到master ，但是我这边在更新到2.14.0版本之后发现问题依然存在。
这是状态更新的方式，麻烦大佬再看一下，谢谢
![image](https://user-images.githubusercontent.com/17402175/125773513-70991549-551f-491f-b83a-772480bbf31d.png)

https://github.com/remaxjs/remax/issues/1633

**复现步骤**
https://github.com/remaxjs/remax/issues/1633

**期望结果**
https://github.com/remaxjs/remax/issues/1633

**复现代码**
https://github.com/remaxjs/remax/issues/1633

**版本信息:**

- remax 版本: [2.14.0]
- 手机型号 [iPhone 11]
- 小程序端 [微信小程序]
- 小程序版本[2.13.2 ]
- 开发环境 [mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
你好，能否提供一个复现的片段吗？尽量不要用截图，没有上下文，不好帮你排查问题。

**Comment by xiaoze77** [comment]
![image](https://user-images.githubusercontent.com/17402175/125902446-012710fb-8320-44a8-9c87-8ea44d8f2ff8.png)
这个是demo，在startTime和endTime被修改的情况下 ，数字1会被打印2遍。

**Comment by noyobo** [comment]
请引用 `import {unstable_batchedUpdates} from 'remax/runtime'` 后按需使用。

```js
events: {
    xxxx: unstable_batchedUpdates(() => {
       setTxxxxx();
        setTxxxxx();
   })
}
```

**Comment by yesmeck** [comment]
目前只有基础组件上绑定的事件会自动合并更新。其他事件回调需要按照上面那样去手动合并更新。
