### ISSUE TITLE
[需求]支持将指定节点以下的状态移至组件层级

### ISSUE THREAD

**Issue by rikumi** [remaxjs/remax#1651]
**需求描述**

微信小程序 setData 始终存在一个性能问题，即使 setData 是 patch 形式，视图层也会创建全量的 exparser vdom 进行 diff，在页面数据量很大的情况下，会影响页面上所有状态更新的执行效率。微信在[这篇文档](https://developers.weixin.qq.com/miniprogram/dev/extended/component-plus/recycle-view.html)中变相承认了这个问题。

例如，我们有一个瀑布流页面，由于瀑布流的特殊性不便于用 VirtualList，而且数据量并不算很大，然而这导致了页面上其他组件任何的状态更新，即使只是点击切换展开/折叠，也会卡 1-2 秒。

为了规避这个问题，Taro 中有 [CustomWrapper](https://docs.taro.zone/docs/optimized#2-customwrapper-%E7%BB%84%E4%BB%B6)，可以将 Page 中对应 vnode 以下的数据全部转移到小程序原生组件之内；Kbone 中也有类似的机制（将需要做数据隔离的节点 `<div>` 改写为 `<wx-view>` 即可）。

[Remax 性能优化的文档](https://remaxjs.org/guide/advanced/performance) 中只说了让开发者自己写自定义组件，但自己编写自定义组件无法实现**组件 slot 以下所有数据**的移植，只能实现组件本身状态的移植，然而并没有一劳永逸的办法把大量数据的拉取和展示逻辑全部封在原生组件状态之内（如果真这样实现了，那用 Remax 开发也没有意义了）。

所以我们即使写自定义组件，也只能把**受影响的**状态更新放到自定义组件中，同一个页面上每次增加新的状态更新，都需要改成自定义组件来实现，而不能从根本上隔离**影响源**。

**解决方案**

目前 Remax 的模板渲染方式似乎是几个框架中最简单的，即直接在 Page 中放所有节点数据；个人猜测其他框架是通过维护节点与逻辑层组件的对应关系，将组件以下的数据更新架空到 Component 层，从而避免性能问题的。

如果 Remax 不做修改，开发者也可以自己通过 Hack 的方式实现，即劫持 Page 的 setData，对传入的 patch 进行解析，对于需要隔离数据的组件以下的数据，改为给组件 setData，同时从 Page 的 setData 中去除，这种方案改动量很大，且不易维护，要彻底解决问题还是需要靠框架本身来实现。

**其他信息**

无

**Comment by watsonhaw5566** [comment]
哇，你的这个需求写的很用心。

**Comment by yesmeck** [comment]
https://github.com/remaxjs/remax/issues/1578 就是解决这个问题的。

**Comment by yesmeck** [comment]
@rikumi 有兴趣可以看看怎么实现这个功能。

**Comment by mushan0x0** [comment]
@rikumi 用户是怎么自己Hack setData的，有个例子吗

**Comment by rikumi** [comment]
暂时没有例子，只是一个设想🤔
