### ISSUE TITLE
[问题]remax添加babel构建失败,Error: Duplicate plugin/preset detected.

### ISSUE THREAD

**Issue by chenmingzhen** [remaxjs/remax#1652]
**问题描述**
使用官网的npx create-remax-app my-app构建remax程序，添加官网示例的babel配置，
`{
  presets: [
    [
      'remax',
      {
        react: {
          runtime: 'automatic',
        },
        typescript: {
          allowNamespaces: true,
        },
        'class-properties': {
          loose: true,
        },
        decorators: {
          legacy: true,
        },
        'throw-if-namespace': true,
        targets: ['chrome >= 49', 'firefox >= 64', 'ios >= 8', 'Android > 4.4'],
      },
    ],
  ];
}`

无法启动项目，去除babel.config.js后可正常启动

**示例代码**

**其他信息**
![image](https://user-images.githubusercontent.com/45579561/126763121-ae44646c-5e56-4439-a6a1-79eaf526e6fc.png)
![image](https://user-images.githubusercontent.com/45579561/126763177-e12c4644-d98d-475b-831d-c59d1e493738.png)

**Comment by watsonhaw5566** [comment]
先再检查一下babel插件配置，如果只是为了支持ts,Remax已内置支持。

**Comment by chenmingzhen** [comment]
> Duplicate plugin/preset detected，是插件定义重复了。如果只是为了支持ts,Remax已内置支持，不需要格外配置。

`module.exports = {
  presets: [
    [
      "remax",
      {
        react: {
          runtime: "automatic",
        },
        "class-properties": {
          loose: true,
        },
        decorators: {
          legacy: true,
        },
        "throw-if-namespace": true,
        targets: ["chrome >= 49", "firefox >= 64", "ios >= 8", "Android > 4.4"],
      },
    ],
  ],
};
`

这是我去掉默认的ts支持后的，也是一样的启动失败~
因为我项目中引用了装饰器和类，所以需要在babel中添加配置

**Comment by chenmingzhen** [comment]
原因找到了！因为使用cnpm安装依赖，导致插件重复，使用yarn后正常
