### ISSUE TITLE
[问题] AppConfig这个接口里面好多属性是必填的?小程序原生js里面好像不是必填的

### ISSUE THREAD

**Issue by yuanjinzhong** [remaxjs/remax#1658]
**问题描述**
 RT, 属性要求必填，不填报波浪线很难受

**Comment by sydeEvans** [comment]
AppConfig 具体是指？

**Comment by yuanjinzhong** [comment]
> AppConfig 具体是指？

![image](https://user-images.githubusercontent.com/13908993/127262875-0de7744e-7611-4ed2-a29c-c73c76ccb6b5.png)

![image](https://user-images.githubusercontent.com/13908993/127262967-cf366abf-2e7e-475a-a2c2-946774db14c7.png)
d.ts 文件里面定义的接口，需要属性必填。使用的时候我不填的话，会有波浪线

**Comment by watsonhaw5566** [comment]
你使用了tabbar这些参数是需要的啊

**Comment by yuanjinzhong** [comment]
> 你使用了tabbar这些参数是需要的啊
不是吧，小程序原生js中，红框里面的可以不需要

**Comment by sydeEvans** [comment]
你写了tarbar之后，里面的属性确实是必填的

**Comment by sydeEvans** [comment]
欢迎提pr来调整这个类型定义

**Comment by yuanjinzhong** [comment]
> 欢迎提pr来调整这个类型定义

好的[呲牙]
