### ISSUE TITLE
[BUG]开发web端修改devServer port无效

### ISSUE THREAD

**Issue by zhang-jiashun** [remaxjs/remax#1665]
**bug 描述**
开发 web 端，需要修改 devServer 的端口，修改后无效：

```javascript
module.exports = {
  one: true,
  output: 'dist/' + process.env.REMAX_PLATFORM,
  configWebpack({config, webpack, addCSSRule}) {
    config.devServer.port(5000).open(true)
  }
};
```

open(true)是有效的，port(5000)无效，配置后仍然是3000端口

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [2.9.1]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by sydeEvans** [comment]
#1671 修复了这个问题
支持在配置文件中设置port
