### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qqwq3** [remaxjs/remax#1677]
**bug 描述**
dist 文件里面的 remax-vendors.js 体积太大

**复现步骤**
npm run dev 后， dist 文件里面的 remax-vendors.js 体积太大

**期望结果**
减小体积

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
dist 文件里面的 remax-vendors.js 体积太大

**Comment by qqwq3** [comment]
dist 文件里面的 remax-vendors.js 体积太大

**Comment by watsonhaw5566** [comment]
开发阶段，需要更多的调试信息所以会保留部分souremap。如果开发阶段包太大超出了预览。可以使用 -m 的命令进行压缩。
但是这样会丢失报错信息。
