### ISSUE TITLE
[问题] 请问remaxjs 如何使用EventChannel ?

### ISSUE THREAD

**Issue by xiaocode337317439** [remaxjs/remax#1678]
请问remaxjs 如何使用EventChannel,
跳转前页面可以通过navigateTo success回调参数获取 eventChannel, 但是跳转后的页面， 通过navigateBack返回，没办法获取，
小程序文档 通过const eventChannel = this.getOpenerEventChannel() 获取， 但是remaxjs 没有暴露方式获取

**Comment by watsonhaw5566** [comment]
这个实现能否通过使用React的Context来传递呢？还是你们有别的需求，因为感觉这个是页面通信，React也有不错的实践了。不一定需要用到微信的实现。

**Comment by yesmeck** [comment]
楼上说的对，React 里不需要用 EventChannel。
