### ISSUE TITLE
[需求]多修复下annar的bug吧，就这一个UI库😭还各种问题

### ISSUE THREAD

**Issue by zzcwzhang** [remaxjs/remax#1680]
**需求描述**
[详细地描述需求，让大家都能理解]

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
为什么在Remax库提交annar库的问题？那个UI库并不是我们维护的。

**Comment by zzcwzhang** [comment]
好的，谢谢这么快回复
