### ISSUE TITLE
[BUG] remax/one中的Textarea组件，maxlength属性是无效的

### ISSUE THREAD

**Issue by LuckyRabbitFeet** [remaxjs/remax#1686]
**bug 描述**
RT
场景：微信小程序
remax/one中的Textarea组件，即使设置了maxlength属性，但在微信小程序中实际最大输入长度还是140

**复现步骤**

```js
import { Textarea } from 'remax/one'

export default Test = () => (
  <Textarea
    maxlength={-1}
    placeholder="测试测试"
  />
)
```

**期望结果**

maxlength属性可以发挥作用

**版本信息:**

- remax 版本: ^2.9.1
- 小程序端 微信小程序
- 小程序版本 2.19.1
- 开发环境 mac OS

**Comment by yesmeck** [comment]
应该是 `maxLength`，L 大写。

**Comment by LuckyRabbitFeet** [comment]
> 应该是 `maxLength`，L 大写。

感谢解答，这样的话建议文档可以更新一下，文档里`maxlength `的L是小写的。
https://remaxjs.org/api/remax-one/components#textarea

**Comment by yesmeck** [comment]
更新了，谢谢
