### ISSUE TITLE
onReachBottom 在h5环境下没有生效 [BUG]

### ISSUE THREAD

**Issue by Mr-haoxuan** [remaxjs/remax#1688]
**bug 描述**
多端项目，在h5中发现没有触发onReachBottom生命周期

**复现步骤**
  usePageEvent('onReachBottom', () => {
    console.log('页面到底了');
    // ... something
  });

没有触发onReachBottom
**期望结果**
在h5中能正常触发生命周期
**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
这个你搞定没
