### ISSUE TITLE
[问题]微信小程序新获取用户信息的API wx.getUserProfile没找到

### ISSUE THREAD

**Issue by AnizGu** [remaxjs/remax#1693]
**问题描述**
[详细地描述问题，让大家都能理解]
开发小程序时遇到微信小程序API wx.getUserProfile未找到，可能是最新API你们还没加入。但是微信小程序以后新注册的小程序就用这个API获取用户信息了，旧的暂时没影响。

**Comment by watsonhaw5566** [comment]
不用找，直接wx.getUserProfile使用即可。

**Comment by yesmeck** [comment]
已添加
