### ISSUE TITLE
在web端，tabBar的修改问题

### ISSUE THREAD

**Issue by Timson020** [remaxjs/remax#1719]
**问题描述**
在web开发上，按文档介绍，使用了activeTitleColor，但是没有任何作用

**示例代码**
app.config.js
```
module.exports.web = {
  page: [],
 tabBar: {
		// 背景色
		backgroundColor: '#ffffff',
		// tab 标题颜色
		titleColor: '#666666',
		// 选中状态的 tab 标题颜色
		activeTitleColor: '#FF6F06',
		// tab 对象列表
		items: [
			{ title: '首页', url: 'pages/index/index', image: '../../tab/home_normal.png', activeImage: '../../tab/home_selected.png' },
			{ title: '个人', url: 'pages/mine/index', image: '../../tab/profile_normal.png', activeImage: '../../tab/profile_selected.png' },
		],
}
```

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Timson020** [comment]
还有一个问题就是 通过remax/one的API
```
navigateTo({ url: 'pages/history/index' })
redirectTo({ url: 'pages/history/index' })
```
跳进去二级页面，底下的tab都是没有关闭的

**Comment by watsonhaw5566** [comment]
@Timson020 把这个改为一个bug吧，如果还有其他问题。也一并写入。我周末抽空修复。谢谢

**Comment by Timson020** [comment]
已经重新提交bug issue

**Comment by hongmaoxiao** [comment]
> 还有一个问题就是 通过remax/one的API
> 
> ```
> navigateTo({ url: 'pages/history/index' })
> redirectTo({ url: 'pages/history/index' })
> ```
> 
> 跳进去二级页面，底下的tab都是没有关闭的

这个问题解决了吗，我也遇到了，我还以为是我的用法有问题

**Comment by watsonhaw5566** [comment]
> > 还有一个问题就是 通过remax/one的API
> > ```
> > navigateTo({ url: 'pages/history/index' })
> > redirectTo({ url: 'pages/history/index' })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 跳进去二级页面，底下的tab都是没有关闭的
> 
> 这个问题解决了吗，我也遇到了，我还以为是我的用法有问题

还没有解决，是一个bug问题
