### ISSUE TITLE
在web端，tabBar的修改问题

### ISSUE THREAD

**Issue by Timson020** [remaxjs/remax#1722]
**bug 描述**
在web开发上，按文档介绍，使用了activeTitleColor，但是没有任何作用
使用API navigateTo 或 redirectTo 进行跳转, 都没有办法使tabBar隐藏

**复现步骤**
app.config.js
```javascript
module.exports.web = {
  page: [],
 tabBar: {
		// 背景色
		backgroundColor: '#ffffff',
		// tab 标题颜色
		titleColor: '#666666',
		// 选中状态的 tab 标题颜色
		activeTitleColor: '#FF6F06',
		// tab 对象列表
		items: [
			{ title: '首页', url: 'pages/index/index', image: '../../tab/home_normal.png', activeImage: '../../tab/home_selected.png' },
			{ title: '个人', url: 'pages/mine/index', image: '../../tab/profile_normal.png', activeImage: '../../tab/profile_selected.png' },
		],
}
```

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
Tanks

**Comment by Timson020** [comment]
有进展了么?
项目需要推进，这个问题有点大。希望尽快修复

**Comment by Timson020** [comment]
使用API navigateTo 或 redirectTo 进行跳转, 都没有办法使tabBar隐藏

@watsonhaw5566

**Comment by watsonhaw5566** [comment]
> 使用API navigateTo 或 redirectTo 进行跳转, 都没有办法使tabBar隐藏
> 
> @watsonhaw5566

嗯，知道这个问题，目前正在想办法修复。群里的小伙伴们说了

**Comment by hongmaoxiao** [comment]
使用API navigateTo 或 redirectTo 进行跳转, 都没有办法使tabBar隐藏
这个bug好像没有修复吧，怎么关了呢？

**Comment by Timson020** [comment]
目前只能使用css来覆盖
 估计还在修复中
