### ISSUE TITLE
请问如何测量某个 View 的尺寸？

### ISSUE THREAD

**Issue by arniu** [remaxjs/remax#1728]
**问题描述**
react-native 的 `View` 有个 `onLayout` 方法，可以用来测量自身的位置、尺寸。就我所知 remax 好像没有类似的功能。

**示例代码**
无

**其他信息**
无

**Comment by watsonhaw5566** [comment]
使用场景是web还是小程序？

**Comment by arniu** [comment]
小程序

**Comment by watsonhaw5566** [comment]
小程序直接使用对应的api即可

**Comment by arniu** [comment]
https://github.com/remaxjs/examples/blob/0a27b5f5f9544363887bb8478d9e16650f4301d2/wechat-f2/src/pages/index/index.js#L51-L60

我看到例子中有这个方法，非常感谢！
