### ISSUE TITLE
`TabList` 应更名为 `TabItem`

### ISSUE THREAD

**Issue by arniu** [remaxjs/remax#1730]
https://github.com/remaxjs/remax/blob/3a390f00f38b40ccb289094109bfc06740e3a86a/packages/remax-wechat/src/types/config.ts#L79

**Comment by watsonhaw5566** [comment]
来个PR？

**Comment by watsonhaw5566** [comment]
@arniu 今天翻了一下，这个参数用于那里的？

**Comment by arniu** [comment]
只在 `AppConfig` 定义中用的，外部并未使用。

**Comment by watsonhaw5566** [comment]
> 只在 `AppConfig` 定义中用的，外部并未使用。至于为什么要改，纯粹是名实不符。此外 ali 中就成称为 `TabItem`。

那就修改ali的就好

**Comment by arniu** [comment]
问题是 ali 的是对的，具体可参考 #1732
