### ISSUE TITLE
[问题]如何覆盖原有的webpack url-laoder配置

### ISSUE THREAD

**Issue by xywai1993** [remaxjs/remax#1736]
**问题描述**
我添加了一个对静态图片处理的url-laoder 配置是可以正常工作的，但是框架原有的url-laoder依然还是会生效，这样图片就会被处理两次，现在想覆盖原有的配置，该如何做

**示例代码**

这是我写的配置，是可以正常工作的
```
module.exports = {
    configWebpack({ config, webpack }) {
      
        config.output.publicPath('http://www.baidu.com/img/');

        config.module
            .rule('static')
            .test(/\.(png|jpe?g|gif|svg)(\?.*)?$/)
            .use('url-loader')
            .loader('url-loader')
            .options({
                limit: 6,
                name: 'img/[name].[hash:5].[ext]',
            });
    },
};
```

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by xywai1993** [comment]
> 可否直接放在public文件里里面再引用，还是您对图片有了二次

是想对图片添加publicPath 和 放在一个单独的文件夹里 。如果引用public里的图片，图片地址会保持原样

**Comment by watsonhaw5566** [comment]
> > 可否直接放在public文件里里面再引用，还是您对图片有了二次
> 
> 是想对图片添加publicPath 和 放在一个单独的文件夹里 。如果引用public里的图片，图片地址会保持原样

那还是推荐在public目录里面新建一个文件夹就好了，你这样的修改会使用到两次url-loader
