### ISSUE TITLE
调试工具

### ISSUE THREAD

**Issue by hzzhuxiaowei** [remaxjs/remax#174]
**需求描述**
代码经过编译之后在开发者工具中都不好调试 请问这块是否有方法解决

**Comment by Darmody** [comment]
你指的是 sourcemap 吗？

**Comment by hzzhuxiaowei** [comment]
但是开发者工具应该都是闭源的吧 不能自己写扩展 sourcemap也读不到

**Comment by Darmody** [comment]
我们可以把 sourcemap 弄弄看，后面还会尝试加上 react dev-tool

**Comment by krhougs** [comment]
直接弄成Chrome插件丢进小程序的开发工具里？

**Comment by Darmody** [comment]
可以试试
