### ISSUE TITLE
[问题]小程序原生页面里引用的 npm 模块编译后如何生效

### ISSUE THREAD

**Issue by cpdeam** [remaxjs/remax#1748]
**问题描述**
小程序原生页面里引用的npm模块，编译后无效，在dist里也找不到

**示例代码**
源码：
```
index.config.js
module.exports = {
  usingComponents: {
    login: '@xxx/mini-app-login-component/login/index', // 源码里npm install的包
  },
};
```
```
index.wxml
<login></login>
```

编译后：
```
index.json:
{
  "usingComponents": {}
}
```

 #762 看这个是已经修复了，还是说原生页面不支持？或者是缺少了哪一步操作吗？

**Comment by watsonhaw5566** [comment]
能否提供一小段代码给我测试一下，最好能提供一个复现的仓库。

**Comment by Tenodec** [comment]
你需要引用dist文件夹下的文件，比如vant  官方例子："van-calendar": "@vant/weapp/calendar/index"，在remax里的原生文件引入："van-calendar": "@vant/weapp/dist/calendar/index"

**Comment by yesmeck** [comment]
@cpdeam 提供下可重现的 repo

**Comment by cpdeam** [comment]
> @cpdeam 提供下可重现的 repo

抱歉，已解决，是我们引用的npm模块自身问题。
