### ISSUE TITLE
remax-cli 启动时检查 remax 版本是否匹配

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#175]
现在 remax-cli 跟 remax 的版本号必须一致，不然可能编译时的模板没法渲染运行时的树。需要在 remax-cli 启动时检查  remax 的版本号并给出警告。

**Comment by Darmody** [comment]
给出警告，还是直接中止呢？

**Comment by yesmeck** [comment]
警告吧

**Comment by Darmody** [comment]
加一个 remax doctor 的命令
