### ISSUE TITLE
[问题]微信更新隐私政策要求，对Remax的影响

### ISSUE THREAD

**Issue by RickoNoNo3** [remaxjs/remax#1751]
**问题描述**
微信于近期更新了隐私政策要求，要求所有提交审核的小程序填写用户隐私协议。其中涉及到小程序调用权限用途的填写，这部分中，调用的权限是微信通过打包后的代码自动检测出来的，都是Remax自动打包的，我们开发中不直接参与任何权限的申请和权限的原生调用（可以看看下图中有多少检测到的权限，几乎覆盖了全部）。这导致在填写此协议时出现困难。我们想知道Remax打算如何适配此变化。

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
![图片](https://user-images.githubusercontent.com/42743884/140772496-6c68d5bf-f252-4c05-8f65-2c69316d6dee.png)
![图片](https://user-images.githubusercontent.com/42743884/140772458-257422d5-b22c-4c9d-9362-bb5a3de04ec6.png)
![图片](https://user-images.githubusercontent.com/42743884/140772736-86b76c7f-c9b4-4523-8a22-196318a3c33c.png)

**Comment by watsonhaw5566** [comment]
#1577 3.0的计划里面会进行小程序的api移除。
2.0的版本由于为了方便直接导出api所以直接内嵌在remax/平台包里，导致打包的时候会全部api接口打包进去。

**Comment by cpdeam** [comment]
我们小程序提审也是这样，必须要填好隐私设置才能提审，但是很多API都没有使用，现在不知道该怎么填了

**Comment by yesmeck** [comment]
简单的做法就是不要用 remax 导出的 API，因为也没什么特别的，直接用全局的 `wx` 上的 API 就行。

**Comment by lhzbxx** [comment]
> 简单的做法就是不要用 remax 导出的 API，因为也没什么特别的，直接用全局的 `wx` 上的 API 就行。

但是组件不也是引用在 'remax/wechat' 这个包里吗？即便不用 remax 导出的 API，也会因为引用组件导出。

**Comment by watsonhaw5566** [comment]
> > 简单的做法就是不要用 remax 导出的 API，因为也没什么特别的，直接用全局的 `wx` 上的 API 就行。
> 
> 但是组件不也是引用在 'remax/wechat' 这个包里吗？即便不用 remax 导出的 API，也会因为引用组件导出。

先填写隐私协议，不要等开发团队。

**Comment by lhzbxx** [comment]
> > > 简单的做法就是不要用 remax 导出的 API，因为也没什么特别的，直接用全局的 `wx` 上的 API 就行。
> > 
> > 
> > 但是组件不也是引用在 'remax/wechat' 这个包里吗？即便不用 remax 导出的 API，也会因为引用组件导出。
> 
> 先填写隐私协议，不要等开发团队。

近期不解决一下吗？个人认为这个不算是小问题。

**Comment by RickoNoNo3** [comment]
> > > 简单的做法就是不要用 remax 导出的 API，因为也没什么特别的，直接用全局的 `wx` 上的 API 就行。
> > 
> > 
> > 但是组件不也是引用在 'remax/wechat' 这个包里吗？即便不用 remax 导出的 API，也会因为引用组件导出。
> 
> 先填写隐私协议，不要等开发团队。

我们的前几个版本都靠瞎填过审了，现在的版本已经打回来三次了，原因都是小程序用户信息授权描述不明确。

微信是每提交一个线上版本都要审查一次，不是一劳永逸的。

**Comment by yesmeck** [comment]
刚发布了 `remax@2.15.8`，这个版本可以通过配置 `webpack.IgnorePlugin` 去掉对所有微信 API 的依赖：

```js
// remax.config.js
module.exports = {
  configWebpack({ config, webpack }) {
    config.plugin('ignore').use(webpack.IgnorePlugin, [
      {
        resourceRegExp: /^\.\/api$/,
        contextRegExp: /@remax\/wechat\/esm$/,
      },
    ]);
  },
};
```

这样配置后需要把所有业务代码中从 `remax/wechat` 引用的 API 全部改成直接调用全局变量 `wx` 上的。

```patch
- import { getUserInfo } from 'remax/wechat';
+ const getUserInfo = promisify(wx.getUserInfo);
```

`promisify` 可以参考 https://github.com/remaxjs/remax/blob/master/packages/remax-framework-shared/src/promisify.ts 自己去实现。

这样修改后 remax 内部只会依赖这 5 个微信 API https://github.com/remaxjs/remax/blob/master/packages/remax-one/src/api/index.wechat.ts#L5-L9

**Comment by Aleczhang1992** [comment]
> 刚发布了 `remax@2.15.8`，这个版本可以通过配置 `webpack.IgnorePlugin` 去掉对所有微信 API 的依赖：
> 
> ```js
> // remax.config.js
> module.exports = {
>   configWebpack({ config, webpack }) {
>     config.plugin('ignore').use(webpack.IgnorePlugin, [
>       {
>         resourceRegExp: /^\.\/api$/,
>         contextRegExp: /@remax\/wechat\/esm$/,
>       },
>     ]);
>   },
> };
> ```
> 
> 这样配置后需要把所有业务代码中从 `remax/wechat` 引用的 API 全部改成直接调用全局变量 `wx` 上的。
> 
> ```diff
> - import { getUserInfo } from 'remax/wechat';
> + const getUserInfo = promisify(wx.getUserInfo);
> ```
> 
> `promisify` 可以参考 https://github.com/remaxjs/remax/blob/master/packages/remax-framework-shared/src/promisify.ts 自己去实现。
> 
> 这样修改后 remax 内部只会依赖这 5 个微信 API https://github.com/remaxjs/remax/blob/master/packages/remax-one/src/api/index.wechat.ts#L5-L9

/^\.\/api$/这个路径的代码需要自己加吗？现在会一直报Cannot find module './api'

**Comment by yesmeck** [comment]
可以搞个重现 repo 看看

**Comment by BlackCloud37** [comment]
我们小程序也遇到这个问题，而且尝试去掉所有API后用Annar会报错，因为Annar的DatePicker等组件似乎依赖了remax导出的API。

考虑到微信是扫描代码来查接口使用，我暂时采用的解决办法是webpack打包的时候把那些会被微信扫到的接口给replace掉（因为我确实没有用到，所以replace可能问题不大？），这样也不会影响已经使用的那些API。具体replace哪些接口需要自己硬编码一下

简单写了个脚本，用到了`string-replace-loader`：
```javascript
// remax.config.js

module.exports = {
   configWebpack({ config }) {
     config.module
       .rule('shake')
       .test(/index.js$/)
       .use('string-replace-loader')
       .loader('string-replace-loader')
       .options({
         multiple: [
           'getWeRunData',
           'chooseInvoiceTitle',
           'chooseInvoice',
           'chooseLicensePlate',
           'openBluetoothAdapter',
           'createBLEPeripheralServer',
           'addPhoneContact',
           'addPhoneRepeatCalendar',
           'addPhoneCalender'
         ]
           .map((search, index) => {
             const replace = `REPLACEMENT${index}`; // or use random string
             return [
               {
                 search,
                 replace
               },
               {
                 search: `wx.${search}`,
                 replace
               }
             ];
           })
           .flat()
       })
       .end();
   }
 };
```

**Comment by lhzbxx** [comment]
一个临时解决方案：通过 patch package 移除不需要的 API 和组件。

**Comment by watsonhaw5566** [comment]
> 我们小程序也遇到这个问题，而且尝试去掉所有API后用Annar会报错，因为Annar的DatePicker等组件似乎依赖了remax导出的API。
> 
> 考虑到微信是扫描代码来查接口使用，我暂时采用的解决办法是webpack打包的时候把那些会被微信扫到的接口给replace掉（因为我确实没有用到，所以replace可能问题不大？），这样也不会影响已经使用的那些API。具体replace哪些接口需要自己硬编码一下
> 
> 简单写了个脚本，用到了`string-replace-loader`：
> 
> ```js
> // remax.config.js
> 
> module.exports = {
>    configWebpack({ config }) {
>      config.module
>        .rule('shake')
>        .test(/index.js$/)
>        .use('string-replace-loader')
>        .loader('string-replace-loader')
>        .options({
>          multiple: [
>            'getWeRunData',
>            'chooseInvoiceTitle',
>            'chooseInvoice',
>            'chooseLicensePlate',
>            'openBluetoothAdapter',
>            'createBLEPeripheralServer',
>            'addPhoneContact',
>            'addPhoneRepeatCalendar',
>            'addPhoneCalender'
>          ]
>            .map((search, index) => {
>              const replace = `REPLACEMENT${index}`; // or use random string
>              return [
>                {
>                  search,
>                  replace
>                },
>                {
>                  search: `wx.${search}`,
>                  replace
>                }
>              ];
>            })
>            .flat()
>        })
>        .end();
>    }
>  };
> ```

你的这个我能否抽出来做成一个组件为群友们用？

**Comment by watsonhaw5566** [comment]
我根据你的代码整理了一个插件写了一个插件在这里。感谢您的付出BlackCloud37
[@remax/plugin-wx-shake](https://www.npmjs.com/package/@remax/plugin-wx-shake)

**Comment by xiaocode337317439** [comment]
我安装了 "@remax/plugin-wx-shake": "^1.0.8",
由于没有使用获取用户信息， 我全部开启了，但是还是报错 "export 'xxxx' was not found in 'remax/wechat'
`
const WxShake = require('@remax/plugin-wx-shake');
const apiList = [
    'getWeRunData',
    'chooseLocation',
    'chooseInvoiceTitle',
    'chooseInvoice',
    'chooseImage',
    'chooseMedia',
    'chooseLicensePlate',
    'openBluetoothAdapter',
    'createBLEPeripheralServer',
    'addPhoneContact',
    'addPhoneRepeatCalendar',
    'addPhoneCalender',
    'saveFileToDisk',
]

module.exports = {
    plugins: [less(), WxShake({ apiList })],
    ....
}
`

**Comment by watsonhaw5566** [comment]
@xiaocode337317439  你好，请使用 一下 @remax/plugin-wx-shake 1.0.9 的插件版本再试试，我已测试过并更新了一下插件。

**Comment by xiaocode337317439** [comment]
> @xiaocode337317439 你好，请使用 一下 @remax/plugin-wx-shake 1.0.10 的插件版本再试试，我已测试过并更新了一下插件。

使用最新版本 "remax": "^2.15.12" 和 "@remax/plugin-wx-shake": "^1.0.10", 
这句引用 import { View } from 'remax/wechat'; 会提示 "export 'View' was not found in 'remax/wechat'

**Comment by xiaocode337317439** [comment]
> @xiaocode337317439 你好，请使用 一下 @remax/plugin-wx-shake 1.0.10 的插件版本再试试，我已测试过并更新了一下插件。

使用 "remax": "^2.15.12" 和 "@remax/plugin-wx-shake": "^1.0.10" 使用默认替换所有 plugins: [less(), WxShake()]
还有下图几个权限，是因为这几个权限是必须的吗？
<img width="728" alt="截屏2022-02-08 下午4 18 51" src="https://user-images.githubusercontent.com/21286091/152946250-7bf26aee-b7f9-44bf-a31f-0d8716cebd1c.png">

**Comment by f48vj** [comment]
> > @xiaocode337317439 你好，请使用 一下 @remax/plugin-wx-shake 1.0.10 的插件版本再试试，我已测试过并更新了一下插件。
> 
> 使用 "remax": "^2.15.12" 和 "@remax/plugin-wx-shake": "^1.0.10" 使用默认替换所有 plugins: [less(), WxShake()] 还有下图几个权限，是因为这几个权限是必须的吗？ <img alt="截屏2022-02-08 下午4 18 51" width="728" src="https://user-images.githubusercontent.com/21286091/152946250-7bf26aee-b7f9-44bf-a31f-0d8716cebd1c.png">

碰到一样的问题

**Comment by xie-zhichao** [comment]
使用插件之后，还有两个问题：

1.  插件缺少一个依赖包：string-replace-loader
2. 和上面同学一样，还有三个项去不掉，应该是因为 reamx/one 封装了小程序的组件。

**Comment by watsonhaw5566** [comment]
> 使用插件之后，还有两个问题：
> 
> 1. 插件缺少一个依赖包：string-replace-loader
> 2. 和上面同学一样，还有三个项去不掉，应该是因为 reamx/one 封装了小程序的组件。

@xiaocode337317439 @xie-zhichao 
1. string-replace-loader 需要额外安装无法在插件内使用，所以需要使用者额外安装，插件包 readme 已有说明。
2. 这三项是 微信对模板的检查，remax 依赖静态模板生成 base_template 暂时无法移除对应模板属性 , 与 remax/one 无关

**Comment by xie-zhichao** [comment]
> > 使用插件之后，还有两个问题：
> > 
> > 1. 插件缺少一个依赖包：string-replace-loader
> > 2. 和上面同学一样，还有三个项去不掉，应该是因为 reamx/one 封装了小程序的组件。
> 
> @xiaocode337317439 @xie-zhichao
> 
> 1. string-replace-loader 需要额外安装无法在插件内使用，所以需要使用者额外安装，插件包 readme 已有说明。
> 2. 这三项是 微信对模板的检查，remax 依赖静态模板生成 base_template 暂时无法移除对应模板属性 , 与 remax/one 无关

了解，多谢解答～

**Comment by hellohejinyu** [comment]
> > > 使用插件之后，还有两个问题：
> > > 
> > > 1. 插件缺少一个依赖包：string-replace-loader
> > > 2. 和上面同学一样，还有三个项去不掉，应该是因为 reamx/one 封装了小程序的组件。
> > 
> > 
> > @xiaocode337317439 @xie-zhichao
> > 
> > 1. string-replace-loader 需要额外安装无法在插件内使用，所以需要使用者额外安装，插件包 readme 已有说明。
> > 2. 这三项是 微信对模板的检查，remax 依赖静态模板生成 base_template 暂时无法移除对应模板属性 , 与 remax/one 无关
> 
> 了解，多谢解答～
![image](https://user-images.githubusercontent.com/8766034/165889328-637e3f3d-5e33-4d04-8b9f-d2da30e301d4.png)
位置可以去掉，最终应该剩下【访问你的麦克风】和【访问你的摄像头】没法去。
<img width="291" alt="image" src="https://user-images.githubusercontent.com/8766034/165889406-1c4a6ea4-59c2-4150-ae9b-50ef6d86ee36.png">
去位置的时候，这两个 api 顺序不要反掉，那个插件有 bug。

**Comment by watsonhaw5566** [comment]
> > > > 使用插件之后，还有两个问题：
> > > > 
> > > > 1. 插件缺少一个依赖包：string-replace-loader
> > > > 2. 和上面同学一样，还有三个项去不掉，应该是因为 reamx/one 封装了小程序的组件。
> > > 
> > > 
> > > @xiaocode337317439 @xie-zhichao
> > > 
> > > 1. string-replace-loader 需要额外安装无法在插件内使用，所以需要使用者额外安装，插件包 readme 已有说明。
> > > 2. 这三项是 微信对模板的检查，remax 依赖静态模板生成 base_template 暂时无法移除对应模板属性 , 与 remax/one 无关
> > 
> > 
> > 了解，多谢解答～
> > ![image](https://user-images.githubusercontent.com/8766034/165889328-637e3f3d-5e33-4d04-8b9f-d2da30e301d4.png)
> > 位置可以去掉，最终应该剩下【访问你的麦克风】和【访问你的摄像头】没法去。
> 
> <img alt="image" width="291" src="https://user-images.githubusercontent.com/8766034/165889406-1c4a6ea4-59c2-4150-ae9b-50ef6d86ee36.png">
> 
> 去位置的时候，这两个 api 顺序不要反掉，那个插件有 bug。

谢谢你的提醒，我已经更新了 @remax/plugin-wx-shake  1.0.11 版本可以处理这个问题了，我猜测顺序问题是用了正则的问题。

**Comment by lqs577lqs** [comment]
`
module.exports = {
    plugins: [
        WxShake(apiList),
        less({
          lessOptions: {
            globalVars: {
              'primary-color': '"#4569d4"',
            },
          },
        })
    ],
};
`
使用了WxShake插件之后，运行所有的
