### ISSUE TITLE
进行通用网络请求的最佳方式是什么？

### ISSUE THREAD

**Issue by dubiao** [remaxjs/remax#1752]
**问题描述**
进行通用网络请求的最佳方式是什么？
目前我要对一个通用（跨平台）小程序进行网络请求，需要从各自的平台中找到`request`方法，然后进行请求。
但不知道是否是正确的方式。

是否可以从 remax/one 中导出一个通用的 `request` 或 `fetch` 方法这样可以对不同平台使用相同的方式进行请求。

**示例代码目前**
```
import {request} from 'remax/wechat'
```

**示例代码（希望可以）**
```
import { request } from 'remax/one'

request('http://api.demo.com/v1/post', {name: 'How', age: 15})
     .then().catch()

```

**Comment by watsonhaw5566** [comment]
不支持，也不会封装。可以用axios adapter做多平台支持。
