### ISSUE TITLE
[问题]

### ISSUE THREAD

**Issue by leeziiAtCn** [remaxjs/remax#1755]
**问题描述**
请问，在 remax 项目里新建一个 `babel.config.js ` 文件后，会覆盖 remax 项目原来的 babel 配置吗？还是会合并？
**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
好好描述问题，你需要在babel里面进行什么操作，在实际使用中遇到什么问题，对应的babel.config.js代码是什么。
这样也有助于后面的小伙伴遇到同样的问题。

**Comment by leeziiAtCn** [comment]
@watsonhaw5566 只是在`babel.config.js`里的增加一个 plugin , 不确定 remax 打包时的行为，是覆盖还是合并，看了一下源码是有一个合并的过程的，想在确认一下
扩展一下，我如果增加了一个 remax 已经使用的插件/配置，那么谁的配置会生效？

```javascript
module.exports = {
  plugins: [ignoreMockStatement],
};
```

**Comment by watsonhaw5566** [comment]
> @watsonhaw5566
> 
> ```js
> module.exports = {
>   plugins: [ignoreMockStatement],
> };
> ```
> 
> 只是在`babel.config.js`里的增加一个 plugin , 不确定 remax 打包时的行为，是覆盖还是合并，看了一下源码是有一个合并的过程的，想在确认一下 扩展一下，我如果增加了一个 remax 已经使用的插件/配置，那么谁的配置会生效？

是会先执行Remax的babel再读取你的babel，可以覆盖Remax的build行为

**Comment by leeziiAtCn** [comment]
3q @watsonhaw5566
