### ISSUE TITLE
[问题]请问 onPageComponent 是在什么时候执行的,  plugins 中使用的时候, 没有工作?

### ISSUE THREAD

**Issue by what-00** [remaxjs/remax#1756]

**Comment by watsonhaw5566** [comment]
请提供对应代码repo

**Comment by what-00** [comment]
```js
fsdpf-remax-miniprogram.js

const React = require('react');

class FsdpfRemaxMiniprogram {
    #routes = new Map

    constructor() {
        this.#routes.set('pages/test-a', {
            layout: '@fsdpf/frameworks/BasicLayout',
            isLogin: true,
            type: 'fsdpf-component',
            component: '@fsdpfApp/components/TestA'
        })

        this.#routes.set('pages/test-b', {
            layout: '@fsdpf/frameworks/BasicLayout',
            isLogin: true,
            type: 'fsdpf-component',
            component: '@fsdpfApp/components/TestB'
        })
    }

    // app.json
    onAppConfig = ({ config }) => {
        config.pages = Array.from(this.#routes.keys())
        return config
    }

    // page.json
    onPageConfig({ config, page }) {
        return config;
    }

    onPageComponent({ component, page }) {
        const selfPage = this.#routes.get(page) || {}

        const SelfPageLayoutComponent = require(selfPage.layout).default
        const SelfPageComponent = require(selfPage.component).default


        return React.forwardRef((props, ref) => {
            return React.createElement(
                SelfPageLayoutComponent,
                null,
                React.createElement(SelfPageComponent, { ...props, ref })
            );
        });
    }
}

module.exports = FsdpfRemaxMiniprogram
```

我想根据自己的 routes 编译 page 内容,  该怎么做才好, 谢谢 @watsonhaw5566

**Comment by watsonhaw5566** [comment]
> ```js
> fsdpf-remax-miniprogram.js
> 
> const React = require('react');
> 
> class FsdpfRemaxMiniprogram {
>     #routes = new Map
> 
>     constructor() {
>         this.#routes.set('pages/test-a', {
>             layout: '@fsdpf/frameworks/BasicLayout',
>             isLogin: true,
>             type: 'fsdpf-component',
>             component: '@fsdpfApp/components/TestA'
>         })
> 
>         this.#routes.set('pages/test-b', {
>             layout: '@fsdpf/frameworks/BasicLayout',
>             isLogin: true,
>             type: 'fsdpf-component',
>             component: '@fsdpfApp/components/TestB'
>         })
>     }
> 
>     // app.json
>     onAppConfig = ({ config }) => {
>         config.pages = Array.from(this.#routes.keys())
>         return config
>     }
> 
>     // page.json
>     onPageConfig({ config, page }) {
>         return config;
>     }
> 
>     onPageComponent({ component, page }) {
>         const selfPage = this.#routes.get(page) || {}
> 
>         const SelfPageLayoutComponent = require(selfPage.layout).default
>         const SelfPageComponent = require(selfPage.component).default
> 
> 
>         return React.forwardRef((props, ref) => {
>             return React.createElement(
>                 SelfPageLayoutComponent,
>                 null,
>                 React.createElement(SelfPageComponent, { ...props, ref })
>             );
>         });
>     }
> }
> 
> module.exports = FsdpfRemaxMiniprogram
> ```
> 
> 我想根据自己的 routes 编译 page 内容, 该怎么做才好, 谢谢 @watsonhaw5566

您看看能否提供一个最小可复现的片段。您这个是开发web/one同构的吗？

**Comment by what-00** [comment]
```js
remax.config.js

const FsdpfRemaxMiniprogram = require('./fsdpf-remax-miniprogram');

module.exports = {
    plugins: [less(), new FsdpfRemaxMiniprogram],
    configWebpack({ config }) {
        config.resolve.alias.set('@fsdpf', path.join(__dirname, '/fsdpf-core'))
        config.resolve.alias.set('@fsdpfPkg', path.join(__dirname, '/packages'))
        config.resolve.alias.set('@fsdpfApp', path.join(__dirname, '/src'))
    }
};
```

我是第一次使用remax,  只配置了 remax.config.js,  想测试一下 "根据自己的 routes 编译 page" 是否可行,

**Comment by watsonhaw5566** [comment]
> ```js
> remax.config.js
> 
> const FsdpfRemaxMiniprogram = require('./fsdpf-remax-miniprogram');
> 
> module.exports = {
>     plugins: [less(), new FsdpfRemaxMiniprogram],
>     configWebpack({ config }) {
>         config.resolve.alias.set('@fsdpf', path.join(__dirname, '/fsdpf-core'))
>         config.resolve.alias.set('@fsdpfPkg', path.join(__dirname, '/packages'))
>         config.resolve.alias.set('@fsdpfApp', path.join(__dirname, '/src'))
>     }
> };
> ```
> 
> 我是第一次使用remax, 只配置了 remax.config.js, 想测试一下 "根据自己的 routes 编译 page" 是否可行,

这个需要你研究一下了，我猜你是想实现类似umi自动路由。
但是这个涉及到Remax内置的打包构建。所以暂时不太清楚是否可行。

**Comment by what-00** [comment]
是的, 谢谢!
