### ISSUE TITLE
[BUG] 微信 Button 组件有无法消除的 border

### ISSUE THREAD

**Issue by YuPototo** [remaxjs/remax#1769]
**bug 描述**

微信 Button 组件有无法消除的 border

**复现步骤**
引入微信小程序 Button 组件，并使用。

**期望结果**
能够消除边框

**复现代码**
测试代码：
```tsx
import React, { ReactElement } from "react";
import { View, Button } from "remax/wechat";
export default function TestComponent(): ReactElement {
    return (
        <View
            style={{
                backgroundColor: "#fff",
                height: "100px",
                marginTop: "30px",
            }}
        >
            <Button style={{ width: "100px", border: 0 }}>按钮</Button>
        </View>
    );
}

```

**版本信息:**

- remax 版本: 2.9.1
- 手机型号：微信开发工具、安卓手机、iOS手机
- 小程序端：微信小程序
- 开发环境：MacOS

**其他信息**
上面代码的运行结果：
![image](https://user-images.githubusercontent.com/7348896/141924936-3f0f04fd-b259-464d-b171-cc51d84d8faf.png)

**Comment by noyobo** [comment]
微信的 Button 的 border 是写在 :after 伪类上的。
