### ISSUE TITLE
npm 页面信息缺失

### ISSUE THREAD

**Issue by afc163** [remaxjs/remax#177]
- [x] 缺 README
- [x] HomePage 错误

https://www.npmjs.com/package/remax

**Comment by yesmeck** [comment]
monorepo 的通病？

https://www.npmjs.com/package/umi

**Comment by afc163** [comment]
README 又没了

**Comment by yesmeck** [comment]
<img width="1600" alt="Screen Shot 2019-09-19 at 6 11 05 PM" src="https://user-images.githubusercontent.com/465125/65235298-df0e7a00-db08-11e9-8fb3-13cb0a032ee5.png">

我看有的

**Comment by afc163** [comment]
见鬼，可能是下午 npm bug 了
