### ISSUE TITLE
[问题]在同时配置 webpack/externals 和 小程序 app.json/workers 时, 会提示 externals 引用的module不存在, 这是 bug 吗?

### ISSUE THREAD

**Issue by what-00** [remaxjs/remax#1770]
remax.config.js
![image](https://user-images.githubusercontent.com/33273088/142959969-51f6fd2a-693c-40b7-89c9-248c53078a0a.png)

app.config.js
![image](https://user-images.githubusercontent.com/33273088/142959807-978619e3-1f48-4473-b56e-db4a93c6ab15.png)

错误提示
![image](https://user-images.githubusercontent.com/33273088/142960037-1c87db73-7df0-4137-9f69-81df7f915ffc.png)

**Comment by yesmeck** [comment]
<img width="440" alt="Screenshot 2021-11-23 at 1 43 21 PM" src="https://user-images.githubusercontent.com/465125/142976350-28775335-cd98-4ace-8e3c-1ebe3a5997e6.png">

构建完后这两个文件在 dist 目录下吗？

**Comment by what-00** [comment]
在的, assets和workers 都是放在 public 目录的.

**Comment by yesmeck** [comment]
提供一个可重现的 repo 吧

**Comment by what-00** [comment]
https://github.com/what-00/wechat-miniprogram.git

**Comment by yesmeck** [comment]
你的 require 路径写错了吧，微信的 require 支持这种绝对路径吗？

**Comment by what-00** [comment]
我看 https://github.com/remaxjs/remax/blob/fdc25e3c456286764be90611a238d66067c1eddb/packages/remax-cli/src/build/webpack/config.mini.ts :247 行附近都可这样写
```js
const externals = config.get('externals');
  const runtimeOptionsExternal = {
    '/__remax_runtime_options__': `require('/__remax_runtime_options__')`,
  };

  if (Array.isArray(externals)) {
    config.set('externals', [...externals, runtimeOptionsExternal]);
  } else {
    config.set('externals', {
      ...externals,
      ...runtimeOptionsExternal,
    });
  }
```

**Comment by yesmeck** [comment]
你试试不用 remax 行不行

**Comment by watsonhaw5566** [comment]
@what-00 最后怎么处理的？
