### ISSUE TITLE
[BUG] 自定义Hooks的返回值行为，与react环境下有不同

### ISSUE THREAD

**Issue by ramen-curator** [remaxjs/remax#1779]
**bug 描述**
remax的自定义hook用不了。
我写了两个demo来表达这个问题：
1. react中正常实现的结果：
https://codesandbox.io/s/shi-yan-reactzi-ding-yi-hookzhi-context-pzxwj?file=/src/App.js
2. 同样的代码，在remax中实现不了（useEffect替换成了useNativeEffect）:
https://github.com/ramen-curator/report-remax-useHook-bug-2021.12.6

这是bug吗？如果不是，这是什么原因呢？

**复现步骤**
# 在remax中，按钮列表渲染不出来
![image](https://user-images.githubusercontent.com/26692240/144848846-1eec25e2-9cef-41ce-9e1f-818c3b0401d4.png)
# 将代码复制，粘贴到codesandbox，列表可以成功渲染
![image](https://user-images.githubusercontent.com/26692240/144849044-78968513-7120-4fbc-aef6-c649cf6eebb8.png)

**期望结果**
期望两者行为一致，即，使用真正的 React 构建跨平台小程序。

**关键代码**
```javascript
const usePickContext = (Context, attrName) => {
  const [data, setData] = React.useState();
  const context = React.useContext(Context);

  useNativeEffect(() => {
    if (context) {
      setData(context[attrName]);
    }
  }, [context]);

  return data;
};
const BtnList = () => {
  // 一旦在remax中使用这个方法，就拿不到值：
  const btnList = usePickContext(TopContext, "btnList");
  // 可以正常取值的代码：
  // const btnList = useContext(TopContext)?.btnList;
  console.log("从Context中取值", btnList);
  ...
}
```

**版本信息:**
- remax 版本: 2.7.7
- 微信开发者工具Stable 1.05.2110290
- 开发环境 win10

**Comment by watsonhaw5566** [comment]
先参考一下remax的ali示例，https://github.com/remaxjs/examples/tree/master/ali
另外这个叫自定义hooks而不是自定义组件

**Comment by ramen-curator** [comment]
> 先参考一下remax的ali示例，https://github.com/remaxjs/examples/tree/master/ali 另外这个叫自定义hooks而不是自定义组件

抱歉，我加班到神智不清了

**Comment by ramen-curator** [comment]
@watsonhaw5566 
    首先，感谢作者的回复和指点。
    其次，希望作者能解惑为什么一样的代码会在react和remax之间产生不一样的行为。毕竟在知道它错误之前，是不知道它错在哪里的，而找出错误所在位置耗费大量时间。我希望下次能避免它，所以才想求解原因所在。

**Comment by yesmeck** [comment]
useNativeEffect 的行为跟 useEffect 就是不一样的。参考 https://remaxjs.org/api/remax#usenativeeffectcallback-deps

**Comment by ramen-curator** [comment]
@yesmeck 
&nbsp;&nbsp;&nbsp;&nbsp;恕我愚昧，我只从文档中看出了“useEffect与useNativeEffect”的执行时机不同。
&nbsp;&nbsp;&nbsp;&nbsp;为什么执行时机不同会导致出现我题中demo的意料之外行为？这是怎么推导出来的？写react真的需要考虑、推导这么多吗？如果是，你这个框架不好用。如果不是，这是个开发体验bug。

**Comment by yesmeck** [comment]
你这里就用 `useEffect`，不要用 `useNativeEffect`。
