### ISSUE TITLE
[BUG] ScrollView组件里slot无效

### ISSUE THREAD

**Issue by ramen-curator** [remaxjs/remax#1787]
**bug 描述**
ScrollView组件slot无效

**期望结果**
如下截图所示

**复现代码**
[可复现问题的代码仓库](https://github.com/ramen-curator/my-remax-issues-demos/tree/21.12.14-scrollViewSlot%E4%B8%8D%E6%98%BE%E7%A4%BA)
**关键代码**
```html
<View className="placeholder">placeholder</View>
<ScrollView scrollY refresherEnabled refresherDefaultStyle="none">
    <View className="refresher" slot="refresher">
        refresher
    </View>
    <View className="body">body</View>
</ScrollView>
```

**版本信息:**
- remax 版本: 2.9.1
- 开发环境 win10，微信开发者工具

**其他信息**
## 微信原生可以
![image](https://user-images.githubusercontent.com/26692240/145970355-dbc96be0-153f-4106-8215-78290d742935.png)
![image](https://user-images.githubusercontent.com/26692240/145970386-79af5584-9c9e-4cf8-9505-5a1c0c98eb67.png)
## remax不可以
![image](https://user-images.githubusercontent.com/26692240/145968823-67ee067c-ccc2-462f-9385-430e205226a6.png)
![image](https://user-images.githubusercontent.com/26692240/145968777-9878e438-9c3c-4df7-bac3-b0208d4e7921.png)

**Comment by fhyoga** [comment]
这个有进展吗，遇到同样的问题

**Comment by ramen-curator** [comment]
> 这个有进展吗，遇到同样的问题

没有，当时我是打算搞个下拉刷新的loading。最后放弃了，直接用小程序原生的整页下拉刷新了。

**Comment by watsonhaw5566** [comment]
> **bug 描述** ScrollView组件slot无效
> 
> **期望结果** 如下截图所示
> 
> **复现代码** [可复现问题的代码仓库](https://github.com/ramen-curator/my-remax-issues-demos/tree/21.12.14-scrollViewSlot%E4%B8%8D%E6%98%BE%E7%A4%BA) **关键代码**
> 
> ```
> <View className="placeholder">placeholder</View>
> <ScrollView scrollY refresherEnabled refresherDefaultStyle="none">
>     <View className="refresher" slot="refresher">
>         refresher
>     </View>
>     <View className="body">body</View>
> </ScrollView>
> ```
> 
> **版本信息:**
> 
> * remax 版本: 2.9.1
> * 开发环境 win10，微信开发者工具
> 
> **其他信息**
> 
> ## 微信原生可以
> ![image](https://user-images.githubusercontent.com/26692240/145970355-dbc96be0-153f-4106-8215-78290d742935.png) ![image](https://user-images.githubusercontent.com/26692240/145970386-79af5584-9c9e-4cf8-9505-5a1c0c98eb67.png)
> 
> ## remax不可以
> ![image](https://user-images.githubusercontent.com/26692240/145968823-67ee067c-ccc2-462f-9385-430e205226a6.png) ![image](https://user-images.githubusercontent.com/26692240/145968777-9878e438-9c3c-4df7-bac3-b0208d4e7921.png)
目前不支持 slot 属性
