### ISSUE TITLE
[RFC]重新设计事件 hooks

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#179]
之前把所有事件分别做成 hooks 是考虑到类型约束和避免字符串的拼错，但是现在发现支付宝小程序的事件有点多，每个事件都做成 hook 的话 API 就会有点多。

考虑把所有事件统一做到 `useEvent`  hook 里：

```javascript
import { useEvent, OnKeyboardHeightEvent } from 'remax/alipay';

export default  () => {
  useEvent('onBack', () => {
     console.log('back');
  });

  useEvent('onKeyboardHeight', (e: OnKeyboardHeightEvent) => {
    console.log('键盘高度：', e.height)
  });
}
```

支付宝小程序事件处理 https://docs.alipay.com/mini/framework/page-detail#%E9%A1%B5%E9%9D%A2%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%87%BD%E6%95%B0

**Comment by Darmody** [comment]
可以保留之前的，再加一个 `useEvent`

**Comment by yesmeck** [comment]
要保留，然后显示废弃提醒。

**Comment by Darmody** [comment]
class 组件呢

**Comment by yesmeck** [comment]
class 组件还是在 class 上直接写 `onBack`

**Comment by malash** [comment]
`useEvent` 的形式会不会不太适合TypeScript类型检查？

**Comment by yesmeck** [comment]
TypeScript 没事吧，第一个参数用 union type，之前主要是考虑到 JavaScript 容易拼错第一个参数。

**Comment by LingYanSi** [comment]
> TypeScript 没事吧，第一个参数用 union type，之前主要是考虑到 JavaScript 容易拼错第一个参数。

@yesmeck 这种方式如何
```js
import { useEvent, OnKeyboardHeightEvent, eventType } from 'remax/alipay';
useEvent(eventType.back, () => {
     console.log('back');
});
```

**Comment by yesmeck** [comment]
@LingYanSi  这样没有类型检查的话还是容易拼错。

**Comment by LingYanSi** [comment]
![image](https://user-images.githubusercontent.com/8621814/65605607-f901fe00-dfdb-11e9-9bbf-8fe88f522579.png)
@yesmeck 这样是否可以满足类型检查

**Comment by yesmeck** [comment]
用 ts 的字符串也没问题的，主要是 js 。

**Comment by LingYanSi** [comment]
那感觉这种担心是多余的，做好语法智能提示就好了。

**Comment by Darmody** [comment]
用字符串，ts写好enum。然后可以在useEvent里对字符串做一次校验，不存在的抛错。

这样应该就好了

**Comment by ilovedesert001** [comment]
与其这样
```
import { useEvent, OnKeyboardHeightEvent, eventType } from 'remax/alipay';
useEvent(eventType.back, () => {
     console.log('back');
});
```
为什么不直接
```
import { xxxEvents, OnKeyboardHeightEvent, eventType } from 'remax/alipay';
xxxEvents.useOnBack(() => {
     console.log('back');
});
```

这样代码压缩的时候，效率不是更高吗？
而且 ts 写起来也更加容易
