### ISSUE TITLE
[问题]小程序提交审核，提示代码调用了用户信息接口

### ISSUE THREAD

**Issue by xiaocode337317439** [remaxjs/remax#1804]
**问题描述**
根据所提交的代码版本，识别到小程序调用了收集用户个人信息的接口，请按照小程序实际运行情况，认真填写《xxxx小程序隐私保护指引》，并在调用情况或用户个人信息处理情况发生变动时及时更新本指引。
本指引将在用户使用小程序时，在更多资料页和授权弹窗等场景进行披露。若小程序实际情况与本指引内容不符，小程序开发者需承担由此产生的法律责任及风险。
<img width="798" alt="截屏2021-12-27 下午4 45 00" src="https://user-images.githubusercontent.com/21286091/147453450-bc3506f3-e840-4f2e-a9ee-854ec26c72de.png">

但是我什么信息都没有收集呀，只是使用了，这个应该没有收集用户信息呀
`
import { login } from 'remax/wechat';

    const info = await login();
    if (info.code) {
        await reLogin(info.code);
    }
`

**Comment by watsonhaw5566** [comment]
你好，可以参考一下 #1751 的issue进行对应处理。

**Comment by xiaocode337317439** [comment]
> 你好，可以参考一下 #1751 的issue进行对应处理。

我安装了 "@remax/plugin-wx-shake": "^1.0.8",   "remax": "2.15.8",
由于没有使用获取用户信息， 我全部开启了，但是还是报错 "export 'xxxx' was not found in 'remax/wechat'
我把全部的api调用都注释了，改用wx.xxx调用， 但是View里面好像有问题 "export 'View' was not found in 'remax/wechat'(现在只报错这一个错了)
```JavaScript 
const WxShake = require('@remax/plugin-wx-shake');
const apiList = [
    'getWeRunData',
    'chooseLocation',
    'chooseInvoiceTitle',
    'chooseInvoice',
    'chooseImage',
    'chooseMedia',
    'chooseLicensePlate',
    'openBluetoothAdapter',
    'createBLEPeripheralServer',
    'addPhoneContact',
    'addPhoneRepeatCalendar',
    'addPhoneCalender',
    'saveFileToDisk',
]

module.exports = {
    plugins: [less(), WxShake({ apiList })],
    ....
}
```

**Comment by watsonhaw5566** [comment]
你好，请使用 一下 @remax/plugin-wx-shake 1.0.9 的插件版本再试试，我已测试过并更新了一下插件。

**Comment by xiaocode337317439** [comment]
> 你好，请使用 一下 @remax/plugin-wx-shake 1.0.9 的插件版本再试试，我已测试过并更新了一下插件。

https://github.com/remaxjs/remax/issues/1751#issuecomment-1032333808

**Comment by xiaocode337317439** [comment]
> 你好，请使用 一下 @remax/plugin-wx-shake 1.0.9 的插件版本再试试，我已测试过并更新了一下插件。

使用最新版还 有几个权限存在，是因为必须吗？

https://github.com/remaxjs/remax/issues/1751#issuecomment-1032333808

**Comment by watsonhaw5566** [comment]
根据[微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/miniprogram-intro.html)再在源码里面搜一遍。
再检查一下自己的代码应用

**Comment by xiaocode337317439** [comment]
> 根据[微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/user-privacy/miniprogram-intro.html)再在源码里面搜一遍。 再检查一下自己的代码应用

编译出来的文件里面包含， 主要是一些标签引发的权限问题，麦克风 <live-pusher>， 摄像头<camera>、<live-pusher>、<voip-room>， 位置信息 startLocationUpdate 使用 WxShake() 替换不掉。

**Comment by watsonhaw5566** [comment]
嗯，那这个的话是过滤不掉的了，因为 remax 用这些都做成了 高阶组件。
