### ISSUE TITLE
[需求]是否能提供一个原生android或reactnative能集成的引擎，可以直接运行remax创建的小程序应用

### ISSUE THREAD

**Issue by silentzone** [remaxjs/remax#1805]
**需求描述**
觉得vue很搓，且uniapp的androidsdk 性能很差且不开源。
 类似uniapp 那样， react 版的uniapp

**解决方案**
android或ios 能集成的一个渲染小程序引擎。

**其他信息**

**Comment by watsonhaw5566** [comment]
remax目前已小程序/h5为主，暂不支持移动端的功能，已有社区的rn支持。你可以参考一下。
[remax-react-native-template](https://github.com/cqkqinfo/remax-react-native-template)

**Comment by sydeEvans** [comment]
目前没有这个计划
