### ISSUE TITLE
[需求]支持自定义的.env文件名写法

### ISSUE THREAD

**Issue by gao525280067** [remaxjs/remax#1806]
![image](https://user-images.githubusercontent.com/25193804/147725912-0298e9d5-8b5e-43bc-807c-035f009a1c9b.png)
类似vue的这个功能 https://cli.vuejs.org/zh/guide/mode-and-env.html#%E7%A4%BA%E4%BE%8B%EF%BC%9Astaging-%E6%A8%A1%E5%BC%8F

也就是 --mode=shanghai 这样的，可以通过省份的变量文件去切换不同的数据！

**Comment by yesmeck** [comment]
支持的 NODE_ENV=shanghai 就行。
