### ISSUE TITLE
[BUG] 使用 vant weapp 时遇到的奇葩问题

### ISSUE THREAD

**Issue by comlejade** [remaxjs/remax#1811]
**bug 描述**
第一次使用 yarn run dev 启动时，没有正常编译出 van-icon van-image 组件的内容

**复现步骤**
1、使用 create-remax-app 初始化项目（这里的版本一直没有升级，不知道是不是没人维护了）
2、手动升级 react 和 remax 版本，并安装最新的 react 、 remax 和 vant weapp
![image](https://user-images.githubusercontent.com/15702577/147999272-cb835313-0f4d-411d-b6c0-67f4543466e7.png)
3、在 pages/index/index 中添加 van-icon 和 van-image 组件
![image](https://user-images.githubusercontent.com/15702577/147999409-a8bc338b-2f21-458d-a89c-2ef8d41799ed.png)
4、如果 有 dist 目录先删除，保证是第一次编译出内容
5、运行 yarn run dev 命令
6、出现以下结果
![image](https://user-images.githubusercontent.com/15702577/147999520-7fa02e7c-b7ae-4452-a1c6-26d536356fd3.png)

页面上只有一个图片占位符

wxml内容是这样的
![image](https://user-images.githubusercontent.com/15702577/147999571-dbca8d16-3116-4199-b6fe-8df546608a53.png)

可以看到 icon的 class 内容不全, image 的 src 也没有

**版本信息:**

- remax 版本: [e.g. 2.15.10]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.21.2]
- 开发环境 [e.g. windows 小程序开发者工具]

**Comment by comlejade** [comment]
我刚把版本回退到 2.15.9，并没有出现这个问题。我前面用的是 create-remax-app 默认的 remax@2.9.1，react@16.14.0版本，那个版本的问题是van-field 只有 type = textarea 时，在微信开发者工具里 bind:change 才有效

**Comment by watsonhaw5566** [comment]
@comlejade 试试使用 @vantweapp/lib 目录下的vant组件，dist目录下的组件是已经es5打包的

create-remax-app 只是作为一个项目的手脚架 ，如果没有新的功能新增，更新版本号的意思在于？

**Comment by comlejade** [comment]
@watsonhaw5566 引用lib目录下还是同样的问题
![image](https://user-images.githubusercontent.com/15702577/148005550-00eaf279-bf88-4b81-a25c-e3804cdfec4c.png)

**Comment by watsonhaw5566** [comment]
@comlejade  vant 传参使用参数传参，而不是字符串。我这里是可以正常显示的。如果还是不行，建议react 版本再降低一下为 ^16.14.0

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by comlejade** [comment]
@watsonhaw5566 你把 dist 目录删了，然后命令行重新执行 yarn run dev，还显示吗？

**Comment by comlejade** [comment]
@watsonhaw5566 这个不光是icon和图片, van-field 组件的 label 也不能展示，2.15.9没有这些问题，9到10到底更新了什么导致的呢？还有就是 van-field 组件在 type 不是 textarea 时， bind:change 事件在开发者工具上（真机上没问题）不执行（这个问题，我在新建的测试项目上面没有重现，但是我的实际项目中确实存在，我把那个页面删的只剩一个van-field，也不执行）

**Comment by watsonhaw5566** [comment]
> @watsonhaw5566 你把生成的dist 目录删了，然后命令行重新执行 yarn run dev，刷新以下开发者工具，还显示吗？

显示的，我这边是正常的。9 到 10 只更新了 babel 的 cache 目录设置 。

最好你可以提供一个小的复现 repo

**Comment by comlejade** [comment]
@watsonhaw5566 这个 git@github.com:comlejade/remax-test.git

**Comment by watsonhaw5566** [comment]
> @watsonhaw5566 这个 [git@github.com](mailto:git@github.com):comlejade/remax-test.git

@comlejade 仓库链接

**Comment by comlejade** [comment]
@watsonhaw5566 https://github.com/comlejade/remax-test.git

**Comment by watsonhaw5566** [comment]
![image](https://user-images.githubusercontent.com/4210367/148026872-bd445c9a-9108-4d95-9894-1b77f92e1aeb.png)

![image](https://user-images.githubusercontent.com/4210367/148026887-ae610a5b-ea06-4606-a660-805a546bbfec.png)

![image](https://user-images.githubusercontent.com/4210367/148026897-61eee595-dbf0-4be9-be73-552160eef324.png)


跟着这个来，这是你使用的问题，不是 remax 的 bug

**Comment by comlejade** [comment]
不要 yarn run dev 启动之后再编辑页面，这样我也可以显示。要先编辑页面好之后，把前面生成的dist目录删了，然后命令行 yarn run dev 启动，这样第一次编译，问题就来了

![image](https://user-images.githubusercontent.com/15702577/148027587-ee93aa27-3222-41a6-ab06-cbb7f9864848.png)

**Comment by watsonhaw5566** [comment]
删除dist目录，同时删除掉 node_modules 中的 .cache 目录。 10 版本中开启了babel cache会缓存上一次的babel编译结果，所以导致cache 引用的是上一次的babel打包结果，所以就出错了，你可以先使用2.15.9 或者 手动删除一下 .cache目录就可以了。

**Comment by comlejade** [comment]
@watsonhaw5566 确实是 .cache 目录的原因，我再看看能不能复现那个输入的问题

**Comment by watsonhaw5566** [comment]
> @watsonhaw5566 确实是 .cache 目录的原因，我再看看能不能复现那个输入的问题

好的，有问题再@ 我，但是不一定回复那么快

**Comment by yesmeck** [comment]
@watsonhaw5566 看起来是 babel cache 引起的？

**Comment by watsonhaw5566** [comment]
> @watsonhaw5566 看起来是 babel cache 引起的？

是的，看来是引起副作用了。要不先移除，我想到办法再提交一个 patch 。

**Comment by yesmeck** [comment]
搞个插件吧要不，让想用的人自己开启。

**Comment by watsonhaw5566** [comment]
> 搞个插件吧要不，让想用的人自己开启。

好的，我来撸一个，那您先 revert 一下

**Comment by comlejade** [comment]
@watsonhaw5566 发现问题了，不同的页面间并没有完全隔离开，会相互影响。
https://github.com/comlejade/remax-test
我这里只测试了 van-button 按钮的情况，相信 van-field 也是相同的情况。
当classify 页面有 button 按钮的时候，index页面的button按钮样式不对（index页面的按钮并没有定义样式），点击事件也是无效的
![image](https://user-images.githubusercontent.com/15702577/148161570-393a7c64-c947-4efd-8c4f-4ee010abeb5b.png)
![image](https://user-images.githubusercontent.com/15702577/148161590-0f242c83-51e8-4c56-9f9a-d5e76c3b57a5.png)

当我把 classify 页面的 button 相关的全部注释掉，发现 index 页面的 button 样式正常了，点击事件也能用了
![image](https://user-images.githubusercontent.com/15702577/148161622-75261f63-7d1a-4774-b8d1-9b00951b1e8c.png)

**Comment by watsonhaw5566** [comment]
@comlejade 更新一下 remax 版本到 2.15.11 再看看这个问题，有可能还是 babel 缓存导致的问题 。
我们的项目没有用到vant button 和 vanr filed 这些组件。
你的repo 需要晚上 才能抽空看了，你自己再研究一下，有新发现，就记录一下。

**Comment by comlejade** [comment]
@watsonhaw5566 我最新提交的版本，已经成功复现了两个不同页面间输入框相互影响，其中一个无法输入的情况，还有按钮样式相互影响的情况
https://github.com/comlejade/remax-test.git

**Comment by watsonhaw5566** [comment]
@comlejade  看来你的问题是和 https://github.com/remaxjs/remax/issues/1538 一样的了。
我看看需要怎么处理。这个无关版本的问题了。感谢你的反馈

**Comment by comlejade** [comment]
@watsonhaw5566 打包的时候像 dialog.js 这些文件好像并没有被打包进去，直接引入也报错
![image](https://user-images.githubusercontent.com/15702577/148484143-5e0dec73-8d5a-4235-b26e-22307fd7886a.png)
![image](https://user-images.githubusercontent.com/15702577/148484246-d593f4fb-b745-4312-a137-d0af3ff1a1c9.png)
![image](https://user-images.githubusercontent.com/15702577/148484277-f92f7939-0c91-4697-b6cd-87325ed15faa.png)

**Comment by watsonhaw5566** [comment]
> @watsonhaw5566 打包的时候像 dialog.js 这些文件好像并没有被打包进去，直接引入也报错 我现在是只能把它们单独拿出来，放进一个文件夹里
> 
> ![image](https://user-images.githubusercontent.com/15702577/148484143-5e0dec73-8d5a-4235-b26e-22307fd7886a.png) ![image](https://user-images.githubusercontent.com/15702577/148484246-d593f4fb-b745-4312-a137-d0af3ff1a1c9.png) ![image](https://user-images.githubusercontent.com/15702577/148484277-f92f7939-0c91-4697-b6cd-87325ed15faa.png)

嗯，应该是判断了 入口文件，这个确实一个 bug 问题， VantFiled 的问题我也发现了，但还没有很好的思路复现

**Comment by comlejade** [comment]
@watsonhaw5566 生成骨架屏有什么好的方案吗

**Comment by watsonhaw5566** [comment]
微信小程序 可以直接打开骨架屏，但目前 Remax 没有做适配 。
你可以先了解一下。https://developers.weixin.qq.com/miniprogram/dev/devtools/skeleton.html

**Comment by comlejade** [comment]
@watsonhaw5566 怎么样，VanField问题能搞定吗？（试了几个UI框架，表单都或多或少有点问题）

**Comment by watsonhaw5566** [comment]
先使用原生 form 代替 ，目前这个问题没有很好的处理方法，需要花多点时间研究。

**Comment by watsonhaw5566** [comment]
@comlejade 可以的话，你加一下我们的钉钉群，在里面返回会方便一些。 群号: 34935625

**Comment by comlejade** [comment]
> @comlejade 可以的话，你加一下我们的钉钉群，在里面返回会方便一些。 群号: 34935625

好的
