### ISSUE TITLE
[BUG] Babel 编译缓存导致 usePageEvent 宏在特定条件下失效

### ISSUE THREAD

**Issue by rikumi** [remaxjs/remax#1813]
**bug 描述**
@remax/macro 中的 `usePageEvent` 宏在某些特定条件下，不会在 `__remax_runtime_options__.js` 中增加对应的 `pageEvent`，导致 `onShareAppMessage` 等声明式生命周期不会正常触发。

该问题在 v2.15.10 中首次出现，关闭 #1789 中的第二个 `cacheDirectory` 后恢复正常，疑似是因为 babel 编译缓存与 `babel-plugin-macros` 不兼容。

**复现步骤**
1. 下载下面的 demo 并解压
2. 安装依赖，执行 `npm run build`
3. 查看 `dist/wechat/__remax_runtime_options__.js` 最末尾
4. `pages/index/index` 对应的 `pageEvent` 为空

**期望结果**
`pages/index/index` 对应的 `pageEvent` 为 `['onShareAppMessage']`

**复现代码**
[demo.zip](https://github.com/remaxjs/remax/files/7808085/demo.zip)

**版本信息:**

- remax 版本: 2.15.10
- 手机型号 任意
- 小程序端 任意
- 小程序版本 任意
- 开发环境 任意

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
嗯，babel cacheDirectory 已经提交 pr 移除了 ，发现了这个加速有副作用。

**Comment by yesmeck** [comment]
新版本已经去掉缓存。
