### ISSUE TITLE
[问题]通过 umijs 间接引入了太多多余编译依赖

### ISSUE THREAD

**Issue by rikumi** [remaxjs/remax#1815]
**问题描述**
babel-preset-remax 中的 @umijs/babel-plugin-auto-css-modules 这个依赖间接引入了 @umijs/deps，后者带来了太多多余的编译依赖，其中包括 esbuild，以及 [compiled 目录](https://github.com/umijs/umi/tree/master/packages/deps/compiled)中的一大堆第三方依赖集合。

建议把 @umijs/babel-plugin-auto-css-modules 作为一个 peer dependency 选择性安装。

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
这个不懂，学习一下。我也觉得奇怪，为什么 remax 没用到 esbuild 也会安装 esbuild 依赖。
这个要看看边柳兄那边有没有依赖其他的功能了，这个我也不好动。

**Comment by yesmeck** [comment]
直接把 [@umijs/babel-plugin-auto-css-modules ](https://github.com/umijs/umi/blob/master/packages/babel-plugin-auto-css-modules/src/index.ts) fork 过来好了。

**Comment by watsonhaw5566** [comment]
> 直接把 [@umijs/babel-plugin-auto-css-modules ](https://github.com/umijs/umi/blob/master/packages/babel-plugin-auto-css-modules/src/index.ts) fork 过来好了。

边柳兄能否帮我fork一个到 remax 仓库里面来，我完成改一下。

**Comment by watsonhaw5566** [comment]
@rikumi  使用了 @umijs/babel-plugin-auto-css-modules 会导致开发时候的 编译包增大吗？
