### ISSUE TITLE
[问题]remax的Input似乎无法触发onConfirm事件？

### ISSUE THREAD

**Issue by jun4rui** [remaxjs/remax#1820]
**问题描述**
微信小程序原生是有这个属性可以绑定的，remax的私护出发不了？看别人说iOS不行、Android某些输入法可以，要软键盘带回车键才行，硬键盘的回车键不行等等。
请问如果兼容性不好，有什么较好的解决办法没？
或者自己扔个Button在后面，叫用户去点按钮触发搜索算了？

**Comment by watsonhaw5566** [comment]
写一个复现的小 demo  repo

**Comment by jun4rui** [comment]
抱歉，我的问题，是代码其它地方导致的，耽误大家了
