### ISSUE TITLE
[问题] 分包配置了没有编译到dist目录

### ISSUE THREAD

**Issue by alilmq** [remaxjs/remax#1825]
app.config.ts设置了subpackages分包，但是编译时dist目录没有生成subpackages目录页面
![image](https://user-images.githubusercontent.com/29850435/149441115-16fe745a-4918-4df6-9e04-c4d38f7b58bd.png)

dist目录没有生成subpackages目录
![image](https://user-images.githubusercontent.com/29850435/149441248-bb97354c-4d46-47cc-8ffe-803ca7e3ba4c.png)

请问一下是什么原因？

**Comment by watsonhaw5566** [comment]
不要在 src/pages下进行分包，在 pages 同级目录下进行新增分包目录把分包的页面加入新增目录中。

**Comment by alilmq** [comment]
好的谢谢
