### ISSUE TITLE
[官方有群吗]

### ISSUE THREAD

**Issue by gavinkd** [remaxjs/remax#184]
**需求描述**
[希望官方可以给个群地址]
**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
![屏幕快照 2019-08-30 09 51 02](https://user-images.githubusercontent.com/6788752/63987668-b5ff5880-cb0b-11e9-8a09-8661a146cdb6.png)

这里有，点开就是二维码
