### ISSUE TITLE
[问题]

### ISSUE THREAD

**Issue by wakeupSu** [remaxjs/remax#1840]
**问题描述**
[详细地描述问题，让大家都能理解]

使用remax/one多端开发（微信小程序和web），引入vant-weapp
微信小程序正常运行，web报错：loadable-components: failed to asynchronously load component
想问一下是不是使用引入小程序组件库的组件，就无法复用在web端了

remax 版本：2.9.1

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

import * as React from 'react';
import { View, Text, Image } from 'remax/one';
import styles from './index.css';
import VantButton from '@vant/weapp/lib/button';

export default () => {
  const handleButtonClick = (e) => {
    console.log(e)
  }
  return (
    <View className={styles.app}>
      <View className={styles.header}>
        <Image
          src="https://gw.alipayobjects.com/mdn/rms_b5fcc5/afts/img/A*OGyZSI087zkAAAAAAAAAAABkARQnAQ"
          className={styles.logo}
          alt="logo"
        />
        <View className={styles.text}>
          编辑 <Text className={styles.path}>src/pages/index/index.js</Text>{' '}
          开始
        </View>

        <VantButton type="warning" bind:click={handleButtonClick}>按钮</VantButton>
      </View>
    </View>
  );
};

**其他信息**
[如截图等其他信息可以贴在这里]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/32351042/154045357-556d000f-13e3-448a-beee-efa13c4905de.png">

**Comment by watsonhaw5566** [comment]
vant-weapp 组件仅限于微信小程序 使用， remax/one 提供了跨平台的能力，但并不是跨平台组件的能力。

**Comment by wakeupSu** [comment]
> vant-weapp 组件仅限于微信小程序 使用， remax/one 提供了跨平台的能力，但并不是跨平台组件的能力。

谢谢回复，了解了

**Comment by watsonhaw5566** [comment]
> > vant-weapp 组件仅限于微信小程序 使用， remax/one 提供了跨平台的能力，但并不是跨平台组件的能力。
> 
> 谢谢回复，了解了。想顺便问一下有推出官方remax 组件库的打算吗，之前翻issue里推荐的annar已经不维护了，剩下的都是一些个人开发的库

抱歉，没有的，维护者剩下的人不多了，精力也有限了。
