### ISSUE TITLE
[问题]为什么remax不支持数组形式的className？

### ISSUE THREAD

**Issue by NiuGuohui** [remaxjs/remax#1847]
**问题描述**
如题

**示例代码**
<img width="466" alt="image" src="https://user-images.githubusercontent.com/37471959/155753300-d1510a64-8072-4eee-b10e-aedd4de9feea.png">

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
使用 classnames 或者 clx 类的库进行链接
