### ISSUE TITLE
请问项目是不是还在长期维护

### ISSUE THREAD

**Issue by bnyte** [remaxjs/remax#1855]
**问题描述**
请问项目是不是还在长期维护，因为我看到项目代码好像有段时间没更新了~

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
2.0 版本的功能已稳定，基本都是 小程序 api 接口的新增，现在主要的精力放在 3.0 的一些新功能开发上。

**Comment by bnyte** [comment]
> 2.0 版本的功能已稳定,主要是小程序 api 接口的新增，现在主要的精力放在 3.0 的一些新功能开发上。

好的。清楚了，辛苦解答，我现在关闭这个issue
