### ISSUE TITLE
[问题]多个页面的情况下，能禁止后退按钮回退到上一个页面么；或者能监听popstate事件么。

### ISSUE THREAD

**Issue by furan495** [remaxjs/remax#1857]
**问题描述**
[详细地描述问题，让大家都能理解]

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
应该不得，小程序也没有抛出这个方法，所以 remax 也做不到

**Comment by furan495** [comment]
好的，谢谢回馈。
