### ISSUE TITLE
[问题]想问一下如果我是获取到元素距离页面offsetLeft的位置 然后需要用这个值给动画

### ISSUE THREAD

**Issue by yushuangxu** [remaxjs/remax#1863]
**问题描述**
获取到元素的offsetLeft然后赋值给line元素 在小程序端值会自动转换为rpx 然后滑动的距离不对了 怎么让他直接使用我设置的这个值

**示例代码**

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
px 改为 PX 大写就不会转义了。
