### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by guwan** [remaxjs/remax#1864]
**bug 描述**
钉钉小程序：
1，remax对getLocation和getAuthCode封装有问题，ios无法使用，安卓可以，
2，苹果只能使用my.request，安卓只能使用：my.httpRequest。无法混合使用

**复现步骤**
写上面的代码小程序直接闪退

**期望结果**
运行良好

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [2.15.12]
- 手机型号 [iPhone 所有型号]
- 小程序端 [钉钉小程序小程序]
- 小程序版本[钉钉 6.5.0 ]
- 开发环境 [windows]

**其他信息**
我现在判断系统来之星查询的

if (my.getSystemInfoSync().platform == 'iOS'||my.getSystemInfoSync().platform == 'iPhone OS') {
        return my.request(options);
    } else {
        return my.httpRequest(options);
    }
但是这样模拟器上运行ios版本又有问题。

**Comment by watsonhaw5566** [comment]
这个不属于 remax 的bug。remax 只负责导出了对应的 api 接口，并且我觉得不应该在框架中做这个转换的需求。
remax 只能判定对应的开发平台进行对应的编译打包工作。而无法判定你要用于 iOS 还是 安卓，所以还需要开发者自行判断。

**Comment by guwan** [comment]
remax对getLocation和getAuthCode封装有问题，ios无法使用，安卓可以

自己包装一下原生钉钉的就没有问题，用remax的getLocation，在ios下就会闪退。这个应该是remax的问题吧？
export function dingGetLocation() {
    //return getLocation()

    return new Promise((resolve, reject) => {
        // @ts-ignore
        dd.getLocation({
            success(res: any) {
                return resolve(res);
            },
            fail(err: any) {
                return reject('请先开启手机定位!');
            },
        })
    })
}

**Comment by watsonhaw5566** [comment]
> remax对getLocation和getAuthCode封装有问题，ios无法使用，安卓可以
> 
> 自己包装一下原生钉钉的就没有问题，用remax的getLocation，在ios下就会闪退。这个应该是remax的问题吧？ export function dingGetLocation() { //return getLocation()
> 
> ```
> return new Promise((resolve, reject) => {
>     // @ts-ignore
>     dd.getLocation({
>         success(res: any) {
>             return resolve(res);
>         },
>         fail(err: any) {
>             return reject('请先开启手机定位!');
>         },
>     })
> })
> ```
> 
> }

好的，我今晚复现再修一下，谢谢。

**Comment by jaluik** [comment]
可以用一下 axios-ali-adapter，适配了钉钉还要阿里小程序
