### ISSUE TITLE
如何调用wx的 getCurrentPages [问题]

### ISSUE THREAD

**Issue by tiancaidaren** [remaxjs/remax#1865]
自定义导航栏 ，需要知道当前页面有没有上个页面，来控制显示隐藏返回键，有人知道怎么做吗

**Comment by watsonhaw5566** [comment]
可以直接使用的，你在 useEffect 里打印一下就好了。

**Comment by tiancaidaren** [comment]
![image](https://user-images.githubusercontent.com/55011932/159126828-74b37258-205f-40ac-95b9-f5804b6c36bf.png)
不行 会报错

**Comment by tiancaidaren** [comment]
console.log("---------", getCurrentPages());
 原来直接调用就可以了
