### ISSUE TITLE
[问题]在分包中定义的组件，也在这个分包中引入的这个组件，打包到主包中?

### ISSUE THREAD

**Issue by WangXang** [remaxjs/remax#1873]
在分包中定义的组件，也在这个分包中引入的这个组件，怎么打包到主包中去了？

结构如下：
![pig](https://user-images.githubusercontent.com/23691331/161170640-46d4a3ef-48d9-4837-80e9-81665777fa62.png)

**其他信息**
![jg](https://user-images.githubusercontent.com/23691331/161170728-b3daa04f-9196-452c-bef9-b4ea16b25415.png)

**Comment by watsonhaw5566** [comment]
#1742 https://github.com/remaxjs/remax/issues/1742#issuecomment-1085262803

这里面已有 webpack 配置，配置一下即可
