### ISSUE TITLE
最近使用remax导出的组件，typescript都在报错

### ISSUE THREAD

**Issue by comlejade** [remaxjs/remax#1881]
![image](https://user-images.githubusercontent.com/15702577/163108179-fd57eaf7-6518-47e2-9be6-f040ce9a1730.png)

所有的组件都在报这个错，我试了remax版本 2.15.12 和 2.15.13 都有这个问题，目前ts版本 4.5.4，尝试切换了几个ts版本，并没有用

**Comment by watsonhaw5566** [comment]
@yesmeck  边柳兄，有劳看看这个问题，我的 ts 不是很熟练。不知道怎么排查这个问题。谢谢

**Comment by watsonhaw5566** [comment]
@comlejade  白天的时候你看看是否回事这个问题导致的。

https://github.com/NervJS/taro/issues/8583

**Comment by comlejade** [comment]
@watsonhaw5566 找到问题了 tsconfig.json 少了一项配置
![image](https://user-images.githubusercontent.com/15702577/163334341-cc597ffb-733a-4a8c-89fb-adf02a92fd80.png)
