### ISSUE TITLE
[BUG]babel-plugin-import 不生效

### ISSUE THREAD

**Issue by AmelloAster** [remaxjs/remax#1883]
**bug 描述**
![image](https://user-images.githubusercontent.com/26178326/163345756-7327927a-15ce-40ff-af95-c730e57101d5.png)
配置 babel-plugin-import 无效
在一个 tsx 文件里面引入 import { xxx } from 'lodash-es'
会把整个 lodash 包都引入该文件

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
应当只引入使用的那部分

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: 2.9.1
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by sydeEvans** [comment]
建议使用lodash.es
