### ISSUE TITLE
[BUG]使用yarn workspace将多个小程序放到一个代码仓库，执行 remax build 报错依赖找不到

### ISSUE THREAD

**Issue by fengliner** [remaxjs/remax#1887]
**bug 描述**
使用yarn workspace将多个小程序放到一个代码仓库，执行 remax build 构建报错依赖找不到
![image](https://user-images.githubusercontent.com/6862756/164165706-e112ac06-cc5e-4945-8369-e918cc267780.png)

**复现步骤**
代码目录结构如下
![image](https://user-images.githubusercontent.com/6862756/164166678-7acd52df-c6f9-4ff3-a018-ee436392ea62.png)

根目录下的package.json
```js
{
  "name": "mini-app",
  "private": true,
  "workspaces": [
    "packages/*"
  ],
  "tnpm": {
    "mode": "yarn",
    "lockfile": "enable"
  }
}
```
packages里的mini-app-a和mini-app-b分别用npx create-remax-app 初始化。
安装好依赖后，进入到mini-app-a执行npm run dev就会报上面截图的错误

**期望结果**
使用yarn workspace可以正常构建

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: 2.15.13
- 小程序端: 钉钉小程序

**Comment by watsonhaw5566** [comment]
remax build 暂不支持这样的用法，请单独抽出来。

**Comment by sydeEvans** [comment]
![image](https://user-images.githubusercontent.com/15522856/169493516-a17ab4ac-3de0-4b87-8c25-a8664486875e.png)
你需要在子包中使用 nohoist 将 react 安装到子包的 node_modules 中
或者使用 lerna 来管理 monorepo
