### ISSUE TITLE
[需求]请问还有支持百度小程序开发的计划吗

### ISSUE THREAD

**Issue by AmelloAster** [remaxjs/remax#1890]
**需求描述**
[详细地描述需求，让大家都能理解]

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
不支持了

**Comment by sydeEvans** [comment]
目前没有规划，欢迎提交pr
