### ISSUE TITLE
我使用React-router-dom@5报错了

### ISSUE THREAD

**Issue by dualseason** [remaxjs/remax#1891]
![image-20220429113819198](http://pic.dualseason.com/uPic/image-20220429113819198.png)

**Comment by WangXang** [comment]
微信小程序没有dom，先看下微信小程序文档：https://developers.weixin.qq.com/miniprogram/dev/api/route/wx.switchTab.html

**Comment by sydeEvans** [comment]
目前不支持使用了DOM的第三方库
