### ISSUE TITLE
[BUG] node@18 编译失败

### ISSUE THREAD

**Issue by geekact** [remaxjs/remax#1895]
**bug 描述**
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
```

**复现步骤**
```bash
yarn run dev wechat
```
**期望结果**
切到node16之后bug消失

**版本信息:**

- remax 版本: 2.15.13
- node 版本: 18.0.0
- 开发环境: macos

**Comment by geekact** [comment]
remax还在升级和维护吗？roadmap有吗？在犹豫是否要做remax的周边

**Comment by yesmeck** [comment]
@geekact 建议用 Taro 吧。

**Comment by geekact** [comment]
> @geekact 建议用 Taro 吧。

@yesmeck  一家独大是我不愿看到的。有竞争才有上升的空间，才能互相借鉴取长补短，remax应该是最有希望和taro干上的。加油大佬 :)

**Comment by watsonhaw5566** [comment]
使用12、 14 或者 16 的版本吧，新版本还不支持

**Comment by geekact** [comment]
https://github.com/nodejs/node/issues/41857

**Comment by sydeEvans** [comment]
建议先用 node16
或者参考这个方案 https://github.com/webpack/webpack/issues/14532#issuecomment-947515866

**Comment by amehito** [comment]
"dev": "cross-env NODE_OPTIONS=--openssl-legacy-provider remax  build -t wechat -w",
