### ISSUE TITLE
[BUG] 哎，就这样给卒了！

### ISSUE THREAD

**Issue by codedart2018** [remaxjs/remax#1899]
**bug 描述**
[详细地描述 bug，让大家都能理解]

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[请提供一个可复现问题的代码仓库]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by miaojinsing** [comment]
可以说我国大厂的开源项目最好都别用，最多闲时借鉴，提心掉胆的感觉。

**Comment by geekact** [comment]
又活过来了
