### ISSUE TITLE
混合模式

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#19]
支持跟小程序代码混写

**Comment by Darmody** [comment]
指定 `src/native` 为原生代码，如何？

**Comment by yesmeck** [comment]
那页面路径不是变了

**Comment by yesmeck** [comment]
奥，copy 出来是吧

**Comment by yesmeck** [comment]
感觉可以

**Comment by Darmody** [comment]
> 奥，copy 出来是吧

是的

**Comment by YYCoder** [comment]
请问该功能可用吗？我按照文档上的描述试了一下，会报下图的错误：

![](https://markey-oss1.oss-cn-beijing.aliyuncs.com/Lark20191106111104.png)

代码中结构如下：

![](https://markey-oss1.oss-cn-beijing.aliyuncs.com/Lark20191106111348.png)

**Comment by Darmody** [comment]
@YYCoder 报错是什么？没看到报错

**Comment by YYCoder** [comment]
> @YYCoder 报错是什么？没看到报错

在第一张图的红框里

**Comment by Darmody** [comment]
@YYCoder 我试了没问题，能把完整的repo放一下吗？

**Comment by YYCoder** [comment]
重新试了一下，发现是页面路径的配置问题。

文档中写的 pages 中的 `pages/native/index` 会对应到目录中 `src/native/pages/native/index `，但实际上 pages 应该是 `pages/native/index/index` 才是正确的。因为编译出来以后 native 目录的结构是这样的：

<img src="https://markey-oss1.oss-cn-beijing.aliyuncs.com/Lark20191107143520.png" width="200" />

**Comment by Darmody** [comment]
这个根据实际情况调整就可以了
