### ISSUE TITLE
交流群

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#194]
<img src="https://user-images.githubusercontent.com/465125/107321458-8238a880-6add-11eb-9d28-86b03e570fe0.JPG" 
 width="360"/>

**Comment by baibai-lee** [comment]
有微信或者QQ群吗？

**Comment by Darmody** [comment]
> 有微信或者QQ群吗？

由于我们有在群里设置发布机器人等需求，所以目前都在钉钉群里交流

**Comment by vscing** [comment]
![image](https://user-images.githubusercontent.com/20698627/82724130-76fedc00-9d06-11ea-8554-1e735603a5c9.png)

**Comment by wulianglaoge** [comment]
对应UI框架可以使用哪个呢，Ant可以吗

**Comment by yesmeck** [comment]
@wulianglaoge https://annasearl.github.io/anna-remax-ui/
