### ISSUE TITLE
[问题]官网被劫持了啊。。。咱们的remax支持支付宝iot小程序么？

### ISSUE THREAD

**Issue by Big-Devils** [remaxjs/remax#1952]
**问题描述**
[详细地描述问题，让大家都能理解]

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
你好，感谢你的提醒，是域名到期了。
你可以访问我搭建的 https://remaxjs.wdchiphop.cn/ 文档。

**Comment by watsonhaw5566** [comment]
iot小程序 这个需要您试试了，我还没对接过支付宝应用。
