### ISSUE TITLE
[问题]标签上的TS2559报错信息

### ISSUE THREAD

**Issue by haobarry** [remaxjs/remax#1955]
**问题描述**

请问这个TS报错信息是什么造成的? 同样的代码 在官方的ts项目里面就没报错 
![图片](https://user-images.githubusercontent.com/9339292/187574014-f90d9dc2-460b-4ded-b1d5-d27f897de30f.png)

**Comment by haobarry** [comment]
强迫症知道了， 这个问题是react18升级后的问题  降级就行了 反正用不上18

**Comment by watsonhaw5566** [comment]
> 强迫症知道了， 这个问题是react18升级后的问题 降级就行了 反正用不上18

是的，暂时不支持 18的版本
