### ISSUE TITLE
[BUG] onShareAppMessage 无效问题

### ISSUE THREAD

**Issue by IFromHell** [remaxjs/remax#1968]
**bug 描述**
在函数组件中使用onShareAppMessage  无效问题

**复现步骤**
核心代码
```react
import { usePageEvent } from 'remax/macro';

export default (props) => {
    usePageEvent('onShareAppMessage', () => {
        return {
            title: '后浪成长计划',
            path: `/pages/index/index?from=share`,
        };
    });
    usePageEvent('onShareTimeline', () => { });
};
```

无效结果
<img width="320" alt="image" src="https://user-images.githubusercontent.com/30306293/201134618-5139d24b-edf2-4c23-9e66-c9ae7427f30d.png">

在排查的时候，发现如下代码注释后是成功的
```react
// babel.config.js
module.exports = {
    presets: [
        ['remax', {
            // 'react': { runtime: 'automatic' }, // 注释这一行打包后是会出现正常分享按钮
            'decorators': { legacy: true },
            'throw-if-namespace': true,
            'targets': ['chrome >= 49', 'firefox >= 64', 'ios >= 8', 'Android > 4.4'],
        }],
    ],
    plugins: [],
};
```
但此修改，整个小程序报如下错误
![image](https://user-images.githubusercontent.com/30306293/201253486-13e0d78c-3ab0-4252-8e8f-abf02c4e8cd3.png)

**期望结果**
期待onShareAppMessage、onShareTimeline能正常展示效果，对小程序进行分享和分享至朋友圈。

**版本信息:**

- remax 版本: [e.g. 2.15.14]
- 手机型号 [e.g. all]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.27.1]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by watsonhaw5566** [comment]
我猜测你配置的 babel preset remax 覆盖了原有的 remax  preset ,  
remax的 onShareAppMessage  onShareTimeline 是正常运行的， 检查一下自己的 preset 配置。

**Comment by IFromHell** [comment]
> 我猜测你配置的 babel preset remax 覆盖了原有的 remax preset , remax 的 onShareAppMessage onShareTimeline 是正常运行的， 检查一下自己的 preset 配置。
> 
> <img alt="image" width="1728" src="https://user-images.githubusercontent.com/4210367/201264833-1fcda554-ebba-48da-9aa7-334e222763a7.png">

![image](https://user-images.githubusercontent.com/30306293/201284576-f3d5c97e-4b45-4f7b-b6ff-9d8c49b4ffab.png)
我就是安装官网的例子配置的，我也不知道哪里出现问题了。我现在都无从下手了~

**Comment by watsonhaw5566** [comment]
移除 babel 的配置，再跑一次

**Comment by IFromHell** [comment]
> 移除 babel 的配置，再跑一次

移除跑，报下面的错误了

![image](https://user-images.githubusercontent.com/30306293/201292729-12fae667-7b9f-4169-977b-08f61c8ccd6a.png)

**Comment by watsonhaw5566** [comment]
先删除一下 babel.config.js ，删除 dist 目录，再跑一次。

**Comment by IFromHell** [comment]
经历了一整天的摸索（还是排除法最好用），问题终于得到解决了。感谢 @watsonhaw5566 兄弟的指导。

**问题原因**

导致我出现onShareAppMessage、onShareTimeline并不是官方库的问题，按照官方文档的使用方法是能够正常实现转发和分享至朋友圈功能的。
也不是babel.config.js的presets配置问题。

而我本地失败的原因是两个地方：
1. 因为在编写组件的时候，有些组件没有引入`import React from 'react';`，即使你导入和`react`，`React`还是必须要写；
> 注意，是所有UI组件必须都要导入`react`。
```js
// 正确导入
import React from 'react';
import React, { useEffect, useState } from 'react';

//错误导入
没有导入`react`
import { useEffect, useState } from 'react';
```
2. 在我的`Container.js`组件中使用了`getCurrentPages()`方法获取页面路由，导致react运行失败。

以上两个因素导致失败的本质原因是程序在运行时，遇到上诉两种错误，产生「[错误边界](https://zh-hans.reactjs.org/docs/error-boundaries.html#gatsby-focus-wrapper)」导致的。
> react官方文档说明：React 的内部状态被破坏，并且在下一次渲染时 [产生](https://github.com/facebook/react/issues/4026) [可能无法追踪的](https://github.com/facebook/react/issues/6895) [错误](https://github.com/facebook/react/issues/8579)。

所以我针对上面两个原因，调整代码后，程序就正常跑通了，开心~
希望能够帮助到遇到同类问题的小伙伴~
