### ISSUE TITLE
[问题] 微信小程序头像与能力填写能力支持

### ISSUE THREAD

**Issue by Youngsccc** [remaxjs/remax#1978]
**问题描述**
[微信小程序小程序用户头像昵称获取规则调整公告](https://developers.weixin.qq.com/community/develop/doc/00022c683e8a80b29bed2142b56c01)

微信小程序后续似乎不能通过GetUserProfile拿到头像信息了，改为通过头像填写能力的方式来获取，请问这部分还会考虑支持一波嘛？同样昵称填写功能也是。谢谢～

**Comment by watsonhaw5566** [comment]
近期我会抽空更新一波的。
