### ISSUE TITLE
remax build -w -t wechat 启动的小程序，引用的小程序原生组件会报Component is not found in path

### ISSUE THREAD

**Issue by jhmobile** [remaxjs/remax#1992]
remax build -w  -t wechat  启动的小程序，引用的小程序原生组件会报
Component is not found in path "npm/_jhjr/react-native-cp/lib/apis/popup/index" (using by "init/index")(env: macOS,mp,1.06.2301040; lib: 2.29.2)

请问如何解决？？

remax build   -t wechat模式没有问题

**Comment by watsonhaw5566** [comment]
检查一下原生文件引用的路径，感觉是引用路径的问题。

**Comment by jhmobile** [comment]
路径没有问题，最后发现是分包导致的，只要设置分包，--watch模式就会提示Component is not found in path ，这个有办法处理吗？业务代码比较多的时候，不分包，无法进行手机预览

**Comment by watsonhaw5566** [comment]
现在还没办法处理这个问题。你要自己琢磨一下了

**Comment by jhmobile** [comment]
好吧
