### ISSUE TITLE
rollup alias 配置优化

### ISSUE THREAD

**Issue by newset** [remaxjs/remax#201]
**需求描述**
看到1.1.0 alpha 版中 alias 的配置代码，建议不要自动替换path,  而是用户自行设置。很多时候需要动态替换到node_modules 目录的。 比如：
```
{
   'antd': require.resolve("antd-mobile")
}
```
这种也是官方推荐的写法

另外还有需要就是，通过正则匹配需要替换的import，如下： 
```
{
    entries: [
      {find:/f(o+)bar/, replacement:'f$1bar2019'},
    ]
}
```

需要的话，我可以提个pr

**Comment by Darmody** [comment]
https://github.com/remaxjs/remax/blob/develop/packages/remax-cli/src/build/rollupConfig.ts#L71

 你说的自动替换是这个吗

**Comment by Darmody** [comment]
第一点确实是有问题

**Comment by newset** [comment]
> https://github.com/remaxjs/remax/blob/develop/packages/remax-cli/src/build/rollupConfig.ts#L71
> 
> 你说的自动替换是这个吗

是的

**Comment by Darmody** [comment]
@newset 来个PR 👍

**Comment by yesmeck** [comment]
```
{
    entries: [
      {find:/f(o+)bar/, replacement:'f$1bar2019'},
    ]
}
```

这个是解决什么问题？

**Comment by newset** [comment]
> ```
> {
>     entries: [
>       {find:/f(o+)bar/, replacement:'f$1bar2019'},
>     ]
> }
> ```
> 
> 这个是解决什么问题？

这个允许正则可以避免包名相似的时候出错

比如
```
 {
   "foo": "foo/lib/index.js"
}

// 引用类似包名的时候会出错
import foobar from "foo/bar";
import foobar from "foo-bar";
```
这种就需要用正则。

我测试的时候是有遇到这种情况哈。

**Comment by Darmody** [comment]
这种情况不用正则不能解决吗

**Comment by newset** [comment]
> 这种情况不用正则不能解决吗

我刚才看了下  rollup-plugin-alias 的测试代码，好像覆盖了这种情况的。
https://github.com/rollup/rollup-plugin-alias/blob/v1.5.2/test/index.js

暂时不考虑正则的用法，可以先把 默认resolve 到 src 目录取消，用户可以别名到 node_modules 或者其他目录。
