### ISSUE TITLE
[BUG]缺失 onReady 事件

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#203]
**bug 描述**
页面没有 onReady hook

**Comment by yesmeck** [comment]
感觉没什么用所以没加

**Comment by Darmody** [comment]
比如我想在页面节点出现后，调用小程序操作节点的 api。可能就需要  onReady 了

**Comment by yesmeck** [comment]
奥，看错了，那需要的

**Comment by lllbahol** [comment]
useReady() 跟 unstable_useNativeEffect(() => {}, []) 有区别吗

**Comment by Darmody** [comment]
@lllbahol `useReady` 是小程序第一次渲染完成回调，`unstable_useNativeEffect` 是每一次渲染完成都会执行

**Comment by lllbahol** [comment]
如果 unstable_useNativeEffect 的依赖项是[]，就等同于 useReady 了？

**Comment by Darmody** [comment]
> 如果 unstable_useNativeEffect 的依赖项是[]，就等同于 useReady 了？

没有依赖是每一次渲染完成都会执行。如果有依赖，只有依赖更新了才会执行。
