### ISSUE TITLE
[BUG] hostConfig 中添加 container 时，不应该进入 setData 队列

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#204]
**bug 描述**
添加 container 时，应该直接 setData，尽量避免第一次 render 执行完后，dom 元素还没有渲染的问题

**Comment by yesmeck** [comment]
https://github.com/remaxjs/remax/commit/33f9a646b363db33b1d868fc6c81adf77c8567f1

**Comment by Darmody** [comment]
respect
