### ISSUE TITLE
增加 lodash 使用指南

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#207]
**需求描述**
配合 rollup 使用 lodash，需要有特殊技巧

**Comment by yesmeck** [comment]
需要什么技巧？

**Comment by Darmody** [comment]
不清楚。目前我遇到两个问题

1. build 过慢
2. 经常 rebuild 会报错（可能和 build 过慢有关系？）

**Comment by yesmeck** [comment]
我们构建可以优化下，`rollup-plugin-babel` 用了好几次

**Comment by Darmody** [comment]
可以
