### ISSUE TITLE
[BUG] 无法生成 json, axml, acss  等文件，内容全为undefined

### ISSUE THREAD

**Issue by newset** [remaxjs/remax#209]
看了下代码

https://github.com/remaxjs/remax/blob/develop/packages/remax-cli/src/build/plugins/template.ts#L171

```
      const manifest = createAppManifest(options, adapter.name, context);
      bundle[manifest.fileName] = manifest;
```
这种直接在bundle添加属性的方式好像不能生效了，只能调用 this.emitFile 添加文件

需要修改为

```
   this.emitFile({
     type: 'asset',
     ...manifest
  })
```

**Comment by Darmody** [comment]
怎么复现呢

**Comment by newset** [comment]
> 怎么复现呢

https://github.com/remaxjs/todo-demo/tree/dva/alipay

这个分支的代码，直接就运行就会出现

![image](https://user-images.githubusercontent.com/847201/64504450-3be88400-d302-11e9-9420-556f5fecabd4.png)

**Comment by newset** [comment]
rollup 昨天发了个新的版本，1.21.0， 应该是这个版本有改动。我把rollup换成 前一个版本1.20.3
就没问题了。

**Comment by yesmeck** [comment]
rollup 发了个有 breaking change 的版本，看 rollup 怎么解决 https://github.com/rollup/rollup/issues/3104。临时方案：

```
 "resolutions": {
    "rollup": "1.20.3"
  },
```

**Comment by yesmeck** [comment]
rollup 那边改了，不过我们还是要把现在这种非标准的方式改成 `emitFile`

**Comment by newset** [comment]
#228
