### ISSUE TITLE
这个可以用antd/antd mobile的组件吗？

### ISSUE THREAD

**Issue by lifegit** [remaxjs/remax#212]
如题，感谢

**Comment by yesmeck** [comment]
不可以，这两个都是依赖的 ReactDOM 的。你可以把  Remax 看成是 React Native。

**Comment by WuJiY** [comment]
可以出一个remax ui

**Comment by lifegit** [comment]
和taro之类的比起来，优点是什么呢 
@yesmeck

**Comment by yesmeck** [comment]
@lifegit 可以参考 https://zhuanlan.zhihu.com/p/79788488

Taro 是静态编译的方案。
