### ISSUE TITLE
[需求]请问remax后期会扩展其他端吗, 如快应用

### ISSUE THREAD

**Issue by XuZhongqiang** [remaxjs/remax#214]
对比市场上大厂跨端框架
1. [京东Taro](https://github.com/NervJS/taro): 支持各个小程序、快应用、H5、React-Native 等主流平台
2. [滴滴chameleon](https://github.com/didi/chameleon): 支持小程序, weex, 快应用(进行中)

**所以想问下蚂蚁大佬们后期会新增这些扩展吗? 很期待蚂蚁金服在antd之外的另一个现象级框架**

**Comment by yesmeck** [comment]
会的，头条小程序已经有头条的同学支持了 https://github.com/remaxjs/remax/pull/166 ，其他小程序欢迎 contribute。
