### ISSUE TITLE
可以用在生产环境么？

### ISSUE THREAD

**Issue by fxxkscript** [remaxjs/remax#215]
**问题描述**
可以用在生产环境么？

**Comment by Darmody** [comment]
微信小程序我自己有两个项目在开发中，即将上线。

**Comment by yutingzhao1991** [comment]
支付宝小程序已有三个应用在线上：

![image](https://user-images.githubusercontent.com/1061968/64663157-7c204180-d47d-11e9-9a69-922ed0bfde6d.png)

这个是其中y一个。
