### ISSUE TITLE
[需求] 支持 styled-components

### ISSUE THREAD

**Issue by briefguo** [remaxjs/remax#218]
**需求描述**

作为一种CSS In JS的实现，我觉得styled-component的样式绑定是更自然的一种形式，可以把样式复用转变成组件复用。好处有很多，我不一一描述。

[styled-components](https://www.styled-components.com)

```tsx
import React, { useEffect, useState } from "react";
import { View, useReachBottom, useShareAppMessage } from "remax/wechat";
import styles from "./index.module.css";
import styled from "styled-components/native";

const Button = ({ render }) => {
  return <View>{render("XXXX")}</View>;
};

const StyledButton = styled(Button)`
  background: #fff;
  color: #000;
`;

export default () => {
  return (
    <View className={styles.app}>
      <StyledButton render={() => <View>HHHH</View>} />
    </View>
  );
};

```

**解决方案**

styled-components可以支持React Native，是不是把它的运行环境需要的东西实现一下就可以接入进来。

**其他信息**

**Comment by Darmody** [comment]
应该是可以直接用的，只不过我们需要让用户可配置 `external`

https://www.styled-components.com/docs/faqs#with-rollupjs

**Comment by briefguo** [comment]
Hi， @Darmody 
嗯，现阶段，我看着remax的配置还是精简的，几乎没有多余的东西。

配置的灵活性可能可以慢慢放开去接受更多生态环境的东西，然后形成一定的趋势后再慢慢聚合。我感觉nextjs的配置就是这么做的。最初它把TS的配置放在单独的包里，到9.0它自己就内置了。

**Comment by Darmody** [comment]
> Hi， @Darmody
> 嗯，现阶段，我看着remax的配置还是精简的，几乎没有多余的东西。
> 
> 配置的灵活性可能可以慢慢放开去接受更多生态环境的东西，然后形成一定的趋势后再慢慢聚合。我感觉nextjs的配置就是这么做的。最初它把TS的配置放在单独的包里，到9.0它自己就内置了。

我认真看来一下，那个配置是给 lib 用的。。你有试过使用 styled-component 吗？应该可以直接用吧

**Comment by briefguo** [comment]
我试过在remax里使用styled-component
不过它抛出了异常

```
node_modules/shallowequal/index.jspreferring built-in module 'stream' over local alternative at 'stream', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'stream' over local alternative at 'stream', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
'stream' is imported by node_modules/styled-components/dist/styled-components.esm.js, but could not be resolved – treating it as an external dependency
```

**Comment by briefguo** [comment]
我尝试了下，直接使用node的内置path模块，遇到的异常也是一样的。

![image](https://user-images.githubusercontent.com/9976575/65366356-5f41f600-dc55-11e9-8987-cc65ec121ccc.png)

可能我对具体的了解不是很清楚，基于webpack，它会把内置模块加上polyfill或者内部resolve掉，rollup是不是有类似的配置？

**Comment by Pochodaydayup** [comment]
@briefguo 刚看了一下 styled-component 的源码，在浏览器上它是会将组件的样式编译后 append 到 body 下 的 style 标签里， 在 react-native 里则是创建一个新的 React Component, 将 style 通过 props 传递给这个新的组件。所以 remax 这里不能直接使用，但是可以类似于 react-native 的做法，这个我们后续可以支持一下。

**Comment by Darmody** [comment]
内置模块 rollup 可以配置。但是 inject style 有点难搞

**Comment by yesmeck** [comment]
看起来不好支持，而且大量使用 inline style 会影响性能（string 的 style 转换成 object）。

**Comment by newset** [comment]
其实配合 babel-pugin-react-css-module 使用 比 styled-components 更方便，简洁些。跨平台也可以支持

**Comment by briefguo** [comment]
Hi yesmeck.

styled-components最终是内联还是外链，应该取决编译层面、视具体平台而定。比如styled-components在SSR时，可以依靠[ServerStyleSheet.collectStyles](https://www.styled-components.com/docs/advanced#example)收集样式生成单独CSS文件。

我猜想，是不是可以在render层面就利用`ServerStyleSheet.collectStyles`把样式输出到`app.wxss`

**Comment by yesmeck** [comment]
@briefguo 有兴趣的话可以一起研究下

**Comment by xieccc** [comment]
如果将来增加这个，希望可以同时增加glamor的支持

**Comment by sqhtiamo** [comment]
@briefguo  我改造了一下 styled-components ，在 generateAndInjectStyles 时，改写成了RN版的 inlineStyle 模式，目前可以支持基本功能，但是对于 keyframe 这种 API 无法通过inlinestyle模式改写，暂时没啥办法。我这两天两天会发个包出来，如果需要的话，可以一起讨论一下。

**Comment by briefguo** [comment]
> @briefguo 有兴趣的话可以一起研究下

@yesmeck  嗯，我觉得我可以尝试一下 ，以插件的形式去支持。

**Comment by briefguo** [comment]
> @briefguo 我改造了一下 styled-components ，在 generateAndInjectStyles 时，改写成了RN版的 inlineStyle 模式，目前可以支持基本功能，但是对于 keyframe 这种 API 无法通过inlinestyle模式改写，暂时没啥办法。我这两天会发个包出来，如果需要的话，可以一起讨论一下。

Hi @sqhtiamo,  秀出你的代码😏

**Comment by yesmeck** [comment]
https://github.com/4Catalyzer/astroturf

这个看起来可以支持

**Comment by fangkyi03** [comment]
还不如直接把remax的转换层抽出来 直接把styles-compoent变成一个view一样去解析不就好了 就是变成vnode 不就啥问题都没了

**Comment by tolerance-go** [comment]
啥时候支持啊（期待

**Comment by yesmeck** [comment]
https://github.com/callstack/linaria 好像也能支持

**Comment by alphasen** [comment]
astroturf:
  css template literal evaluated at runtime. Make sure astroturf is properly configured to compile this file
Error: css template literal evaluated at runtime. Make sure astroturf is properly configured to compile this file
