### ISSUE TITLE
[BUG] Remax 使用 import 引入代码时的 bug

### ISSUE THREAD

**Issue by elowes** [remaxjs/remax#232]
**bug 描述**
使用 import 引入 echarts，通过 log 可以看到 echarts 对象中有 version 等属性，但是在代码中使用 echarts.version 时，打包后的代码中 echarts.version 会被替换成 undefined

**复现步骤**
下面附有最小复现此bug的demo仓库地址

**期望结果**
可以正常使用 echarts 中的属性和方法

**复现代码**
https://github.com/elowes/remax-import-repro

**版本信息:**

- remax 版本：1.0.16
- 小程序端：微信小程序
- 开发环境：macOS

**其他信息**
![image](https://user-images.githubusercontent.com/8766034/65007964-45916d80-d93a-11e9-99fc-a7e7e3ccd932.png)
![image](https://user-images.githubusercontent.com/8766034/65007973-4aeeb800-d93a-11e9-895f-8acc09900486.png)

**Comment by yesmeck** [comment]
原因是我们用了 [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) 来支持 cjs 模块，但是这个插件要求为每个 cjs 模块指定导出的属性 https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports ，对于 npm 模块我们现在的解决方案是把 cjs 的 npm 包提前配置好 https://github.com/remaxjs/named-exports-db 。但是 echarts 是把文件自己下载到本地的这个方案就不行了。

**Comment by yesmeck** [comment]
我们得把  `namedExports` 配置开放出来

**Comment by yesmeck** [comment]
临时方案是把 `wx-echarts` 发布成一个 npm 包，然后给   https://github.com/remaxjs/named-exports-db 发个 PR。

**Comment by elowes** [comment]
> 原因是我们用了 [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) 来支持 cjs 模块，但是这个插件要求为每个 cjs 模块指定导出的属性 https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports ，对于 npm 模块我们现在的解决方案是把 cjs 的 npm 包提前配置好 https://github.com/remaxjs/named-exports-db 。但是 echarts 是把文件自己下载到本地的这个方案就不行了。

明白你意思了，echarts有npm包，我直接用npm上面的版本就行了。他官方提供的小程序版本我也不知道为啥要把echarts.js文件单独拿出来。
