### ISSUE TITLE
[RFC] 微信 props 收集重构

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#243]
## 背景

目前 remax 收集微信 props 的做法是针对每一个组件，收集用到的所有props，形成一个合集，最终写死在对应的组件模板中，具体效果如：

```jsx
<>
  <View className="view" />
  <View id="id" />
</>
```

以上代码将会收集到 `View` 组件有 `className` 和 `id` 两个属性，因此在 `wxml` 中定义好的 `View` 模板就会写死 `className` 和 `id` 两个属性。

## 问题

这种做法的问题在于，由于最后收集到的是属性的合集，就会让有些组件写上了它原本没有用到的属性，这种做法在微信小程序里是有可能引起bug的。如 #241 

## 解决方案

之前在考虑切分 base.wxml 时曾做过一个方案，是对所有用户用到的 jsx 片段收集组件，然后生成对应的模板。但最终由于微信小程序不支持模板递归放弃了。我们可以沿用当时的思路，收集所有jsx片段中组件用到的props，这样就不用做属性合集，可以让每个element只生成他定义好的props

如：

```jsx
<>
  <View className="className" />
  <View id="id" />
</>
```

对于如上的片段，我们就可以收集到有两个 View ,分别生成对应的唯一标识，比如 v1,v2,可以记录下 v1 的 props 是 className，v2 的 props 是 id。在模板渲染的时候便可通过 id 映射取到对应的 props

### 衍生的问题

这种做法本质上是接近静态编译的思路，比较动态的写法会受到限制，比如 cloneElement， spreadAttributes 等。

#### spreadAttributes

遇到 spreadAttributes 我们可以把所有属性都写入。

#### cloneElement 和 createElement 的做法

还没有好的思路，在微信小程序里将会收到限制

#### 组件重命名

如：
```jsx
import { View } from 'remax';
const CustomView = View;
// 这种写法会导致无法识别 CustomView 是否是 remax 内置组件。
```

以上这些动态用法只是目前能想到的，并没有全部穷举。因此最好有一个能统一解决的方案。

**Comment by newset** [comment]
@Darmody @yesmeck 这个现在有方向吗？

**Comment by Darmody** [comment]
我目前的想法还是收集每个 jsx tag 的 props。对于动态的情况，就用全部 props

**Comment by Darmody** [comment]
微信不支持递归没法做到

**Comment by briefguo** [comment]
Hi @Darmody,
我这边也遇到了类似 #241 这样的问题
是不是可以考虑，给那些没有用到的属性缺省值或默认值？小程序组件里的每个属性应该都有它的缺省值

**Comment by Darmody** [comment]
> Hi @Darmody,
> 我这边也遇到了类似 #241 这样的问题
> 是不是可以考虑，给那些没有用到的属性缺省值或默认值？小程序组件里的每个属性应该都有它的缺省值

是的，可以先这么处理。能说明一下你遇到的问题吗

**Comment by Darmody** [comment]
改变一下思路，通过js文件切分模板，每个模板收集自己的props，也能一定程度上解决这个问题

**Comment by Darmody** [comment]
但同时要考虑微信模板大小的问题。每一个模板为了支持递归都要循环定义组件

**Comment by briefguo** [comment]
我描述下我的问题吧。

多个页面存在 `Navigator` 组件，但是只有某一个组件设置了属性 `openType`，最终生成的模版上其他未添加 `openType` 的 `Navigator` 组件就共享了这一属性

点击未设置openType的Navigator异常，提示 `<navigator invalid openType>`

> 属性 | 类型 | 默认值 | 必填 | 说明 | 最低版本
> open-type | string | navigate | 否 | 跳转方式
> https://developers.weixin.qq.com/miniprogram/dev/component/navigator.html

其实，我想的就是，这时候如果生成模版时，给它一个默认值 `navigate`，它就可以正常运作了
