### ISSUE TITLE
可以使用云开发么？

### ISSUE THREAD

**Issue by wenxiangdong** [remaxjs/remax#244]
我在文档里没有看到这部分的说明

**Comment by Darmody** [comment]
大概看了一下文档。云开发主要是调用 `wx.cloud` ?

**Comment by wenxiangdong** [comment]
> 大概看了一下文档。云开发主要是调用 `wx.cloud` ?

也就是说还是可以使用wx这个全局命名空间的，非常感谢！

**Comment by Darmody** [comment]
可以使用，但是最好从 remax 导入 api.

后面我们会把 cloud 导出
