### ISSUE TITLE
[问题] 请问和 taro 相比，有哪些优势？

### ISSUE THREAD

**Issue by Richard-Choooou** [remaxjs/remax#254]
**问题描述**
[详细地描述问题，让大家都能理解]

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by pkaq** [comment]
确实需要一篇这样的文章  就像当年VUE一样 一篇文章拉了好几车人
