### ISSUE TITLE
[BUG] 页面在引入 React Context 的情况下，useShow 函数会在错误的情况下被触发

### ISSUE THREAD

**Issue by elowes** [remaxjs/remax#256]
**bug 描述**
如果一个页面引入了 React Context，那么这个页面除了在第一次显示在前台时能正常的触发 `useShow`，后续在它切入后台时也会触发，且再切换到前台时无法再触发`useShow`。

**复现步骤**
下面有最小复现此问题的 demo，注意查看控制台输出

**期望结果**
`useShow`可以正常的触发

**复现代码**
[https://github.com/elowes/remax-useShow-repro](https://github.com/elowes/remax-useShow-repro)

**版本信息:**

- remax 版本: 1.1.0
- 手机型号 手机条件无关
- 小程序端 微信小程序
- 小程序版本 2.8.3
- 开发环境 macOS

**其他信息**
无

**Comment by yesmeck** [comment]
Fixed in 1.1.2
