### ISSUE TITLE
[BUG] 在入口文件 app.tsx 中对 children 进行延迟渲染，则页面的 useShow 不会被触发。

### ISSUE THREAD

**Issue by elowes** [remaxjs/remax#257]
**bug 描述**
在入口文件 `app.tsx` 中对 `children` 进行延迟渲染，则首页初次加载完成显示时， `useShow` 不会被触发。

**复现步骤**
下面附有最小复现 demo

**期望结果**
`useShow` 可以正常工作

**复现代码**
[https://github.com/elowes/remax-useShow-repro](https://github.com/elowes/remax-useShow-repro) 
```diff
- 注意在 other 分支上
```

**版本信息:**

- remax 版本: 1.1.0
- 手机型号 手机型号无关
- 小程序端 微信小程序
- 小程序版本 2.8.3
- 开发环境 macOS

**其他信息**
无

**Comment by yesmeck** [comment]
这个行为是预期的。不渲染 `children` 只是页面组件没有渲染，不代表小程序页面没有加载。小程序页面加载的时候因为页面组件还没加载，所以 `onShow` 事件没有注册上。

只能建议不要在 App 里有条件的渲染  `children`。
