### ISSUE TITLE
[BUG] Slider 组件异常

### ISSUE THREAD

**Issue by elowes** [remaxjs/remax#273]
**bug 描述**
项目中出现多个 Slider 组件时，Slider 组件之间的一些 props 会互相干扰。
![image](https://user-images.githubusercontent.com/8766034/66623817-ffb98380-ec1f-11e9-849b-e86f83f67613.png)
可以看到上图中第二个 Slider 的 blockSize 被第一个 Slider 的 blockSize 设置影响了，且第一个 Slider 设置 step 会导致第二个 Slider step 为 0；

**复现步骤**
下面附有最小复现 demo 仓库地址

**期望结果**
Slider 可以正常工作

**复现代码**
[最小复现代码仓库](https://github.com/elowes/remax-slider-repro)

**版本信息:**

- remax 版本: 1.1.3
- 手机型号 手机无关
- 小程序端 微信小程序
- 小程序版本 2.8.3
- 开发环境 macOS

**其他信息**
无

**Comment by Darmody** [comment]
#243 和这个有关系。

这个周末就会解决这个问题。

目前的话 Slider 如果受控了，就要全部受控。
