### ISSUE TITLE
[RFC][需求] 支持 wxs/sjs

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#278]

**Comment by Darmody** [comment]
支持用户在 remax 中创建 `wxs` （以微信为例，对应支付宝的sjs），可以处理一些对性能有要求的问题。

https://developers.weixin.qq.com/miniprogram/dev/reference/wxs/

## Feature

1. `wxs` 文件使用 `wxs` 的语法。
2. `wxs` 中只支持引入 `wxs` 文件。
3. `wxs` 必须写在 `wxs` 文件中。
4. 使用 `wxs` 时，只能直接作为 `jsx` 属性使用

正确的用法：

```jsx
import helper from './helper.wxs';

function Page({ src }) {
  return (
    <Image src={helper(src)} />
  )
}
```

错误的用法：

```jsx
import helper from './helper.wxs';

function Page({ src }) {
  function normalizeSrc () {
    return helper(src);
  }

  return (
    <Image src={normalizeSrc()} />
  )
}
```

## Solution

1. 在 jsx 中收集所有 `wxs` 引用和使用。
1. 实现一个 babel `wxs` 处理器，解析 `wxs` 语法。
3. 生成 `wxs` 文件。

## Addtional

1. 还可以考虑支持 `js/ts` 转 `wxs`。
2. 针对 `React.createElement` 等动态用法的支持，可能引入 `macros` 更合适？

**Comment by Darmody** [comment]
在 remax 项目中，可以直接开发原生自定义组件。如果有使用 `wxs/sjs` 的需求，可以直接写原生代码

**Comment by watsonhaw5566** [comment]
这个实现的需求是对第三方组件的一些转换，比如vant/anti组件，在微信中用了wxs,所以无法在支付宝和头条中使用，头条copy了支付宝的sjs实现。所以只需要解决wxs转为sjs就可以使第三方组件支持支付宝和头条平台，我看看需要怎么实现一波。
