### ISSUE TITLE
[BUG]微信 catchClick 无法正常使用

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#279]

**Comment by Darmody** [comment]
通过 #283  来实现会更合适。

**Comment by superman0159** [comment]
所以问题修复了吗

**Comment by Darmody** [comment]
@superman0159 我们打算支持 stopPropagation，废弃 catchClick 的用法

看这里 #292

**Comment by superman0159** [comment]
就是这个，我也看到了，还没有merge吧？

**Comment by superman0159** [comment]
> @superman0159 我们打算支持 stopPropagation，废弃 catchClick 的用法
> 
> 看这里 #292

就是这个我也看到了，还没有merge吧？

**Comment by Darmody** [comment]
> 就是这个，我也看到了，还没有merge吧？

是的，还在 review 中
