### ISSUE TITLE
[需求] 支持*.config.js用ts代替，并且给出相应的类型定义

### ISSUE THREAD

**Issue by vvni** [remaxjs/remax#280]
**需求描述**
[详细地描述需求，让大家都能理解]
支持*.config.js用ts代替，并且给出相应的类型定义
**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
我想开发者的主要诉求是在写 config 的时候能有自动补全。如果支持 config 用 ts 来写，增加了一点复杂度，我觉得我们可以提供一个 createConfig 的小方法来帮助创建 config

**Comment by QC-L** [comment]
@Darmody 或者提供 VSCode 插件或者代码片段

**Comment by yesmeck** [comment]
提供类型就可以了吧。

```typescript
import { RemaxConfig, AppConfig } from 'remax';
```

**Comment by Darmody** [comment]
> 提供类型就可以了吧。
> 
> ```ts
> import { RemaxConfig, AppConfig } from 'remax';
> ```

主要是要在 config.js 里面用到

**Comment by yesmeck** [comment]
```typescript
import { AppConfig } from 'remax';

const appConfig: AppConfig = {
  pages: ['pages/index/index']
}

export default appConfig;
```

**Comment by Darmody** [comment]
那就是支持 config 用 ts 写了

**Comment by Darmody** [comment]
@yesmeck 但是这样对写 js 的同学不太友好

**Comment by yesmeck** [comment]
js 只能这样。

**Comment by Darmody** [comment]
> js 只能这样，这里讨论的是支持 ts。

如果提供一个 createConfig 方法，js应该也可以补全。

```js
createConfig({
  xxx: 'xxx',
})
```

**Comment by yesmeck** [comment]
没必要，加个 schema 检查就可以了。

**Comment by Darmody** [comment]
可以

**Comment by Darmody** [comment]
对了，直接 declare *.config.js 应该就可以了吧

**Comment by fjc0k** [comment]
直接提供 ts 定义就可以了。

```js
/** @type {import('remax').RemaxConfig} */
const config = {}

module.exports = config
```
