### ISSUE TITLE
[BUG] placeholderStyle等没有被转换成内联解释型样式

### ISSUE THREAD

**Issue by briefguo** [remaxjs/remax#281]
**bug 描述**
一些组件的特殊style属性，没有正常被转换，譬如：
- PickerView的`indicatorStyle`
- Input的`placeholderStyle`
- Map的style
- 。。。

**期望结果**
能够正常转换为内联解释型样式

**复现代码**
```
placeholderStyle={{ color: "#adb1b9" }}
// 转换成了 placeholder-style="[object Object]"

```

**版本信息:**

- remax 版本: [1.2.0]
- 手机型号 [iPhone X]
- 小程序端 [微信小程序]
- 小程序版本[2.8.2]
- 开发环境 [mac OS]

**Comment by yesmeck** [comment]
一些自定组件也会有这个问题。

我可能需要约定把  style 结尾的属性都转换一下🤔。
