### ISSUE TITLE
[需求]合成事件

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#283]
**需求描述**
引入合成事件，用于解决事件冒泡捕获等问题

**解决方案**
https://reactjs.org/docs/events.html

**Comment by evilbs** [comment]
需要有人做这个功能吗？

**Comment by Darmody** [comment]
> 需要有人做这个功能吗？

还在思考中，可以看看 #292 ，如果有想法可以做做看

**Comment by Darmody** [comment]
重新实现，去除 data-rid
