### ISSUE TITLE
[BUG] 节点太多时，IDE 卡爆了

### ISSUE THREAD

**Issue by Lizhooh** [remaxjs/remax#284]
**bug 描述**
[详细地描述 bug，让大家都能理解]

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/19299088/66909554-88308d80-f03f-11e9-83b4-0effa45a15aa.png)

**Comment by Darmody** [comment]
一共有多少个节点？微信本身有对节点做限制。

如果是长列表需求，可以考虑使用 [remax-window](https://github.com/remaxjs/remax-window)

**Comment by Lizhooh** [comment]
@Darmody 
- 详情页，节点层次太多，不光光是列表页的问题。
- 这个 remax-window 我看了一下，需要有确定的 item 高度，但是我们的列表 item 高度是不太确定的。

**Comment by Darmody** [comment]
@Lizhooh 如果方便的话，可以提供一个可复现的repo吗？

**Comment by Darmody** [comment]
IDE 卡顿感觉和 remax 关系不大。如果还有疑问的话，请贴出可以复现的例子方便排查问题
