### ISSUE TITLE
[需求] 支持 react-spring

### ISSUE THREAD

**Issue by skywalker512** [remaxjs/remax#285]
**需求描述**
react-spring 来构建动画体验更好

**解决方案**
他们的 react-three-fiber 也是 React renderer，应该可以用类似的方法达成 https://github.com/react-spring/react-spring/blob/master/src/targets/three/index.ts

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
@skywalker512 有兴趣的话一起研究下吧

**Comment by Darmody** [comment]
主要需要实现的部分是 `injectApplyAnimatedValues`

https://github.com/react-spring/react-spring/blob/master/src/targets/web/globals.ts#L82

把 react-spring 的 AnimatedValues 转换成小程序的 Animation 对象

**Comment by Darmody** [comment]
小程序没有提供 `requestAnimationFrame` ，所以在 `react-spring` 中没办法执行 loop

https://github.com/react-spring/react-spring/blob/master/src/animated/Globals.ts#L73
https://github.com/react-spring/react-spring/blob/master/src/animated/Globals.ts#L23

可能不能给 react-spring 提供一个 remax target 了，把 react-spring 魔改成 remax-spring 好一点

**Comment by Darmody** [comment]
加上 remax target 以后可以用了 https://github.com/remaxjs/remax-spring

不过这种在逻辑层频繁更新的方式，做些复杂的动画会卡，没有小程序本身提供的 Animation 体验好。

**Comment by Darmody** [comment]
后续看一下 react-spring 接不接受新的 target，或者我们自己发布一个 remax-spring
