### ISSUE TITLE
[问题]是否支持mobx,是直接使用mobx-react吗?

### ISSUE THREAD

**Issue by deng-yc** [remaxjs/remax#287]
**问题描述**
[详细地描述问题，让大家都能理解]

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
@deng-yc 可以试一下

**Comment by jueinin** [comment]
它依赖了react-dom,跑不起来的,但是mobx本身可以的

**Comment by Darmody** [comment]
https://github.com/remaxjs/examples/blob/master/wechat-mobx/package.json

可以参考上面的例子
