### ISSUE TITLE
[需求]API 和组件的同步机制

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#293]
**需求描述**

需要有一个机制能快速跟进小程序 API 和组件的更新。

**解决方案**

待讨论

**Comment by Darmody** [comment]
把 `wx` 或 `my` 包装成 `remax` 导出吧。这样即使我们没有 ts 或者 promise 支持，开发者至少能获取到最新的 api。

然后再提供一个类似 `React.createElement` 的方式支持开发者引入不存在的组件

**Comment by Darmody** [comment]
噢，不过模板需要预先定义，不能接受动态的组件。

可以在 remax.config.js 里定义组件
