### ISSUE TITLE
build的时候，报错：NODE_ENV不是内部或外部命令

### ISSUE THREAD

**Issue by KouSum** [remaxjs/remax#295]
**问题描述**
[详细地描述问题，让大家都能理解]

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]
windows系统

**Comment by yesmeck** [comment]
需要引入下 cross-env，参考：

https://github.com/remaxjs/template-alipay/commit/e64e1535b2f0d87cc3194fb0ed99c1478f72ee12
