### ISSUE TITLE
引入vant-weapp 报错

### ISSUE THREAD

**Issue by 15207799874** [remaxjs/remax#299]
**bug 描述**
[详细地描述 bug，让大家都能理解]

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

import * as React from 'react';
import { View, Text, Image } from 'remax/wechat';
import styles from './index.module.css';
import Button from 'vant-weapp/dist/button'

export default () => {
  return (
    <View className={styles.app}>
      <Button type="primray">Remax</Button>
      <View className={styles.header}>
        <Image
          src="https://gw.alipayobjects.com/mdn/rms_b5fcc5/afts/img/A*OGyZSI087zkAAAAAAAAAAABkARQnAQ"
          className={styles.logo}
          alt="logo"
        />
        <View className={styles.text}>
          编辑 <Text className={styles.path}>src/pages/index/index.js</Text>开始
        </View>
      </View>
    </View>
  );
};

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/21092529/67846035-7e2c8580-fb3b-11e9-81cf-a1e1161c6430.png)

**Comment by yesmeck** [comment]
@15207799874 可以提供一个重现仓库吗？

**Comment by xuqianjin** [comment]
@15207799874  把微信开发者工具关闭再打开

**Comment by Darmody** [comment]
@15207799874 还有问题吗
