### ISSUE TITLE
项目运行报错[BUG]

### ISSUE THREAD

**Issue by JazzOne** [remaxjs/remax#302]
**bug 描述**

![image](https://user-images.githubusercontent.com/17613972/67921585-36613900-fbe3-11e9-8c6a-56c7ed51df8f.png)

UnhandledPromiseRejectionWarning: Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-import'

如图，一直卡在此步骤

 **复现步骤**

```
1. npx degit remaxjs/template-wechat my-app
2. cd my-app && npm install
3. npm run dev
```

**期望结果**

项目正常运行

**复现代码**

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 开发环境 macOS 10.14.6

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
npm 的版本是？删除 node_modules 重新安装试试。

**Comment by JazzOne** [comment]
> npm 的版本是？删除 node_modules 重新安装试试。

![image](https://user-images.githubusercontent.com/17613972/67921887-1e3de980-fbe4-11e9-8c23-6def547d6e81.png)

删除node_modules依然如此，每次卡在 (87)

**Comment by yesmeck** [comment]
用 yarn 呢？

**Comment by JazzOne** [comment]
> 用 yarn 呢？

还是一样；
1.  删除node_modules文件夹
2. yarn install
3. yarn dev 

![image](https://user-images.githubusercontent.com/17613972/67922188-fe5af580-fbe4-11e9-849d-6a67d7818068.png)

**Comment by JazzOne** [comment]
> 删除你用户目录下的 `.postcssrc.js`。。。。

检查了一下。。。我用户目录下面没有`.postcssrc.js`文件。。。我再看看排查一下问题

**Comment by yesmeck** [comment]
![20191031140104](https://user-images.githubusercontent.com/465125/67922837-e71d0780-fbe6-11e9-97e6-3c5c29f6bdec.jpg)

你看这个

**Comment by JazzOne** [comment]
> ![20191031140104](https://user-images.githubusercontent.com/465125/67922837-e71d0780-fbe6-11e9-97e6-3c5c29f6bdec.jpg)
> 
> 你看这个

搞定了， 是这个问题。。感谢百忙之中的积极响应～
