### ISSUE TITLE
希望能提供一个dva + typescript 的示例项目

### ISSUE THREAD

**Issue by tomzio** [remaxjs/remax#303]
**需求描述**
之前已经使用过dva，现在想在Typescript小程序中使用，希望能提供一个dva + typescript 的示例项目

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
可以 google  一下 dva + typescript

**Comment by yesmeck** [comment]
js 的版本 https://github.com/remaxjs/examples/tree/master/alipay-dva
