### ISSUE TITLE
[BUG] 多次打开同一页面，初始渲染速度逐渐变慢

### ISSUE THREAD

**Issue by coppyC** [remaxjs/remax#304]
**bug 描述**
多次打开同一页面，初始渲染速度逐渐变慢，在模拟器上点了近20次，出现肉眼可见的白屏时间，在性能差的手机会更明显。
起初我是在手机发现的，奈何电脑没有复现，以为是小程序本身的问题，今天在电脑模拟器上，多点了很多次也复现了，初步怀疑是remax的问题。

**复现步骤**
准备一个二级页面，UI 复杂一点，这样可以减少需要复现的点击次数，然后像gif中一样，点击进入二级页面，回来，再进入，多次重复后，二级页面的初始渲染有越来越明显的卡顿。
（不知是框架问题还是微信小程序的问题）

效果如gif所示
![2019-11-01 10-23-44 2019-11-01 10_29_22](https://user-images.githubusercontent.com/25004510/67999096-d7a8c780-fc95-11e9-8608-12d987c51b81.gif)

**期望结果**
每次打开同一页面速度都一样

**复现代码**
按理说任何项目都能复现。
如果不能复现的话，我再提供。

**版本信息:**

- remax 版本: [1.2.1]
- 小程序端 [1.02.1907300]
- 小程序版本[e.g. 2.9.1]
- 开发环境 [e.g. mac OS]

**Comment by coppyC** [comment]
好像找到原因了

 在[Container.ts](https://github.com/remaxjs/remax/blob/master/packages/remax/src/Container.ts#L84)打开了调试模式后，每次打开页面如图

![image](https://user-images.githubusercontent.com/25004510/68065312-42bfd000-fd62-11e9-9da0-12f5cc826466.png)

打开同一个页面，主要是 setData 这部分渲染时间从第二次开始越来越长，且不是等差递增。
但每次打开页面remax setData过去的数据始终是一致，也就是说不是 remax js层的逻辑问题。哪道是小程序的问题?

第二天，我突发奇想，最终在 wxs 脚本找到了问题所在。
在[helper.wxs](https://github.com/remaxjs/remax/blob/master/packages/remax-cli/templates/helper.js) 的 reduce 打印了每次进来页面时 tree 的大小。
```js
console.log(JSON.stringify(tree).length)
```

![image](https://user-images.githubusercontent.com/25004510/68065417-f4abcc00-fd63-11e9-9de7-b333ef200916.png)

我没怎么用过 wxs ，不太清楚为什么一个console.log 控制台会打印出两个甚至三个，但可以看出带WXSRT前缀的值比较符合setData的渲染时候不断增长的情况

**猜测：在wxs中使用全局变量，值不会随着下次页面的打开清空，还可能导致内存泄漏?**
(*目前仅在微信端测试，其它平台没有做过测试，可能也有这个问题*)

我在每次打开页面时进行了一次数据初始化，速度有所改善，每次增长的速度没有那么夸张，但问题依旧存在，可能还是内存泄漏的关系
![image](https://user-images.githubusercontent.com/25004510/68065680-aa2c4e80-fd67-11e9-8926-d3a4b9175bcc.png)

或许，应该把dom树放在 js 层而不是 wxs 层

**Comment by Darmody** [comment]
👍  我在研究 #156 的时候也注意到 wxs 有些奇怪，你的发现和当时发现的性能问题可能是一个问题。

你每次进入到同一个页面，但是 tree 的长度是不断增加的对吗？

**Comment by Darmody** [comment]
> 我在每次打开页面时进行了一次数据初始化

这个你具体是做了什么操作？

**Comment by Darmody** [comment]
wxs的问题我通过各种比较，虽然他会重复执行，但是应该对性能的影响不是很大。

我个人猜测，由于反复切换页面，node 是不断创建的，属于自增的 id 会不断增大，等到增长到一定位数后，就会对传输量造成影响。

你能不能打开 console.log 的payload，看看里面的 id 是不是变得很长了？如果你每个页面有很多的 node，每个 node 的 id 又很长，是有可能影响传输量的

**Comment by krhougs** [comment]
我也遇到了一样的问题，可以试试这个临时patch：
https://github.com/krhougs/remax/tree/feature/dont-compute-tree-in-wxs

把wxs里的运算丢到逻辑层里做可以解决问题，但是还没有为长列表做优化。

**Comment by coppyC** [comment]
> > 我在每次打开页面时进行了一次数据初始化
> 
> 这个你具体是做了什么操作？

@Darmody 
我修改了 reduce ，添加了init，然后在Container的构造函数(每次进来页面的时候)，发送一个 init 的action `context.setData({  action: {type: 'init'}  })`
但神奇的是，这次的渲染时间居然保持稳定了。哪道我这次做的和上次有哪里不一样。
```js
function reduce(action) {
  switch (action.type) {
+   case 'init':
+     tree.root = {
+       children: [],
+     }
      return tree
    case 'splice':
      for (var i = 0; i < action.payload.length; i += 1) {
        var value = get(tree, action.payload[i].path);
        if (action.payload[i].item) {
          value.splice(
            action.payload[i].start,
            action.payload[i].deleteCount,
            action.payload[i].item
          );
        } else {
          value.splice(action.payload[i].start, action.payload[i].deleteCount);
        }
        set(tree, action.payload[i].path, value);
      }
      return tree;
    default:
      return tree;
  }
}

```
![image](https://user-images.githubusercontent.com/25004510/68095013-ed5dfd00-fee0-11e9-90fe-ba38d08f8199.png)

对了，之前忽略了 init 的渲染时间，这次算上init的时间，也是在一个区间内稳定
![image](https://user-images.githubusercontent.com/25004510/68095296-2d25e400-fee3-11e9-944f-e449419ddc58.png)


ps: 楼上的做法，把wxs放在js层我也试过，渲染时间也会保持稳定。

tree 的长度是不断增加，而且是递增的，里面node的id虽然会不断增长，但我跑的数据最多让id在三位数，不是 id 的关系(而且我是在reduce里面的第一行打印的，这个时候，payload的数据还没有加入至tree里面)，我看了tree的内容，每次进来保留了上次离开的数据，而且是累加起来的数据。

想到这里，我又稍微改造了一下，把 'init' 的调用时机改到页面卸载，这次，tree的长度 每次进来都不会增长了
![image](https://user-images.githubusercontent.com/25004510/68095675-6dd32c80-fee6-11e9-9dad-d6b9cb8a19b6.png)
初始渲染速度也保持相对稳定
![image](https://user-images.githubusercontent.com/25004510/68095725-c9051f00-fee6-11e9-8fd1-16518bf8c63b.png)

相对 把wxs放在js层，在unload在clear tree这个做法对当前代码的改动更小


一开始，我也以为可能和156是一个问题，但现在我觉得应该不是
这个问题是页面的打开与关闭才触发，但156不是。
或许也是同一个问题，wxs的迷之机制。

**Comment by Darmody** [comment]
@coppyC 能不能来个PR？

**Comment by coppyC** [comment]
我抽空搞一下。

**Comment by Pochodaydayup** [comment]
@coppyC  @Darmody 感觉 unload 时 clear tree ，那么上一个页面的 tree 会被干掉，这样做可能会导致一些问题，感觉还是把 wxs 放在 js 层好点。

**Comment by Darmody** [comment]
> @coppyC @Darmody 感觉 unload 时 clear tree ，那么上一个页面的 tree 会被干掉，这样做可能会导致一些问题，感觉还是把 wxs 放在 js 层好点。

当时引入 wxs 的目的是为了减少 setData 传输量。如果去掉的话，长列表或者节点很多的时候，很有可能会卡

**Comment by coppyC** [comment]
从目前测试来看目前是不会影响其它页面的tree

但这wxs有什么蝴蝶效应我也不能保证，还是先按兵不动了。
