### ISSUE TITLE
[问题]usePageScroll 回调函数获取不到scrollTop 

### ISSUE THREAD

**Issue by DarkerGarfield** [remaxjs/remax#308]
**问题描述**
我使用usePageScroll 后回调函数没有返回任何参数，还请各位指教，谢谢。
第一张图是我的代码，第二张图是滚动屏幕的时候打印出的内容

**示例代码**
`    usePageScroll(res => console.log('res-->：' + res));`

![Image of Yaktocat](https://wiz-ztb.oss-cn-beijing.aliyuncs.com/22.png?OSSAccessKeyId=LTAIjZvUSfH9iwy8&Expires=1576192530&Signature=DnZ4MPkXaUEC7RUPK40ed9rpUTI%3D)

![Image of Yaktocat](https://wiz-ztb.oss-cn-beijing.aliyuncs.com/11.png?OSSAccessKeyId=LTAIjZvUSfH9iwy8&Expires=1576192582&Signature=XVwvUZamYXazFLDaF4tSZFjp%2Bxs%3D)

**Comment by Darmody** [comment]
#307
