### ISSUE TITLE
[bug] 微信转发功能不配置不显示

### ISSUE THREAD

**Issue by xuqianjin** [remaxjs/remax#309]
**需求描述**
当一个页面没有配置分享内容时,不需要出现 转发按钮

**Comment by Darmody** [comment]
由于小程序中，只要定义了 onShareAppMessage 方法，就认定有转发功能，但是我们在实现 React 组件和 React hooks 时，是需要预先定义 onShareAppMessage 方法的。所以 remax 页面中转发按钮都会显示出来。

针对这个无奈的情况，目前的解决方案是用 [hideShareMenu](https://developers.weixin.qq.com/miniprogram/dev/api/share/wx.hideShareMenu.html) API 把按钮隐藏

```js
import { hideShareMenu } from 'remax/wechat'
```

**Comment by whereiscode** [comment]
在页面里使用 usePageEvent('onShareAppMessage', ()=>{
   title:'xxxx',
....
})
无效，这个usePageEvent   onShareAppMessage到底应该怎么用呢？
