### ISSUE TITLE
[BUG] 图片资源转换路径错误,导致图片无法显示

### ISSUE THREAD

**Issue by jueinin** [remaxjs/remax#311]
**bug 描述**
yarn run dev 后remax会进行打包操作,然而遇见图片时处理方式有些诡异, 经过测试, 如果<Image src="图片路径"/> 则图片不会自动被打包进去,需要手动把图片复制到dist指定目录里. 

如果`import img from 'xxx图片路径'` , 然后 `<Image src={img}/>`则图片会被正确打包,但是生成的路径错误, 依旧无法使用

**复现步骤**
`npx degit remaxjs/template-wechat-typescript my-app` 新建一个项目, 然后随便在 ` src/pages/index/index.tsx`中引入图片即可观察到该现象, 也可以 克隆本项目查看dist目录的编译结果
`https://github.com/jueinin/remax-test`

**期望结果**
路径正确

**复现代码**
<a href="https://github.com/jueinin/remax-test">链接</a>

**版本信息:**

- remax 版本: 最新版本
- 手机型号 [e.g. iPhone X]
- 小程序端 2.9.1
- 小程序版本2.9.1
- 开发环境 windows10

**其他信息**
![等等](https://user-images.githubusercontent.com/22928234/68070722-c1415f80-fdac-11e9-9b44-0dbfdcbeb0e2.png)

**Comment by jueinin** [comment]
另外创建完项目首次进行打包的时候并不会自动生成sitemap.json, 小程序那边编译不过去,需要手动写一个,或者直接删掉sitemap那一行好像也可以

**Comment by Darmody** [comment]
> 另外创建完项目首次进行打包的时候并不会自动生成sitemap.json, 小程序那边编译不过去,需要手动写一个,或者直接删掉sitemap那一行好像也可以

sitemap 不是必须的吧？
