### ISSUE TITLE
[BUG]钉钉小程序中View组件绑定onClick事件无效

### ISSUE THREAD

**Issue by chishen** [remaxjs/remax#314]
**bug 描述**
钉钉小程序中View组件绑定onClick事件无效

**复现步骤**
import { View, Button } from 'remax/alipay'
其余代码可看下图
点击button按钮会触发点击事件输出打印值，点击view没有触发点击事件

**期望结果**
点击view能正常触发点击事件

**复现代码**
![image](https://user-images.githubusercontent.com/15800045/68112616-ad246c00-ff2c-11e9-9642-c26f0b07fb8e.png)

**版本信息:**
- remax 版本: [1.1.0]
- 钉钉小程序IDE [0.70.14]
- 开发环境 [mac OS]

**Comment by Pochodaydayup** [comment]
@chishen remax 升级后再看看？

**Comment by chishen** [comment]
> @chishen remax 升级后再看看？

普通创建的remax项目我试过在View组件上可以出发点击事件
但是我用的是 https://github.com/remaxjs/examples/tree/master/alipay-redux
在这里View组件绑定onClick事件确实无效,remax和remax-redux已经升级到最新版本，
钉钉小程序IDE也是最新的0.70.14版本

**Comment by Darmody** [comment]
@chishen 我用 alipay redux 那个模板试了一下没问题，能不能提供一个复现 repo？

**Comment by chishen** [comment]
> @chishen 我用 alipay redux 那个模板试了一下没问题，能不能提供一个复现 repo？

录了个视频，有点大，所以放到了百度云盘，可以看一下复现的过程
链接: https://pan.baidu.com/s/1H0XjG8dcfBaEqVtoNq6EiA 提取码: axj4

**Comment by Darmody** [comment]
@yesmeck 按照上面的复现步骤确实可以重现。感觉上是钉钉的问题？需要你看一下

**Comment by Darmody** [comment]
@chishen 你试下 1.4.1 还有这个问题不

**Comment by Darmody** [comment]
这个问题可能和钉钉处理 catchTap 的逻辑有关系。1.4.1 默认去掉了 catchTap 属性。

**Comment by chishen** [comment]
> @chishen 你试下 1.4.1 还有这个问题不

验证过在1.4.1版本下onClick事件生效了

**Comment by Darmody** [comment]
@chishen cool
