### ISSUE TITLE
[BUG] subpackages 下引入 plugin 编译报错

### ISSUE THREAD

**Issue by magicshui** [remaxjs/remax#317]
**bug 描述**
plugin 在 subpackges 下引入将会导致编译错误

**复现步骤**
在 `app.config.js` 中如果全局引入 plugin 可以正常编译，但是如果放到 subpackages 下中引入将会导致无法找到模块报错；

```tsx
 subpackages: [
    {
      name: "packageRoot",
      root: "packageRoot/",
      pages: ["pages/demo/demo"],
      plugins: {
          myPlugin: {
            version: "1.2.1",
             provider: "xxxxxxxx"
          }
       }
    }
  ]
```

**期望结果**
允许在 subpackages 下引入 plugin

**复现代码**
参考`复现步骤`

**版本信息:**

- remax 版本: 1.3.1
- 手机型号 所有平台
- 小程序端 微信小程序
- 小程序版本 2.9.2
- 开发环境  mac OS

**其他信息**
N/A

**Comment by Darmody** [comment]
@Pochodaydayup 这个是要去收集分包下的 plugin 路径吗？

**Comment by Pochodaydayup** [comment]
@Darmody 不用 直接复用原生组件是属于哪个 page 那部分功能就好 最近有点忙 我周末改下这个吧

**Comment by Darmody** [comment]
> @Darmody 不用 直接复用原生组件是属于哪个 page 那部分功能就好 最近有点忙 我周末改下这个吧

可以
