### ISSUE TITLE
请问怎么使用组件库呢？可以使用antd吗[问题]

### ISSUE THREAD

**Issue by hefengly** [remaxjs/remax#321]
**问题描述**
请问怎么使用组件库呢？可以使用antd吗

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Pochodaydayup** [comment]
@hefengly 可以使用 mini-antui，参照 https://remaxjs.org/guide/custom-component

**Comment by yesmeck** [comment]
antd 是基于 ReactDOM 的，无法在小程序里运行。

**Comment by hefengly** [comment]
感谢🙏

**Comment by hefengly** [comment]
mini-antui是不是只有支付宝小程序才可以使用？如果是字节跳动小程序的话，是只能用原生的组件库了么？

**Comment by Pochodaydayup** [comment]
@hefengly 是的，mini-antui 有些 api 和 字节跳动小程序不兼容

**Comment by hefengly** [comment]
感谢🙏。
