### ISSUE TITLE
[BUG]升级1.4.1后引入的vantIcon组件不显示

### ISSUE THREAD

**Issue by xuqianjin** [remaxjs/remax#334]
**bug 描述**
在1.4.1下引入vanticon,不显示,且没有请求font字体文件,发现原因是vant需要的class-prefix没有传递下去

**复现步骤**
在1.3.1是下写一个vanticon组件,然后升级1.4.1

**复现代码**
```
<VantIcon class-prefix="van-icon" name="chat" size="20px" color="white" />
<VantIcon classPrefix="van-icon" name="chat" size="20px" color="white" />
以上两种写法都不行,但在1.3下classPrefix是可以的
```

**版本信息:**

- remax 版本: [e.g. 1.4.1]
- 小程序端 [e.g. 微信小程序]

**其他信息**
[如截图等其他信息可以贴在这里]
![{F1683A87-C198-40A5-AC2B-8719BC2837E8}_20191112095256](https://user-images.githubusercontent.com/12406066/68635017-3857c000-0532-11ea-9359-a724a843be2c.jpg)

**Comment by Darmody** [comment]
@xuqianjin 根据 vantage-weapp 的文档，需要使用中折线风格的属性命名方式。

```jsx
<VantIcon class-prefix="van-icon" name="chat" size="20px" color="white" />
```

**Comment by xuqianjin** [comment]
@Darmody class-prefix的写法也试过了...

**Comment by Darmody** [comment]
<img width="425" alt="屏幕快照 2019-11-12 10 16 08" src="https://user-images.githubusercontent.com/6788752/68636150-8de19c00-0535-11ea-8444-700c884d7a4a.png">
<img width="360" alt="屏幕快照 2019-11-12 10 17 01" src="https://user-images.githubusercontent.com/6788752/68636162-95a14080-0535-11ea-8361-f3033f1d95ea.png">


@xuqianjin 我试了一下是可以的额

**Comment by Darmody** [comment]
```jsx
<VantIcon class-prefix="van-icon" name="chat" size="20px" color="white" />
```

这样也是OK的

**Comment by Darmody** [comment]
@xuqianjin 试试把 dist 删除重新 build 有没有帮助？

**Comment by xuqianjin** [comment]
@Darmody 我发现问题了...如果页面同时出现class-prefix和classPrefix...就不会出现icon...不知道这算不算一个bug...
```
    <View>
      <VantIcon class-prefix="van-icon" name="chat" size="20px" color="white" />
      <VantIcon classPrefix="van-icon" name="chat" size="20px" color="white" />
    </View>
```

**Comment by Darmody** [comment]
@xuqianjin 噢，可以改进下
