### ISSUE TITLE
增加环境判断

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#34]
```js
import { REMAX } from 'remax'

const isWeapp = REMAX.TARGET.CURRENT === REMAX.TARGET.WEAPP
const isAlipay = REMAX.TARGET.CURRENT === REMAX.TARGET.ALIPAY
```

`REMAX` 作为常量，方便以后扩展

`REMAX.TARGET` 存储环境变量
`REMAX.TARGET.CURRENT` 当前环境
`REMAX.TARGET.WEAPP` 微信小程序对应常量值
`REMAX.TARGET.ALIPAY` 支付宝小程序对应常量值
 ... 其他平台

**Comment by yesmeck** [comment]
```javascript
import { env } from 'remax';

console.log(env.isAliay); // true
console.log(env.isWexin); // false
```

这样？

**Comment by Darmody** [comment]
`env` 可以用来表示 `production` `development`？

另外常量是不是应该大写

**Comment by yesmeck** [comment]
我们不分 production/development 的。

**Comment by Darmody** [comment]
> 我们不分 production/development 的。

为什么呢？如果我写了一个辅助调试的组件，只想在开发环境打开，怎么办

**Comment by yesmeck** [comment]
有道理，那用 platform?

```
import { Platform } from 'remax';

console.log(Platform.current); // 'alipay'
console.log(Platform.isAliay); // true
console.log(Platform.isWexin); // false
```

**Comment by yesmeck** [comment]
https://facebook.github.io/react-native/docs/platform-specific-code

**Comment by Darmody** [comment]
LGTM

**Comment by Darmody** [comment]
```js
Platform.os // ios | android
Platform.target // alipay | weapp | ...
Platform.env // production | development | testing
Platform.isAlipay
Platform.isProduction
Platform.isIOS
...
```

@yesmeck

**Comment by Darmody** [comment]
~~Platform.os~~
os 应该交给各端的api 去获取

**Comment by yesmeck** [comment]
~~Platform.env~~ 不要

**Comment by yesmeck** [comment]
`Platform.target`  => `Platform.current`

target 是构建的时候构建目标平台是什么。当下就不叫 target 了。

**Comment by yesmeck** [comment]
环境还是用

`process.env.REMAX_ENV`？

**Comment by Darmody** [comment]
> 环境还是用
> 
> ~`process.env.REMAX_ENV`？~
> 
> `process.env.NODE_ENV`

👍
