### ISSUE TITLE
[BUG]富文本编辑器无法使用 mini-html-parser 

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#341]
**bug 描述**
https://github.com/remaxjs/examples/issues/13#issue-521621976

**复现代码**

[alipay-mini-app.zip](https://github.com/remaxjs/remax/files/3837004/alipay-mini-app.zip)

**Comment by yesmeck** [comment]
mini-html-parser 用了 cjs 的问题，我去推他们改一下。
