### ISSUE TITLE
[BUG]自定义组件重复引用

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#342]
如果 A 页面依赖了一个自定义组件，那么这个自定义组件会同时出现在 B 页面的 json 配置里。

**Comment by yesmeck** [comment]
@Pochodaydayup 有空看看么

**Comment by Pochodaydayup** [comment]
@yesmeck 我晚上看一下吧

**Comment by yesmeck** [comment]
@Pochodaydayup 我们这边比较急，我先看了。
