### ISSUE TITLE
[BUG]App组件缺少生命周期Hooks

### ISSUE THREAD

**Issue by krhougs** [remaxjs/remax#343]
**bug 描述**
缺少App组件内的生命周期Hooks

**复现代码**
https://github.com/remaxjs/remax/blob/9b5bc84192eac4911d3baf8b94c02ae722d38ab9/packages/remax/src/createAppConfig.ts

**版本信息:**

- remax 版本: 1.4.x

**Comment by Darmody** [comment]
#398 修复这个了吧？ @yesmeck

**Comment by yesmeck** [comment]
不是，这里说的是没有 hooks

**Comment by Darmody** [comment]
噢，这个需要 hooks 吗？

**Comment by krhougs** [comment]
使用App as React components之后就无法访问App()中定义的生命周期hooks了。目前还是不少第三方小程序SDK依赖这玩意的。

**Comment by imccode** [comment]
这个BUG预计下个版本能修复吗，用hooks不要太爽

**Comment by yesmeck** [comment]
@imccode 可以给我们 PR

**Comment by wbget** [comment]
+1，初始化app的时候，需要这个hook
