### ISSUE TITLE
自动更新类型申明

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#344]
需要有个 GitHub action 能自动更新合并 https://github.com/ant-mini-program/mini-types 和 https://github.com/remaxjs/api-typings 的改动，然后自动发包。

**Comment by Darmody** [comment]
把 type 分一个包出来吧，更灵活一些。

**Comment by yesmeck** [comment]
https://github.com/remaxjs/mini-types
https://github.com/remaxjs/api-typings

先让这个两个能自动更新

**Comment by Darmody** [comment]
https://github.com/remaxjs/mini-types/runs/313265520

**Comment by Darmody** [comment]
https://github.com/remaxjs/api-typings/commit/3945f41accb3bd3564a202d75c32ea2591a56587/checks?check_suite_id=321731974

**Comment by yesmeck** [comment]
pull bot 可以换成这个 https://github.com/marketplace/actions/fork-sync
