### ISSUE TITLE
[需求]能不能直接用material-ui组件的？

### ISSUE THREAD

**Issue by zaq2zaq** [remaxjs/remax#348]
**需求描述**
能不能使用现成react组件库

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
不可以哦，先有的大部分 React 组件都是基于 react-dom，但是小程序没有 dom，你可以选择使用已有的小程序组件。使用小程序组件的文档 https://remaxjs.org/guide/custom-component
