### ISSUE TITLE
项目配置文件

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#35]
区分不同端的配置文件：

* 支付宝 app.alipay.json
* 微信 app.weapp.json
* ... 其他平台

**Comment by yesmeck** [comment]
为啥区分？

**Comment by Darmody** [comment]
<img width="600" alt="屏幕快照 2019-08-02 18 31 57" src="https://user-images.githubusercontent.com/6788752/62364361-d6131a80-b553-11e9-93a2-02e7cb297f5f.png">

配置不同

**Comment by yesmeck** [comment]
那相同的部分怎么 DRY？

**Comment by Darmody** [comment]
那就 `app.config.js`，导出 JSON 数据作为配置。这样就可以在 js 里面 DRY，让用户自己控制，比如：

```js
const base = {
  pages: ['pages/index/index', 'pages/new/index', 'pages/login/index'],
}

const title = 'Todo App';
const navigationbarColor = '#323239';

module.exports = {
  weapp: {
    ...base,
    window: {
        backgroundTextStyle: 'light',
        navigationBarBackgroundColor: navigationbarColor,
        navigationBarTitleText: title,
        navigationBarTextStyle: 'white'
      }
    },
  alipay: {
    ...base,
    window: {
        defaultTitle: title,
        titleBarColor: navigationbarColor
    }
  }
};
```

**Comment by yesmeck** [comment]
能不能跟 taro 那样也抹平掉这层呢

**Comment by Darmody** [comment]
![屏幕快照 2019-08-02 18 52 33](https://user-images.githubusercontent.com/6788752/62365480-c34e1500-b556-11e9-8034-92caa1557fd6.png)

他们没有抹平吧

而且我一直觉得抹平交给开发者做比较好，lib抹平有点不灵活🤔

**Comment by yesmeck** [comment]
那就 `app.alipay.json` 吧

**Comment by yesmeck** [comment]
还是 `app.config.js` 吧。。

**Comment by Darmody** [comment]
`app.config.js` LGTM

**Comment by Darmody** [comment]
`app.json` 用 `app.config.js` ，page的config还是json，会不会有点奇怪，行为不统一 @yesmeck
