### ISSUE TITLE
[BUG]1.4以上版本实时编译无效

### ISSUE THREAD

**Issue by chishen** [remaxjs/remax#350]
**bug 描述**
在remax的1.3.1版本中实时编译有效
升级到最新的1.4.2版本实时编译无效

**复现步骤**
具体复现步骤可看视频
链接: https://pan.baidu.com/s/1XDyBu6UcXjira1qKw7R3qA 提取码: a3jr

**Comment by Darmody** [comment]
@chishen 我在本地试过是可以的。最好只能提供一个复现 repo，这样我们可以按你的环境调试

**Comment by Darmody** [comment]
@chishen 还有问题不？

**Comment by chishen** [comment]
> @chishen 还有问题不？

目前在最新的1.4.7版本上测试了一下没有问题了
