### ISSUE TITLE
[BUG]升级1.4.3后引入的第三方组件通过 自定义组件包一层不可用

### ISSUE THREAD

**Issue by xuqianjin** [remaxjs/remax#352]
![{80918FA7-5D78-433E-93D2-EAB4BDA09F83}_20191114174044](https://user-images.githubusercontent.com/12406066/68845174-f8493680-0705-11ea-87f7-720f10b82f04.jpg)

如图..上面的用法样式没有了..

**Comment by yesmeck** [comment]
1.4.5 修复了。
