### ISSUE TITLE
关于把所有节点渲染到一个Page里面的疑问？

### ISSUE THREAD

**Issue by ykforerlang** [remaxjs/remax#353]
有个小小的疑问，我看remax是把所有的节点，包括自定义组件的节点都渲染到一个Page里面去了，在实际的项目中这样会不会有问题呢（只是猜测，当业务复杂了以后）？比如，一个很深层级的小组件setData一次？:smile: :smile: :smile:

**Comment by yesmeck** [comment]
你指的问题具体是什么问题呢？

**Comment by ykforerlang** [comment]
Thanks , 我先关掉 再自己思考思考 :smile:
