### ISSUE TITLE
[BUG]小程序组件属性错误

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#357]
重现仓库：https://github.com/remaxjs/alipay-api-demo

这个 `subTtitle` 不生效 https://github.com/remaxjs/alipay-api-demo/blob/master/src/pages/components/card/index.tsx#L18

因为运行时这个 `subTitle` 被转换成  `sub-title` 了。

**Comment by Darmody** [comment]
原生组件应该不会转的

**Comment by yesmeck** [comment]
你跑那个重现仓库看看

**Comment by yesmeck** [comment]
另外，上面的 demo 里，card 的 `onClick` 事件也有问题，最后到模板层是 undefined

**Comment by yesmeck** [comment]
![20191115182250](https://user-images.githubusercontent.com/465125/68936238-1467d900-07d5-11ea-89f1-45f732eb4f99.jpg)

是 onClick 被转成 onTap 了，这也不对。
