### ISSUE TITLE
[需求]支持开发小程序组件

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#368]
新增一个 `component` 子命令，可以把项目构建成小程序组件：

```bash
$ remax component build
```

组件开发的目录结构：

```bash
.
├── packages.json
├── remax.config.js
└── src
    ├── component.config.js
    └── index.js
```

**Comment by fwh1990** [comment]
请问如果想要创建remax的第三方UI库，就需要用到这个吧？

**Comment by Darmody** [comment]
> 请问如果想要创建remax的第三方UI库，就需要用到这个吧？

不用的。这个是给原生自定义组件用的。

第三方 UI 库可以参考 https://github.com/AnnaSearl/anna-remax-ui

**Comment by fwh1990** [comment]
目前的需求是用户能在react文件直接import我的包，但包里使用的是原生小程序的代码

**Comment by fwh1990** [comment]
> 目前的需求是用户能在react文件直接import我的包，但包里使用的是原生小程序的代码 @Darmody

@Darmody  这种案例有吗？

**Comment by Darmody** [comment]
> > 目前的需求是用户能在react文件直接import我的包，但包里使用的是原生小程序的代码 @Darmody
> 
> @Darmody 这种案例有吗？

https://remaxjs.org/guide/custom-component 

Remax 本身就支持直接引入原生自定义组件

**Comment by yesmeck** [comment]
发现之前想复杂了，编译到组件的话就不需要 bundle。

假设这样一个组件：

```javascript
import * React from 'react';

export default () => {
  return <View>hello</View>;
}
```

编译后：

```javascript
import * React from 'react';
import { createComponentConfig } from 'remax';

const _component = () => {
  return <View>hello</View>;
}

export default Component(createComponentConfig(_component));
```

以及 `index.axml` 和 `index.json`。

由项目自己去依赖 react 和 remax。
