### ISSUE TITLE
[RFC]重新设计跨平台的支持

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#373]
目前[跨平台](https://remaxjs.org/advanced-guide/cross-platform)的支持不是特别友好，需要自己去封装基础组件。

我们可以提供一套抹平了属性差异的基础组件：

```javascript
import { View } from 'remax/universal'

export default () => <View className="greeting">Hello Remax</View>
```

### 保留业务无关的属性:

比如  `className` 是所有平台都一致且业务无关的属性，可以直接保留。

### 功能相同但命名不同的属性改成我们觉得合理的命名

比如支付宝 `onTap` 和微信的 `bindtap` 我们改成 `onClick`。

### 平台特有的属性加前缀

比如支付宝 `Button` 组件的 `public-id` 属性我们改成 `alipayPublicId`

## 如何抹平 API？

通过 https://github.com/remaxjs/hooks 提供抹平后的 API

**Comment by myronliu347** [comment]
## 关于平台差异性抹平

无论 API 或者 组件，对应该已支付宝小程序 提供的API 为标准，不支持的能力标记为不支持，然后将微信/头条的api向支付宝这里靠齐，最终 `remax/universal` 输出额api 和组件都是以支付宝小程序为准，跨端开发最终也只需要保留共有能力，如果有个别端的差异可以直接使用 `remax/wehchat` 这样的包就行。

```js
import { getAuthCode, View, Text } from 'remax/universal';
```

至于 `remax-hooks` 并不能覆盖所有的API，但是可以作为 `remax/universal` 的上层封装的工具库，便于使用方调用

**Comment by yesmeck** [comment]
@myronliu347 还要考虑 H5

**Comment by myronliu347** [comment]
可以参考taro 的设计， API 和 组件在 H5 端对应实现

**Comment by chj-damon** [comment]
组件库这块怎么考虑呢？现在没有一个跨各个小程序平台的组件库，开发的时候很麻烦

**Comment by IronLu233** [comment]
不仅仅是API，类型系统同样需要（比如各种组件的props)

**Comment by fangkyi03** [comment]
不要用universal直接就叫ui不就行了
api走api ui走ui 老是合在一块干嘛 搞得我现在要调用api得
import * as remax from 'remax/wechat';
这样写 而且这样写还不能保证支付宝跟微信兼容 我还得自己独立封装一个
