### ISSUE TITLE
[问题] 在页面中引入了命名为Page的组件导致的非预期行为

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#377]
**问题描述**
我在页面中引入了一个组件并命名为Page, 这会导致编译的时候出现意外结果, 将其改名就可恢复正常.
这是预期的吗, 后续是否会允许这样的命名?

**示例代码**
```
import { Page } from '@/components/Page'
export default () => {
	return (<Page />)
}
```
可正常工作的版本
```
import { Page as NSPage } from '@/components/Page'
```

**其他信息**
编译后的差异
![image](https://user-images.githubusercontent.com/9160743/69051684-010c7600-0a40-11ea-9ec9-6437614c9159.png)

**Comment by Darmody** [comment]
请问 remax 版本是多少

**Comment by yesmeck** [comment]
Page 是小程序的保留关键字，不要使用 Page 命名变量。
