### ISSUE TITLE
[需求] px 自动转 rpx 功能很赞，不过建议增加一个配置项来控制此功能的开关，因为有些地方不适合用 rpx

### ISSUE THREAD

**Issue by Clarence-pan** [remaxjs/remax#380]
**需求描述**
[详细地描述需求，让大家都能理解]
px 自动转 rpx 功能很赞，不过建议增加一个配置项来控制此功能的开关，因为有些地方不适合用 rpx
比如大屏手机或平板上的应用，如果都用 rpx 为单位，则可能会导致有些文字特别大，反而对用户造成不便。

**解决方案**
[如果你有解决方案，在这里清晰地阐述]
在 `remax.config.js` 的配置项里面增加一个 `transformPx2Rpx: true/false` 的配置项，默认是 true 以兼容老的代码。

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
就叫 `pxToRpx` 吧，默认是 `true`。

**Comment by Pochodaydayup** [comment]
不需要转换的使用大写的 PX 就可以了吧？

**Comment by Clarence-pan** [comment]
@yesmeck  已经提了 PR，求合入

**Comment by Clarence-pan** [comment]
@Pochodaydayup 大写的 PX 写法挺奇怪的，不符合直觉
