### ISSUE TITLE
[BUG] npm包weapp-navigation-bar在较新版本的remax上无法正常渲染 (应该不是这个包本身的问题)

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#382]
**bug 描述**
在1.4.1版本中可正常工作, 升级到1.5.0后失效, 不正常渲染, 但slot的内容渲染了

**复现步骤**
为方便复现, 可以直接使用复现代码中提供的仓库地址.
一共2个commit, 1.4.1的, 然后是升级到1.5.0的.
npm run dev, 可以看到组件并没有渲染.
reset到第一个commit, 然后dev, 即可看到正常渲染的组件.

**期望结果**
组件正常渲染

**复现代码**
[https://github.com/WhiteMinds/remax-bug-demo](https://github.com/WhiteMinds/remax-bug-demo)

**版本信息:**

- remax 版本: [1.5.0]
- 手机型号 [iPhone X]
- 小程序端 [微信小程序]
- 小程序版本[微信开发者工具]
- 开发环境 [mac OS]

**其他信息**
1.4.1:
![1.4.1](https://user-images.githubusercontent.com/9160743/69206408-8484af00-0b87-11ea-9c1a-1c68c781708b.png)
1.5.0:
![1.5.0](https://user-images.githubusercontent.com/9160743/69206416-88b0cc80-0b87-11ea-8e78-ec26b130d2b8.png)

**Comment by yesmeck** [comment]
Fixed in 1.5.1

**Comment by WhiteMinds** [comment]
@Pochodaydayup 
修复不太彻底, 在多页面时依旧会出现渲染不正常的情况.
已将复现代码push至 [](https://github.com/WhiteMinds/remax-bug-demo).
npm run dev, 只有启动的那一次编译可以正常渲染, 一旦修改代码保存触发热更新后, 就无法正常渲染了.

**Comment by WhiteMinds** [comment]
@Pochodaydayup
简单封装后再次渲染不正常
已将复现代码push至之前的仓库.
npm run dev后, 即可复现.

**Comment by WhiteMinds** [comment]
@yesmeck 方便看一下上面说的这个bug吗

**Comment by yesmeck** [comment]
@WhiteMinds 已经在看啦 https://github.com/remaxjs/remax/pull/390

**Comment by WhiteMinds** [comment]
@yesmeck 噢, 我看issue没有open以为没看到

**Comment by WhiteMinds** [comment]
@yesmeck 
我升级到1.6后编译出现了`Error: Target wechat is not supported yet.`
是我配置错误, 还是1.6 beta目前暂不支持微信?
如果不支持的话, 是否可以先release个1.5.3版本, 我想测下这个效果.

**Comment by yesmeck** [comment]
@WhiteMinds 试试把这个 `e` 打印出来看看

https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/index.ts#L26

**Comment by WhiteMinds** [comment]
> @WhiteMinds 试试把这个 `e` 打印出来看看
> 
> https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/index.ts#L26

```
/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax.macro/lib/macro.js:1
Error: Cannot find module 'babel-plugin-macros'
Require stack:
- /Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax.macro/lib/macro.js
- /Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax.macro/lib/index.js
- /Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax/cjs/propsAlias.js
- /Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/build/adapters/wechat/index.js
- /Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/build/index.js
- /Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/index.js
- /Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/bin/remax
    at Object.<anonymous> (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax.macro/lib/macro.js:10:29)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax.macro/lib/macro.js',
    '/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax.macro/lib/index.js',
    '/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax/cjs/propsAlias.js',
    '/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/build/adapters/wechat/index.js',
    '/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/build/index.js',
    '/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/index.js',
    '/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/bin/remax'
  ]
}
Error: Target wechat is not supported yet.
    at Object.exports.default (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/build/index.js:33:15)
    at Object.handler (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/index.js:14:71)
    at Object.runCommand (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/yargs/yargs.js:1078:30)
    at Object.parse (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/yargs/yargs.js:566:25)
    at Object.run (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/lib/index.js:29:10)
    at Object.<anonymous> (/Users/whitemind/git-repos/nutstore-assignment-assist/mini-program/node_modules/remax-cli/bin/remax:3:28)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
error Command failed with exit code 1.
```

**Comment by yesmeck** [comment]
@Darmody

**Comment by yesmeck** [comment]
@WhiteMinds 可以临时把这一行 https://github.com/remaxjs/remax/blob/master/packages/remax.macro/src/macro.ts#L3

改成 `import { createMacro } from '@remax/babel-plugin-macros';`

**Comment by WhiteMinds** [comment]
@yesmeck ok, 目前可编译了, 只是第三方组件还是会在一些情况下渲染失效, 我等会把复现代码抽出来

**Comment by WhiteMinds** [comment]
@Pochodaydayup 
在1.6.0 beta中还是渲染失效的, npm run dev就可以看到.
已将复现代码push至 https://github.com/WhiteMinds/remax-bug-demo.
(实际上没改动东西, text标签随手加的, 不影响)

**Comment by WhiteMinds** [comment]
刚刚代码少传了, 等我改改...

**Comment by WhiteMinds** [comment]
@Pochodaydayup 
1.6.0 beta跳转到其他页面后, 就会渲染失效.
复现代码force push到之前的仓库了, npm run dev, 然后点击Go foo就可以复现.

**Comment by yesmeck** [comment]
@WhiteMinds 试试 1.6.0-beta.2

**Comment by WhiteMinds** [comment]
@yesmeck 渲染看起来都是正常的, 就是出了报错, 和useEffect有关.
这似乎会导致一些第三方组件的功能不正常, 但我这里的demo就只是简单的抽离出会使它报错的代码, 没有做具体的场景复现, 那样比较麻烦.
复现代码 [https://github.com/WhiteMinds/remax-bug-demo](https://github.com/WhiteMinds/remax-bug-demo)

**Comment by yesmeck** [comment]
@WhiteMinds 看起来是另外一个问题，我看看

**Comment by WhiteMinds** [comment]
@yesmeck  需要新建一个issue, 或者提供更详细的复现代码吗?

**Comment by yesmeck** [comment]
@WhiteMinds 我这边重现了

**Comment by yesmeck** [comment]
@WhiteMinds issue 我建了 https://github.com/remaxjs/remax/issues/423
