### ISSUE TITLE
[BUG] 1.5.0版本编译特别慢

### ISSUE THREAD

**Issue by wuhuanda** [remaxjs/remax#385]
**bug 描述**
升级到1.5.0版本后编译特别慢，可能原因是`remax-cli`内`nativeComponent`的`generateBundle`([传送门](https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/plugins/nativeComponents/index.ts#L99-L146))方法导致的。测试了一下，该方法用时46s左右。

**复现步骤**

**期望结果**
降低编译时间

**复现代码**
[nativeComponent](https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/plugins/nativeComponents/index.ts#L99-L146)

**版本信息:**

- remax 版本: 1.5.0
- 小程序端 微信小程序
- 开发环境 Windows

**其他信息**
v1.4.5 耗时 23秒
v1.5.0 耗时 1分13秒

工程页面25个

v1.5.0内`nativeComponent`的`generateBundle`方法耗时截图：
![image](https://user-images.githubusercontent.com/32833804/69220976-24a2fe00-0bb1-11ea-8e66-e0cc8751c65a.png)

**Comment by Pochodaydayup** [comment]
@superman0159 你的项目文件数量很多吗？文件数量很多的话可能会很慢

**Comment by superman0159** [comment]
> @superman0159 你的项目文件数量很多吗？文件数量很多的话可能会很慢

25个页面，不算很多吧
