### ISSUE TITLE
注册基础组件问题

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#391]
1. 无法在 npm 包里去注册组件，因为现在 babel 不会处理 node_modules。
2. 需要在注册组件的时候支持设置别名，props 里支持 tuple，第二个元素为别名。

```javascript
import { createHostComponent } from 'remax/macro';

const Video = createHostComponent('video', [
  'src',
  ['show-mute-btn', 'showMuteBtn'],
]);

export default Video;

```

**Comment by Darmody** [comment]
1 要怎么处理

**Comment by yesmeck** [comment]
babel 处理下 node_modules

**Comment by yesmeck** [comment]
我记得现在 babel 会处理 node_modules 的

**Comment by Darmody** [comment]
https://github.com/kentcdodds/babel-plugin-macros/issues/87

**Comment by Darmody** [comment]
https://github.com/kentcdodds/babel-plugin-macros/pull/138 fix 了 1  的问题，我们可以等他们发布后切换回去了
