### ISSUE TITLE
[BUG] 动态props Input, Android焦点切换有问题

### ISSUE THREAD

**Issue by coppyC** [remaxjs/remax#395]
**bug 描述**
在两个input组件之间切换焦点，有问题，焦点会在两个INput之间来回跳动（只在安卓手机上有）

**复现步骤**
只要有动态 {...props} 给 Input 组件，其它Input的组件全部会
```jsx
import React, { useState } from 'react'
import { View, Input } from 'remax/wechat'

export default () => {
  const [a, setA] = useState('')
  const [b, setB] = useState('')
  const [c, setC] = useState('')
  return (
    <View style={{ margin: '32px' }}>
      <Input placeholder="a" value={a} onInput={e => setA(e.detail.value)} />
      <Input placeholder="b" value={b} onInput={e => setB(e.detail.value)} />
      <Input placeholder="c" value={c} onInput={e => setC(e.detail.value)} />
    </View>
  )
}

export function CustomInput(props: any) {
  return <Input {...props}  />
}
```
这段代码没有引用CustomInput，只是定义而已
把CustomInput删除，而不会有bug

后来，我发现把给每个 Input 组件添加 focus 自动聚焦属性，也是相同的bug表现

**推测:** 动态props，remax 定义模版的时候，因为不知道可能有什么属性，预定义了 focus,autoFocus等的属性，然后所有 Input 组件都成这样了

因为我发现没有props和有props的模版不一样

**版本信息:**

- remax 版本: 1.5.2
- 手机型号 mate 20X
- 小程序端 2.8.0

**Comment by Darmody** [comment]
这个问题其实在 https://github.com/remaxjs/remax/issues/243 有提到。

由于微信小程序只要写上了 `focus` 属性，不管他有没有值，都一定会生效的。所以动态传值的方式就会让所有 `Input` 都带上 focus 属性。

为了解决这个问题，Remax 在内部预处理了 focus 属性。

但是这里引出了另一个问题。Remax 会自动合并 setData 操作，所以 两个 Input 如果都有 focus 属性但是没有赋值时，就会依赖 Remax 内置处理 focus 的逻辑，这个时候 setData 被合并了，focus 的处理就会出现像你说的闪跳的现象

**Comment by yesmeck** [comment]
不用 `{...props}` 是不是就能绕过？

**Comment by Darmody** [comment]
我们要想想怎么处理。如果你不需要处理 focus 逻辑的话，临时的解决方案是不用动态赋值，在 `CustomInput` 里面把属性写全。

**Comment by Darmody** [comment]
> 不用 `{...props}` 是不是就能绕过？

是的

**Comment by coppyC** [comment]
如果 有 focus ，默认给个 false 的值呢

**Comment by Darmody** [comment]
> 如果 有 focus ，默认给个 false 的值呢

你可以试试。我记得好像这样就不能被 focus 上了。。

**Comment by WhiteMinds** [comment]
@Darmody @yesmeck hi, 这个issue目前进展如何, 这个bug比较影响用户体验, 大概什么时候可以修复

**Comment by WhiteMinds** [comment]
> > 不用 `{...props}` 是不是就能绕过？
> 
> 是的

我这里是未使用扩散属性的, 直接使用的2个input, 但是也会出现跳动的情况

**Comment by coppyC** [comment]
@WhiteMinds 是不是有使用 focus 过属性。

**Comment by WhiteMinds** [comment]
> @WhiteMinds 是不是有使用过 focus 属性。

仔细看了下, 是我搞错了, 我以为是2个input中任意一个使用了扩散属性时会出bug, 原来是指全局任意一个input使用了扩散属性就会导致bug...

我现在把使用了扩散属性的input移除了, 确实就不会触发这个问题了.

**Comment by Darmody** [comment]
@coppyC @WhiteMinds 

```bash
yarn add https://pkg.csb.dev/remaxjs/remax/commit/6a0fe40d/remax
yarn add https://pkg.csb.dev/remaxjs/remax/commit/6a0fe40d/remax-cli
```

可以试试这个测试包有没有解决上面的问题吗
