### ISSUE TITLE
[问题] 为什么input (wechat)组件不是受控的?

### ISSUE THREAD

**Issue by jueinin** [remaxjs/remax#396]
**问题描述**
感觉有点不那么react  哈哈

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
这是小程序的行为，和 React 无关

**Comment by yesmeck** [comment]
@Darmody 我们不能改掉？

**Comment by Darmody** [comment]
https://developers.weixin.qq.com/miniprogram/dev/component/input.html

小程序 input 的 value 只是初始值。

**Comment by yesmeck** [comment]
我们不能封装下吗？

**Comment by Darmody** [comment]
<img width="757" alt="屏幕快照 2019-11-22 11 41 23" src="https://user-images.githubusercontent.com/6788752/69396400-0eb24c00-0d1d-11ea-806a-9dec89085893.png">

小程序的 onInput 可以通过返回值控制
