### ISSUE TITLE
[BUG] input的onInput事件不会被触发

### ISSUE THREAD

**Issue by jueinin** [remaxjs/remax#397]
**bug 描述**
input组件的onInput事件,在某些条件下不会被触发, 有可能是它导致了, 在我这边vant组件的bindchange bindfocus之类的事件都无法触发.

**复现步骤**
新项目是可以正确触发的, 目前未找到稳定的复现步骤,  写了个小[demo](https://github.com/jueinin/remax-lib)
使用微信开发者工具 进入 `pages/test/test`, 屏幕左上角有个空白输入框, 随意输入, 并不会触发onInput事件

**期望结果**
正确触发,并且vant组件的事件也能正确触发(bindchange, bindsearch)

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: 1.5.2
- 手机型号 [e.g. iPhone X]
- 小程序端 wechat
- 小程序版本 2.9.3
- 开发环境 win10

**其他信息**
![1](https://user-images.githubusercontent.com/22928234/69395684-ddd11780-0d1a-11ea-952b-b6ce672f004b.png)
![2](https://user-images.githubusercontent.com/22928234/69395689-e3c6f880-0d1a-11ea-8f12-ae1231ea3e12.png)

**Comment by WhiteMinds** [comment]
这是微信开发者工具的bug, 把基础库切换到2.9.2即可
