### ISSUE TITLE
[需求]直接支持 react-redux/mobx-react

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#405]
目前是 fork 了 react-redux/mobx-react，这样做的问题是需要跟进上游更新，另外是不能直接用 `@types/react-redux`

**解决方案**

现在 fork 主要是因为这两个库依赖了 `react-dom`，`export { unstable_batchedUpdates } from 'react-dom'`，可以直接在 remax-cli 里把  `react-dom` alias 成 `remax`。

**Comment by Darmody** [comment]
可以的
