### ISSUE TITLE
[BUG]Windows 下测试报错

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#407]
https://github.com/remaxjs/remax/pull/406/checks?check_run_id=318804312

看 test 的日志，remax-cli 有报错。

<details>
  <summary>错误信息</summary>
<pre>
remax-cli: PASS src/__tests__/build.test.ts (52.679s)
remax-cli:   ● Console
remax-cli:     console.error src/build/plugins/postcssUrl.ts:715
remax-cli:       { [Error: EBUSY: resource busy or locked, copyfile 'D:\a\remax\remax\packages\remax-cli\src\__tests__\fixtures\assets\src\assets\images\cat.png' -> 'D:\a\remax\remax\packages\remax-cli\src\__tests__\fixtures\assets\dist\assets\images\cat.png']
remax-cli:         errno: -4082,
remax-cli:         code: 'EBUSY',
remax-cli:         syscall: 'copyfile',
remax-cli:         path:
remax-cli:          'D:\\a\\remax\\remax\\packages\\remax-cli\\src\\__tests__\\fixtures\\assets\\src\\assets\\images\\cat.png',
remax-cli:         dest:
remax-cli:          'D:\\a\\remax\\remax\\packages\\remax-cli\\src\\__tests__\\fixtures\\assets\\dist\\assets\\images\\cat.png' }
remax-cli:     console.error src/build/plugins/postcssUrl.ts:715
remax-cli:       { [Error: EBUSY: resource busy or locked, copyfile 'D:\a\remax\remax\packages\remax-cli\src\__tests__\fixtures\assets\src\assets\images\cat.png' -> 'D:\a\remax\remax\packages\remax-cli\src\__tests__\fixtures\assets\dist\assets\images\cat.png']
remax-cli:         errno: -4082,
remax-cli:         code: 'EBUSY',
remax-cli:         syscall: 'copyfile',
remax-cli:         path:
remax-cli:          'D:\\a\\remax\\remax\\packages\\remax-cli\\src\\__tests__\\fixtures\\assets\\src\\assets\\images\\cat.png',
remax-cli:         dest:
remax-cli:          'D:\\a\\remax\\remax\\packages\\remax-cli\\src\\__tests__\\fixtures\\assets\\dist\\assets\\images\\cat.png' }
<pre>
</details>

**Comment by Darmody** [comment]
应该是多处引用同一个文件，然后代码是异步流程导致的

**Comment by Darmody** [comment]
https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/plugins/postcssUrl.ts#L19-L29
