### ISSUE TITLE
[需求]提供 compress 配置项

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#416]
**需求描述**
项目变大以后，开发环境不 uglify，生成的文件有可能会很大，也会需要 uglify。

**解决方案**
remax.config.js 增加 uglify 配置项，允许开发者手动开启 uglify。

**其他信息**

**Comment by yesmeck** [comment]
生成的文件是指那些文件？

**Comment by Darmody** [comment]
dist 目录

**Comment by Darmody** [comment]
需要 uglify 的主要是 `wxml`

**Comment by yesmeck** [comment]
对去掉 wxml 里的几个空格就能加快编译速度表示怀疑

**Comment by Darmody** [comment]
> 对去掉 wxml 里的几个空格就能加快编译速度表示怀疑

是做 uglify，不是提速

**Comment by yesmeck** [comment]
那为什么不用 `NODE_ENV=production`

**Comment by Darmody** [comment]
> 那为什么不用 `NODE_ENV=production`

因为毕竟不是生产环境，语义不对。
开发者很可能有根据 `NODE_ENV=production` 区分 生产，测试`api` 等行为。

**Comment by Darmody** [comment]
有遇到这样的问题，开发环境打包过大，无法生产预览

**Comment by Darmody** [comment]
由于我们只对 wxml/axml 做压缩，不是完整的 uglify。所以配置名称改成 compress
