### ISSUE TITLE
[RFC] 统一 adapter 代码

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#421]
将 remax-cli 中各平台的 adapter 移到 remax 中，统一 adapter 代码。

也为后续平台切分做准备。

**Comment by yesmeck** [comment]
方案呢

**Comment by Darmody** [comment]
要做的事情比较少，简单想了下：

1. 把 remax-cli 下的 adapter 直接移植到 remax 下对应 adapter 的 compilerFactory 模块中。
2. remax-cli 根据 target 自动引入 `remax/cjs/adapters/${target}/compilerFactory`， `compilerFactory` 模块在 remax 中不导出。

**Comment by yesmeck** [comment]
不如直接考虑下插件机制，remax 跟 remax-cli 做到平台无关，平台特性通过插件引入

**Comment by Darmody** [comment]
有道理

**Comment by Darmody** [comment]
不过先移出来，再做插件应该会更顺利一些
