### ISSUE TITLE
[BUG] scheduler 升级后使用 useEffect 报错

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#423]
重现：https://github.com/remaxjs/remax/issues/382#issuecomment-559030049
commit: https://github.com/remaxjs/remax/commit/78de5c9f160e39299c8e4520bf7ec02b4fd3986c

**Comment by WhiteMinds** [comment]
hi, 这个issue目前进展如何?

**Comment by yesmeck** [comment]
@WhiteMinds 我已经把  Scheduler 降级了，不会对你有影响

**Comment by Darmody** [comment]
close via #429
