### ISSUE TITLE
[问题] 在remax中, scss的@import是否支持使用别名?

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#431]
**问题描述**
如最下方图片中的示例, `@import "../../module";`是可以正常工作的.
但如果换成`@import "@/module";`则会报错:
`🚨 [postcss]: File to import not found or unreadable: @/module.`

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
![Lark20191202091929](https://user-images.githubusercontent.com/9160743/69924172-e4167f00-14e4-11ea-8fb0-3bee3aaab180.png)

**Comment by Darmody** [comment]
https://github.com/egoist/rollup-plugin-postcss#imports

目前只支持 `~` 别名到 `node_modules` 路径

**Comment by upupming** [comment]
可以在 use 中使用 alias 插件的，我用的是 less，可以这样使用：

```js
import LessPluginAliases from 'less-plugin-aliases';

/// ...
plugins: [
    // ...
    postcss({
      extract: false,
      modules: false,
      use: {
        less: {
          plugins: [
            new LessPluginAliases({
              prefix: '~',
              aliases: {
                '@': 'src',
              },
            }),
          ],
        },
      },
    }),
// ...
```
