### ISSUE TITLE
[BUG]children 顺序改变之后出现重复渲染

### ISSUE THREAD

**Issue by yinhangfeng** [remaxjs/remax#438]
**bug 描述**
children 顺序改变之后出现重复渲染，微信小程序开发工具提示 key 重复 `Do not set same key \"28\" in wx:key.`

**复现步骤**
data 从 [1, 2, 3] 改为 [2, 1, 3]

**期望结果**
期望结果为 2 1 3，但实际为 1 2 1 3

**复现代码**
```javascript
class BUG extends React.Component {
  state = {
    data: [1, 2, 3],
  };

  handleClick = () => {
    this.setState({
      data: [2, 1, 3],
    });
  };

  render() {
    return (
      <View>
        <View>
          {this.state.data.map(v => (
            <View key={v}>{v}</View>
          ))}
        </View>
        <Button onClick={this.handleClick}>test</Button>
      </View>
    );
  }
}
```

**版本信息:**

- remax 版本: 1.6.0
- 手机型号
- 小程序端 微信小程序
- 小程序版本
- 开发环境 mac OS

**其他信息**
[hostConfig](https://github.com/remaxjs/remax/blob/master/packages/remax/src/hostConfig.ts) 中 `appendChild` `insertBefore` 需要考虑 child 已经在 parent 中的情况

**Comment by Darmody** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Node/insertBefore

**Comment by Darmody** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Node/appendChild

**Comment by Darmody** [comment]
参考这两个 API，确实需要对已存在的 node 做移动处理，而非创建

**Comment by yinhangfeng** [comment]
1.7.0 还是有问题

**Comment by Darmody** [comment]
> 1.7.0 还是有问题

是一样的错误吗

**Comment by yinhangfeng** [comment]
> > 1.7.0 还是有问题
> 
> 是一样的错误吗

是的

**Comment by yinhangfeng** [comment]
估计是[helper.js](https://github.com/remaxjs/remax/blob/master/packages/remax-cli/templates/helper.js)的问题

**Comment by Darmody** [comment]
yarn add https://pkg.csb.dev/remaxjs/remax/commit/50681c6e/remax https://pkg.csb.dev/remaxjs/remax/commit/50681c6e/remax-cli

@yinhangfeng  试试这个行不行

**Comment by yinhangfeng** [comment]
> yarn add https://pkg.csb.dev/remaxjs/remax/commit/50681c6e/remax https://pkg.csb.dev/remaxjs/remax/commit/50681c6e/remax-cli
> 
> @yinhangfeng 试试这个行不行

可以了

**Comment by Darmody** [comment]
close via #441
