### ISSUE TITLE
[BUG]使用 redux 时 Class Component 的小程序生命周期函数不能触发

### ISSUE THREAD

**Issue by danielzddd** [remaxjs/remax#446]
**bug 描述**
使用 redux 时 Class Component 的小程序生命周期函数不能触发

**期望结果**
期望在使用 redux 时 Class 组件下的小程序生命周期可正常执行

**版本信息:**

- remax 版本: [e.g. 1.7.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**Comment by yesmeck** [comment]
是因为生命周期的出来依赖组件的 `ref`，但是组件被 `connect` 包裹后就拿不到原来的 `ref` 了。建议用 hook 去注册生命周期的回调。

**Comment by danielzddd** [comment]
> 是因为生命周期的调用依赖组件的 `ref`，但是组件被 `connect` 包裹后就拿不到原来的 `ref` 了。建议用 hook 去注册生命周期的回调。

已提交 PR #449 

组件被 connect 包裹后，原始组件被挂载到了 Connect.WrappedComponent 属性上，判断 WrappedComponent 是否是 Class Component，并且配合 connect 参数 options.forwardRef = true 即可解决

`
export default connect(
  mapStateToProps,
  mapDispatchToProps,
  null,
  {
    forwardRef: true
  }
)(IndexPage);
`
