### ISSUE TITLE
[BUG] regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#451]
**bug 描述**
在使用`react-hook-form`这个包时出现`regeneratorRuntime is not defined`

**复现步骤**
运行复现代码, 点击handleSubmit按钮即可复现

**期望结果**
正确的提供runtime

**复现代码**
[https://github.com/WhiteMinds/remax-bug-demo](https://github.com/WhiteMinds/remax-bug-demo)

**版本信息:**

- remax 版本: [e.g. 1.7.2]
- 手机型号 [e.g. 微信开发者工具]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.6.6]
- 开发环境 [e.g. mac OS]

**其他信息**
![image](https://user-images.githubusercontent.com/9160743/70198840-fb56a600-174a-11ea-8b11-52f021346a46.png)

**Comment by WhiteMinds** [comment]
https://www.npmjs.com/package/babel-plugin-auto-import
这个可能会有帮助?

**Comment by Darmody** [comment]
@WhiteMinds 你可以加上这个插件试试

**Comment by WhiteMinds** [comment]
配置了这个插件后可以了, 这是我的配置:
```
// babel.config.js
module.exports = {
    "plugins": [
        [
            "auto-import",
            {
                "declarations": [
                    { "default": "regeneratorRuntime", "path": "regenerator-runtime" }
                ]
            }
        ]
    ]
}
```

**Comment by Darmody** [comment]
```bash
yarn add https://pkg.csb.dev/remaxjs/remax/commit/c1dbe6aa/remax https://pkg.csb.dev/remaxjs/remax/commit/c1dbe6aa/remax-cli
```

@WhiteMinds  试试这个测试包，我们内置了这个逻辑，不需要引入这个插件了

**Comment by WhiteMinds** [comment]
@Darmody 测试了, 现在可以正确的提供runtime了
