### ISSUE TITLE
支持 ScrollView 滚动到特定位置

### ISSUE THREAD

**Issue by yinhangfeng** [remaxjs/remax#459]
**bug 描述**
ScrollView 设置 scrollTop 之后任何地方 setState 都会引起所有 ScrollView scrollTop 重置(未设置 scrollTop 的 ScrollView 会滚动到 0，设置了的会滚动到设置的值)

**复现步骤**
给 ScrollView 设置 scrollTop 属性，任何地方 setState 触发小程序模板重新渲染

**期望结果**
**复现代码**
```javascript
<ScrollView
  scrollTop={this.state.scrollTop}
>
</ScrollView>
```

**版本信息:**

- remax 版本: 1.8.0
- 手机型号
- 小程序端 微信小程序
- 小程序版本
- 开发环境 mac OS

**其他信息**
测试原生微信小程序之后发现，scroll-view scroll-top 的表现就是这样的 setData 之后给跟原来相同的值也会引起滚动，除非该值放在 page data 上且 setData 时不要给值。其它类似原理的属性可能都有问题，比如 input 的 focus

**Comment by Darmody** [comment]
#243 我们还在尝试解决

**Comment by Darmody** [comment]
根据你的描述，这应该是和原生表现一致的。因为你给 scrollTop 设置以后，ScrollView 就受控了。

**Comment by yinhangfeng** [comment]
其实我的问题包含几个子问题
1. 由于目前模板的实现方式，一个 ScrollView 设置了 scrollTop 属性会导致所有 ScrollView 都有 scrollTop 也就是都"受控"了
2. 受控的表现与小程序不同，不更新 scrollTop 的值在重新渲染时也会导致滚动
3. 如果 scrollTop 是“受控”性质的话，这个属性就没什么用了，该如何在需要的时候让 ScrollView 滚动特定位置呢

其实小程序中 scrollTop 的概念介于 React 受控属性(value)和非受控属性(defaultValue 传入的值改变才更新)之间
比如下面代码，假设初始时 scrollTop 设为 10，然后用户手动滚动到了 20 的位置，之后再执行对应的 test
```javascript
<scroll-view scroll-top={{scrollTop}} />

{
  data: {
    scrollTop: 10,
  },

  // setData 之后 scrollTop 20 -> 15
  test1() {
    this.setData({
      scrollTop: 15,
    });
  },

  // setData 之后 虽然 scrollTop 与原来的值相同但还是会滚动 scrollTop 20 -> 10
  test2() {
    this.setData({
      scrollTop: 10,
    });
  },

  // 不会引起滚动
  test3() {
    this.setData({
      scrollTop: undefined,
    });
  },

  // 更新其他属性，不会引起滚动
  test4() {
    this.setData({
      xxx: 111,
    });
  },
}

```
因为小程序不能操作 dom，没有类似 react-native 获取 scroll-view 的 ref 然后调用 ref.scrollTo()  的概念，就产生了一类有这种表现的属性。但这种表现的属性需要字段直接位于 this.data 上。如果把上面例子中的 scrollTop 放入一个对象中比如 this.data.foo.bar.scrollTop 就不行了，这就是我上面的问题 2 出现的原因

**Comment by Darmody** [comment]
嗯，说实话微信小程序这种设计真的看不懂。。。

我们考虑看看能不能提供  `scroll` 方法。

**Comment by Darmody** [comment]
@yinhangfeng  

```bash
yarn add https://pkg.csb.dev/remaxjs/remax/commit/d75ff5e4/remax 
yarn add https://pkg.csb.dev/remaxjs/remax/commit/d75ff5e4/remax-cli
```

可以试试看这两个测试包有没有解决你的问题吗？
