### ISSUE TITLE
[问题] 在remax中如何使用微信小程序的Editor组件

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#464]
**问题描述**

我看官方文档, 使用Editor似乎需要初始化它的context, 这需要执行
`<editor bindready="onEditorReady" />`
```
onEditorReady() {
    const that = this
    wx.createSelectorQuery().select('#editor').context(function (res) {
        that.editorCtx = res.context
    }).exec()
}
```
目前remax还未支持微信小程序的ref, 如何方便的实现这些操作?
我似乎只能用native混合开发来做.

**示例代码**

组件文档 https://developers.weixin.qq.com/miniprogram/dev/component/editor.html
官方提供的代码片段 https://developers.weixin.qq.com/s/W7uZ3EmU7jbl
官方的进阶例子 https://github.com/wechat-miniprogram/miniprogram-demo/blob/master/miniprogram/page/component/pages/editor/editor.wxml

**其他信息**

期望效果
![Lark20191209151901](https://user-images.githubusercontent.com/9160743/70415296-43e9c880-1a97-11ea-9346-0f624c386cca.png)

**Comment by WhiteMinds** [comment]
@yesmeck 请问微信小程序的ref支持有在计划中吗, 如果有的话, 实现时间大概是什么时候?

**Comment by yesmeck** [comment]
@WhiteMinds 微信小程序 ref 有文档么？

**Comment by yesmeck** [comment]
`wx.createSelectorQuery().select('#editor')` 这种跟 React 的 `ref` 不是一回事。

**Comment by WhiteMinds** [comment]
@yesmeck 呃, 我是指如果有ref的话, 就可以在remax中, `editorRef.context(...)`这样操作了

**Comment by Darmody** [comment]
@yesmeck 也许我们可以把 `wx.createSelectorQuery().select('#editor')` 塞到 ref 中？

**Comment by yesmeck** [comment]
不，不是一回事，不能搞混

**Comment by WhiteMinds** [comment]
只能选择用这种方法来做了...
```typescript
// components/Editor/index.tsx
import { Editor as RMEditor, createSelectorQuery } from 'remax/wechat'
import React, { useEffect, useState } from 'react'
import { createGuidGenerator } from '@/utils/common'

const guid = createGuidGenerator()

interface EditorProps {
  onInit: (ctx: WechatMiniprogram.EditorContext) => void
}

export const Editor = (props: EditorProps) => {
  const [uniqueId] = useState(`editor-${guid()}`)

  useEffect(() => {
    createSelectorQuery().select('#' + uniqueId).context(res => {
      props.onInit(res.context as WechatMiniprogram.EditorContext)
    }).exec()
  }, [])

  return (
    <RMEditor id={uniqueId} />
  )
}
```

**Comment by yesmeck** [comment]
@WhiteMinds 对，就应该这样
