### ISSUE TITLE
多端代码统一的思考

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#47]
**长话短说**

由于国内小程序众多，一套代码在多端运行的需求高涨，然而如果在**lib 层面去做多端抹平**，可以看到会有这些**问题**：

* 每个端对 api，组件的定义不同，lib 抹平后，如何让开发者更**灵活地控制**？
* 如果使用 typescript 编码，**只能看到一份 type 定义**，例如 Taro 看到的就是微信的 type 定义
* 不同的小程序，特性不同，平台不同，需求不同（不论是整体还是细节），**一套代码运行在多端本身是不是个伪命题？** 

我的建议：
* `remax` 划分成 `remax/alipay` `remax/wechat` ...
* 每个平台都完成各自的组件和 api
* 毕竟大多数人只有一个小程序端的开发需求，可以直接对应平台完成工作
* 有跨端开发需求的，通过**脚手架**引导开发者对不同平台的差异，**根据具体业务**做抹平处理。如：

```jsx
// components/Button.js
import { Platform } from 'remax';
import { Button as AlipayButton } from 'remax/alipay';
import { Button as WechatButton } from 'remax/wechat';

export default function Button(props) {
  if (Platform.isWechat)  return <WechatButton {...props} />;
  if (Platform.isAlipay)  return <AlipaytButton {...props} />;
}
```

`api` 用相似的逻辑，根据**具体业务**做处理

**Comment by yesmeck** [comment]
可以的就这么干
