### ISSUE TITLE
[BUG]导入全局模块(Polyfill)无效

### ISSUE THREAD

**Issue by awaw00** [remaxjs/remax#475]
使用`reflect-metadata`这个包做尝试，这个包会给Reflect这个对象添加`getMetadata`、`defineMetadata`等方法。

在Remax项目中，`import 'reflect-metadata'`后，`'getMetadata' in Reflect`为`false`：
![image](https://user-images.githubusercontent.com/16967083/70600243-34e74f80-1c2a-11ea-9765-64da097a0846.png)

相对的，在原生小程序项目中，做同样的check，结果为`true`：
![image](https://user-images.githubusercontent.com/16967083/70600224-2731ca00-1c2a-11ea-9f43-a869d4d4a9d6.png)

**Comment by Darmody** [comment]
这个库实际上是把 Reflect 设置到 global 中去的，应该在小程序中不可用才对
