### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#48]

**Comment by Darmody** [comment]
![image](https://user-images.githubusercontent.com/6788752/62465892-99008f80-b7c2-11e9-8f96-b47642caf564.png)

**Comment by yesmeck** [comment]
有没有源文件？

**Comment by Darmody** [comment]
把 alipay p 掉

**Comment by Darmody** [comment]
> 有没有源文件？

没有。。

**Comment by yesmeck** [comment]
那还不如自己 Sketch 画一下。

**Comment by Darmody** [comment]
@yesmeck 给你灵感了，剩下的靠你了 😈

**Comment by Darmody** [comment]
结合一点react的元素

**Comment by yesmeck** [comment]
![xx](https://user-images.githubusercontent.com/465125/62647823-00197200-b984-11e9-808b-16eecdae063f.png)

**Comment by yesmeck** [comment]
![xx](https://user-images.githubusercontent.com/465125/62647945-4d95df00-b984-11e9-879b-ad22c2e417c1.png)

**Comment by Darmody** [comment]
怎么那么像redux或者什么状态管理的东西

**Comment by yesmeck** [comment]
![logo](https://user-images.githubusercontent.com/465125/62673857-907ea380-b9d2-11e9-9d5c-0f0bfd4c3a33.png)
