### ISSUE TITLE
[需求]能否按分包模块打包样式资源

### ISSUE THREAD

**Issue by wangkuan** [remaxjs/remax#484]
**需求描述**
因为项目情况的限制，很多界面上使用的图像资源无法使用CDN资源，只能够通过 base64 的方式打包进 css 中。
然后发现 app.wxss 的体积达到1.7MB 了，导致微信小程序主包大小超过2048KB，无法上传。
即便是通过分包处理依然无效，因为分包里用到的样式还是会被 remax 打包进 app.wxss 中，而 app.wxss 属于主包的一部分。

**解决方案**
需要考虑一下分包的样式如何同分包一样分离打包，而不是都集中在app.wxss

**Comment by Darmody** [comment]
duplicated of #130
