### ISSUE TITLE
[问题]如何在remax上使用Jest或者Mocha+Chai做单元测试？

### ISSUE THREAD

**Issue by watsonhaw5566** [remaxjs/remax#485]
**问题描述**
开发大大们好，我想问一下如何在remax中做项目或者组件的单元测试？
我看了一下你们的npmjs上面有几个Jest的测试库，看了一下文档还不知道怎么使用。
我看了一下实例的examples的json好像都没有。所以前来问问，有劳你们抽空回复一下，谢谢你们。

https://www.npmjs.com/package/@remax/jest-environment-puppeteer
https://www.npmjs.com/search?q=%40remax%2Fjest
**示例代码**
[如果有必要，展示代码，线上示例，或仓库]
**其他信息**
[如截图等其他信息可以贴在这里]

![image](https://user-images.githubusercontent.com/4210367/70843026-53398f00-1e66-11ea-8e7d-59fd8b83d483.png)

**Comment by Darmody** [comment]
https://github.com/remaxjs/remax/blob/master/packages/remax/src/__tests__/wechat/components/Input.test.tsx

可以参考我们的测试

**Comment by watsonhaw5566** [comment]
@Darmody 感谢，我去看看你们的实例。
