### ISSUE TITLE
小程序引入 @vant/weapp/xx 如何使用onclick事件

### ISSUE THREAD

**Issue by jimmyann** [remaxjs/remax#495]
**问题描述**

我在组件引入一个vant的button 但是在做onclick事件的时候无反应

**示例代码**

import * as React from 'react';
import { View, Text, Image } from 'remax/wechat';
import VanButton from "@vant/weapp/dist/button/index"
import "./index.scss";

export default () => {
    const handleBarClick = () => {
        console.log('aa')
    }
    return (
        <View>
            <VanButton onClick={handleBarClick} type="default">默认按钮</VanButton>
           </View >
    );
};

**Comment by yesmeck** [comment]
请参考 vant 的文档，点击事件是 `bindclick`。Remax 不会对小程序组件的属性做转换，参考 https://remaxjs.org/guide/custom-component#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
