### ISSUE TITLE
[BUG] one `catchEvent` cause all `onEvent` failed

### ISSUE THREAD

**Issue by malash** [remaxjs/remax#503]
**bug 描述**
After using one `catchEvent` on `View` all `onEvent` won't be fired at all. 

**复现步骤**

1. Build and run the example code.
2. Click the `click me` and `click me 2`.
3. `See console.log` output

**期望结果**

1. When click `click me` it should output 
```
should emit onTap in children
should emit catchTap
```

But in fact only `should emit catchTap` logged.

2. When click `click me 2` it should output `should emit onTap 2`. But in fact, nothing happened.

**复现代码**
```tsx
import * as React from "react";
import { View } from "remax/wechat";
import styles from "./index.module.css";

export default () => {
  return (
    <View className={styles.app}>
      <View onTap={() => console.log("should not emit onTap")}>
        <View catchTap={() => console.log("should emit catchTap")}>
          <View onTap={() => console.log("should emit onTap in children")}>
            click me
          </View>
        </View>
      </View>
      <View onTap={() => console.log("should emit onTap 2")}>click me 2</View>
    </View>
  );
};

```

**版本信息:**

- remax 版本: 1.10.4
- 手机型号 WeChat Dev Tool simulator
- 小程序端 WeChat
- 小程序版本2.9.4
- 开发环境 mac OS

**其他信息**
None

cc @byunicorn

**Comment by Darmody** [comment]
https://remaxjs.org/guide/event

建议使用 `stopPropagation`

**Comment by malash** [comment]
So if `catchEvent` doesn't work, do you have any plan to remove it ?

**Comment by Darmody** [comment]
> So if `catchEvent` doesn't work, do you have any plan to remove it ?

我们现在有废弃警告，将来适时的时候是会废弃的
