### ISSUE TITLE
[BUG] 某些情况下的useEffect生命周期不正确?

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#505]
**bug 描述**
我不太确定是否是由remax引起的bug, 我将复现代码抽离出来了.

**复现步骤**
clone repository, checkout到demo1
`yarn && yarn build`
点击任意一个next按钮进入到Step2组件.
此时点击第一个按钮会有bug, 无法获取到bounding (输出为`res null`, 应该是由于此时指定的组件并没有加载引起的? 因为如果做成setTimout(() => getBounding(...), 0), 它就能获取成功了)
如果点击第二个按钮则是能正常的获取到.

**期望结果**
表现一致

**复现代码**
https://github.com/WhiteMinds/remax-bug-demo/tree/demo1

**版本信息:**

- remax 版本: [1.10.4]
- 手机型号 [开发者工具]
- 小程序端 [微信小程序]
- 小程序版本[2.7.1]
- 开发环境 [mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
需要获取挂载节点的话，需要在 useReady 中执行。useEffect 是虚拟 dom 挂载完成，实际的 小程序节点不一定渲染了

**Comment by WhiteMinds** [comment]
@Darmody 我觉得不是这个原因, useReady是page的生命周期, 也没法在这里使用.
而且这里可以固定复现出一个按钮可行, 一个按钮不可行, 说明确实是这2个next的代码影响到了挂载
要不你再看看

**Comment by Darmody** [comment]
> @Darmody 我觉得不是这个原因, useReady是page的生命周期, 也没法在这里使用.
> 而且这里可以固定复现出一个按钮可行, 一个按钮不可行, 说明确实是这2个next的代码影响到了挂载�
> 要不你再看看

噢，setState 之后的获取挂载节点，目前只能先通过 setTimeout 解决。第一个有 bug 是因为第一个执行了更多的 setState 操作，所以节点挂载更慢了。

相关 issue #310

**Comment by Darmody** [comment]
我们目前在设计如何解决这个问题： https://github.com/remaxjs/rfcs/pull/4
