### ISSUE TITLE
VanNotify 提示 未找到 van-notify 节点，请确认 selector 及 context 是否正确

### ISSUE THREAD

**Issue by jimmyann** [remaxjs/remax#506]
**问题描述**
我在remax 使用了van-notify组件  尝试多个方法 始终提示错误 ‘van-notify 节点，请确认 selector 及 context 是否正确’

**示例代码**
import * as React from 'react';
import {View, Text, Image, Input, login} from 'remax/wechat';
import VanNotify from "@vant/weapp/dist/notify/index"
import Notify from "@vant/weapp/dist/notify/notify"
import {useReady} from "remax";

export default () => {
 useReady(() => {
        setTimeout(() => {
            Notify({type: 'danger', message: 'aaa'})
        }, 3000)
})
 return (
            <View className='header_bg'>
                <VanNotify id="van-notify"/>
        </View>
    )
}

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Pochodaydayup** [comment]
@jimmyann 有在 jsx 里使用 VanNotify 组件吗

**Comment by Darmody** [comment]
v1.10.4 的bug，升级到最新版就好了
