### ISSUE TITLE
[BUG] 内联style对css变量的解析有问题

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#507]
**bug 描述**
```
<View className={styles.app}
          style={{
            '---color1': 'red',
            '--color2': 'blue'
          }} />
```
会被解析为
```
--color1: red
-color2: blue
```

**复现步骤**
clone repository, checkout到demo2
`yarn && yarn build`
可以看到color1有效, color2无效

**期望结果**
只需要正常的2个横线就可以解析, 不需要3个横线

**复现代码**
https://github.com/WhiteMinds/remax-bug-demo/tree/demo2

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
`---color` 和 `--color` 是什么写法？

**Comment by WhiteMinds** [comment]
> `---color` 和 `--color` 是什么写法？

是css3的变量, 可以通过`var(--color)`来调用, 比如`color: var(--color1)`
