### ISSUE TITLE
[需求]支持对.wxss文件引入的支持

### ISSUE THREAD

**Issue by zhutiancheng2** [remaxjs/remax#513]
**需求描述**
支持对.wxss文件引入的支持

**其他信息**
比如
`import "weui-miniprogram/miniprogram_dist/weui-wxss/dist/style/weui.wxss"`
编译的支持

**Comment by 514360255** [comment]
@Darmody 这个玩意近期可以支持不？

**Comment by Darmody** [comment]
> @Darmody 这个玩意近期可以支持不？

可以直接把 wxss 改成 css 引入。估计要在插件机制后再搞

**Comment by Darmody** [comment]
建议通过 postcss 配置 wxss 来实现

**Comment by shauvet** [comment]
> 建议通过 postcss 配置 wxss 来实现

可否举个例子？如何配置postcss？我之前直接改成css不行，打包报错

**Comment by l769829723** [comment]
> > 建议通过 postcss 配置 wxss 来实现
> 
> 可否举个例子？如何配置postcss？我之前直接改成css不行，打包报错

求栗子

**Comment by maohhgg** [comment]
weui.wxss 可以使用  useExtendedLib 引入， app.config.ts中加入
```  
useExtendedLib: {
    weui: true
}
```

**Comment by EqualMa** [comment]
或者可以[在 `import` 中指定 loader](https://webpack.js.org/concepts/loaders/#inline)

```js
import "css-loader!weui-miniprogram/miniprogram_dist/weui-wxss/dist/style/weui.wxss";
```

**Comment by EqualMa** [comment]
参考[文档](https://remaxjs.org/guide/config/remax#configwebpack)对webpage进行配置

```js
// remax.config.js
module.exports = {
  configWebpack({ addCSSRule }) {
    // 引用 wxss
    addCSSRule({
      name: 'wxss',
      test: /\.wxss(\?.*)?$/,
    });
  },
};
```
