### ISSUE TITLE
请问remax.config.js文件应该放在什么位置？我放在根位置，导致了编译不通过

### ISSUE THREAD

**Issue by zhangjiuyang** [remaxjs/remax#522]
![image](https://user-images.githubusercontent.com/14884839/71349235-7f14ed00-25a9-11ea-96e8-aa1a37ec75fa.png)

![image](https://user-images.githubusercontent.com/14884839/71349335-bdaaa780-25a9-11ea-8dbc-ea1eb7d43461.png)
以下是错误日志
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle remax-template@1.0.0~predev: remax-template@1.0.0
6 info lifecycle remax-template@1.0.0~dev: remax-template@1.0.0
7 verbose lifecycle remax-template@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle remax-template@1.0.0~dev: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\zjy_work\3.111\微信小程序\my-app\node_modules\.bin;C:\Users\EDZ\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\local\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files\Git\usr\bin;C:\Users\EDZ\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;D:\Program Files\nodejs;D:\Program Files\Git\cmd;C:\Users\EDZ\AppData\Local\Microsoft\WindowsApps;C:\Users\EDZ\AppData\Roaming\npm;D:\Node\npm_modules;D:\Program Files\Git\usr\bin\vendor_perl;D:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle remax-template@1.0.0~dev: CWD: D:\zjy_work\3.1111\微信小程序\my-app
10 silly lifecycle remax-template@1.0.0~dev: Args: [ '/d /s /c', 'remax build -t wechat -w' ]
11 silly lifecycle remax-template@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle remax-template@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: remax-template@1.0.0 dev: `remax build -t wechat -w`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid remax-template@1.0.0
15 verbose cwd D:\zjy_work\3.1111\微信小程序\my-app
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error remax-template@1.0.0 dev: `remax build -t wechat -w`
22 error Exit status 1
23 error Failed at the remax-template@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Darmody** [comment]
`remax.config.js` 的代码贴一下

**Comment by zhangjiuyang** [comment]
就是官网中的内容：
const path = require('path');

// remax.config.js 默认配置
module.exports = {
  // boolean | RegExp 开启或关闭 css modules，支持传入正则表达式配置开启的文件命名格式
  cssModules: /\.module\.(less|scss|css)$/,
  // 配置项目路径，默认当前路径
  cwd: process.cwd(),
  // 是否显示 build 进度，默认显示
  progress: true,
  // 指定代码的根目录，默认 src
  rootDir: 'src',
  // build 目录，默认 dist
  output: 'dist',
  // 配置路径别名
  alias: {},
  // 是否开启 wxml/axml 文件压缩
  compressTemplate: process.env.NODE_ENV === 'production',
  // 是否将 px 转换为 rpx, 默认是 true
  pxToRpx: true,
  postcss: {
    options: {
      use: [
        [
          'less',
          {
            paths: [
              // 可方便解析 node_modules 中样式文件
              path.resolve(__dirname, 'node_modules'),
              // 可作为全局样式目录
              path.resolve(__dirname, 'src/assets/styles'),
            ],
          },
        ],
        // 其他样式文件配置，比如sass, stylus, 如果有多种样式文件，则也需要添加对应配置
        ['stylus', {}],
      ],
    },
    url: {
      // 是否自动将图片转换成 base64
      inline: false,
      // 转换图片的最大限制， 单位 KB
      maxSize: 8,
    },
    // 其他postcss 插件, 会和默认的插件进行拼接
    plugins: [],
  },
  // 修改 rollup 的配置
  rollupOptions: options => {
    options.inputs.push('foo.js');
    return options;
  },
};

**Comment by Darmody** [comment]
input 不是 inputs

**Comment by zhangjiuyang** [comment]
谢谢！

**Comment by Darmody** [comment]
> 谢谢！

这里文档有纰漏，我们要改一下

**Comment by zhangjiuyang** [comment]
老板辛苦了！
