### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by webCoderJ** [remaxjs/remax#526]
**bug 描述**
[typescript-通用模块模板无法启动]

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
![image](https://user-images.githubusercontent.com/19652730/71430711-696a0980-2708-11ea-8654-d5294d0306eb.png)

**Comment by Darmody** [comment]
指定需要启动的平台，比如 wechat
