### ISSUE TITLE
[BUG]如果第三方包依赖了另外一个第三方包则不会被打包在npm目录里

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#527]
**bug 描述**

我引用了一个`rc-from-hooks`的包，这个包里面依赖了`async-validator`，结果使用就会报错，检查发现`dist/npm`目录里面没有将`async-validator`打包进来

**复现步骤**

安装
```shell
 yarn add rc-form-hooks 
```
使用
```tsx
import useForm from 'rc-form-hooks';
```

**期望结果**
能正常使用

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: 1.10.7
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
控制台报错
![image](https://user-images.githubusercontent.com/29084441/71436905-44868e00-272a-11ea-8335-c5fd6110a220.png)
`dist/npm` 目录
![image](https://user-images.githubusercontent.com/29084441/71437025-cb3b6b00-272a-11ea-8bb9-6cc1b1a4b6a6.png)

**Comment by Darmody** [comment]
这个包 es 打包不对

改成

`import useForm from 'rc-form-hooks/dist/index';`
