### ISSUE TITLE
[需求]支持引入core-js

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#528]
**需求描述**

现在这样想要支持`Promise.finally`的话会报错
```tsx
import 'core-js/es/promise/finally';
```

**解决方案**

扩展 babel

**其他信息**

![image](https://user-images.githubusercontent.com/29084441/71456332-eada9e00-27d3-11ea-8a89-e04d71381a2d.png)

**Comment by Darmody** [comment]
小程序没有全局变量，需要拓展 babel 支持

**Comment by Darmody** [comment]
似乎在小程序里搞不定。。没整明白
