### ISSUE TITLE
[BUG]如果自定义组件名是Page就不会渲染

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#529]
**bug 描述**

![image](https://user-images.githubusercontent.com/29084441/71456838-59206000-27d6-11ea-94a2-284a0ec596ad.png)
![image](https://user-images.githubusercontent.com/29084441/71456848-64738b80-27d6-11ea-81e5-2a4d2e0d127b.png)

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: 1.10.7
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
Page 是小程序关键字
