### ISSUE TITLE
[性能] setData 数据冗余

### ISSUE THREAD

**Issue by coppyC** [remaxjs/remax#531]
**bug 描述**
更新一个input 的值，setData 会set两个data，一个是 input的tree, 一个是 input 所在的整个组件tree

**复现步骤**
页面代码
```js
import React, { useState } from 'react'
import { View, Input } from 'remax/wechat'

export default () => {
  const [a, setA] = useState('')
  return (
    <View style={{ margin: '32px' }}>
      <Input placeholder="a" value={a} onInput={e => setA(e.detail.value)} />
    </View>
  )
}
```

然后在 setData 前面打印一下 action 
https://github.com/remaxjs/remax/blob/27e07c2a24e6401c3880f19e69bc44b4ee3908ea/packages/remax/src/Container.ts#L97

然后启动页面，在Input输入点什么

![image](https://user-images.githubusercontent.com/25004510/71462742-45cdbe80-27ef-11ea-818c-78c1a8ba08b0.png)

可以看到了的 action 包含了两个 payload
root.children 是 view
root.children.0.children 是 input

**期望结果**
应该只有root.children.0.children更新才对，view 不需要更新

另一种情况：如果两者都要更新，应该只有一个 payload: ` root.children `
因为 root.children 包含了 root.children.0.children

还有就是， action 每次都 split 类型，进行 tree 的替换，
是不是还可以再分情况，插入 tree 和 删除 tree 才用 split，
节点的更新应该用别的方式，进行更加颗粒化的 更新操作。
比如这里 其实只要更新 input.props.value，不需要把整个 input setData 过去替换掉。

**版本**
- remax 版本: [e.g. 1.10.6]

**Comment by Darmody** [comment]
和 prepareUpdate 中的 shallowequal 有关
