### ISSUE TITLE
[BUG] 当用 View 包一层原生自定义组件后，在 View 上监听 onClick 使用 e.stopPropagation 会有问题

### ISSUE THREAD

**Issue by Pochodaydayup** [remaxjs/remax#536]
**bug 描述**
当用 View 包一成原生组件后，在 View 上监听 onClick 使用 e.stopPropagation时， 会报 e.stopPropagation is not a function; 的错误

**期望结果**
 e.stopPropagation 正确生效

**复现代码**
```
<View
        onClick={(e: any) => {
          console.log('dddsadsadsdasdsadasdas');
          e.stopPropagation();
        }}
      >
        <Button className="add-button" hoverClass="none">
          <Text className="add-icon">+</Text>
          <Text>{text}</Text>

          {/* <Info info="dsdasd"></Info> */}
        </Button>
      </View>
```

**版本信息:**

- remax 版本: [e.g. 1.10.7]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.9.4]
- 开发环境 [e.g. mac OS]

**其他信息**
![image](https://user-images.githubusercontent.com/22768639/71552144-cc71de00-2a31-11ea-9c90-3cde87629225.png)

**Comment by yexiaosong** [comment]
在remax 1.10.9版本上没有复现。我看回调的事件对象也是正常的。
