### ISSUE TITLE
[问题]remax是否可以直接拿react这边的组件库来用？

### ISSUE THREAD

**Issue by chj-damon** [remaxjs/remax#543]
**问题描述**
[详细地描述问题，让大家都能理解]
既然现在remax是可以享受完全的react生态，是否意味着基于react封装的组件库也可以直接拿来用呢？比如ant-mobile之类的
**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
react-dom 依赖的库不能用。就好比 react-native 也不能用 web 的组件
