### ISSUE TITLE
[问题]怎么拦截全局的错误呢？

### ISSUE THREAD

**Issue by hefengly** [remaxjs/remax#549]
**问题描述**
你好，怎么拦截全局的错误呢？我试了react 的生命周期componentDidCatch，和在app 入口组件使用小程序的onError，都没有生效唉？

**Comment by Darmody** [comment]
按理说就是你说的这两个生命周期，不知道具体是什么错误？

**Comment by hefengly** [comment]
在一个点击事件里，console.log了一个为定义的变量

**Comment by Darmody** [comment]
@hefengly 你试一下原生 onError 和 componentDidCatch 能捕捉到吗

**Comment by hefengly** [comment]
试了原生的，是可以抓到的。感觉是remax入口的app组件，onError事件不生效？

**Comment by Darmody** [comment]
![截屏2020-01-03上午10 40 05](https://user-images.githubusercontent.com/6788752/71704445-7b892d80-2e15-11ea-8315-c1e5a0800454.png)
<img width="270" alt="截屏2020-01-03上午10 40 17" src="https://user-images.githubusercontent.com/6788752/71704447-7b892d80-2e15-11ea-8978-c5522929e585.png">
我试了下是可以抓到的。不知道你是写的

**Comment by Darmody** [comment]
有问题的话，再打开 issue

**Comment by hefengly** [comment]
抱歉抱歉呀，信息更新不及时。
我是这么写的，没有生效唉, 似乎onError方法报错了
![image](https://user-images.githubusercontent.com/28841926/71774460-0f8bfe00-2faa-11ea-8bf6-f82335a149d7.png)
![image](https://user-images.githubusercontent.com/28841926/71774467-43672380-2faa-11ea-9308-131ee418f579.png)
![image](https://user-images.githubusercontent.com/28841926/71774472-73aec200-2faa-11ea-8f5e-9f4090695118.png)

**Comment by Darmody** [comment]
remax 版本是？

**Comment by hefengly** [comment]
1.7.2

**Comment by Darmody** [comment]
> 1.7.2

可以用最新版试试吗

**Comment by hefengly** [comment]
好的，我等下试一下



---原始邮件---
发件人: "Cai Huanyu"<notifications@github.com&gt;
发送时间: 2020年1月5日(周日) 中午1:06
收件人: "remaxjs/remax"<remax@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"hefengly"<1047568365@qq.com&gt;;
主题: Re: [remaxjs/remax] [问题]怎么拦截全局的错误呢？ (#549)


 
1.7.2
  
可以用最新版试试吗

**Comment by hefengly** [comment]
我找到原因了，唉，很尴尬，是开发者工具的问题：在开发者工具上onError会报错，抓不到，但在真机上表现是正常的，非常感谢你的解答🙏❤️
