### ISSUE TITLE
[需求]用hooks获取小程序组件实例

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#555]
**需求描述**
类似`IntersectionObserver`api的组件参数支持用`hooks`获取

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Pochodaydayup** [comment]
@mushan0x0 获取组件的实例应该获取不到，但是可以获取到 Page 的实例

**Comment by Darmody** [comment]
目前 React 组件并不是原生自定义组件
