### ISSUE TITLE
[BUG]引入rxjs后报错

### ISSUE THREAD

**Issue by wangmingxu** [remaxjs/remax#561]
**bug 描述**
通过下面的方式引入rxjs subject
`
import { Subject } from 'rxjs/internal/Subject';

console.log(Subject);
`
出现报错
![image](https://user-images.githubusercontent.com/15760369/71713652-91164b80-2e45-11ea-9013-868178d13bf7.png)

查看编译后的代码dist/_virtual/observable.js_commonjs-proxy.js
![image](https://user-images.githubusercontent.com/15760369/71713691-bf942680-2e45-11ea-845a-b5c10901f622.png)
编译后的代码多了一段奇怪的`ports`
**复现步骤**
见问题描述

**期望结果**
正常运行

**复现代码**
见问题描述

**版本信息:**

- remax 版本: [1.1.0]
- 小程序端 [字节跳动小程序]
- 开发环境 [mac OS]

**Comment by yesmeck** [comment]
看起来是 rollup 的 bug

**Comment by wangmingxu** [comment]
_virtual文件夹编译出来的文件看上去只是做了引入和导出，可以通过配置去掉这一步么

**Comment by yesmeck** [comment]
是 rollup 的 bug，我看看给他们发个 PR

**Comment by yesmeck** [comment]
https://github.com/rollup/rollup/pull/3317

**Comment by yesmeck** [comment]
已经修复了，重新安装下依赖
