### ISSUE TITLE
[BUG]官方demo编译报错

### ISSUE THREAD

**Issue by wittech** [remaxjs/remax#562]
**bug 描述**
> remax build -w -t

没有提供足够的值给此选项：t
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remax-template@1.0.0 dev: `remax build -w -t`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the remax-template@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**复现步骤**
mac os

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
跨平台demo需要选择你要编译的目标平台，如 `remax dev wechat`

**Comment by fattydevelop** [comment]
> 跨平台demo需要选择你要编译的目标平台，如 `remax dev wechat`

建议修改一下文档，快速入门多处实际操作与文档不符
