### ISSUE TITLE
[需求] 支持无单位 inline style

### ISSUE THREAD

**Issue by coppyC** [remaxjs/remax#574]
**需求描述**
[详细地描述需求，让大家都能理解]

自动添加 ”rpx” 后缀到内联样式为数字的属性后。如需使用 ”rpx” 以外的单位，请将此值设为数字与所需单位组成的字符串。

```jsx
// Result style: '10rpx'
<div style={{ height: 10 }}>
  Hello World!
</div>
```

> https://zh-hans.reactjs.org/docs/dom-elements.html#style

**解决方案**
https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/CSSProperty.js

**Comment by Darmody** [comment]
感觉没有必要。写 style 的时候说不定更需要的是 px?

**Comment by coppyC** [comment]
好像不冲突?

目前不加单位，remax没有处理，到开发者工具后直接无效属性了

而且现在 style 写 px 也会编译成 rpx 吧

这个功能也没有影响现有代码，是增加性的。

**Comment by yesmeck** [comment]
我觉得可以吧，跟 ReactDOM 行为一致。
