### ISSUE TITLE
[问题]支持原生页面TypeScript

### ISSUE THREAD

**Issue by cytle** [remaxjs/remax#580]
**需求描述**

现在`Remaxjs`对原生页面的支持，只仅限在copy。而很可能旧项目使用了`TypeScript`来进行开发，希望支持这部分。

**解决方案**

`native/pages/**/*.ts`做`TypeScript`预编译

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
原生小程序是如何使用 typescript 的？

**Comment by Darmody** [comment]
remax 只是将 native 的代码复制过去，如果原生支持 ts，那应该不影响使用

**Comment by cytle** [comment]
没描述清楚，官方的脚手架支持Typescript预编译，旧项目用到了Typescript，并且想继续用。是否可以支持编译`native/pages`文件夹里`ts`文件

https://developers.weixin.qq.com/miniprogram/dev/devtools/edit.html#TypeScript-%E6%94%AF%E6%8C%81

**Comment by Darmody** [comment]
看这意思只要加了预编译命令就行了

**Comment by Darmody** [comment]
@cytle 还有问题不

**Comment by cytle** [comment]
还有问题，您是指
![image](https://user-images.githubusercontent.com/5120505/72238609-2e793880-3619-11ea-827d-81fd6d28866b.png)
这个设置吗。

如果在remax构建完后，再编译dist/native文件夹的`ts`文件。`npm`的依赖，以及对非native文件夹的依赖都会出现问题

**Comment by cytle** [comment]
期望remax可以把原生ts文件这部分也编译了，可以省很多事

**Comment by yesmeck** [comment]
我们应该不会做这个事，后面开放插件了，可以自己实现。
