### ISSUE TITLE
[问题]小程序原生不能使用getApp，如何结合redux

### ISSUE THREAD

**Issue by yatessss** [remaxjs/remax#587]
**问题描述**
小程序原生依赖一些global上的数据，在逐步迁移过程中原有页面需要继续使用，如何可以使用global数据，如果不可以使用如何在小程序原生页面中引用app.js中定义的store。试着改了一下，发现native是直接copy过去的，内部引用地址都没有改，在dist目录下运行不起来。望解答

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
第一个问题，写个 `./globalData.js`，在页面里引用即可。

第二个问题，可以描述的详细点么？

**Comment by yatessss** [comment]
如native下的文件引用redux，dist下的其他页面经过编译引用的是`var connect = require('../../npm/react-redux/es/connect/connect.js');`而native下的页面引用的还是`import {connect} from "react-redux";` 引用会报错

**Comment by yesmeck** [comment]
hmm，确实是个问题。

**Comment by yatessss** [comment]
还有另外一个疑问，native下的文件夹文件是移动到了dist目录的哪一层级？目前试了一下好像是native下的直接移动到了dist目录下面吗？  这里的文档说的有些简略。

**Comment by yesmeck** [comment]
是的，直接移动。你提到的问题，我们研究下。

**Comment by yatessss** [comment]
好的谢谢，逐步迁移时会遇到这些问题，望能多考虑一些和小程序原生结合上的体验 😀😀

**Comment by yatessss** [comment]
你好，还有就是在目前通过更改引用地址的方式可以支持到结合redux嘛？

**Comment by yesmeck** [comment]
你可以尝试下

**Comment by Darmody** [comment]
native 目录里应该直接引用 `/npm/react-redux/es/connect/connect.js`

**Comment by Darmody** [comment]
native 目录里应该按照原生的方式写代码
