### ISSUE TITLE
[BUG]不同页面page选择器的样式会直接相互覆盖

### ISSUE THREAD

**Issue by IronLu233** [remaxjs/remax#592]
**bug 描述**
多个页面的样式下使用page选择器会导致样式覆盖。

**复现步骤**
使用remax的template并且创建文件，使得目录结构如下
```
src/pages
├── index
│   ├── index.module.css
│   └── index.tsx
└── other
    ├── index.module.css
    └── index.tsx
```
index/index.module.css
``` less
page {
  background: #fff;
}
```
index/index.tsx
``` tsx
import * as React from "react";
import { View, Text, Image, Button, navigateTo } from "remax/alipay";
import styles from "./index.module.css";

export default () => {
  return (
    <View className={styles.app}>
      <Button onClick={() => navigateTo({ url: "/pages/other/index" })}>
        跳转
      </Button>
    </View>
  );
};
```
other/index.module.css
```less
page {
  background: pink;
}

```

other/index.tsx
```tsx
import * as React from "react";
import { View, Text, Image } from "remax/alipay";
import styles from "./index.module.css";

export default () => {
  return <View className={styles.app}></View>;
};
```

编译之后发现两个page的css都被编译到了app.acss中
![image](https://user-images.githubusercontent.com/20639676/72434120-d176b180-37d5-11ea-9954-88489880be68.png)

**期望结果**
pages/index/index 页面的背景色为白色，pages/other/index的背景色为可爱的粉色

**复现代码**
见上面复现步骤。

**版本信息:**

- remax 版本: 1.11.2
- 手机型号: 不需要
- 小程序端 支付宝小程序
- 小程序版本 1.19.0
- 开发环境 mac OS

**其他信息**

**Comment by Darmody** [comment]
不建议直接修改 page 样式。可以用一个 root view 包裹页面

**Comment by yesmeck** [comment]
这是个坑，还是要解决的

**Comment by sydeEvans** [comment]
页面的样式为何不打到页面自己的page.acss里

**Comment by yesmeck** [comment]
@sydeEvans 来修下这个问题么

**Comment by edwardfhsiao** [comment]
current workaround
```css
.page {
	min-height: 100vh;
	background-color: #000000;
}
```

**Comment by edwardfhsiao** [comment]
@Darmody 请问更新了 remax remax-cli 1.15.0，微信小程序还是只有一个app.wxss，
还需要其他什么配置吗
![image](https://user-images.githubusercontent.com/11728228/76492085-467b0600-646a-11ea-9428-36c9322455e9.png)

**Comment by Darmody** [comment]
> @Darmody 请问更新了 remax remax-cli 1.15.0，微信小程序还是只有一个app.wxss，
> 还需要其他什么配置吗
> ![image](https://user-images.githubusercontent.com/11728228/76492085-467b0600-646a-11ea-9428-36c9322455e9.png)

这个还没有发布

**Comment by edwardfhsiao** [comment]
ok, 谢谢
