### ISSUE TITLE
[BUG]api没有类型提示了

### ISSUE THREAD

**Issue by mushan0x0** [remaxjs/remax#598]
**bug 描述**
![image](https://user-images.githubusercontent.com/29084441/72675712-5f4ae900-3ac3-11ea-935a-61910ca079bd.png)

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 1.11.5]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yybawang** [comment]
在 1.11.0 之后就一直没有了，感谢

**Comment by yesmeck** [comment]
@yybawang 看起来是 WebStorm 会有问题。。。

**Comment by yybawang** [comment]
> @yybawang 看起来是 WebStorm 会有问题。。。

是的，还是修复一下比较好...
1.11.0 之后就没有自动提示了

**Comment by yesmeck** [comment]
@yybawang 有点尴尬，现在不知道怎么修，我去给 jetbrains 提个 issue 看看。

**Comment by yesmeck** [comment]
@yybawang @mushan0x0 把 `node_modules/remax-wechat` 这个目录设置为 “not excluded” 就可以了。

![20200120193408](https://user-images.githubusercontent.com/465125/72723587-f4310d80-3bbb-11ea-84d3-763866789678.jpg)

**Comment by yesmeck** [comment]
原因是 `remax-wechat` 不是项目的直接依赖，WebStorm 就不会去索引它。

**Comment by yybawang** [comment]
> 原因是 `remax-wechat` 不是项目的直接依赖，WebStorm 就不会去索引它。

好 可以的😘
