### ISSUE TITLE
[问题]根节点添加统一元素没有渲染

### ISSUE THREAD

**Issue by yatessss** [remaxjs/remax#602]
**问题描述**
想在最外层provider下添加一些统一的元素，如下：
```js
const App = ({ children }: PageProps) => {
  return <Provider store={store}>
      <View>
          <Text>1111111</Text>    <---- 此处为想要统一添加的
          {children}
      </View>
  </Provider>;
};
```
为了满足通用组件的调用，比如popup，dialog等，添加到根节点就不需每个页面单独引入。但发现这样在根节点添加并不会渲染出来，求指教是Remax问题还是我没有使用对方法。

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
这是预期行为，App 里不支持写基础组件的。参考文档：https://remaxjs.org/guide/framework

**Comment by yatessss** [comment]
是否考虑添加？查看源码发现page嵌入app用的是protal，这个是否考虑放出来一个插槽用来存放基础组件，每个页面自己引入基础组件的方式太繁琐了

**Comment by yesmeck** [comment]
这个问题之前讨论过，在 App 里无法区分页面，没办法做到针对页面的 layout，所以不支持在 App 里写基础组件。之前的讨论 https://github.com/remaxjs/remax/pull/189

**Comment by yatessss** [comment]
根据路由栈顶判断在哪个页面也是一个比较常见的判断方式，如果这样的方式觉得不好，我是否可以把所有页面继承自一个base page的class，利用插槽去插入组件。但是createProtal是依赖于react dom的，看到remax也有一个createProtal，这个是否可以开放出来呢

**Comment by yesmeck** [comment]
写个组件在页面里引用就可以了（不建议用继承）

```javascript
import Layout from '@/components/Layout';

export default () => {
  return (
    <Layout>
        ...
    </Layout>
  );
}
```

**Comment by yatessss** [comment]
你们在应用过程中用继承方式会有哪些隐藏的坑吗

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wei Zhu <notifications@github.com&gt;
发送时间: 2020年1月20日 11:53
收件人: remaxjs/remax <remax@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[remaxjs/remax] [问题]根节点添加统一元素没有渲染 (#602)




写个组件在页面里引用就可以了（不建议用继承）
 import Layout from '@/components/Layout'; export default () =&gt; {   return (     <Layout&gt;         ...     </Layout&gt;   ); }

**Comment by yybawang** [comment]
自己外层套一个组件就可以了，没那么复杂的
或者写个 userContext 状态和 Layout 组件，每个页面都用 Layout 包裹

**Comment by yesmeck** [comment]
我们没有，但继承不是 react 推荐的方式。
