### ISSUE TITLE
[问题]如何catch蒙层触摸事件防止背后页面滚动

### ISSUE THREAD

**Issue by yatessss** [remaxjs/remax#609]
**问题描述**
蒙层catch触摸事件 防止背后页面滚动，看到click时间有stopPropagation，但是catchmove并没有这个方法，看了文档也没有找到方法，求指教

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
试试 `catchTouchMove` 呢

**Comment by yatessss** [comment]
应该也是不行的我记得我试过



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Cai Huanyu <notifications@github.com&gt;
发送时间: 2020年1月30日 11:27
收件人: remaxjs/remax <remax@noreply.github.com&gt;
抄送: yatessss <897969073@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[remaxjs/remax] [问题]如何catch蒙层触摸事件防止背后页面滚动 (#609)




试试 catchTouchMove 呢

**Comment by Darmody** [comment]
可以看看微信小程序官方论坛里关于这个问题是怎么解决的

**Comment by bigbig-head** [comment]
有知道怎么解决了吗

**Comment by Darmody** [comment]
建议搜索微信官方的解决方案

**Comment by Darmody** [comment]
一个简单的解决方法，在弹层样式里添加 `touch-action: none;`
