### ISSUE TITLE
[BUG] 微信小程序Video标签绑定全屏事件无效

### ISSUE THREAD

**Issue by vvni** [remaxjs/remax#614]
**bug 描述**
微信小程序Video标签绑定全屏事件无效

**复现步骤**
给Video标签绑定全屏事件即可复现

**期望结果**
触发全屏事件

**复现代码**
https://github.com/vvni/one-video-miniprogram

**版本信息:**

- remax 版本: [e.g. 1.12.3]
- 手机型号 [e.g. iPhone XS Max，一加6]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.10.1]
- 开发环境 [e.g. mac OS]

**Comment by Darmody** [comment]
事件名怎么写的

**Comment by vvni** [comment]
![image](https://user-images.githubusercontent.com/50414099/73056127-395d8400-3ec9-11ea-934e-1ae3e7c56891.png)

**Comment by Darmody** [comment]
如果remax没有做别名的，可以用原生的属性名

**Comment by vvni** [comment]
> 如果remax没有做别名的，可以用原生的属性名

好的，我试试。

**Comment by vvni** [comment]
> 如果remax没有做别名的，可以用原生的属性名

原生绑定有效。
