### ISSUE TITLE
onUnload好像没有对应的hook

### ISSUE THREAD

**Issue by journey-xt** [remaxjs/remax#626]
**问题描述**
在class组件中可以直接使用onUnload,但是函数式组件中并没有对应onUnload的hook

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by journey-xt** [comment]
我找到问题了，谢谢

**Comment by weijiahui1** [comment]
请问怎么监听到onUnload这个方法？能在这个方法的回调执行自己的代码？

**Comment by lyboy2012** [comment]
二级页面返回 onUnload onHide 并不会触发，有人遇到吗
usePageEvent('onUnload', () => {
  
  });
usePageEvent('onHide', () => {
  
  });

**Comment by Darmody** [comment]
> 二级页面返回 onUnload onHide 并不会触发，有人遇到吗
> usePageEvent('onUnload', () => {
> 
> });
> usePageEvent('onHide', () => {
> 
> });

没有 `onUnload`。onUnload 对应的就是 componentWillUnmount

**Comment by lyboy2012** [comment]
> > 二级页面返回 onUnload onHide 并不会触发，有人遇到吗
> > usePageEvent('onUnload', () => {
> > });
> > usePageEvent('onHide', () => {
> > });
> 
> 没有 `onUnload`。onUnload 对应的就是 componentWillUnmount

目前"remax": "^2.2.0", 微信小程序 一级页面usePageEvent 对应 onUnload onHide，断点有调用，只是二级页面点返回没有触发，为什么没有 onUnload 呢？

**Comment by Darmody** [comment]
@lyboy2012 可以提供一个复现的例子吗

**Comment by lyboy2012** [comment]
> @lyboy2012 可以提供一个复现的例子吗

https://developers.weixin.qq.com/s/t5zmpPmz7whe

**Comment by Darmody** [comment]
@lyboy2012 

yarn add https://pkg.csb.dev/remaxjs/remax/commit/1ab092d6/remax

试试这个测试包有没有问题

**Comment by Darmody** [comment]
@lyboy2012 我看了一下 demo 页返回上一页，触发的不是 onHide 。而是 onUnload.

onUnload 在 remax 中对应的就是 `componentWillUnmount` 或者 `useEffect` 的 unsubscribe 方法。

所以是没问题的

**Comment by lyboy2012** [comment]
> onUnload

----pages/index/index onHide
remax-vendors.js:30818 ----pages/demo/index onShow
remax-vendors.js:30815 ----pages/demo/index
remax-vendors.js:30818 ----pages/index/index onShow

**Comment by lyboy2012** [comment]
> @lyboy2012
> 
> yarn add https://pkg.csb.dev/remaxjs/remax/commit/1ab092d6/remax
> 
> 试试这个测试包有没有问题

“TypeError: shared_1.slash is not a function ” 安装后回报错，这个安装地址 代码有什么变化吗

**Comment by Darmody** [comment]
我们目前没有 `onUnload` 这个生命周期

**Comment by lyboy2012** [comment]
> 我们目前没有 `onUnload` 这个生命周期

感谢解答 ; )
