### ISSUE TITLE
[BUG]微信小程序中如click-left这样的事件无法捕捉

### ISSUE THREAD

**Issue by lee88688** [remaxjs/remax#642]
**bug 描述**
使用van-nav-bar的组件时存在一个click-left类似的事件，在代码中使用bindclick-left无法绑定事件。

**复现代码**
```
import React from 'react'
import VanPopup from '@vant/weapp/dist/popup'

function Example(props) {
  const click = () => console.log('click')
  return <VanNavBar left-text="123" bindclick-left={click} />
}
```

**版本信息:**

- remax 版本: [e.g. 1.1.0]
- 小程序端 [e.g. 微信小程序]

**Comment by lee88688** [comment]
我在微信小程序中进行尝试发现，小程序中bindclick-left确实无法绑定，只能通过bind:click-left方式才行

**Comment by Darmody** [comment]
这个我们可以支持一下

**Comment by Darmody** [comment]
通过配置 https://github.com/remaxjs/remax/blob/master/packages/babel-preset-remax/README.md#throw-if-namespace
就可以使用命名空间属性

**Comment by lee88688** [comment]
@Darmody 我在项目中升级到对应版本配置好throw-if-namespace后编译出现错误（如下），通过错误提示应该是 [这段代码](https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/plugins/nativeComponents/babelPlugin.ts#L108) 出现了问题。
`TypeError: C:\Users\lenovo\Documents\project\small-program\grid-method-plus\src\components\addStockTrading\index.jsx: prop.replace is not a function
    at JSXElement.usedProps.filter.filter.map.prop (C:\Users\lenovo\Documents\project\small-program\grid-method-plus\node_modules\remax-cli\lib\build\plugins\nati
veComponents\babelPlugin.js:86:43)`

**Comment by Darmody** [comment]
@lee88688 

`yarn add https://pkg.csb.dev/remaxjs/remax/commit/3978ae72/remax https://pkg.csb.dev/remaxjs/remax/commit/3978ae72/remax-cli`

试试这两个测试包可不可以

**Comment by lee88688** [comment]
可以没问题 @Darmody

**Comment by Darmody** [comment]
@lee88688 v1.13.1 发布了
