### ISSUE TITLE
使用vant组件库可以给属性起别名吗

### ISSUE THREAD

**Issue by Bigpawn** [remaxjs/remax#649]
**问题描述**
使用vant的组件库，想让组件的属性使用别名，但是一直不成功

**示例代码**
`import { createHostComponent } from 'remax/macro'

const TreeSelect = createHostComponent("VantTreeSelect", [["items", "data"]]);`

**Comment by Darmody** [comment]
`createHostComponent` 是用来创建 Host 组件的，不能用来起别名。

**Comment by Bigpawn** [comment]
@Darmody 第二个参数不能吗？
![image](https://user-images.githubusercontent.com/25793232/74825817-83f5e300-5345-11ea-9f3b-6be47232cd9c.png)

**Comment by Darmody** [comment]
这个意思是，给你创建的 host component 的属性起别名
