### ISSUE TITLE
[BUG] 在IOS 13.1.3的iPhone7上，出现异常 Template `REMAX_TPL_1_undefined` not found

### ISSUE THREAD

**Issue by briefguo** [remaxjs/remax#653]
**bug 描述**
在IOS 13.1.3的iPhone7上，出现异常

```
WXMLRT_$gwx:./base.wxml:templete:1:9305:
Template `REMAX_TPL_1_undefined` not found
```
导致后续的页面都崩溃，页面为白屏状态

**复现步骤**
重新步骤暂不清晰，因为我在iPhoneX上和一些其他手机上基本上都是正常的。唯独在一台IOS 13.1.3的iPhone7上有问题

**期望结果**
告诉我可能的原因，让我好去避免这种问题

**复现代码**

**版本信息:**

- remax 版本: [1.5.2]
- 手机型号 [iPhone 7 iOS 13.1.3]
- 小程序端 [微信小程序]
- 小程序版本[2.8.3]
- 开发环境 [mac OS]

**其他信息**

**Comment by Darmody** [comment]
IOS 13.1.3的iPhone7 可以稳定复现吗？

**Comment by inJs** [comment]
iOS 7P 13.3.1

**Comment by Darmody** [comment]
似乎是微信的问题，并且他们已经偷偷修复了
