### ISSUE TITLE
[BUG]在 app 文件中引入图片，导致编译后样式文件名错误

### ISSUE THREAD

**Issue by hackers267** [remaxjs/remax#663]
**bug 描述**
为了能够在小程序中共享状态，引入了`constate`来实现，在 app.tsx 内引入之后，会导致样式渲染不出来，编译后的结果没有 `app.wxss`文件

**复现步骤**
1. 在项目中安装 `constate`，并引用。
2. 在 app.tsx 文件中，如下使用`constate`.
3. 运行 `yarn dev`。
4. 发现 *dist*目录下没有 `app.wxss`文件

**期望结果**
引入`constate`，样式可以正常使用。

**复现代码**
只需引入`constate`。并且在`app.tsx`中，使用如下代码：
```
import * as React from "react";
import "./app.css";
import { useState } from "react";
import constate from "constate";

const [CountProvider, useCount] = constate(() => {
  const [count] = useState(0);
  return count;
});
const App: React.FC = props => <CountProvider>props.children as React.ReactElement</CountProvider>;

export default App;

```

**版本信息:**

- remax 版本: 1.13.2
- 开发环境 window 10

**Comment by Darmody** [comment]
无法复现额。。

**Comment by Darmody** [comment]
最好提供完整的项目 demo

**Comment by hackers267** [comment]
demo git@github.com:hackers267/remax-dome.git

**Comment by hackers267** [comment]
https://github.com/remaxjs/remax/issues/663#issue-571864278 此issue虽然编译出了 wxss文件。但是微信开发者工具并不能渲染出页面

**Comment by Darmody** [comment]
@hackers267
 `yarn add https://pkg.csb.dev/remaxjs/remax/commit/66cc642e/remax https://pkg.csb.dev/remaxjs/remax/commit/66cc642e/remax-cli`

试试这个测试包有没有解决你的问题
