### ISSUE TITLE
[问题]请问微信文档中"扩展能力"的weui如何使用

### ISSUE THREAD

**Issue by edwardfhsiao** [remaxjs/remax#678]
**问题描述**
由于找不DIalog这个组件而发现好像关于“扩展能力”里面的组件都无法使用。
![image](https://user-images.githubusercontent.com/11728228/75780361-270f1980-5d96-11ea-8c6a-a8bd5f5480e5.png)

以Dialog为例子，我该怎么使用？还是说目前只支持最基础的组件？

**Comment by Darmody** [comment]
https://remaxjs.org/guide/custom-component

可以看下文档。直接安装 weui，然后像引入 react 组件一样引入使用

**Comment by edwardfhsiao** [comment]
Being so struggled for a while.

Solution for this: 
```js
import Dialog from 'weui-miniprogram/miniprogram_dist/dialog/dialog.js';

...
      <Dialog
        type="ios"
        title={'dummy'}
        buttons={[
          {
            text: 'Cancel',
          },
          {
            text: 'Ok',
          },
        ]}
        show={true}
        bindbuttontap={e => {
          console.log(e);
        }}
      >
        This is iOS Style 1
      </Dialog>
...
```
@Darmody Thanks again.
