### ISSUE TITLE
[问题]微信小程序自定义组件slot无效

### ISSUE THREAD

**Issue by edwardfhsiao** [remaxjs/remax#679]
**问题描述**
不知道是我配置问题还是怎么样，按照
https://remaxjs.org/guide/custom-component
只要用View包着就可以显示出slot，但此示例是支付宝的，微信的我目前出不来。

**示例代码**

```js
import Msg from 'weui-miniprogram/miniprogram_dist/msg/msg.js';
...
    <Msg desc={'My description'} type="success" size={64} title={'My title'}>
      <View slot="foot">My footer</View>
    </Msg>
...
```

**其他信息**
![image](https://user-images.githubusercontent.com/11728228/75850050-4737ea80-5e21-11ea-989b-ed46d9c48e7c.png)

![image](https://user-images.githubusercontent.com/11728228/75850150-849c7800-5e21-11ea-96b9-069d57ab63fa.png)

**Comment by Darmody** [comment]
是 `footer` 不是 `foot`
