### ISSUE TITLE
[问题]在“状态共享”wechat example中通过navigateTo来回切换页面报“same key”的错

### ISSUE THREAD

**Issue by edwardfhsiao** [remaxjs/remax#683]
**问题描述**
在“状态共享”wechat example中通过navigateTo

我在new的页面增加一个按钮，通过```navigateTo({ url: '../index/index' });```来返回index页面，会报以下错误。

VM1794:1 Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s page_1 
    in _App

**示例代码**
```js
// new/index.js
     <View className="todo-footer">
        <AddButton text="Add Todo" onClick={handleAdd} />
      </View>
      <View className="todo-footer">
        <AddButton text="index" onClick={()=>{
          navigateTo({ url: '../index/index' });
        }} />
      </View>
```

**其他信息**

![ezgif-3-0c2c20b0c2dd](https://user-images.githubusercontent.com/11728228/75962983-a835f000-5eff-11ea-9177-4bf684d0a9dd.gif)

**Comment by Darmody** [comment]
哪一个 example？

**Comment by edwardfhsiao** [comment]
https://github.com/remaxjs/examples/tree/master/wechat/src

**Comment by Darmody** [comment]
无法复现

**Comment by edwardfhsiao** [comment]
微信开发者工具 Stable v1.02.1911180
我做的改动只有添加了以下
```js
import { ... navigateTo } from 'remax/wechat';
...
     <View className="todo-footer">
        <AddButton text="返回index页面" onClick={()=>{
          navigateTo({ url: '../index/index' });
        }} />
      </View>
...
```
然后用navigateTo来回切换页面。
