### ISSUE TITLE
[需求]从库中选择页面

### ISSUE THREAD

**Issue by caijiang** [remaxjs/remax#698]
**需求描述**
将页面等组件单独打包(PageConfig,React组件成对出现)成库之后，需要在配置中引入这些页面。

**解决方案**
无

**其他信息**
目前的页面配置只支持针对源码路径。详见 AppConfig#pages

**Comment by Darmody** [comment]
在页面里直接引用组件是不是就好了呢

**Comment by caijiang** [comment]
这算是我处理过的需求，场景是一个核心项目可能需要被多次分流开发，但是变动都极少。

所以组件级的使用应该无法满足需求。

面前也就2条路。

## 运行时（供应方）解决方案
比如选择微信小程序的插件，优势在于将remax打包出来的东西从小程序改成插件即可；不过不是很清楚微信对于小程序插件支持是否足够的自由或者丰满，算是受制于人了。

##  编译时解决方案
remax 在编译时增加从库中获取页面元素然后添加到合法的页面目录里去（假装是有代码的页面文件上读到的）。
对于remax工作原理不是太了解，所以无法断言这种方式成本会有多高，但对于开发者而言这个解决方案更具备自主性。

**Comment by Darmody** [comment]
```js
// src/pages/index/index
import PageComponent from 'PageConfig';

export default PageComponent;
```

这样不行吗

**Comment by caijiang** [comment]
！！

就是在分流出来的项目里写一个空的桥接页面？
