### ISSUE TITLE
[需求]支持微信小程序的云函数

### ISSUE THREAD

**Issue by xuhong** [remaxjs/remax#699]
**需求描述**
project.config 配置 cloudfunctionRoot 编译后被忽略了，cloudfunctionRoot 里面的代码也需要编译到 dist 文件夹

**Comment by Darmody** [comment]
cloudfunctionRoot 指定的目录下是原生代码吗

**Comment by Darmody** [comment]
可以用 gulp 或者其他插件，把这个目录复制进 `output` 目录

**Comment by xuhong** [comment]
remax config 可以支持吗？自己配置肯定是可以的，但是就两套在里面了

**Comment by Darmody** [comment]
> remax config 可以支持吗？自己配置肯定是可以的，但是就两套在里面了

可以加个 rollup 插件

**Comment by liujiayii** [comment]
`
"cloudfunctionRoot": "src/cloud/",

"miniprogramRoot": "dist/",
`
试试这样配置……

**Comment by xuhong** [comment]
> `
> "cloudfunctionRoot": "src/cloud/",
> 
> "miniprogramRoot": "dist/",
> `
> 试试这样配置……

晚上回去试试
