### ISSUE TITLE
能使用react的第三方ui库吗？能编译成h5吗？

### ISSUE THREAD

**Issue by freemember007** [remaxjs/remax#7]
如题

**Comment by CodeFalling** [comment]
目前无法直接使用第三方库，因为我们底层组件目前依赖 `@remax/components`，不能直接写 `div`，这需要后面来兼容，估计过程中会有一些坑（毕竟 div 和 View 还是有区别的）。

编译成 h5 应该是能够支持的，就是现在暂时还没实现

**Comment by yesmeck** [comment]
后面我会跟 umi 做集成，可以同时编译到小程序和 Web 页面。

https://github.com/remaxjs/remax#roadmap

**Comment by freemember007** [comment]
very good!
