### ISSUE TITLE
改进错误提示

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#70]
#54

**Comment by Darmody** [comment]
错误提示挺清晰的，就是 React 的错误栈

**Comment by Darmody** [comment]
rollup 有的时候没有捕捉插件的错误，倒是可以优化一下

**Comment by Darmody** [comment]
> rollup 有的时候没有捕捉插件的错误，倒是可以优化一下

实际情况是 watch 模式我们没有处理抛出来的错误
