### ISSUE TITLE
[BUG] 升级到 1.15 后项目无法正常使用了

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#702]
**bug 描述**
似乎是从 app.tsx 导出东西到其他文件中使用就会导致 bug，编译出现问题
![Lark20200313114038](https://user-images.githubusercontent.com/9160743/76587630-84863180-651f-11ea-8bb3-7f30fa9b2f98.png)

**复现步骤**
已经将复现代码抽离到 demo 中
clone 仓库，然后 yarn && yarn dev，用微信开发者工具打开，即可看到报错

**期望结果**
一切正常

**复现代码**
https://github.com/WhiteMinds/remax-bug-demo

**版本信息:**

- remax 版本: [e.g. 1.15.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
是用哪个分支呢

**Comment by WhiteMinds** [comment]
> 是用哪个分支呢

主分支

**Comment by Darmody** [comment]
可以先把 app 文件改成 js 文件就好了

**Comment by WhiteMinds** [comment]
> 可以先把 app 文件改成 js 文件就好了

我还是等修复吧。。是下个版本修复吗？
