### ISSUE TITLE
[需求]remax支持开发小程序插件

### ISSUE THREAD

**Issue by esky** [remaxjs/remax#705]
**需求描述**
支持开发小程序插件页面开发

**解决方案**
小程序插件页面不同与小程序页面
1、没有App：可以模拟一个App容器，app的生命周期使用wx的api监听
2、独立的配置plugin.json：部分属性有差异比如pages，可以延用app.json。新增编译参数插件模式，在app.json里新增pluginConfig，最终插件模式下生产plugin.json。
3、独立的入口js：初始化插件代码的同时导出供外部使用的API

**其他信息**

**Comment by yesmeck** [comment]
好像是一回事？ https://github.com/remaxjs/remax/issues/368

**Comment by juvham** [comment]
能支持使用remax开发组件么，好像看到有个pull request
