### ISSUE TITLE
[BUG]微信小程序weui组件中cell的link箭头无法显示。

### ISSUE THREAD

**Issue by alansuhe** [remaxjs/remax#706]
**bug 描述**
如题

**复现步骤**

```
import MpCell from 'weui-miniprogram/miniprogram_dist/cell/cell.js';
...
<MpCell link>
    <View>标题文字（使用slot）</View>
    <View slot="footer">说明文字</View>
</MpCell>
```

**期望结果**
在这个cell右侧应该出现箭头图标，然而无；
weui其余组件均未发现问题

**版本信息:**
- remax 版本: [^1.1.0]
- 手机型号 [微信小程序模拟iPhone X及安卓等终端]
- 小程序端 [微信小程序]

**Comment by Darmody** [comment]
根据官方的例子 https://developers.weixin.qq.com/miniprogram/dev/extended/weui/cell.html

右侧的箭头是代码里自己加上的
