### ISSUE TITLE
[BUG]weui中uploader组件无法上传文件

### ISSUE THREAD

**Issue by wangzhipeng404** [remaxjs/remax#707]
按照weui文档里面写了

import Uploader from 'weui-miniprogram/miniprogram_dist/uploader/uploader';
export default () => {
  const uplaodFile = (files) => {
    console.log('upload files', files)
    // 文件上传的函数，返回一个promise
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            reject('some error')
        }, 1000)
    })
  }
  return (
    \<View>
     \<Uploader 
        upload={uplaodFile}
      />
    \</View>
  );
};

uploader 里面判断了props的类型
`
if (typeof _this.data.upload === 'function') {
    _this.upload().then(...)
}
`
但调试发现typeof upload 的类型变成了 string 无法触发upload
upoload的值为"$$REMAX_METHOD_2_upload"

**Comment by yesmeck** [comment]
没想到微信会把 function 作为属性值，这个我们暂时没有很好的解法。

**Comment by yesmeck** [comment]
暂时无法解决这个问题。
