### ISSUE TITLE
[BUG]打包后的dist文件夹中有引用.tsx文件导致报错

### ISSUE THREAD

**Issue by IMakiMaki** [remaxjs/remax#708]
**bug 描述**
开发环境build的dist文件夹中有引用.tsx文件导致报错，自己手动将引用的.tsx改成.js后可以通过小程序开发者工具正常运行

**复现步骤**
运行`remax build -t alipay -w`

**版本信息:**

- remax 版本: [1.15.2]
- 开发环境 [mac OS]

**其他信息**
生成的/dist文件中的index-xxxxx.js文件中错误引用了app.tsx
![image](https://user-images.githubusercontent.com/18737872/76742501-228e2c00-67ac-11ea-8004-0805cce04157.png)
![image](https://user-images.githubusercontent.com/18737872/76742510-2752e000-67ac-11ea-8dbc-58265786b052.png)

**Comment by Darmody** [comment]
最新版本应该不会有这个问题了🤔，能确认下版本是否正确吗？如果还有问题能不能提供一个复现 demo？

**Comment by IMakiMaki** [comment]
> 最新版本应该不会有这个问题了🤔，能确认下版本是否正确吗？如果还有问题能不能提供一个复现 demo？

版本确实是1.15.2

**app.tsx:**

import * as React from 'react';
import './app.css';
import {isFullScreen} from "@/utils/util";

export type GlobalDataType = {
    isFullScreen: Boolean
}

// 全局变量
const initGlobalData: GlobalDataType = {
    isFullScreen: isFullScreen()
}

export const GlobalContext = React.createContext(initGlobalData);

export default class extends React.Component  {
    render() {
        return (
            this.props.children
        )
    }
}

**index.tsx**
import {GlobalContext, GlobalDataType} from "@/app";

// TabBar主渲染函数
const TabBar: React.FC<Props> = (props: Props) => {
    return (
        <GlobalContext.Consumer>
            {
                (globalData: GlobalDataType) => <view>xxxxxxx</view>
            }
        </GlobalContext.Consumer>
    )
};


TabBar.defaultProps = defaultProps;

export default TabBar;

**Comment by Darmody** [comment]
我试了你这个代码没有问题。

如果还有问题请提供完整的复现 demo

**Comment by Darmody** [comment]
可以试一下删除 `yarn remove remax remax-cli`，再重新安装 `yarn add remax remax-cli`

**Comment by IMakiMaki** [comment]
😂好的 下班了 等明天我试一下 感谢回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Cai Huanyu <notifications@github.com&gt;
发送时间: 2020年3月16日 18:04
收件人: remaxjs/remax <remax@noreply.github.com&gt;
抄送: AntiLun <479016893@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[remaxjs/remax] [BUG]打包后的dist文件夹中有引用.tsx文件导致报错 (#708)






可以试一下删除 yarn remove remax remax-cli，再重新安装 yarn add remax remax-cli

**Comment by IMakiMaki** [comment]
> 可以试一下删除 `yarn remove remax remax-cli`，再重新安装 `yarn add remax remax-cli`

还是不行，完整项目脱敏打包了一下。链接: https://pan.baidu.com/s/17zhY12oS9H3EsAPGvQrSYA 提取码: 8tm7

**Comment by Darmody** [comment]
> > 可以试一下删除 `yarn remove remax remax-cli`，再重新安装 `yarn add remax remax-cli`
> 
> 还是不行，完整项目脱敏打包了一下。链接: https://pan.baidu.com/s/17zhY12oS9H3EsAPGvQrSYA 提取码: 8tm7

能不能直接放一个 github 仓库，百度下不下来

**Comment by IMakiMaki** [comment]
> > > 可以试一下删除 `yarn remove remax remax-cli`，再重新安装 `yarn add remax remax-cli`
> > 
> > 
> > 还是不行，完整项目脱敏打包了一下。链接: https://pan.baidu.com/s/17zhY12oS9H3EsAPGvQrSYA 提取码: 8tm7
> 
> 能不能直接放一个 github 仓库，百度下不下来

好的 https://github.com/IMakiMaki/test

**Comment by Darmody** [comment]
`yarn add https://pkg.csb.dev/remaxjs/remax/commit/00d969e4/remax https://pkg.csb.dev/remaxjs/remax/commit/00d969e4/remax-cli
`

@IMakiMaki 试试看这个测试包有没有解决问题

**Comment by IMakiMaki** [comment]
> `yarn add https://pkg.csb.dev/remaxjs/remax/commit/00d969e4/remax https://pkg.csb.dev/remaxjs/remax/commit/00d969e4/remax-cli `
> 
> @IMakiMaki 试试看这个测试包有没有解决问题

OK了 这个没问题了 感谢~
