### ISSUE TITLE
请教一下$$REMAX_METHOD不生效的问题

### ISSUE THREAD

**Issue by ybzjsxh** [remaxjs/remax#724]
**问题描述**
刚接触remax，想请教下大佬们，我这里的方法不生效是啥原因呀，用的是@vant/weapp的tree-select组件的两个方法
![image](https://user-images.githubusercontent.com/18141198/77029225-108fd180-69d6-11ea-9f44-c92aef24b7d6.png)

![image](https://user-images.githubusercontent.com/18141198/77029840-d6bfca80-69d7-11ea-840f-04e23c7e0754.png)

**示例代码**
两个方法如下
![image](https://user-images.githubusercontent.com/18141198/77029111-c4449180-69d5-11ea-9305-c7f6571f9d65.png)

改成`bindclick-item`, `bindclick-nav`也不行

**其他信息**
`package.json`版本如下
![image](https://user-images.githubusercontent.com/18141198/77029795-aaa44980-69d7-11ea-94fb-2db88c1eb15f.png)

**Comment by Darmody** [comment]
关闭 `throw-if-namesapce`
https://github.com/remaxjs/remax/blob/master/packages/babel-preset-remax/README.md#throw-if-namespace
然后用 `bind:click-item` 试试。

**Comment by ybzjsxh** [comment]
> 关闭 `throw-if-namesapce`
> https://github.com/remaxjs/remax/blob/master/packages/babel-preset-remax/README.md#throw-if-namespace
> 然后用 `bind:click-item` 试试。

大佬好，我照着添加了`yarn add babel-preset-remax --dev`, 然后添加了`.babelrc`，内容：
```json
{
  "presets": [
    [
      "remax",
      {
        "typescript": {
          "allowNamespaces": true
        },
        "class-properties": {
          "loose": true
        },
        "decorators": {
          "legacy": true
        },
        "throw-if-namespace": false
      }
    ]
  ]
}
```
并将方法改为，貌似依旧没起作用
![image](https://user-images.githubusercontent.com/18141198/77036075-2f4b9380-69e9-11ea-8e7c-dbf1078f83e7.png)
![image](https://user-images.githubusercontent.com/18141198/77036182-72a60200-69e9-11ea-83d0-363cab226d0e.png)

**Comment by Darmody** [comment]
那我有空的时候康康

**Comment by Darmody** [comment]
你没有改成 `bind:click-item` 呀

**Comment by ybzjsxh** [comment]
> 你没有改成 `bind:click-item` 呀

嗷嗷可以了，多谢大佬
