### ISSUE TITLE
Remax 2.0 计划

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#755]
## 新功能

- 支持 Web 同构 #741 
- ~支持开发小程序组件 #368~
- create-remax-app

## 不兼容改动

- 构建工具切换到 Webpack，这样 Web 和小程序的构建可以统一 #744 。
- 去掉 native 目录的支持。
- 去掉 `catchTap/catchClick`。
- 去掉以纯 class 定义 App 的方式。
- 配置
  - 去掉 rollupOptions
  - 去掉 postcss
  - 去掉 cssModules
  - 去掉 alias

**Comment by Darmody** [comment]
css 中支持相对路径引入图片，绝对路径引入的图片，要开发者自行把图片copy到绝对路径对应的文件位置。

**Comment by Darmody** [comment]
`remax/macro` 提供 `requirePlugin` `requirePluginComponent` 方法用于引入原生插件。

**Comment by Darmody** [comment]
`remax-one` `Image` 组件去除 `lazyLoad` 属性

**Comment by Darmody** [comment]
2.0 修复 https://github.com/remaxjs/remax/issues/763

**Comment by Darmody** [comment]
`unstable_createNativeComponent` -> `createNativeComponent`

废弃 生命周期 hook `useXXX`。如 `useShow`

**Comment by Darmody** [comment]
配置：`compressTemplate` -> `minimize` 提供对 template 和 js 的压缩

**Comment by Darmody** [comment]
`remax-one` 需要说明：

`input` `type` 类型在 web 端和小程序端不一致
`form` reset 表现在微信平台表现不一致，建议开发者自己做受控 reset。

**Comment by Darmody** [comment]
`remax-one` 全平台支持的生命周期：

页面生命周期：

`onShow` `onHide` `onPullDownRefresh ` `onReachBottom` `onUnload` `onLoad` `onPageScroll `

**Comment by Darmody** [comment]
`remax-one` 提供统一配置项，web 平台配置项与 `remax-one` 对齐

**Comment by Darmody** [comment]
web 端 有 tabbar 时，viewport 和小程序不同

**Comment by Darmody** [comment]
remax-one Event 中的 `originalEvent` 改为 `nativeEvent`

**Comment by Darmody** [comment]
remax-one 中 `onPullDownRefresh` 生命周期支持返回 promise 来控制是否结束 pulldownrefresh

**Comment by Darmody** [comment]
新增 web 平台的应用配置及页面配置，与小程序对齐。

**Comment by Darmody** [comment]
`uesPageEvent` `useAppEvent` 从 `remax/macro` 导出

**Comment by Darmody** [comment]
`unstable_useNativeEffect` -> `useNativeEffect`

**Comment by Darmody** [comment]
去除 `remax` 中的 `Platform` 对象

**Comment by WangJM001** [comment]
后续考虑支持react-native么

**Comment by yesmeck** [comment]
> 后续考虑支持react-native么

暂时不考虑，我们自己没需求

**Comment by yesmeck** [comment]
`Input[maxlength]` => `Input[maxLength]`

**Comment by Darmody** [comment]
class 组件 BeforeTabItemTap -> beforeTabItemTap
