### ISSUE TITLE
[BUG]ScrollView的onScroll方法中setState数据会引起页面抖动

### ISSUE THREAD

**Issue by LuckyHH** [remaxjs/remax#756]
**bug 描述**
在ScrollView的 onScroll 方法中 setState 一个无关滚动的数据，会引起页面抖动。本以为是 setState 数据引起了页面重新渲染导致的，但是拆分组件，使用 memo 控制后，setState 不再会引起有滚动代码的组件重新渲染，但还是有页面抖动的问题。

**复现步骤**
监听 onScroll 方法，在 Math.random() < 0.4 的条件下 setState 一个无关数据。

**期望结果**
页面不会抖动

**复现代码**
```javascript
  function onPageScroll(e: any) {
    const { scrollTop } = e.detail
    if(Math.random() < 0.4) {
      setVal(scrollTop)
    }
  }

  return (
      <ScrollView
        className="plot-scroll-view"
        scrollY
        scrollTop={scrollToTop}
        onScroll={onPageScroll}
      >
       ...
      </ScrollView>
)
```

**版本信息:**

- remax 版本: 1.18.4
- 手机型号  devtools
- 小程序端 微信小程序
- 小程序版本 2.10.4
- 开发环境 mac OS

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by LuckyHH** [comment]
在 ScrollView 中包裹一个Swipper ， Swipper切换也会有页面闪动的问题

**Comment by Darmody** [comment]
原生也会抖动
