### ISSUE TITLE
[BUG] Typescript 模板编译报错

### ISSUE THREAD

**Issue by myronliu347** [remaxjs/remax#760]
**bug 描述**
当一个文件中定义了 `type/interface` 另外一个文件引用会有文件，babel处理ts是每个文件单独编译，会把定义的interface 等删除，但是另外一个文件引用没有被删除，在Rollup 打包时会报错。

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
提供一下复现 demo。我试了一下没有复现

**Comment by Darmody** [comment]
可以用 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html 第一段提到的方式解决。

**Comment by Darmody** [comment]
如果没有升级到 TypeScript 3.8 可以参考 https://github.com/Microsoft/TypeScript/issues/24322
