### ISSUE TITLE
[问题]usePageEvent的问题

### ISSUE THREAD

**Issue by zhqinux** [remaxjs/remax#768]
**问题描述**
函数组件中，我希望能够监听到onLoad的生命周期回调
但是好像没有相应的useOnLoad
然后我尝试了调用usePageEvent，eventName我填写的是onLoad，仍然没有成功
在函数组件中不能监听到onLoad的生命周期吗？
**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
`componentDidMount` 相当于 `onLoad`
