### ISSUE TITLE
[BUG] remax使用微信的自定义组件，properties传值无效

### ISSUE THREAD

**Issue by MrTung** [remaxjs/remax#775]
**bug 描述**
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/
按照微信小程序官方给的demo，通过import导入到页面中，组件的外部属性传入无效。
**复现步骤**

**期望结果**
应该传入的值有效

**复现代码**
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/

**版本信息:**

- remax 版本: [e.g. 1.19.3]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**

**Comment by Darmody** [comment]
有没有具体的代码

**Comment by MrTung** [comment]
https://github.com/MrTung/remax-demo  demo已经上传

**Comment by MrTung** [comment]
> 有没有具体的代码



> 有没有具体的代码

https://github.com/MrTung/remax-demo

**Comment by Darmody** [comment]
应该是 `import CunstomHeader from '@/components/header/index';`
