### ISSUE TITLE
[BUG] 在 mac 端上连续发起多个请求时，差异更新的 action 丢失导致渲染不正常

### ISSUE THREAD

**Issue by WhiteMinds** [remaxjs/remax#780]
**bug 描述**
我引入了一个埋点用的 Sdk，该 Sdk 会在配置 `{ auto_report: true }` 时在 App/Page 的一些生命周期自动上报数据，如 app_launch、app_terminate、predefine_pageview 等。
选择图片的 api 会导致连续触发上面所说的3个生命周期，发出3个请求，我的代码逻辑是在选择完文件后就会跳到下一个页面（带着选中的临时文件地址过去）。
然后这个页面会做一个对临时地址列表（`Array<string>`）的初始化，获取相关的文件信息，并设置到 `state` 中，展示为一个列表。
但一切处理都正常时，列表未正常渲染，内部数据都已经更新完成了，最后检查发现是 `remax` 用于差异更新的一个 `action` 被抛弃了，我们分析可能是因为连续的 `request` 导致的。
目前的临时处理是在 `initUploadList` 前增加了一个 `nextTick`。

**复现步骤**
克隆复现代码，编译后在开发者工具打开，开启不校验合法域名，自动预览设置为 PC 端。
启动预览，然后点击 Choose Image，选完图片后即可看到未正常渲染的列表。
![Kapture 2020-04-08 at 14 51 14](https://user-images.githubusercontent.com/9160743/78753725-e617af80-79a8-11ea-97e2-8c5acc3c17fc.gif)

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
https://github.com/WhiteMinds/remax-bug-demo

**版本信息:**

- remax 版本: [e.g. 1.19.2]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.7.7]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by WhiteMinds** [comment]
这是我们判断 `action` 被抛弃的依据

![Kapture 2020-04-08 at 15 05 32](https://user-images.githubusercontent.com/9160743/78754817-ba95c480-79aa-11ea-8a40-e4cbafcd8cb5.gif)

在开发者工具中可以看到页面2执行了 [3,5,6] 这3个 action，而在 mac 端中，只有 [3,5] 这2个 action 被执行了

**Comment by Darmody** [comment]
所以是 mac 端的小程序才有这个问题？

**Comment by WhiteMinds** [comment]
> 所以是 mac 端的小程序才有这个问题？

目前来看是这样

**Comment by Darmody** [comment]
好的，那我有空试一下

**Comment by Darmody** [comment]
先关闭这个 issue，如果还有问题再开启
