### ISSUE TITLE
[需求] px转rpx

### ISSUE THREAD

**Issue by fwh1990** [remaxjs/remax#781]
**需求描述**
有时候react组件需要传入size之类的数值，假设是px单位，那么没办法手动变成rpx，但是css文件的px会直接转为rpx，这样会导致size不正确。

**解决方案**
希望能在js层面支持px转rpx。类似 [Taro.pxTransform](https://taro-docs.jd.com/taro/docs/size.html#api)

**Comment by yesmeck** [comment]
style 上的 px 现在会自动转的 https://github.com/remaxjs/remax/blob/master/packages/remax/src/utils/plainStyle/index.ts#L50

**Comment by fwh1990** [comment]
现在的需求是把size传到原生组件，没法自动转。

如果remamax后面要支持h5的话，还需要转成rem；以及后面如果支持了设计尺寸，那么px转rpx也不是等比转换。

所以手动处理不合适，希望官方能支持

**Comment by yesmeck** [comment]
@fwh1990 可以举个代码的例子么

**Comment by fwh1990** [comment]
就是size传的是px值，然后组件内部用JS处理一下转换成对应的rpx值，然后传递给原生的组件。

和remax框架的css在编译时转换px成rpx是一个道理，不同的是我需要在运行的时候动态处理。

**Comment by fwh1990** [comment]
```javascript
<Plugin size={20} />
```

**Comment by fwh1990** [comment]
1

**Comment by fwh1990** [comment]
目前remax是按照750的设计尺寸，并且没支持h5（rem），所以size即使不转换也不会报错。

**Comment by yesmeck** [comment]
后面应该都会按 750 来（按小程序的设计）。

**Comment by Darmody** [comment]
@fwh1990  如果你是把 size 直接应用到 style 上的话，remax 会处理 style 的单位的

**Comment by fwh1990** [comment]
@Darmody 

size直接传给原生组件了，没走框架的style。

**Comment by coppyC** [comment]
@fwh1990 
这个好像做不到啊，size 是用户自己定义的，remax 不知道这个 size 是不是px单位，万一就是要 数字类型，结果自动转成字符串，不就凉了?

或者你可以根据自己需要用装饰者模式 覆写 React.createElement 方法?

**Comment by coppyC** [comment]
如果你说的是像 `Taro.pxTransform(10)` 这样的api倒是可行。
但如果像 style 一样自动加 rpx 就。。

**Comment by fwh1990** [comment]
> 如果你说的是像 `Taro.pxTransform(10)` 这样的api倒是可行。

对的，我说的是这个

**Comment by yesmeck** [comment]
> 我从 createSelectorQuery API 拿到节点的 Rect ，然后要对另一个元素赋值，还有一个就是取键盘高度，对页面进行偏移

**Comment by Darmody** [comment]
应该建议用户关闭 px 转 rpx

**Comment by farzer** [comment]
默认转有点坑....
