### ISSUE TITLE
[BUG]再配合vant-Weapp 时，绑定after-enter事件失败

### ISSUE THREAD

**Issue by ysc123** [remaxjs/remax#793]
**bug 描述**
在开发微信小程序时，用了vant-weapp UI框架，在用Popup组件时，有一个after-enter事件，bindafter-enter时，触发不了。但是bindenter，能够触发事件。 我再node_modules 直接修改vant的transition.js,
把this.$emit(`after-${this.status}`) 改成了this.$emit(`after${this.status}`)，尝试bindafterenter时，发现可以触发事件。 猜测  bind***-*** 是否不支持。
**复现步骤**
使用vant-weapp里面的 Popup  触发 after-enter 事件获取元素。

**复现代码**
<Popup
         show={show}
        closeable
        overlay={false}
        position="bottom"
        customStyle={{"height":"100%"}}
        bindclose={this.onShowCityPopup}
        bindafter-enter={this.transitionend}
   >

<Popup>

**版本信息:**
"@vant/weapp": "^1.2.1",
"remax": "^1.9.0",
"remax-cli": "^1.9.0",

**Comment by Darmody** [comment]
可以直接使用 `bind:after-enter`。

如果你的 remax 版本使用 `bind:after-enter` 会报错，可以把 https://github.com/remaxjs/remax/blob/master/packages/babel-preset-remax/README.md#throw-if-namespace 这个选项关掉。

**Comment by ysc123** [comment]
添加"babel-preset-remax": "^1.20.0" 后 ，编译报错
`node_modules/react-reconciler/index.js
[babel]: /Users/mindasset/workspace/qdhk/Remax/remax-qdhk/node_modules/symbol-observable/es/index.js: 'import' and 'export' may only appear at the top level (5:0)
  3 | var es = commonjsHelpers.createCommonjsModule(function (module) {
  4 | /* global window */
> 5 | import ponyfill from './ponyfill.js';
    | ^
  6 | 
  7 | var root;
`

**Comment by ysc123** [comment]
@Darmody

**Comment by yesmeck** [comment]
@ysc123 这个报错可以新开一个 issue 么

**Comment by ysc123** [comment]
@yesmeck  好的提交了
