### ISSUE TITLE
[BUG]编译错误 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by ysc123** [remaxjs/remax#794]
**bug 描述**
编译的时候后报错

**复现步骤**
用的examples里面 redux 的demo，添加babel-preset-remax后，编译报错。

**复现代码**
`(63): node_modules/react-reconciler/index.js`
`[babel]: /Users/mindasset/workspace/qdhk/Remax/remax-qdhk/node_modules/symbol-observable/es/index.js: 'import' and 'export' may only appear at the top level (5:0)
`
`var es = commonjsHelpers.createCommonjsModule(function (module) {`
`/* global window */`
`import ponyfill from './ponyfill.js';`
`var root;`

**版本信息:**

- remax 版本: [e.g. 1.9.0]

**其他信息**

**Comment by yesmeck** [comment]
这个其实是 @rollup/plugin-commonjs 的 [bug](https://github.com/rollup/plugins/issues/304)

临时的方案时先用旧版本的 Remax，试试 `1.10.7`

**Comment by ysc123** [comment]
退回了 1.9.0 版本 ，没问题了！

**Comment by yesmeck** [comment]
先开着吧，等 @rollup/plugin-commonjs  修复了可以再升级上来。

**Comment by ysc123** [comment]
@yesmeck    ok

**Comment by yesmeck** [comment]
临时解决方法，在 package.json 里加上：

```
{
    ...,
    "resolutions": {
        "@rollup/plugin-commonjs": "11.0.2"
    }
}
```

**Comment by yesmeck** [comment]
2.0 里不会有这个问题了。
