### ISSUE TITLE
编译时间很久

### ISSUE THREAD

**Issue by Penn010** [remaxjs/remax#796]
**问题描述**
使用yarn dev命令，本人电脑启动watch的编译时间非常长。但同样的电脑，同样的项目，有同事编译只需三分钟。

**其他信息**
主要输出信息：
💡 编译完成
🚚 开始编译...
99% (245): src/modules/shop/pages/payment/index.module.less[BABEL] Note: The code generator has deoptimised the styling of /Users/penn/开发文件/remax/cuckoo/node_modules/react-reconciler/cjs/react-reconciler.development.js as it exceeds the max of 500KB.

**Comment by yesmeck** [comment]
三分钟也够长的。。。项目很大么？

**Comment by Penn010** [comment]
> 三分钟也够长的。。。项目很大么？

并没有很大，就是一个普通的商城项目，但是项目做了项目工程化，基本都是按功能分模块，模块比较多，编译过程基本都是会提示上面我贴出来的信息，摸不着头脑

**Comment by yesmeck** [comment]
@Penn010 我正在从 rollup 切换到 webpack，最近会发布，到时候可以试一下

**Comment by Penn010** [comment]
> @Penn010 我正在从 rollup 切换到 webpack，最近会发布，到时候可以试一下还慢不慢

好的，你敢相信。每次改动一下就yarn build 一次？说多了都是泪。另外，只有-watch模式才会慢。

**Comment by yesmeck** [comment]
有点奇怪啊，试过升级 node  版本么？

**Comment by yesmeck** [comment]
另外你是 Windows 吗？

**Comment by Penn010** [comment]
特意升级到了node版本 v12.16.2，还是很慢

**Comment by Penn010** [comment]
> 有点奇怪啊，试过升级 node 版本么？

特意升级到了node版本 v12.16.2，还是很慢

**Comment by scarcoco** [comment]
> @Penn010 我正在从 rollup 切换到 webpack，最近会发布，到时候可以试一下还慢不慢



Webpack 多久可以 OK？

**Comment by yesmeck** [comment]
2.0 已发布，试一下 2.0 吧
