### ISSUE TITLE
[需求]自动识别 css modules

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#800]
自动识别为 CSS Modules：

```javascript
import styles from `./style.css`;
```

自动识别为非 CSS Modules：

```javascript
import `./style.css`;
```

**Comment by linjiajian999** [comment]
为啥移除 `modules.css` 这种方式？
配合 [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules) ,开发的时候可以像下面这种方式
```jsx
import 'xx.module.css'
<div styleName="container" />
```
现在这种方式只能
```jsx
import styles from 'xx.css'
<div className={styles.container} />
```

或者可以提供让开发者更改是否启用 css module 的配置项，如果使用 webpack config 的话，实际上还需要开发者重新配置一遍

**Comment by yesmeck** [comment]
@linjiajian999 有道理，能单独写个 issue 吗
