### ISSUE TITLE
[BUG]  remax 2.0  web 预览样式单位未生效？

### ISSUE THREAD

**Issue by noyobo** [remaxjs/remax#803]
**bug 描述**
```html
 <View className='tttt'>111</View>
 <View style={{ height: 100, borderBottom: '1px solid red' }}>111</View>
```
编译后

```html
<div class="tttt">111</div>
<div class="" style="height: 100px; border-bottom: 1px solid red;">111</div>
```

![image](https://user-images.githubusercontent.com/1292082/79524860-1ee41280-8094-11ea-92a1-77e27cf590e3.png)

.tttt 高度应该是 100px  = 2rem ?  此时 html.style.fontSize = '50px', 实际截图看起来未生效。

内联样式，同样未生效

![image](https://user-images.githubusercontent.com/1292082/79524954-5d79cd00-8094-11ea-8dc8-48c417aeedc2.png)

**复现步骤**

**期望结果**

.tttt div 渲染高度 100px.

内联样式的 div 渲染高度 100px.

**复现代码**

https://github.com/remaxjs/examples/tree/next/one

修改 `./src/pages/image/index.tsx`

**版本信息:**

- remax 版本: Remax v2.0.0-alpha.3

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
现在没处理 inline style 的单位

**Comment by noyobo** [comment]
> 现在没处理 inline style 的单位

嗯，明白。编译结果符合预期。

**Comment by noyobo** [comment]
查了下，原来是  `.page-todos` 设置了 max-height & flex
