### ISSUE TITLE
[BUG]web端样式中以rpx的单位的属性无效

### ISSUE THREAD

**Issue by IronLu233** [remaxjs/remax#810]
**bug 描述**
样式表样式
![image](https://user-images.githubusercontent.com/20639676/79680072-47a80b80-823e-11ea-9b31-789bc07d0d16.png)

![image](https://user-images.githubusercontent.com/20639676/79680003-63f77880-823d-11ea-87a1-3042bc1cb0f9.png)

内联样式
![image](https://user-images.githubusercontent.com/20639676/79680024-a02ad900-823d-11ea-81a6-64d9b0bd1356.png)
![image](https://user-images.githubusercontent.com/20639676/79680027-a9b44100-823d-11ea-8940-a8b63541cb10.png)

**复现步骤**
- 用one模板创建一个项目并升级到2.0
- 修改index.module.less随便把一个单位从px改至rpx
- 添加rpx的内联样式
- `yarn dev web`
**期望结果**
样式能正确展示

**复现代码**
见上图

**版本信息:**

- remax 版本: [e.g. 2.0.0-alpha.4]
- 小程序端 [web]
- 开发环境 [Windows (Linux环境下执行构建)]

**其他信息**

**Comment by Darmody** [comment]
跨平台的话，应该都用 `px`
