### ISSUE TITLE
二次封装 @remax/one 后 构建无法收集到 components

### ISSUE THREAD

**Issue by noyobo** [remaxjs/remax#851]
**bug 描述**

```js
import { View } from 'myui';
```

```js
//myui/index.js
import { View } from '@remax/one'
export default View;
```

此时无法收集到 View 内容 , 被

https://github.com/remaxjs/remax/blob/master/packages/remax-cli/src/build/babel/componentManifest.ts#L130

过滤了。

**版本信息:**

- remax 版本: next

**Comment by noyobo** [comment]
由于微信的一些限制问题，需要按需的收集 hostComponent 以及 props 来实现。
通过 JSXElement 标签来收集，那么就需要：

1. 二次封装的组件保留 `<View />` 的写法。发布到 npm 上的包需要保留。
2. babel-laoder 不能 exclude(/node_modules/)

**Comment by yesmeck** [comment]
新增一个配置 `hostComponentProvider` 来配置提供 host component 的包能解决问题吗？

默认：
```javascript
{
  hostComponentProvider: /^@remax\/
}
```

**Comment by noyobo** [comment]
> 新增一个配置 `hostComponentProvider` 来配置提供 host component 的包能解决问题吗？
> 
> 默认：
> 
> ```js
> {
>   hostComponentProvider: /^@remax\//
> }
> ```

可以的。

**Comment by noyobo** [comment]
简单的场景可以覆盖，复杂一些的就没法解决了，收集的方案，希望还是能兼顾生态发展的需求。

例如 https://github.com/noyobo/remax-issues-demo 此时 components 下的就无法收集到了。

未来 remax 发展起来后，避免不了发布 npm 包的三方组件。

**Comment by Darmody** [comment]
resolved by #1010
