### ISSUE TITLE
[BUG]Type error in node 14

### ISSUE THREAD

**Issue by linningmii** [remaxjs/remax#865]
**bug 描述**
[详细地描述 bug，让大家都能理解]
![image](https://user-images.githubusercontent.com/14858674/80377183-7fadef00-88cd-11ea-9600-d54ce9f12bee.png)

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]
Node 14下编译时报错，node 14.0中有一个breaking change, fs.writeFileSync 的data数据类型不再接受数字类型。报错源头是rollup-progress-plugin

已有PR修复，等待合并
https://github.com/jkuri/rollup-plugin-progress/pull/18

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 1.0.0] 1.21.4
- 手机型号 [e.g. iPhone X] 
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS] macOS

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by hurui** [comment]
不知道rollup-plugin-progress的作者什么时候才发布上去。我看那个npm上已经一年多没更新了

**Comment by yesmeck** [comment]
2.0 应该没这个问题了。
