### ISSUE TITLE
[需求] input输入框支持支付宝原生 enableNative 属性

### ISSUE THREAD

**Issue by JYkid** [remaxjs/remax#874]
**需求描述**
remax input输入框支持支付宝原生 enableNative 属性。

目前 remax 在编译的时候会将 input 输入框的 enableNative 属性去掉，该属性是支付宝小程序原生提供用于解决键盘事件冲突 和输入框选中光标下移问题的属性。

期望remax支持input的该属性

**解决方案**
在编译的时候无需将  input 输入框的 enableNative 属性去掉

**其他信息**

![image](https://user-images.githubusercontent.com/52743950/80594275-4902e080-8a55-11ea-97c8-f6e6af8dda16.png)

**Comment by yesmeck** [comment]
已修正
