### ISSUE TITLE
其他资源 loader 该如何配置，比如 yaml 等文件

### ISSUE THREAD

**Issue by scarcoco** [remaxjs/remax#878]
其他资源 loader 该如何配置，比如 yaml 等文件

**Comment by noyobo** [comment]
https://remax.now.sh/guide/config/remax#configwebpack  

查看 https://github.com/neutrinojs/webpack-chain 的用法

**Comment by RicholeYu** [comment]
(node:13204) UnhandledPromiseRejectionWarning: ValidationError: Invalid configuration object. remax has been initialized 
using a configuration object that does not match the API schema.
 - configuration has an unknown property 'configWebpack'. These properties are valid:
   object { turboPages?, cssModules?, notify?, pxToRpx?, cwd?, progress?, compressTemplate?, output?, rootDir?, UNSAFE_wechatTemplateDepth?, alias?, one?, postcss?, rollupOptions? }

**Comment by scarcoco** [comment]
> https://remax.now.sh/guide/config/remax#configwebpack
> 
> 查看 https://github.com/neutrinojs/webpack-chain 的用法

好的，我看看这个。
