### ISSUE TITLE
remax-swr 能给一个文档吗

### ISSUE THREAD

**Issue by hurui** [remaxjs/remax#883]
**问题描述**
看了remax-swr的readme，那是swr的文档，remax-swr怎么安装和使用什么都没有，issues也不开，只能来这里问了

**Comment by hurui** [comment]
如果是个废弃的项目，请把它移出remaxjs列表，让认真维护的人加入

**Comment by watsonhaw5566** [comment]
@hurui 你好，请参考一下[实例里面的demo](https://blog.csdn.net/gnail_oug/article/details/52754491),里面是有swr的示例的
