### ISSUE TITLE
[需求] remax/wechat 没有导出 getRealtimeLogManager

### ISSUE THREAD

**Issue by rikumi** [remaxjs/remax#884]
**需求描述**
remax/wechat 没有导出 `getRealtimeLogManager`

**解决方案**
在 [packages/remax-wechat/src/api/index.ts](https://github.com/remaxjs/remax/blob/master/packages/remax-wechat/src/api/index.ts) 中添加导出 `getRealtimeLogManager`

**其他信息**
无

**Comment by yesmeck** [comment]
@rikumi 来个 PR 吧
