### ISSUE TITLE
[问题]急需升级迁移指南.

### ISSUE THREAD

**Issue by joesdu** [remaxjs/remax#893]
**问题描述**
[详细地描述问题，让大家都能理解]

**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
https://remaxjs.org/guide/v2-migration

**Comment by joesdu** [comment]
> https://remaxjs.org/guide/v2-migration

感谢,公司内网好像这个页面打不开,我换成手机热点看看.
