### ISSUE TITLE
[BUG] build项目后自定义组件没有随之打包导致组件缺失

### ISSUE THREAD

**Issue by q759410559** [remaxjs/remax#905]
**bug 描述**
使用dev运行时正常，build打包后 NativeCard 自定义组件不显示。

**复现步骤**

```
import React from 'react';
import { View } from 'remax/wechat';
import VantIcon from 'vant-weapp/dist/icon';

export default () => (
  <View>
 <VantIcon name="close" />
  </View>
);
使用项目中的自定义组件：

import React from 'react';
import { View } from 'remax/wechat';
import NativeCard from './native-card'; // native-card 是一个原生自定义组件

export default () => (
   <View>
     <NativeCard />
   </View>
);

```
**版本信息:**

- remax 版本: [e.g. 2.0.2]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**Comment by Darmody** [comment]
我试了一下可以的额，能提供一个复现 demo 吗

**Comment by q759410559** [comment]
https://github.com/q759410559/remax-test.git

**Comment by q759410559** [comment]
![image](https://user-images.githubusercontent.com/11240348/81299859-7a109000-90a9-11ea-8264-26dd2af9c535.png)
dev 运行时

![image](https://user-images.githubusercontent.com/11240348/81300111-d378bf00-90a9-11ea-893a-ae2d4af8ea84.png)
build 打包

1.x时是没问题的，今天刚升级2.0.2就不行了

**Comment by Darmody** [comment]
@q759410559 感谢提供复现 demo，问题已修复
