### ISSUE TITLE
[BUG]编译后的样式中单位不一致,start和build表现一致

### ISSUE THREAD

**Issue by joesdu** [remaxjs/remax#912]
**bug 描述**
具体情况如图.目前也没发现有什么特别影响
![image](https://user-images.githubusercontent.com/13188169/81460614-108f9f00-91d9-11ea-8c65-1859e7f65784.png)

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: [e.g. 2.0.3]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
代码里是怎么写的？

**Comment by joesdu** [comment]
> 代码里是怎么写的？

代码里都是px

**Comment by Darmody** [comment]
代码贴一下，我看看是不是 IDE 显示的问题

**Comment by joesdu** [comment]
> 代码贴一下，我看看是不是 IDE 显示的问题

https://github.com/remaxjs/remax/issues/912
上边是复现代码库
![image](https://user-images.githubusercontent.com/13188169/81462013-41280680-91e2-11ea-9a5e-57c55e38b2f4.png)

**Comment by Darmody** [comment]
是 IDE 本身的问题
