### ISSUE TITLE
[BUG] usePageEvent onShow 触发异常

### ISSUE THREAD

**Issue by dominicleo** [remaxjs/remax#914]
**bug 描述**

usePageEvent('onShow') 在分包页面执行偶尔会触发异常

Error: Cannot call an event handler while rendering.
at "pages/settings/profile/index" page lifeCycleMethod onShow function

**版本信息:**
- remax 版本: [e.g. 2.0.3]

**Comment by yesmeck** [comment]
试下 2.0.4

**Comment by dominicleo** [comment]
2.0.4 存在同样的问题

**Comment by yesmeck** [comment]
@dominicleo 能搞个 demo 么？

**Comment by Darmody** [comment]
因为在 usePageEvent 里面使用了 umi 的 hook。和 hook 的执行时机有关系，和 usePageEvent 无关。
