### ISSUE TITLE
[BUG]window 下 class 页面的生命周期函数无效

### ISSUE THREAD

**Issue by joesdu** [remaxjs/remax#917]
**bug 描述**
如题页面周期函数又挂了.

**复现步骤**
不论是start或者build后,控制台均未输出生命周期函数中的文字.

**期望结果**
希望别再出现这种情况了.修复了一次又一次.

**复现代码**
复现仓库地址:https://github.com/joesdu/remax-bug-issue

**版本信息:**

- remax 版本: [e.g. 2.0.4]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by joesdu** [comment]
@Darmody 希望大佬能再看一下.这种问题还是有点急.

**Comment by joesdu** [comment]
目前OnShow我还是用componentDidMount作为替代吧.你们这个页面生命周期函数太不稳了.

**Comment by joesdu** [comment]
经验证,onHide生命周期函数也挂掉了,无法正常调用到函数内输出信息.

**Comment by yesmeck** [comment]
🧐等我今天重构下这一块。

**Comment by joesdu** [comment]
> 🧐等我今天重构下这一块。

感谢大佬❤👍

**Comment by Darmody** [comment]
我试了一下，页面上的 onShow 没问题呀？

**Comment by joesdu** [comment]
> 我试了一下，页面上的 onShow 没问题呀？
你用的我的issue那个仓库的代码吗?我今天试了好几次,正式项目和issue仓库 的项目均不正常.

**Comment by joesdu** [comment]
> 我试了一下，页面上的 onShow 没问题呀？
我又在家里的电脑拉了代码试过了,确实是没有效果.
![image](https://user-images.githubusercontent.com/13188169/81568226-0edbfc00-93d0-11ea-84b5-8401e4a906fc.png)

**Comment by Darmody** [comment]
> > 我试了一下，页面上的 onShow 没问题呀？
> > 你用的我的issue那个仓库的代码吗?我今天试了好几次,正式项目和issue仓库 的项目均不正常.

对，用的复现 demo

**Comment by joesdu** [comment]
> > > 我试了一下，页面上的 onShow 没问题呀？
> > > 你用的我的issue那个仓库的代码吗?我今天试了好几次,正式项目和issue仓库 的项目均不正常.
> 
> 对，用的复现 demo

![image](https://user-images.githubusercontent.com/13188169/81568854-f02a3500-93d0-11ea-8065-c42a3c396e5a.png)
啊,那这个事情就太奇怪了.我删掉dist文件夹重新生成也不行.

**Comment by Darmody** [comment]
你是 windows 吧？

**Comment by joesdu** [comment]
> 你是 windows 吧？

对

**Comment by Darmody** [comment]
`yarn add https://pkg.csb.dev/remaxjs/remax/commit/c8bdb520/remax`

试试这个

**Comment by joesdu** [comment]
> `yarn add https://pkg.csb.dev/remaxjs/remax/commit/c8bdb520/remax`
> 
> 试试这个

start模式下还是无效,甚至连App中的onShow都失效了.
![image](https://user-images.githubusercontent.com/13188169/81586244-d0ead200-93e7-11ea-98f1-3b1e5bb3a12a.png)
build模式下和start模式下表现一致
![image](https://user-images.githubusercontent.com/13188169/81586443-18715e00-93e8-11ea-8d9c-adfe449f6d15.png)

**Comment by Darmody** [comment]
`yarn add https://pkg.csb.dev/remaxjs/remax/commit/2b5b8f4e/remax`

再试试这个。。  @joesdu

**Comment by joesdu** [comment]
> yarn add https://pkg.csb.dev/remaxjs/remax/commit/2b5b8f4e/remax

👍👍👍👍太强了,解决了.真机调试,其他生命周期函数应该也正常了.
![image](https://user-images.githubusercontent.com/13188169/81628565-93ac3180-9433-11ea-8ef1-231c2ccd134a.png)
![image](https://user-images.githubusercontent.com/13188169/81628684-e554bc00-9433-11ea-97a3-b7f5025ce12a.png)

**Comment by joesdu** [comment]
希望早点发布新的版本

**Comment by joesdu** [comment]
还是存在一些问题.正式项目中,部分class页面的函数正常,部分不正常.

**Comment by joesdu** [comment]
> `yarn add https://pkg.csb.dev/remaxjs/remax/commit/2b5b8f4e/remax`
> 
> 再试试这个。。 @joesdu

还是存在一些问题.正式项目中,部分class页面的生命周期函数正常,部分不正常.

**Comment by Darmody** [comment]
@joesdu yarn add https://pkg.csb.dev/remaxjs/remax/commit/e04a21fa/remax 试试这个。

windows 下可能需要你多测测，watch 模式，新增删除等等

**Comment by joesdu** [comment]
> @joesdu yarn add https://pkg.csb.dev/remaxjs/remax/commit/e04a21fa/remax 试试这个。
> 
> windows 下可能需要你多测测，watch 模式，新增删除等等

好的,后期遇到什么问题,我会反馈的.

**Comment by joesdu** [comment]
> @joesdu yarn add https://pkg.csb.dev/remaxjs/remax/commit/e04a21fa/remax 试试这个。
> 
> windows 下可能需要你多测测，watch 模式，新增删除等等
这个e04a21fa版本的remax目前各方面表现正常.还没有发现什么不正常的地方.
