### ISSUE TITLE
[需求]希望未来Remax或者AntD团队能够出一个Remax的UI库.

### ISSUE THREAD

**Issue by joesdu** [remaxjs/remax#921]
**需求描述**
目前使用Van Weapp库,感觉部分功能太弱了,而且没有TS支持,引入后编辑器会报错,看着很难受.希望官方能出一个好看且好用的UI库.

**解决方案**
[如果你有解决方案，在这里清晰地阐述]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
可以先试试 https://github.com/AnnaSearl/anna-remax-ui

**Comment by joesdu** [comment]
> 可以先试试 https://github.com/AnnaSearl/anna-remax-ui

用小程序看了下,感觉还可以,但是网站好像挂了.Umi 404了.
![image](https://user-images.githubusercontent.com/13188169/81532653-52664400-9397-11ea-929a-14206b91e71b.png)

**Comment by yesmeck** [comment]
@AnnaSearl 应该正在搞新网站

**Comment by joesdu** [comment]
> @AnnaSearl 应该正在搞新网站
👍

**Comment by AnnaSearl** [comment]
是的，正在弄...

**Comment by joesdu** [comment]
> 是的，正在弄...
😃支持一波.

**Comment by AnnaSearl** [comment]
> > 是的，正在弄...
> > 😃支持一波.

谢谢！
