### ISSUE TITLE
[BUG] 头条小程序Input maxlength 默认值不对

### ISSUE THREAD

**Issue by winteraq** [remaxjs/remax#931]
**bug 描述**
头条小程序Input 无法输入

**复现步骤**
引入Input，开发者工具中尝试输入即可复现

**期望结果**
正常输入

**复现代码**
```jsx
<Input value={text} onInput={(e) => {
            setText(e.target.value)
          }}/>
```

**版本信息:**

- remax 版本: [2.0.4]
- 开发环境 [mac OS]

**Comment by winteraq** [comment]
原来是 maxlength 不主动设置值的话，默认就设置为 0 了，感觉这里不应该默认给0吧？

**Comment by Darmody** [comment]
> 原来是 maxlength 不主动设置值的话，默认就设置为 0 了，感觉这里不应该默认给0吧？

是 `remax/one` 还是 `remax/toutiao` 呢？

**Comment by winteraq** [comment]
remax/toutiao

**Comment by winteraq** [comment]
@Darmody 另外 input的adjust-position属性默认值也不对，文档上默认应该是true，目前不传看起来应该是等效于false的值。会导致键盘覆盖住input，建议默认值这块按照文档梳理一下，可能还有其他没发现的问题

**Comment by yesmeck** [comment]
@Pochodaydayup 看看啊

**Comment by Pochodaydayup** [comment]
行，我晚上看下

**Comment by Pochodaydayup** [comment]
@winteraq 我没看到头条有 adjust-position 属性啊，其他的默认值的属性我都加上了
