### ISSUE TITLE
remax/one PickerView 设置 indicatorStyle 里面样式单位没有进行转换

### ISSUE THREAD

**Issue by shijunwen** [remaxjs/remax#935]
**bug 描述**
[在用PickerView，设置 indicatorStyle={{ height: '68rpx' }} view style={{ height: '68rpx', lineHeight: '68rpx' }} indicatorStyle里面的rpx没有进行单位转换，导致页面显示异常。在微信开发工具切换手机类型，即可复现bug]

**期望结果**
[能够正确显示]

**复现代码**
[https://github.com/shijunwen/remax-bug]

**版本信息:**

- remax 版本: [2.0.4]
- 手机型号 [iPhone 7 Plus]
- 小程序端 [ 微信小程序]
- 开发环境 [windows]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
rpx需要转换成什么？

**Comment by shijunwen** [comment]
indicatorStyle={{ height: '68rpx' }} view style={{ height: '68rpx', lineHeight: '68rpx' }}  indicatorStyle 上面的设置的68rpx 跟view的rpx 不一样
![image](https://user-images.githubusercontent.com/33819581/81760529-0aabfd80-94fa-11ea-806d-baa7530e5989.png)

**Comment by Darmody** [comment]
rpx 转换成 px 不是正常的吗？原生是怎么样的？

**Comment by Darmody** [comment]
确认下和原生有什么不一样，如果有问题再开启

**Comment by EndlessTJ** [comment]
PickerView的indicatorStyle中高度单位设置成rpx是无效的，必须设置成px

**Comment by EndlessTJ** [comment]
是否有什么方法能够对某些特殊属性不进行px转rpx

**Comment by Darmody** [comment]
> 是否有什么方法能够对某些特殊属性不进行px转rpx

试试单位写成 "PX"
