### ISSUE TITLE
[BUG]头条 Canvas 渲染错误

### ISSUE THREAD

**Issue by gavin99587** [remaxjs/remax#939]
**bug 描述**
import {Canvas as CanvasTt, createCanvasContext} from 'remax/toutiao';
此处的Canvas组件,在源码里是
import { BaseProps } from '../../types/component';
export interface CanvasProps extends BaseProps {
    **cavasId: string;**
}
问题1,cavasId属性写错了,导致在应用时会出现canvas-id attribute is undefined 错误
问题2: 即使我改成了canvasId,错误是不报了,但是用context画图依然不显示
**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]
1,源码里的属性名改正确
2,remax/toutiao里的canvas能正常绘图
**复现代码**
[提供可复现的代码，仓库，或线上示例]
import * as React from 'react';
import {useNativeEffect} from 'remax';
import {View} from "remax/one";
import {BasicDataProps} from "@/interface";
import styles from './index.module.css'
import {Canvas as CanvasTt, createCanvasContext} from 'remax/toutiao';

/**
 * 头条组件
 * */
const TreeCardTt = (props: BasicDataProps) => {
    const {data} = props;
    if (!data) {
        return null;
    }
    /**
     * */
    useNativeEffect(() => {
        const context = createCanvasContext("myCanvas"); // 创建绘图上下文
        //下面这个圆,图案不显示
        context.beginPath();
        context.arc(150, 150, 30, 0, Math.PI * 2)
        context.setFillStyle('#1aad19');
        context.fill();
        context.stroke();
    }, []);
    return (
        <View>
            <View>
                <CanvasTt
                    cavasId="myCanvas"
                    className={styles.wordTreeCanvasTest}/>
            </View>
        </View>
    );
};
export default TreeCardTt;

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]
<img width="949" alt="截屏2020-05-13 09 48 30" src="https://user-images.githubusercontent.com/11565497/81762321-f1f21680-94fe-11ea-9eec-2485d29ff19d.png">

**Comment by Pochodaydayup** [comment]
@gavin99587 是用的 remax 2.0 吗。 是的话，你代码没调用 `context.draw()`, 这样 `canvas` 才会画出来。
