### ISSUE TITLE
[BUG]remax/one中,  Icon组件在头条里显示,在微信里不显示

### ISSUE THREAD

**Issue by gavin99587** [remaxjs/remax#940]
**bug 描述**
用文件名后缀来区分不同平台,对于showTast,showModal来说,我这样写,在头条和微信里都能正常调用, 但是对于Swiper,或这是Icon这样的组件,在头条里能正常显示,但是在微信里就会提示 ./base.wxml
 Template `REMAX_TPL_1_icon` not found.

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]
<img width="720" alt="截屏2020-05-13 11 21 49" src="https://user-images.githubusercontent.com/11565497/81767836-f3760b80-950b-11ea-98fe-15cd0ac498c3.png">

`import * as React from 'react';
import {View, Button, Text, Image} from 'remax/one';
import styles from './index.css';
import Icon from '@/api/Icon'
import showToast from '@/api/showToast'
import showModal from '@/api/showModal'

export default () => {

    const handleShowToast = (event) => {
        showToast({title: "在微信和头条了都会看到我", icon: "none"});
    };
    const handleShowModal = (event) => {
        showModal({
            title: '提示',
            content: '在微信和头条了都会看到我',
            showCancel: true,
            cancelText: "取消",
            confirmText: "确定"
        }).then((resolved) => {
        }).catch((reject) => {
        });
    };
    return (
        <View>
            <View>
                <Button onTap={handleShowToast}>显示Toast</Button>
                <Button onTap={handleShowModal}>显示Modal</Button>
                <View>
                    <Icon type='search'
                          className={styles.searchImg}
                          size='15' color='red'/>
                </View>
            </View>
        </View>
    );
};
`
**版本信息:**

- remax 版本: [2.0.5]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [ mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]
![image](https://user-images.githubusercontent.com/11565497/81767661-882c3980-950b-11ea-922e-233c4eb8ba83.png)
<img width="716" alt="截屏2020-05-13 11 22 18" src="https://user-images.githubusercontent.com/11565497/81767865-0be62600-950c-11ea-8714-3943558fe01a.png">

**Comment by Darmody** [comment]
微信需要写出 jsx 片段

```jsx
import { Icon } from 'remax/wechat';

export default function WechatIcon() {
...  
return <Icon />
...
}
```
