### ISSUE TITLE
[需求]启动 web devServer 时自动判断可用端口

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax#943]
**需求描述**

![Screen Shot 2020-05-13 at 16 02 20](https://user-images.githubusercontent.com/465125/81787097-2384d500-9533-11ea-9367-01103b0f74bc.png)

现在写死了 3000 会导致端口冲突。

**解决方案**

需要在启动时自动判断可用端口。可以参考下 CRA 的做法。

**Comment by inJs** [comment]
@yesmeck 这个可以 close 了吧？
