### ISSUE TITLE
[BUG] yarn run dev 命令受到 ./dist 目录下历史数据的干扰

### ISSUE THREAD

**Issue by wlfcss** [remaxjs/remax#950]
**bug 描述**
当由remax构建的项目出现**文件级别**的变化时，运行 npm run dev wechat/ali/toutiao 时无法有效的替换./dist目录下原有的历史打包文件，导致运行调试出错

本bug似乎并未出现在2.0.3及更早的版本上

**复现步骤**
-  none

**期望结果**
执行 npm run dev 后正常执行并正确更换./dist 目录下的文件

**复现代码**
![image](https://user-images.githubusercontent.com/12138285/81906058-40371080-95f8-11ea-8b46-8db9a12bfc49.png)

**版本信息:**

- remax 版本: [2.0.6]
- 小程序端 [微信小程序]
- 开发环境 [mac OS]

**其他信息**

##### 临时修补方法：
- 在项目 `package` 文件中修改 `dev` 命令：
```
"dev": "rm -rf ./dist && remax build -w -t ",
```

##### 关联bug：
- 执行 npm run dev wechat/ali/toutiao 后 `watch` 功能也无法有效监控到文件级别的代码变化

**Comment by yesmeck** [comment]
@wlfcss 能提供一个复现的 demo 吗？

**Comment by yesmeck** [comment]
@wlfcss
