### ISSUE TITLE
[BUG]微信小程序Text标签渲染异常

### ISSUE THREAD

**Issue by IronLu233** [remaxjs/remax#952]
**bug 描述**
![image](https://user-images.githubusercontent.com/20639676/81912797-aa07e800-9601-11ea-8d82-5672ef1166cb.png)
把右边的第10行注释掉，或者把他换成第11行。那么微信编译出来的内容里就不会有下面的三个Icon

**复现步骤**
![image](https://user-images.githubusercontent.com/20639676/81915651-75962b00-9605-11ea-9f36-2cfe8b109e03.png)

wxml中
![image](https://user-images.githubusercontent.com/20639676/81915942-cdcd2d00-9605-11ea-8f5d-f5ec0dad4186.png)
加了一个空的 <Text />标签后
![image](https://user-images.githubusercontent.com/20639676/81916316-416f3a00-9606-11ea-8ffb-09d1c8a3b851.png)
![image](https://user-images.githubusercontent.com/20639676/81916042-eb01fb80-9605-11ea-9e7a-5b66160c5712.png)
给空标签加上className
![image](https://user-images.githubusercontent.com/20639676/81916383-55b33700-9606-11ea-9f95-5a5f5e01510b.png)
![image](https://user-images.githubusercontent.com/20639676/81916529-83987b80-9606-11ea-8d2c-0435d40e1a3c.png)

**期望结果**
无论存在<Text />标签，自定义的Icon都应该被渲染出来

**复现代码**
见 https://github.com/IronLu233/remax-iconfont/blob/master/example/src/pages/index/index.tsx

**版本信息:**

- remax 版本: [e.g. 2.0.6]
- 小程序端 [微信小程序]
- 小程序版本[2.3.0]
- 开发环境 [ mac OS]

**其他信息**
在Web和支付宝小程序下是完全正常的

**Comment by yesmeck** [comment]
@LeoYuan 等你 PR

**Comment by Darmody** [comment]
这个要看 remax-iconfont-component。应该是 jsx 编译掉了

**Comment by IronLu233** [comment]
> 这个要看 remax-iconfont-component。应该是 jsx 编译掉了

编译掉了也应该能正常工作。毕竟也只是编译成了React.createElement

**Comment by yesmeck** [comment]
@IronLu233 保留 jsx 看看

**Comment by IronLu233** [comment]
我把tsconfig里的"module"字段改成"ESNext"，打包出这样的文件，可以在微信里工作
```jsx
import React from "react";
import { Text } from "remax/one";
import clsx from "clsx";
const Icon = ({ type, className, ...restProps }) => {
    return <Text className={clsx("iconfont", type, className)} {...restProps}/>;
};
export default Icon;
```
Module改为"commonjs", jsx为preserve之后无法工作
它打包出来的代码是这样的。是React这个变量未定义导致的。
```jsx
"use strict";
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
const one_1 = require("remax/one");
const clsx_1 = __importDefault(require("clsx"));
const Icon = (_a) => {
    var { type, className } = _a, restProps = __rest(_a, ["type", "className"]);
    return <one_1.Text className={clsx_1.default("iconfont", type, className)} {...restProps}/>;
};
exports.default = Icon;
```
以及原来编译出的代码是这样的。**注意：这份代码在Web和支付宝端都可以运行**
```js
"use strict";
var __rest = (this && this.__rest) || function (s, e) {
    var t = {};
    for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
        t[p] = s[p];
    if (s != null && typeof Object.getOwnPropertySymbols === "function")
        for (var i = 0, p = Object.getOwnPropertySymbols(s); i < p.length; i++) {
            if (e.indexOf(p[i]) < 0 && Object.prototype.propertyIsEnumerable.call(s, p[i]))
                t[p[i]] = s[p[i]];
        }
    return t;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
const one_1 = require("remax/one");
const clsx_1 = __importDefault(require("clsx"));
const Icon = (_a) => {
    var { type, className } = _a, restProps = __rest(_a, ["type", "className"]);
    return react_1.default.createElement(one_1.Text, Object.assign({ className: clsx_1.default("iconfont", type, className) }, restProps));
};
exports.default = Icon;

```

**Comment by Darmody** [comment]
这个和 #851 是一个问题，到时候一起解决
