### ISSUE TITLE
@remax/one 去除对 history 的强制依赖

### ISSUE THREAD

**Issue by noyobo** [remaxjs/remax#954]
**bug 描述**

依赖了 @remax/router

https://github.com/remaxjs/remax/blob/25171f6debaa087b0d3dd34de96e8c762f2466ca/packages/remax-router/web.js#L4

当文件加载完成后会增加一个 `#/` hash 值

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
 页面路径保持不变。

**复现代码**
```
import { View } from '@remax/one';
```
构建后会执行到 createHashHistory。

**版本信息:**

- remax 版本: 2.0.7

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by yesmeck** [comment]
具体导致的问题是什么呢？

**Comment by noyobo** [comment]
> 具体导致的问题是什么呢？

加载文件后 /home 变成 /home#/

**Comment by noyobo** [comment]
> 具体导致的问题是什么呢？

今天h5项目上线造成的影响是会触发 hashchange 事件，App 就有一定的业务逻辑被触发了。 对于一个组件库的定义，认为不符合预期。

**Comment by yesmeck** [comment]
意思是你们引用是部署在 `/home` 目录下的是吧？

你期望是什么样子的？

**Comment by Darmody** [comment]
https://github.com/remaxjs/remax/blob/master/packages/remax-one/src/hostComponents/Navigator/index.web.tsx#L3

这个组件还没有导出。但是如果我们提供了 Navigator 组件支持，就是会依赖的

**Comment by noyobo** [comment]
> 意思是你们应用是部署在 `/home` 目录下的是吧？

不是这个意思 @Darmody 就更熟悉一些，就是一个普通的 h5 SPA 应用。

现在同构之后，编译到 web 端，`import { View } from '@remax/one';`  由于没有配置按需加载，也没有 treeshake 就会引入 https://unpkg.com/@remax/one@2.0.7/esm/index.js => https://unpkg.com/browse/@remax/one@2.0.7/esm/api/index.web.js => https://unpkg.com/browse/@remax/router@2.0.7/web.js 整个文件。

> 你期望是什么样子的？

单独的 UI 库， 引入 View 就是 一个 div 组件。 引入一个  Navitator 就是一个单纯的路径跳转功能。至于是  hashHistory 还是  browserHistory 应该由业务决定， 比如 `<Router history={history.createHashHistory()} />` 等其他的方式传递到子组件中，而不是内置到 one API 中。

**Comment by Darmody** [comment]
close via #1044
