### ISSUE TITLE
[问题]导入 crypto-js后文件大小增加约1.6M

### ISSUE THREAD

**Issue by yelon21** [remaxjs/remax#957]
**问题描述**
新建项目初始化成功后，直接导入`crypto-js`（`npm install crypto-js`），crypto-js 文件夹大小为435kb，
在`app.js`或`index.js`引入`import CryptoJS from 'crypto-js';`,
编译后的`app.js`或`remax-vendors.js`增加约1.6M

1. 仅在`index.js`文件中添加`import CryptoJS from 'crypto-js';`，编译后的`index.js`为1.6M。
2. 仅在`app.js`文件中添加`import CryptoJS from 'crypto-js';`，编译后的`app.js`为1.6M。
3. 同时在index.js和app.js添加，编译后的`remax-vendors.js`为2.5M。

不知此现象是否正常，请解答，谢谢！

**Comment by yesmeck** [comment]
![C4B05825-AEA5-444E-8AA1-9DAAF976F79A](https://user-images.githubusercontent.com/465125/82026791-d08f5700-96c5-11ea-95f7-83af7c007cd0.png)


先自己用 webpack-bundle-analyzer 分析下。

**Comment by Darmody** [comment]
webpack dev 模式确实会比较大，建议看看 build 后上传的大小。
