### ISSUE TITLE
[需求]支持小程序的云函数

### ISSUE THREAD

**Issue by IronLu233** [remaxjs/remax#963]
**需求描述**
支付宝和微信小程序都可以使用云函数，将函数部署到云端。减少后端开发和运维成本。可以在构建Remax时，将云函数一并构建到云函数对应的目录中
[微信文档](https://developers.weixin.qq.com/minigame/dev/wxcloud/basis/getting-started.html)
[支付宝文档](https://opendocs.alipay.com/mini/cloudservice/introduction)
**解决方案**
起了一个微信官方的云应用，翻阅了阿里云的小程序Serverless文档，一个带云函数的小程序目录结构大致如下：
![image](https://user-images.githubusercontent.com/20639676/82118793-06a70680-97ac-11ea-92e9-165a128f9e8e.png)

一个微信的云函数通过暴露exports.main来描述
```js
const cloud = require('wx-server-sdk')

// 初始化 cloud
cloud.init({
  // API 调用都保持和云函数当前所在环境一致
  env: cloud.DYNAMIC_CURRENT_ENV
})

/**
 * 这个示例将经自动鉴权过的小程序用户 openid 返回给小程序端
 * 
 * event 参数包含小程序端调用传入的 data
 * 
 */
exports.main = async (event, context) => {
  console.log(event)
  
  console.log(context)

  // 可执行其他自定义逻辑
  // console.log 的内容可以在云开发云函数调用日志查看

  // 获取 WX Context (微信调用上下文)，包括 OPENID、APPID、及 UNIONID（需满足 UNIONID 获条件）等信息
  const wxContext = cloud.getWXContext()

  return {
    event,
    openid: wxContext.OPENID,
    appid: wxContext.APPID,
    unionid: wxContext.UNIONID,
    env: wxContext.ENV,
  }
}
```
而支付宝的云函数则大同小异，暴露module.exports。云服务的API，从ctx获得。
```js
module.exports = async ctx => {
  const args = ctx.args;
  return await ctx.mpserverless.db.collection('user').find({ uid: args.uid });
};
```
其中package.json对于微信小程序是必须的，config.json是可选的。另外对于微信小程序，函数中引用到的库是可以在package.json中声明而无需直接上传。

云函数的目录，由 project.config.json 的 cloudfunctionRoot 字段决定。

我的解决方案是，在Remax源代码中，专门有个存储云函数的目录（例如cloudfunction）。在cloundfunction目录下的子目录约定为一个云函数。每个子目录都有一个index.ts和一个可选的config.json。当构建开始时，将这些云函数添加进入口，生成对应的package.json。并输出到相应的目录下。对于微信。我们可以考虑将node_modules中的依赖设置为external。并写进对应云函数的package.json中。

**其他信息**
云函数就不用想着跨端了。

**Comment by Darmody** [comment]
可以通过 public 目录支持
