### ISSUE TITLE
[BUG]微信小程序ScrollView组件在滑动时不触发onScroll,onScrollToLower事件

### ISSUE THREAD

**Issue by gavin99587** [remaxjs/remax#965]
**bug 描述**
使用remax/one的时候,import {ScrollView} from 'remax/wechat'; 组件不触发onScroll,onScrollToLower事件
但是一模一样的代码,在头条小程序中,import {ScrollView} from 'remax/toutiao';则会正常触发
onScroll,onScrollToLower

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
[提供可复现的代码，仓库，或线上示例]

**版本信息:**

- remax 版本: remax/one 2.0.7
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
是不是用了同构的方式定义了 `ScrollView` ？

**Comment by gavin99587** [comment]
> 是不是用了同构的方式定义了 `ScrollView` ？

是的,我用remax/one,然后在页面中  import ScrollView from '@/api/ScrollView'; 这样使用
<img width="752" alt="截屏2020-05-19 10 51 54" src="https://user-images.githubusercontent.com/11565497/82279291-c370b180-99be-11ea-8164-50994e67ce6b.png">

**Comment by Darmody** [comment]
目前微信端有限制，必须写明 jsx
https://remaxjs.org/guide/one#%E4%BD%BF%E7%94%A8%E6%96%87%E4%BB%B6%E5%90%8D%E5%90%8E%E7%BC%80%E5%8C%BA%E5%88%86%E4%B8%8D%E5%90%8C%E5%B9%B3%E5%8F%B0%E4%BB%A3%E7%A0%81

后续会解决这个问题，目前请按照文档的指示修改
