### ISSUE TITLE
[需求] 支持自定义 css module 配置

### ISSUE THREAD

**Issue by linjiajian999** [remaxjs/remax#966]
**需求描述**
目前 2.0 版本会自动识别 css module，方式为
```js
import styles from 'xxx.css'
```
但是希望能够支持下面这种方式：
配合 [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules) ,开发的时候可以像下面这种方式
```jsx
import 'xx.module.css'
<div styleName="container" />
```
现在这种方式只能
```jsx
import styles from 'xx.css'
<div className={styles.container} />
```

**解决方案**
1. 支持开发者配置是否启用  css module，例如支持`import 'xx.module.css'`而不是只支持 `import styles from 'xx.css'`
2. 开发者可以拓展 css module 配置，而不是只能使用框架的默认配置项，例如 [remax 目前的 css module 配置](https://github.com/linjiajian999/remax/blob/b0bd005d0042735d4413924adddeff92441454c9/packages/remax-cli/src/build/webpack/config/css.ts#L38)只有
```js
 modules: cssModules
          ? {
              localIdentName: '[local]___[hash:base64:5]',
            }
          : false,
```
希望开发者能够自定义配置 `modules` 选项

**Comment by Darmody** [comment]
好像需求不是很高
