### ISSUE TITLE
非Page组件也要有 onshow onhide 事件

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax#97]

**Comment by yesmeck** [comment]
为啥啊？

Cai Huanyu <notifications@github.com>于2019年8月15日 周四01:01写道：

**Comment by Darmody** [comment]
比如我定义了一个modal组件，希望页面onhide的时候隐藏起来，onshow的时候现实。如果组件也有对应的生命周期就可以封装在组件内部

**Comment by yesmeck** [comment]
用原生小程序怎么实现的？

**Comment by Darmody** [comment]
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html

**Comment by yesmeck** [comment]
页面都隐藏了，modal 藏不藏有什么关系？

**Comment by Darmody** [comment]
> 页面都隐藏了，modal 藏不藏有什么关系？

当然有关系了。这是个例子，那我换个例子，我页面 onShow 和 onHide 需要 subscribe 和 unsubscribe 怎么办

**Comment by yesmeck** [comment]
页面 Context 自己实现
