### ISSUE TITLE
ScrollView 组件的 refresherDdefaultStyle 默认值不对

### ISSUE THREAD

**Issue by dominicleo** [remaxjs/remax#974]
**bug 描述**

 微信平台 ScrollView、 @vant/weapp 组件库在 remax@2.0.7 版本所有属性默认值需要手动设置

**Comment by Darmody** [comment]
默认值需要手动设置是什么意思？

**Comment by dominicleo** [comment]
ScrollView refresherDdefaultStyle 属性在微信平台上的默认值为 "black"
但是在 remax@2.0.7 中并没有输出这个默认值，需要再设置 refresherDdefaultStyle="black"
其他组件同理

**Comment by Darmody** [comment]
了解了

**Comment by noyobo** [comment]
related #1010
