### ISSUE TITLE
one 模式下，平台组件的属性被覆盖

### ISSUE THREAD

**Issue by dominicleo** [remaxjs/remax#975]

**Comment by yesmeck** [comment]
@dominicleo 你在什么情况下即要用 one 的组件，又要用平台的组件呢？

**Comment by yesmeck** [comment]
> remax/wechat
> Form reportSubmit
> Button formType
> 微信小程序这两个组件的属性不生效

> wechat-report-submit
> wechat-form-type
> 加上平台前缀就生效了，但是是从 remax/wechat 引入的。
