### ISSUE TITLE
[BUG]微信小程序引用第三方组件，style属性和onTap方法没有成功添加到节点上

### ISSUE THREAD

**Issue by AnnaSearl** [remaxjs/remax#977]
**bug 描述**
微信小程序引用第三方组件，style属性和onTap方法没有成功渲染

**复现代码**
[复现代码地址](https://github.com/AnnaSearl/wechat_demo)

**版本信息:**

- remax 版本: [2.0.7]
- 小程序端 [微信小程序]
- 小程序版本[2.3.0]
- 开发环境 [mac OS]

**Comment by Darmody** [comment]
depulicate #851
