### ISSUE TITLE
[问题] remax 里如何使用微信小程序的 createAnimation api

### ISSUE THREAD

**Issue by xiamu14** [remaxjs/remax#984]
**问题描述**
微信小程序的 wx.createAnimation 方法创建的动画实例 animation，最后需要通过动画实例的 export 方法导出动画数据传递给组件的 animation 属性。现在我不知道 在 remax 里的组件里应该传递给哪个 组件属性，我尝试了 ‘wechat-animation’ , 'wx-animation' 都没有用
**示例代码**
[如果有必要，展示代码，线上示例，或仓库]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
如果使用的是 `remax/wechat`，直接传给 `animation` 就行。
如果使用的是 `remax/one`，传给 `wechat-animation`
