### ISSUE TITLE
[BUG] Wechat Editor工具栏不显示

### ISSUE THREAD

**Issue by q759410559** [remaxjs/remax#986]
**bug 描述**
真机测试 android 和 ios  Editor 工具栏不显示

**复现步骤**
正常添加使用
![image](https://user-images.githubusercontent.com/11240348/82638035-8f082a00-9c38-11ea-9ab7-bc129895fb63.png)

**期望结果**
Editor 工具栏显示

**版本信息:**

- remax 版本: [e.g. 2.1.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.3.0]

**Comment by Darmody** [comment]
原生是怎么样的呢？

**Comment by Darmody** [comment]
看看是不是哪个属性控制显示的，remax的默认值不对呢？

**Comment by q759410559** [comment]
![image](https://user-images.githubusercontent.com/11240348/82724719-ac0d2d80-9d0a-11ea-8a39-84edb2ab9aa4.png)
https://developers.weixin.qq.com/miniprogram/dev/component/editor.html
官方的代码片段就是这样，输入框focus时就会显示工具栏。

![image](https://user-images.githubusercontent.com/11240348/82724853-816fa480-9d0b-11ea-9398-a155b5b09a90.png)
remax源码就这样，不用自己设置的吧。

**Comment by Darmody** [comment]
这个工具栏是 demo 里他们用 view 自己实现的啊。。不是 Editor 的一部分
