### ISSUE TITLE
[BUG] 使用vent-weapp的van-grid-item组件，content-class属性无效果

### ISSUE THREAD

**Issue by YikSanChan** [remaxjs/remax#990]
**bug 描述**
[详细地描述 bug，让大家都能理解]
根据vant的文档，我在https://github.com/YikSanChan/remax-vant-demo/blob/master/src/pages/index/index.tsx#L11 中设置content-class可使得icon变红，然而icon依旧为原来的颜色。

vant 文档见 https://youzan.github.io/vant-weapp/#/grid

**复现步骤**
[清晰描述复现步骤，让别人也能看到问题]
git clone [项目](https://github.com/YikSanChan/remax-vant-demo)，yarn dev，在开发者工具中打开，即可看到结果。

**期望结果**
[描述你原本期望看到的结果]
icon呈现红色。我另外用原生小程序试了该组件，content-class产生了应有的效果，见 https://github.com/YikSanChan/miniprogram-helloworld/blob/master/pages/index/index.wxml#L14

**复现代码**
[提供可复现的代码，仓库，或线上示例]
https://github.com/YikSanChan/remax-vant-demo

**版本信息:**

- remax 版本: [e.g. 1.0.0] 2.0.7
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序] 微信小程序
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS] mac OS

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
<img width="412" alt="Screen Shot 2020-05-23 at 3 18 57 PM" src="https://user-images.githubusercontent.com/6788752/82724430-c6460c00-9d08-11ea-9fe4-942c5e6daaa9.png">

**Comment by Darmody** [comment]
我试了一下有额。。

**Comment by Darmody** [comment]
试试更新一下 remax 版本？

**Comment by YikSanChan** [comment]
@Darmody 在你的截图中，icon不是红色的。期待中的效果应该是：

![image](https://user-images.githubusercontent.com/17229109/82724490-63faf600-9c8b-11ea-91fa-9339aa5773b3.png)

麻烦再open一下，谢谢

**Comment by Darmody** [comment]
红色是怎么设置的呢？

**Comment by Darmody** [comment]
![Screen Shot 2020-05-23 at 3 29 30 PM](https://user-images.githubusercontent.com/6788752/82724664-3dc86b00-9d0a-11ea-9bc6-566fd4acabab.png)
<img width="364" alt="Screen Shot 2020-05-23 at 3 29 25 PM" src="https://user-images.githubusercontent.com/6788752/82724665-3ef99800-9d0a-11ea-926a-2c3348dcd95a.png">

红色不生效，是因为你用了 css modules 的引入方式，但是样式类没有指明 global

**Comment by YikSanChan** [comment]
除了css module的引入方式，还有什么引入方式呢？

**Comment by YikSanChan** [comment]
@Darmody 以及关于global，我没有找到有关文档，可以加一下吗？谢谢

**Comment by Darmody** [comment]
> @Darmody 以及关于global，我没有找到有关文档，可以加一下吗？谢谢

https://github.com/css-modules/css-modules
