### ISSUE TITLE
使用微信小程序的picker组件，在多列选择器模式下无法触发columnChange事件[BUG]

### ISSUE THREAD

**Issue by fuqiang01** [remaxjs/remax#992]
**bug 描述**
引入微信小程序的picker组件，其他模式事件都是正常的，但是在多列（mode='multiSelector'）模式下，无法触发专属的columnChange事件

**复现步骤**
把任意页面的js文件，替换成下边的复现代码，打开对应的页面，点击测试文字，这时候就可以看到不会触发columnChange事件了

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
index.js
```
import React from 'react';
import {Picker} from 'remax/wechat';

export default props => {

  const handleColumnChange = e => {
    console.log('触发了columnChange事件')
  }

  return (
    <Picker 
      mode='multiSelector'
      onColumnChange={handleColumnChange}
      range={ [['选项一', '选项二'], ['内容一', '内容二', '内容三']] } 
    >多列选择器测试 </Picker>
  )
}
```

**版本信息:**

- remax 版本: [2.0.7]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 微信小程序]
- 小程序版本[e.g. 2.9.4]
- 开发环境 [e.g. window]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Darmody** [comment]
我试了一下，是可以的

**Comment by Darmody** [comment]
试试更新一下 remax 版本？

**Comment by fuqiang01** [comment]
> 试试更新一下 remax 版本？

嗯嗯  我刚更新成2.1.1版本也不行是这样的https://fqiang-1300549778.cos.ap-chongqing.myqcloud.com/other/WeChat_20200523155851.mp4，我叫我朋友试了一下也是没问题的，可能我这环境什么的有影响，我再看看，多谢啦

**Comment by danieltanfh95** [comment]
这个picker oncolumnchange 效果很不稳定，偶尔行偶尔不行，但是onchange没问题
