### ISSUE TITLE
[BUG]头条createInnerAudioContext播放声音时,会多次重复播放

### ISSUE THREAD

**Issue by gavin99587** [remaxjs/remax#993]
![IMG_3705](https://user-images.githubusercontent.com/11565497/82729546-facabf80-9d2a-11ea-9d80-470f02e6e499.PNG)
**bug 描述**
import {createInnerAudioContext as createInnerAudioContextTt} from 'remax/toutiao';
用头条里的createInnerAudioContext播放声音时,声音会多次重复播放,大约播放十几次然后才会停止

**复现步骤**
页面有个按钮,触发onTap后,会调用handlePlayVoice()方法,此时在handlePlayVoice中
console.log('开始播放,,,' + data.word); 会执行一次,但是onPlay函数则会执行多次,从而导致声音被重复播放了多次, 在微信小程序中createInnerAudioContext表现是正常的

**期望结果**
[描述你原本期望看到的结果]

**复现代码**
import {createInnerAudioContext as createInnerAudioContextTt} from 'remax/toutiao';
const handlePlayVoice = () => {
        if (data && data.youdao) {
            const speakUrl = data.youdao.speakUrl;
            if (speakUrl) {
                if (process.env.REMAX_PLATFORM === PlatFormType.wechat) {
                    //临时注释掉,微信播放声音功能是正常的
                    // const audio = createInnerAudioContext();
                    // audio.autoplay = true;
                    // audio.src = speakUrl;
                    // audio.onPlay(() => {
                    // });
                    // audio.onEnded(() => {
                    // });
                    // audio.onError((res) => {
                    //     console.log('播放出错,' + res.errMsg + "," + res.errCode);
                    // })
                } else if (process.env.REMAX_PLATFORM === PlatFormType.toutiao) {
                    console.log('开始播放,,,' + data.word);
                    const audio = createInnerAudioContextTt();
                    audio.autoplay = true;
                    audio.obeyMuteSwitch = false;
                    audio.src = speakUrl;
                    audio.onPlay(() => {
                        console.log('onPlay-' + data.word);
                    });
                    audio.onEnded(() => {
                        console.log('onEnded-' + data.word);
                    });
                    audio.onError((res) => {
                        console.log('播放出错,' + res.errMsg + "," + res.errCode);
                    })
                }
            }
        }
    };

**版本信息:**

- remax 版本: [e.g. 1.0.0]
- 手机型号 [e.g. iPhone X]
- 小程序端 [e.g. 头条小程序]
- 小程序版本[e.g. 2.3.0]
- 开发环境 [e.g. mac OS]

**其他信息**
[如截图等其他信息可以贴在这里]

**Comment by Pochodaydayup** [comment]
@gavin99587 是小程序这边的问题，我已反馈给内部开发人员。
