### ISSUE TITLE
[BUG]在app.js导入含有样式的js文件，在npm run build 时丢失样式

### ISSUE THREAD

**Issue by AnnaSearl** [remaxjs/remax#996]
**bug 描述**
// app.js
`
import  'style/index.js';
`
// style/index.js
`
import './index.css';
`
npm run dev 是正常的，但是npm run build发现样式丢失

**版本信息:**

- remax 版本: [2.1.1]
- 手机型号 [iPhone X]
- 小程序端 [微信小程序和钉钉小程序]
- 小程序版本[2.3.0]
- 开发环境 [mac OS]

**Comment by yesmeck** [comment]
issue no 亮了

**Comment by yesmeck** [comment]
估计是被 tree shaking 掉了。

**Comment by yesmeck** [comment]
@AnnaSearl 我没重现，能给个 demo 么。

**Comment by AnnaSearl** [comment]
> @AnnaSearl 我没重现，能给个 demo 么。

好的！马上上传个demo。

**Comment by AnnaSearl** [comment]
哦哦我知道了，可能是因为我引用的是第三方库的style

**Comment by AnnaSearl** [comment]
996哈哈

**Comment by yesmeck** [comment]
库的话要这样设置一下防止 tree shaking https://github.com/ant-design/ant-design/blob/master/package.json#L37-L42

**Comment by AnnaSearl** [comment]
哦哦是的，我没有设置style文件夹下的为副作用，导致样式被去掉了，谢谢边柳大大指正。
